---
permalink: a1k/bootmedia-replace.html 
sidebar: sidebar 
keywords: aff a1k, replace the boot media 
summary: Para localizar el medio de arranque con error en el módulo del controlador, extraiga el Riser 3 en el módulo del controlador antes de poder sustituir el soporte de arranque. 
---
= Sustituya el soporte de arranque: AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sustituir el soporte de arranque, debe extraer el módulo de gestión del sistema de la parte posterior del sistema, retirar el soporte de arranque defectuoso e instalar el soporte de arranque de repuesto en el módulo de gestión del sistema.



== Paso 1: Sustituya el soporte de arranque

El soporte de arranque se encuentra dentro del módulo de gestión del sistema y se accede a él quitando el módulo del sistema.

image::../media/drw_a1k_boot_media_remove_replace_ieops-1377.svg[Gráfico de sustitución de soporte de arranque]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
 a| 
Bloqueo de leva del módulo de gestión del sistema



 a| 
image::../media/legend_icon_02.svg[Número de llamada 2]
 a| 
Botón de bloqueo del soporte de arranque



 a| 
image::../media/legend_icon_03.svg[Número de llamada 3]
 a| 
Soporte de arranque

|===
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Desconecte los cables de la fuente de alimentación de las PSU del controlador.
+

NOTE: Si el sistema de almacenamiento tiene suministros de alimentación de CC, desconecte el bloque de cables de alimentación de las unidades de suministro de alimentación (PSU).

+
.. Retire todos los cables conectados al módulo de gestión del sistema. Asegúrese de etiquetar dónde estaban conectados los cables, de modo que pueda conectarlos a los puertos correctos cuando vuelva a instalar el módulo.
.. Gire la bandeja de gestión de cables hacia abajo tirando de los botones situados en ambos lados del interior de la bandeja de gestión de cables y, a continuación, gire la bandeja hacia abajo.
.. Pulse el botón de leva de gestión del sistema.
.. Gire el pestillo de la leva hacia abajo hasta el tope.
.. Retire el módulo de gestión del sistema de la carcasa enganchando el dedo en la abertura de la palanca de leva y tirando del módulo para sacarlo de la carcasa.
.. Coloque el módulo de gestión del sistema en una alfombrilla antiestática, de forma que se pueda acceder al soporte de arranque.


. Retire el soporte de arranque del módulo de gestión:
+
.. Pulse el botón de bloqueo azul.
.. Gire el soporte de arranque hacia arriba, deslícelo para extraerlo de la toma y déjelo a un lado.


. Instale el soporte de arranque de repuesto en el módulo de gestión del sistema:
+
.. Alinee los bordes del soporte del maletero con el alojamiento del zócalo y, a continuación, empújelo suavemente en el zócalo.
.. Gire el soporte de arranque hacia abajo hacia el botón de bloqueo.
.. Pulse el botón de bloqueo, gire el soporte del maletero completamente hacia abajo y, a continuación, suelte el botón de bloqueo.


. Vuelva a instalar el módulo Gestión del sistema.
+
.. Alinee el módulo con los bordes de la abertura de la ranura de la carcasa.
.. Deslice suavemente el módulo dentro de la ranura hasta el fondo de la carcasa y, a continuación, gire el pestillo de leva completamente hacia arriba para bloquear el módulo en su lugar.


. Gire la bandeja de gestión de cables hasta la posición cerrada.
+
.. Vuelva a conectar el módulo Gestión del sistema.






== Paso 2: Transfiera la imagen ONTAP al soporte de arranque

El soporte de arranque de repuesto que instaló no tiene una imagen ONTAP, puede transferir la imagen ONTAP al soporte de arranque de reemplazo descargando la imagen de servicio ONTAP adecuada de https://mysupport.netapp.com/["Sitio de soporte de NetApp"] a una unidad flash USB y, a continuación, al soporte de arranque de reemplazo.

.Antes de empezar
* Debe tener una unidad flash USB vacía, formateada a FAT32, con al menos 4GB GB de capacidad.
* Debe tener una copia de la misma versión de imagen de ONTAP que se estaba ejecutando la controladora dañada. Puede descargar la imagen adecuada de https://support.netapp.com/downloads["Descargas"] la sección del sitio de soporte de NetApp
+
** Si NVE es compatible, descargue la imagen con NetApp Volume Encryption, tal y como se indica en el botón de descarga.
** Si NVE no es compatible, descargue la imagen sin cifrado de volúmenes NetApp, como se indica en el botón de descarga.


* Si el sistema es una pareja de alta disponibilidad, debe tener una conexión de red entre los puertos de gestión de nodos de las controladoras (normalmente las interfaces de e0M GbE).


.Pasos
. Descargue y copie la imagen de servicio adecuada desde el https://mysupport.netapp.com/["Sitio de soporte de NetApp"] a la unidad flash USB.
+
.. Descargue la imagen del servicio desde el enlace Descargas de la página, en su espacio de trabajo en su portátil.
.. Descomprima la imagen de servicio.
+

NOTE: Si está extrayendo el contenido con Windows, no utilice WinZip para extraer la imagen netboot. Utilice otra herramienta de extracción, como 7-Zip o WinRAR.



+
La unidad flash USB debe tener la imagen ONTAP adecuada de lo que está ejecutando el controlador dañado.

+
.. Extraiga la unidad flash USB del ordenador portátil.


. Inserte la unidad flash USB en la ranura USB del módulo de administración del sistema.
+
Asegúrese de instalar la unidad flash USB en la ranura indicada para dispositivos USB, y no en el puerto de consola USB.

. Conecte los cables de alimentación a las fuentes de alimentación y vuelva a instalar el retén del cable de alimentación.
+
La controladora comienza a arrancar en cuanto se vuelve a conectar la alimentación al sistema.

. Interrumpa el proceso de arranque pulsando Ctrl-C para detenerse en el símbolo del sistema DEL CARGADOR.
+
Si omite este mensaje, pulse Ctrl-C, seleccione la opción de arrancar en modo de mantenimiento y detenga la controladora para arrancar en EL CARGADOR.

. Configure el tipo de conexión de red en el símbolo del sistema del CARGADOR:
+
** Si va a configurar DHCP: `ifconfig e0M -auto`
+

NOTE: El puerto de destino que configure es el puerto de destino que utiliza para comunicarse con la controladora con la controladora con deterioro de la controladora en buen estado durante la restauración del sistema de archivos var con una conexión de red. También puede utilizar el puerto e0M en este comando.

** Si está configurando conexiones manuales: `ifconfig e0M -addr=filer_addr -mask=netmask -gw=gateway`
+
*** Filer_addr es la dirección IP del sistema de almacenamiento.
*** La máscara de red es la máscara de red de la red de gestión conectada al partner de alta disponibilidad.
*** gateway es la puerta de enlace de la red.




+

NOTE: Es posible que sean necesarios otros parámetros para la interfaz. Puede introducir ayuda ifconfig en el símbolo del sistema del firmware para obtener más detalles.


