---
permalink: a1k/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a1k,  verify and set HA state, complete the replacement process 
summary: Reinicie el controlador, verifique el estado del sistema y devuelva la pieza defectuosa a NetApp para completar el paso final del procedimiento de reemplazo del chasis AFF A1K . 
---
= Completa la sustitución del chasis de un sistema AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reinicia el controlador, comprueba el estado del sistema y devuelve la pieza defectuosa a NetApp para completar el último paso del proceso de sustitución del chasis de tu sistema AFF A1K.



[[step-1-boot-the-controllers-and-verify-system-health]]
== Paso 1: Inicie los controladores y verifique el estado del sistema.

Después de que los controladores se reinicien, inicia ONTAP, devuelve los controladores y verifica el estado del sistema.

.Pasos
. Compruebe la salida de la consola:
+
.. Si la controladora arranca en el símbolo del SISTEMA DE Loader, reinicie la controladora con `boot_ontap` el comando.
.. Si la consola aparece `waiting for giveback` después del reinicio, inicie sesión en la controladora asociada y compruebe que la controladora reemplazada esté lista para el retorno con `storage failover show` el comando.


. Realice la devolución del control:
+
.. Conecte el cable de la consola al controlador asociado.
.. Devuelva la controladora afectada a su funcionamiento normal devolviendo su almacenamiento: `storage failover giveback -ofnode _impaired_node_name_`
.. Si se deshabilitó la devolución automática, vuelva a habilitarla: `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos: `system node autosupport invoke -node * -type all -message MAINT=END`


. Una vez finalizada la devolución, corre https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] para verificar el estado del sistema de almacenamiento y corregir cualquier problema que encuentre.




[[step-2-return-the-failed-part-to-netapp]]
== Paso 2: Devuelve la parte fallida a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
