---
permalink: a1k/io-module-overview.html 
sidebar: sidebar 
keywords: aff a1k, replace io module 
summary: El sistema AFF A1K ofrece flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido. 
---
= Descripción general de ADD y SUSTITUIR UN MÓDULO DE E/S - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema AFF A1K ofrece flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

Puede sustituir un módulo de I/O con fallo en el sistema de almacenamiento AFF A1K por el mismo tipo de módulo de I/O o por otro tipo de módulo de I/O diferente. También puede agregar un módulo de E/S a un sistema con ranuras vacías.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
La adición de módulos adicionales puede mejorar la redundancia, lo que ayuda a garantizar que el sistema siga funcionando incluso si falla un módulo.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de E/S que falla puede restaurar el sistema a su estado operativo óptimo.



.Numeración de ranuras de E/S.
Las ranuras de I/O del controlador ASA A1K están numeradas de 1 a 11, como se muestra en la ilustración siguiente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeración de ranuras en una controladora AFF A1K]
