---
permalink: a1k/maintain-overview.html 
sidebar: sidebar 
keywords: aff a1k maintenance, maintenance, repairing a1k, repairing aff a1k, replace aff a1k components, replace aff a1k components 
summary: Mantenga el hardware de AFF A1K 
---
= Mantener el hardware de AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para el sistema de almacenamiento AFF A1K, puede realizar procedimientos de mantenimiento en los componentes siguientes.



== Soporte de arranque

Los medios de arranque almacenan un conjunto primario y secundario de archivos de imagen ONTAP que el sistema utiliza cuando se inicia.



== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades y ejecuta el software del sistema operativo ONTAP.



== DIMM

Un módulo de memoria dual en línea (DIMM) es un tipo de memoria del ordenador. Se instalan para agregar memoria del sistema a una placa base de la controladora.



== Ventilador

Un ventilador enfría el controlador.



== NVRAM

La NVRAM (memoria de acceso aleatorio no volátil) es un módulo que permite a la controladora proteger y guardar datos en movimiento si el sistema sufre un corte de alimentación. El ID del sistema reside en el módulo de NVRAM. Cuando se sustituye, la controladora asume el nuevo ID del sistema desde el módulo NVRAM de reemplazo.



== Batería de NV

La batería de NVRAM es responsable de suministrar alimentación al módulo de NVRAM mientras los datos en tránsito se separan a la memoria flash después de una pérdida de alimentación.



== Módulo de I/O.

El módulo de E/S (módulo de entrada/salida) es un componente de hardware que actúa como intermediario entre el controlador y varios dispositivos o sistemas que necesitan intercambiar datos con el controlador.



== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



== Batería del reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.



== Módulo de gestión del sistema

El módulo de gestión del sistema proporciona la interfaz entre el controlador y una consola o portátil para el mantenimiento del controlador o del sistema. El módulo de gestión del sistema contiene el soporte de arranque y almacena el número de serie del sistema (SSN).
