---
permalink: a400/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a400, verify and set HA state, run diagnostics, complete the replacement process 
summary: Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. 
---
= Completar el proceso de restauración y sustitución - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit.



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

Debe verificar el estado de alta disponibilidad del chasis y, si es necesario, actualizar el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis: `ha-config modify chassis _HA-state_`
+
El valor de _ha-state_ puede ser uno de los siguientes:

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Confirme que el ajuste ha cambiado: `ha-config show`


. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.
. Vuelva a instalar el bisel en la parte delantera del sistema.




== Paso 2: Ejecutar el diagnóstico

Después de sustituir un componente del sistema, deberá ejecutar pruebas de diagnóstico de ese componente.

El sistema debe estar en el aviso del CARGADOR para iniciar los diagnósticos.

Todos los comandos de los procedimientos de diagnóstico se emiten desde el nodo en el que se sustituye el componente.

. Si el nodo que se va a mantener no está en el símbolo del sistema del CARGADOR, reinicie el nodo: `system node halt -node node_name`
+
Tras emitir el comando, debe esperar hasta que el sistema se detenga en el símbolo del sistema del CARGADOR.

. En el aviso DEL CARGADOR, acceda a los controladores especiales diseñados específicamente para que los diagnósticos del sistema funcionen correctamente: `boot_diags`
. Seleccione *Scan System* en el menú que aparece para activar la ejecución de las pruebas de diagnóstico.
. Seleccione *sistema de prueba* en el menú que aparece para ejecutar pruebas de diagnóstico.
. Seleccione la prueba o la serie de pruebas de los distintos submenús.
. Proceda según el resultado del paso anterior:
+
** Si la prueba falla, corrija el fallo y vuelva a ejecutar la prueba.
** Si la prueba no ha informado de ningún fallo, seleccione Reiniciar en el menú para reiniciar el sistema.






== Paso 3: Vuelva a cambiar los agregados en una configuración MetroCluster de dos nodos

Una vez que haya completado el reemplazo de FRU en una configuración de MetroCluster de dos nodos, podrá llevar a cabo la operación de conmutación de estado de MetroCluster. De este modo, la configuración vuelve a su estado operativo normal, con las máquinas virtuales de almacenamiento (SVM) sincronizada en el sitio anteriormente afectado que ahora están activas y sirviendo datos de los pools de discos locales.

Esta tarea solo se aplica a configuraciones MetroCluster de dos nodos.

.Pasos
. Compruebe que todos los nodos estén en el `enabled` provincia: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Compruebe que la resincronización se haya completado en todas las SVM: `metrocluster vserver show`
. Compruebe que las migraciones LIF automáticas que realizan las operaciones de reparación se han completado correctamente: `metrocluster check lif show`
. Lleve a cabo la conmutación de estado mediante el `metrocluster switchback` comando desde cualquier nodo del clúster superviviente.
. Compruebe que la operación de conmutación de estado ha finalizado: `metrocluster show`
+
La operación de conmutación de estado ya está en ejecución cuando un clúster está en el `waiting-for-switchback` provincia:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
La operación de conmutación de estado se completa cuando los clústeres están en el `normal` estado:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Si una conmutación de regreso tarda mucho tiempo en terminar, puede comprobar el estado de las líneas base en curso utilizando el `metrocluster config-replication resync-status show` comando.

. Restablecer cualquier configuración de SnapMirror o SnapVault.




== Paso 4: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://["Retorno de artículo  sustituciones"] para obtener más información.
