---
permalink: a70-90/aff-a-series-affa90-overview.html 
sidebar: sidebar 
keywords: AFF A90 specifications, AFF A90 specs, NetApp AFF A90, AFF A90 hardware 
summary: Especificaciones clave del sistema de almacenamiento AFF A90 
---
= Especificaciones clave del AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el AFF A90.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del AFF A90 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del AFF A90

Configuración de la plataforma: AFF A90, par HA de chasis único

Capacidad bruta máxima: 6,6096 PB

Memoria: 2048.0000 GB

Factor de forma: chasis 4U con 2 controladores HA y 48 ranuras de unidad

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 18

Versión mínima de ONTAP : ONTAP 9.15.1RC2



=== Máximos de escalamiento

* NAS: 12 pares HA, capacidad bruta de 79,3 PB/70,4 PiB, memoria máxima de 24576 GB
* SAN: 6 pares HA, capacidad bruta de 39,7 PB/35,2 PiB, memoria máxima de 12288 GB
* Par HA: 6,6 PB / 5,9 PiB de capacidad bruta, 2048,0000 GB de memoria máxima




=== IO



==== E/S integrada

No hay datos de E/S integrados.



==== E/S total

* Ethernet 200 Gbps: 24 puertos
* Ethernet 100 Gbps: 36 puertos
* Ethernet 25 Gbps: 56 puertos
* Ethernet 10 Gbps: 56 puertos
* FC 64 Gbps: 56 puertos
* NVMe/FC 64 Gbps: 56 puertos
* SAS 12 Gbps: 56 puertos




==== Puertos de gestión

* Ethernet 1 Gbps: 2 puertos
* RS-232 115 Kbps: 4 puertos
* USB 600 Mbps: 2 puertos




=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 8304 BTU/h
* Potencia en el peor de los casos: 10948 BTU/h
* Peso: 118,0 lb 53,5 kg
* Altura: 4U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad: 34,5” (36,6” con soporte para gestión de cables)
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °C (50 °F a 95 °F) a una altitud de 3048 m (10 000 pies); humedad relativa del 8 % al 80 %, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12192 m (40000 pies) 10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,6; Presión sonora (LpAm) (posición de transeúntes): 71,6 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de gestión de placa base (BMC) basado en Ethernet e interfaz de gestión ONTAP ; Controladores redundantes intercambiables en caliente; Fuentes de alimentación redundantes intercambiables en caliente; Gestión en banda de SAS a través de conexiones SAS para estantes externos; [//] 2025-10-15 ontap-systems-internal/issues/1357
