---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Revise los requisitos antes de reemplazar el medio de arranque en su sistema de almacenamiento AFF A70 o AFF A90 . 
---
= Requisitos para la recuperación automatizada de medios de arranque: AFF A70 y AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise los requisitos antes de reemplazar el medio de arranque en su sistema de almacenamiento AFF A70 o AFF A90 , incluida la funcionalidad del puerto de clúster, la configuración del administrador de claves y la compatibilidad de la versión de ONTAP .

El proceso automatizado de recuperación de medios de arranque requiere ONTAP 9.17.1 o posterior.  Si su sistema de almacenamiento ejecuta una versión anterior de ONTAP, utilice lalink:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"] .

Revise los siguientes requisitos.

* Debe sustituir el medio de arranque con errores por un medio de arranque de reemplazo que recibió desde NetApp.
* Los puertos del clúster se utilizan para la comunicación entre los dos controladores durante el proceso de recuperación de arranque automático. Asegúrese de que los puertos del clúster del controlador dañado funcionen correctamente.
* Para OKM, necesita la frase de contraseña de todo el clúster y también los datos de respaldo.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/cliente.clave
** /cfcard/kmip/certs/CA.pem


* Comprenda la terminología del controlador utilizada en este procedimiento:
+
** El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
** El _controlador saludable_ es el socio HA del controlador dañado.




.El futuro
Después de revisar los requisitos de soporte de arranque, usted link:bootmedia-shutdown-bmr.html["apague la controladora"].
