---
permalink: a70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: Se sustituye un chasis deficiente por el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Requisitos y consideraciones: AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sustituir el chasis, debe mover el panel frontal, los módulos de controladora y las unidades NVMe desde el chasis dañado hasta el chasis de reemplazo y, a continuación, quitar el chasis dañado del rack del equipo o armario del sistema e instalar el chasis de reemplazo en su lugar.

* Asegúrese de que todos los demás componentes del sistema funcionan correctamente; de lo contrario, póngase en contacto con el soporte técnico.
* Puede usar el procedimiento de reemplazo de chasis con todas las versiones de ONTAP compatibles con el sistema.
* El procedimiento de sustitución del chasis se escribe suponiendo que va a mover el panel frontal, las unidades NVMe y los módulos de controladora al nuevo chasis, y que el chasis de reemplazo es un nuevo componente de NetApp.
* *El procedimiento de reemplazo del chasis es disruptivo.* En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

