---
permalink: a70-90/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a70, aff a90, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Tras completar el reemplazo y el arranque del hardware en modo de mantenimiento, debe verificar la configuración del sistema de bajo nivel de la controladora de reemplazo y volver a configurar los ajustes del sistema según sea necesario. 
---
= Restaurar y verificar la configuración del sistema: AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique la configuración de bajo nivel del sistema de la controladora de reemplazo y vuelva a configurar los ajustes del sistema según sea necesario.



== Paso 1: Establecer y verificar la hora del sistema

Debe comprobar la hora y la fecha del módulo de la controladora de sustitución en comparación con el módulo de controladora en buen estado de un par de alta disponibilidad o con un servidor de tiempo fiable en una configuración independiente. Si la hora y la fecha no coinciden, debe reiniciarlas en el módulo del controlador de repuesto para evitar posibles interrupciones en los clientes debido a diferencias de tiempo.

.Acerca de esta tarea
Es importante que aplique los comandos en los pasos de los sistemas correctos:

* El nodo _regrUSTITUCION_ es el nuevo nodo que reemplazó al nodo dañado como parte de este procedimiento.
* El nodo _heated_ es el compañero de alta disponibilidad del nodo _regrel_.


.Pasos
. Si el nodo _reader_ no está en el aviso del CARGADOR, detenga el sistema en el símbolo del sistema del CARGADOR.
. En el nodo _Healthy_, compruebe la hora del sistema: `cluster date show`
+
La fecha y la hora se basan en la zona horaria configurada.

. En el símbolo del SISTEMA del CARGADOR, compruebe la fecha y la hora del nodo _regrel_: `show date`
+
La fecha y la hora se indican en GMT.

. Si es necesario, establezca la fecha en GMT en el nodo de reemplazo: `set date _mm/dd/yyyy_`
. Si es necesario, establezca la hora en GMT del nodo de reemplazo: `set time _hh:mm:ss_`
. En el símbolo del SISTEMA del CARGADOR, confirme la fecha y la hora del nodo _regrel_: `show date`
+
La fecha y la hora se indican en GMT.





== Paso 2: Verificar y establecer el estado de alta disponibilidad del chasis

Debe comprobar el `HA` estado del módulo de la controladora y, si es necesario, actualice el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento del nuevo módulo de controlador, compruebe que todos los componentes muestran lo mismo `HA` provincia: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado del módulo del controlador no coincide con la configuración del sistema, defina el `HA` estado para el módulo de la controladora: `ha-config modify controller ha-state`
+
El valor de la condición de alta disponibilidad puede ser uno de los siguientes:

+
** `ha`
** `mcc` (no compatible)
** `mccip`
** `non-ha` (no compatible)


. Si el estado del sistema mostrado del módulo del controlador no coincide con la configuración del sistema, defina el `HA` estado para el módulo de la controladora: `ha-config modify controller ha-state`
. Confirme que el ajuste ha cambiado: `ha-config show`

