---
permalink: a70-90/install-prepare.html 
sidebar: sidebar 
keywords: aff a70-90k, prepare installation 
summary: Prepárese para instalar su plataforma AFF A70, AFF A90. 
---
= Preparación para la instalación: AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepárate para instalar tu plataforma.

.Antes de empezar
* Use el https://docs.netapp.com/us-en/ontap/software_setup/index.html["hoja de cálculo de configuración del clúster"] para registrar los valores que necesita al configurar el clúster. Si se proporciona un valor predeterminado, puede usar dicho valor, o bien introducir el que desee.
* Confirme que dispone de todos los equipos y herramientas adicionales necesarios para completar la instalación de hardware.
+
** Destornillador Phillips número 2
** Linterna
** Correa ESD
** Un clip de papel o un bolígrafo con punta estrecha para fijar NS224 ID de estante
** Portátil o consola con conexión USB/serie
** Acceso a un explorador web para configurar el sistema de almacenamiento


* Debe ser consciente de los problemas de seguridad asociados con el peso de la plataforma.
+
Una plataforma A70-90 completamente cargada puede pesar hasta 68,8 kg (151,68 lb) y requiere cuatro personas para levantar o usar un elevador hidráulico.

+
image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Icono de advertencia de peso AFF A90 AFF A70]

* Debe ser consciente de los problemas de seguridad asociados con el peso del estante.
+
Un estante completamente cargado puede pesar hasta 30,29 kg (66,78 lb) y requiere que dos personas levanten o utilicen un elevador hidráulico. Evite quitar los componentes de la bandeja (desde la parte delantera o trasera de la bandeja) para reducir el peso de la bandeja, ya que el peso de la bandeja se equilibrará.

+
image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Cuidado de elevación]

* El flujo de aire a través del sistema de almacenamiento entra desde la parte frontal donde se instalan las tapas del bisel o de los extremos y sale de la parte trasera donde se encuentran los puertos.




== Paso 1: Preparar el sitio

Asegúrese de que el sitio y el gabinete o rack que planea utilizar cumplan con las especificaciones de su sistema de almacenamiento.

.Pasos
. Confirme que su centro cumple con los requisitos ambientales y eléctricos de su plataforma, como se muestra en la https://hwu.netapp.com["Hardware Universe de NetApp"^].
. Asegúrese de que dispone de espacio de rack adecuado:
+
** 4U para el chasis de la plataforma
** 2U por cada bandeja de NS224


. Instale los switches de red necesarios cerca de la plataforma.
+
Consulte la https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentación de los switches"^] para obtener instrucciones de instalación y link:https://hwu.netapp.com["Hardware Universe de NetApp"^] para obtener información sobre compatibilidad.





== Paso 2: Desempaquetar las cajas

Desembale todas las cajas y compare el contenido con los artículos de la hoja de embalaje.

. Abra cuidadosamente todas las cajas y coloque el contenido de una manera organizada.
. Compara el contenido que has desempaquetado con la lista de la hoja de embalaje.
+

NOTE: Usted puede obtener su lista de embalaje escaneando el código QR en el lado de la caja de envío.

+
Los siguientes elementos son algunos de los contenidos que puede ver en las cajas.

+
Asegúrese de que todo lo que hay en las cajas coincide con la lista de la hoja de embalaje. Si hay alguna discrepancia, anótelas para realizar otras acciones.

+
[cols="12,9,4"]
|===


| *Hardware* | *Cables* |  


 a| 
** Plataforma con unidades integradas instaladas
** Bandeja (opcional)
** Kits de rieles con instrucciones (opcional)
** Dos dispositivos de gestión de cables
** Frontal

 a| 
** Cables de alimentación
** Cables de red
** Cables Ethernet de gestión (cables RJ-45)
** Cable de puerto serie USB-C.
** Cables de almacenamiento (si se solicita almacenamiento adicional)

|  
|===




== Paso 3: Registre su hardware

Registre su plataforma para obtener las ventajas de soporte.

.Pasos
. Localice el número de serie del sistema para su plataforma.
+
Puede encontrar el número en la hoja de embalaje, en su correo electrónico de confirmación o en el controlador después de desempaquetarlo.

+
image::../media/drw_ssn_label.svg[Ejemplo del número de serie del sistema donde se muestra la ubicación del número]

. Vaya al sitio de soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^].
. Registre el hardware:
+
[role="tabbed-block"]
====
.Opción 1: Cliente de NetApp existente
--
.Pasos
.. Inicie sesión con su nombre de usuario y contraseña.
.. Selecciona *Sistemas* > *Mis sistemas*.
.. Confirme que el número de serie del nuevo sistema aparece en la lista.



NOTE: Si el número de serie del nuevo sistema no aparece, siga las instrucciones para nuevos clientes de NetApp.

--
.Opción 2: Nuevo cliente de NetApp
--
.. Haga clic en *Registrar ahora* y cree una cuenta.
.. Selecciona *Sistemas* > *Registrar sistemas*.
.. Introduzca el número de serie del sistema del producto y los detalles solicitados.


Una vez aprobado el registro, puede descargar el software necesario. El proceso de aprobación puede llevar hasta 24 horas.

--
====

