---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: Revise el equipo necesario y las precauciones de elevación de su plataforma y estantes. 
---
= Requisitos de instalación: AFF A70 y AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento y las bandejas de almacenamiento de AFF A70 o AFF A90.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Peso del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.

El sistema de almacenamiento puede pesar hasta 68,8 kg (151,68 lb). Para levantar el sistema de almacenamiento, utilice cuatro personas o un elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== Peso del estante

Tome las precauciones necesarias al mover o levantar su estante.

Un estante NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante, utilice dos personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de hardware, usted link:install-prepare.html["Prepare la instalación del sistema de almacenamiento AFF A70 o AFF A90"].
