---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: Revise el equipo necesario y las precauciones de elevación de su plataforma y estantes. 
---
= Requisitos de instalación: AFF A70 y AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento y las bandejas de almacenamiento de AFF A70 o AFF A90.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento AFF A70 o AFF A90, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento AFF A70 y AFF A90 y las bandejas de almacenamiento NS224 son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Sistemas de almacenamiento AFF A70 y AFF A90

Un sistema de almacenamiento A70 de AFF o un sistema de almacenamiento A90 de AFF pueden pesar hasta 68,8 kg (151,68 libras). Para levantar el sistema, se necesitan cuatro personas o un elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== Bandeja NS224

Un estante de almacenamiento NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante de almacenamiento, se necesitan dos personas o un elevador hidráulico. Conserve todos los componentes en la bandeja de almacenamiento (tanto delantera como trasera) para evitar que se desequilibre el peso de bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de hardware, usted link:install-prepare.html["Prepare la instalación del sistema de almacenamiento AFF A70 o AFF A90"].
