---
permalink: a70-90/install-hardware.html 
sidebar: sidebar 
keywords: aff a70, a90, install hardware, telco rack 
summary: Instale su sistema de almacenamiento en un armario o rack de telecomunicaciones. 
---
= Instale la tornillería: AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes instrucciones describen cómo instalar el hardware en un armario vacío o rack de telecomunicaciones. Omita este paso si el armario está rellenado previamente.

.Antes de empezar
* Debe revisar https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Avisos de seguridad"] el documento y comprender las precauciones para mover e instalar el hardware.
* Deberá presentar las instrucciones en el paquete del kit de raíl.
* Debe ser consciente de los problemas de seguridad asociados con el peso de la plataforma y el estante.


.Pasos
. Instale los kits de guías para la plataforma y los estantes, según sea necesario, siguiendo las instrucciones incluidas con los kits.
. Instale y asegure su plataforma en el gabinete o rack de telecomunicaciones:
+
.. Coloque la plataforma en los rieles en el centro del gabinete o bastidor de telecomunicaciones, y luego apoye la plataforma desde la parte inferior y deslícela en su lugar.
.. Fije la plataforma al armario o al rack Telco con los tornillos de montaje incluidos.


. Instale la bandeja o las bandejas:
+
.. Coloque la parte posterior de la bandeja en los rieles, y luego sostenga la bandeja desde la parte inferior y deslícela en el armario o rack de telecomunicaciones.
+
Si va a instalar varias bandejas, coloque la primera bandeja directamente encima de las controladoras. Coloque la segunda bandeja directamente debajo de las controladoras. Repita este patrón para todas las bandejas de unidades adicionales.

.. Fije la bandeja al armario o al rack Telco con los tornillos de montaje incluidos.


. Conecte los dos dispositivos de gestión de cables a la parte posterior de las controladoras.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Instale el dispositivo de gestión de cables]

. Fije la cubierta protectora en la parte frontal de la plataforma.

