---
permalink: a70-90/install-cable.html 
sidebar: sidebar 
keywords: aff a70, a90, prepare installation 
summary: Los puertos de red de gestión de las controladoras están conectados a los switches. Los puertos de interconexión de clúster y de alta disponibilidad se cablean en ambas controladoras. Los módulos del controlador están conectados al almacenamiento externo, si se solicita. 
---
= Conecte el cable de la tornillería: AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conecte los cables de las controladoras y las bandejas de acuerdo con la configuración específica del sistema de almacenamiento.

.Antes de empezar
Compruebe que la flecha de la ilustración en los diagramas de cableado tiene la orientación correcta de la lengüeta de extracción del conector de cable.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[Ejemplo de orientación de la pestaña de extracción de cable]

* Al insertar el conector, debe sentir que encaja en su sitio; si no siente que hace clic, quítelo, gire el cabezal del cable y vuelva a intentarlo.
* Si se conecta a un switch óptico, inserte el SFP en el puerto de la controladora antes de establecer el cableado al puerto.




== Paso 1: Conecte los controladores a la red

Conecte los cables de las controladoras a la red como un clúster sin switches de dos nodos o un clúster con switches.

.Antes de empezar
Póngase en contacto con el administrador de red para obtener información sobre cómo conectar el sistema de almacenamiento a los switches.

.Acerca de esta tarea
Estos procedimientos muestran configuraciones comunes. Tenga en cuenta que el cableado específico depende de los componentes solicitados para su sistema de almacenamiento. Para obtener información completa sobre la configuración y la prioridad de las ranuras, consulte link:https://hwu.netapp.com["Hardware Universe de NetApp"^].

[role="tabbed-block"]
====
.Opción 1: Cable del clúster sin switches
--
Conecte mediante cable las conexiones del clúster sin switch.

.Pasos
. Conecte los puertos de interconexión de clúster/alta disponibilidad e1a a e1a y e7a a e7a con el cable de interconexión de clúster/alta disponibilidad.
+

NOTE: El tráfico de interconexión de clúster y el tráfico de alta disponibilidad comparten los mismos puertos físicos.

+
.. Puerto de cable e1a de la controladora A al puerto E1A de la controladora B.
.. Puerto de cable e7a de la controladora A al puerto E1A de la controladora B.
+
* Cables de interconexión Cluster/HA*

+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cable de alta disponibilidad de clúster]



+
image::../media/drw_70-90_tnsc_cluster_cabling_ieops-1653.svg[Diagrama de cableado de clústeres de dos nodos sin switches]

. Conecte los puertos del módulo Ethernet a la red host.
+
A continuación se muestran algunos ejemplos típicos de cableado de red host. Consulte link:https://hwu.netapp.com["Hardware Universe de NetApp"^] para obtener información sobre la configuración específica del sistema.

+
.. Conecte los puertos e9a y e9b al switch de red de datos Ethernet como se muestra.
+

NOTE: Para obtener el rendimiento máximo del sistema para el tráfico de clúster y de alta disponibilidad, es mejor no utilizar puertos e1b y e7b para las conexiones de red de host. Utilice una tarjeta de host independiente para maximizar el rendimiento.

+
*Cable de 100 GbE*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100GB Cable Ethernet]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cable a red Ethernet de 100 Gb]

.. Conecte los cables de los switches de red host de 10/25 GbE.
+
*4 puertos, 10/25 GbE Host*

+
image::../media/oie_cable_sfp_gbe_copper.svg[Cable de 10/25 GB]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cable a red Ethernet 100GB]



. Conecte los puertos de gestión de controladoras (llave) a los switches de red de gestión con cables 1000BASE-T RJ-45.
+
image::../media/oie_cable_rj45.svg[Cables RJ45]

+
* 1000BASE-T CABLES RJ-45*

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Conéctese a su red de gestión]




IMPORTANT: No enchufe los cables de alimentación todavía.

--
.Opción 2: Cable de clúster conmutado
--
Conecte los cables de las conexiones de clúster conmutadas.

.Pasos
. Realice las siguientes conexiones de cableado:
+

NOTE: El tráfico de interconexión de clúster y el tráfico de alta disponibilidad comparten los mismos puertos físicos.

+
.. Puerto de cable e1a de la Controladora A y el puerto e1a de la Controladora B al switch de red de clúster A.
.. Cable del puerto e7a de la Controladora A y el puerto e7a de la Controladora B al switch de red de clúster B.
+
*Cable de 100 GbE*

+
image::../media/oie_cable100_gbe_qsfp28.svg[Cable de 100 GB]

+
image::../media/drw_70-90_switched_cluster_cabling_ieops-1657.svg[Cablear las conexiones del clúster a la red del clúster]



. Conecte los puertos del módulo Ethernet a la red host.
+
A continuación se muestran algunos ejemplos típicos de cableado de red host. Consulte link:https://hwu.netapp.com["Hardware Universe de NetApp"^] para obtener información sobre la configuración específica del sistema.

+
.. Conecte los puertos e9a y e9b al switch de red de datos Ethernet como se muestra.
+

NOTE: Para obtener el rendimiento máximo del sistema para el tráfico de clúster y de alta disponibilidad, es mejor no utilizar puertos e1b y e7b para las conexiones de red de host. Utilice una tarjeta de host independiente para maximizar el rendimiento.

+
*Cable de 100 GbE*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100GB Cable Ethernet]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cable a red Ethernet 100GB]

.. Conecte los cables de los switches de red host de 10/25 GbE.
+
*4 puertos, 10/25 GbE Host*

+
image::../media/oie_cable_sfp_gbe_copper.svg[Cable Ethernet 10/25GB]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cable a red Ethernet 10/25GB]



. Conecte los puertos de gestión de controladoras (llave) a los switches de red de gestión con cables 1000BASE-T RJ-45.
+
image::../media/oie_cable_rj45.svg[Cables RJ-45]

+
* 1000BASE-T CABLES RJ-45*

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Conéctese a su red de gestión]




IMPORTANT: No enchufe los cables de alimentación todavía.

--
====


== Paso 2: Conecte los controladores a las bandejas

Conecte los cables de las controladoras a la bandeja o las bandejas.

Estos procedimientos muestran cómo conectar los cables de las controladoras a una bandeja y a dos bandejas. Es posible conectar las controladoras con un máximo de cuatro bandejas.

[role="tabbed-block"]
====
.Opción 1: Conecte los cables a una bandeja NS224
--
Conecte mediante cable cada controladora a los módulos NSM de la bandeja NS224. Los gráficos muestran el cableado de cada una de las controladoras: El cableado de la controladora A en azul y el cableado de la controladora B en amarillo.

.Pasos
. Conecte el puerto e11a de la controladora A al puerto NSM A e0a.
. Conecte la controladora A del puerto e11b al puerto NSM B e0b.
+
image:../media/drw_a70-90_1shelf_cabling_a_ieops-1731.svg["Controladora A e11a y e11b a una única bandeja NS224"]

. Conecte el puerto e11a de la controladora B al puerto NSM B e0a.
. Conecte el puerto e11b de la controladora B al puerto NSM A e0b.
+
image:../media/drw_a70-90_1shelf_cabling_b_ieops-1732.svg["Controladoras B e11a y e11b a una sola bandeja NS224"]



--
.Opción 2: Conecte los cables a dos bandejas NS224
--
Conecte mediante cable cada controladora a los módulos NSM en ambas bandejas NS224. Los gráficos muestran el cableado de cada una de las controladoras: El cableado de la controladora A en azul y el cableado de la controladora B en amarillo.

.Pasos
. En la controladora A, conecte las siguientes conexiones:
+
.. Conecte el puerto e11a a la bandeja 1, NSM A, puerto e0a.
.. Conecte el puerto e11b a la bandeja 2, puerto NSM B e0b.
.. Conecte el puerto E8a a la bandeja 2, NSM A, puerto e0a.
.. Conecte el puerto e8b a la bandeja 1, puerto NSM B e0b.
+
image:../media/drw_a70-90_2shelf_cabling_a_ieops-1733.svg["Conexiones de controladora a bandeja para la controladora A"]



. En la controladora B, conecte las siguientes conexiones:
+
.. Conecte el puerto e11a a la bandeja 1, puerto NSM B e0a.
.. Conecte el puerto e11b a la bandeja 2, NSM A, puerto e0b.
.. Conecte el puerto E8a a la bandeja 2, puerto NSM B e0a.
.. Conecte el puerto e8b a la bandeja 1, NSM A, puerto e0b.
+
image:../media/drw_a70-90_2shelf_cabling_b_ieops-1734.svg["Conexiones de controladora a bandeja para la controladora B"]





--
====