---
permalink: a70-90/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: Puede sustituir un módulo de I/O con fallo en el sistema de almacenamiento AFF A70 o AFF A90 por el mismo tipo de módulo de I/O, o por otro tipo de módulo de I/O diferente. También puede agregar un módulo de E/S a un sistema con ranuras vacías. 
---
= Descripción general de ADD y SUSTITUIR UN MÓDULO DE E/S - AFF A70 y AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas AFF A70 y AFF A90 ofrecen flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

Puede sustituir un módulo de I/O con fallo en el sistema de almacenamiento AFF A70 o AFF A90 por el mismo tipo de módulo de I/O, o por otro tipo de módulo de I/O diferente. También puede agregar un módulo de E/S a un sistema con ranuras vacías.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
La adición de módulos adicionales puede mejorar la redundancia, lo que ayuda a garantizar que el sistema siga funcionando incluso si falla un módulo.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de E/S que falla puede restaurar el sistema a su estado operativo óptimo.



.Numeración de ranuras de E/S.
Las ranuras de I/O de las controladoras AFF A70 y AFF A90 están numeradas de 1 a 11, como se muestra en la ilustración siguiente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeración de ranuras en controladores AFF A70 y AFF A90]
