---
permalink: a70-90/io-module-add.html 
sidebar: sidebar 
keywords: aff a70, aff a90, add I/O module 
summary: Para sustituir un módulo de E/S, debe desconectar los cables del módulo, quitar los módulos SFP y QSFP del módulo, quitar el módulo, instalar el módulo de reemplazo, volver a instalar los módulos SFP y QSFP y, a continuación, conectar el cable al módulo de E/S. 
---
= Añada el módulo I/O: AFF A70 y AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede añadir un módulo de I/O al sistema de almacenamiento AFF A70 y AFF A90 cuando haya ranuras vacías disponibles o cuando todas estén completamente ocupadas.



== Paso 1: Apague el módulo del controlador defectuoso

Apague o tome el control del módulo del controlador defectuoso.

[role="tabbed-block"]
====
.Opción 1: La mayoría de los sistemas
--
Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

.Acerca de esta tarea
Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].

.Pasos
. Si AutoSupport está habilitado, suprima la creación automática de casos invocando un comando de mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente comando de la AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
`Waiting for giveback...`
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Detenga o tome el control del controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===


--
.Opción 2: Configuración de MetroCluster
--

NOTE: No use este procedimiento si el sistema está en una configuración de MetroCluster de dos nodos.

Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

* Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].
* Si tiene una configuración MetroCluster, debe haber confirmado que el estado de configuración de MetroCluster está configurado y que los nodos están en estado normal y habilitado (`metrocluster node show`).


.Pasos
. Si AutoSupport está habilitado, suprima la creación automática de casos invocando un comando de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente comando de la AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al siguiente paso.



 a| 
Esperando devolución...
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Detenga o tome el control del controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===


--
====


== Paso 2: Agregue el nuevo módulo de E/S.

Si el sistema de almacenamiento tiene ranuras disponibles, instale el nuevo módulo de I/O en una de las ranuras disponibles. Si todas las ranuras están ocupadas, retire un módulo de E/S existente para hacer espacio e instale el nuevo.

.Antes de empezar
* Compruebe la https://hwu.netapp.com/["Hardware Universe de NetApp"^] para asegurarse de que el nuevo módulo de I/O es compatible con su sistema de almacenamiento y la versión de ONTAP que ejecuta.
* Si hay varias ranuras disponibles, compruebe las prioridades de las ranuras en https://hwu.netapp.com/["Hardware Universe de NetApp"^] Y utilice el mejor disponible para su módulo de E/S.
* Asegúrese de que todos los demás componentes funcionan correctamente.


[role="tabbed-block"]
====
.Agregue un módulo de E/S a una ranura disponible
--
Puede agregar un nuevo módulo de I/O a un sistema de almacenamiento con ranuras disponibles.

.Pasos
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Gire hacia abajo la bandeja de gestión de cables tirando de los botones del interior de la bandeja de gestión de cables y girándola hacia abajo.
. Retire el módulo de obturación de la ranura de destino del soporte:
+
.. Presione el pestillo de leva del módulo de supresión de la ranura de destino.
.. Gire el pestillo de leva hacia fuera del módulo hasta el tope.
.. Retire el módulo de la carcasa enganchando el dedo en la abertura de la palanca de leva y sacando el módulo de la carcasa.


. Instale el módulo de E/S:
+
.. Alinee el módulo de E/S con los bordes de la abertura de la ranura del compartimento.
.. Deslice suavemente el módulo dentro de la ranura hasta el fondo de la carcasa y, a continuación, gire el pestillo de leva completamente hacia arriba para bloquear el módulo en su lugar.


. Conecte el módulo de E/S al dispositivo designado.
+

NOTE: Asegúrese de que las ranuras de E/S no utilizadas tengan espacios en blanco instalados para evitar posibles problemas térmicos.

. Gire la bandeja de gestión de cables hasta la posición cerrada.
. Desde el aviso del CARGADOR, reinicie el nodo:
+
`bye`

+

NOTE: De este modo, se reinicializa el módulo de I/O y otros componentes, y se reinicia el nodo.

. Devuelva la controladora de la controladora asociada:
+
`storage failover giveback -ofnode target_node_name`

. Repita estos pasos para la controladora B.
. Desde el nodo en buen estado, restaure la devolución automática si la deshabilitó:
+
`storage failover modify -node local -auto-giveback _true_`

. Si AutoSupport está habilitado, restaure la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.Agregue un módulo de E/S a un sistema completamente completo
--
Puede agregar un módulo de E/S a un sistema completamente completo eliminando un módulo de E/S existente e instalando uno nuevo en su lugar.

.Acerca de esta tarea
Asegúrese de comprender las siguientes situaciones para agregar un nuevo módulo de E/S a un sistema completamente completo:

[cols="1,2"]
|===
| Situación | Acción necesaria 


 a| 
NIC a NIC (el mismo número de puertos)
 a| 
Los LIF migrarán automáticamente cuando se apaga su módulo de controladora.



 a| 
NIC a NIC (distinto número de puertos)
 a| 
Reasignar permanentemente las LIF seleccionadas a un puerto raíz diferente. Consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["Migrar una LIF"^] para obtener más información.



 a| 
De NIC al módulo de I/O de almacenamiento
 a| 
Utilice System Manager para migrar de forma permanente las LIF a distintos puertos principales, como se describe en https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["Migrar una LIF"^].

|===
.Pasos
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Desconecte cualquier cableado del módulo de E/S de destino.
. Gire hacia abajo la bandeja de gestión de cables tirando de los botones del interior de la bandeja de gestión de cables y girándola hacia abajo.
. Extraiga el módulo de I/o de destino del chasis:
+
.. Pulse el botón de bloqueo de leva.
.. Gire el pestillo de leva hacia fuera del módulo hasta el tope.
.. Retire el módulo de la carcasa enganchando el dedo en la abertura de la palanca de leva y sacando el módulo de la carcasa.
+
Asegúrese de realizar un seguimiento de la ranura en la que se encontraba el módulo de E/S.



. Instale el módulo de E/S en la ranura de destino del receptáculo:
+
.. Alinee el módulo con los bordes de la abertura de la ranura de la carcasa.
.. Deslice suavemente el módulo dentro de la ranura hasta el fondo de la carcasa y, a continuación, gire el pestillo de leva completamente hacia arriba para bloquear el módulo en su lugar.


. Conecte el módulo de E/S al dispositivo designado.
. Repita los pasos de extracción e instalación para reemplazar módulos adicionales para la controladora.
. Gire la bandeja de gestión de cables hasta la posición cerrada.
. Reinicie la controladora desde el símbolo del sistema del CARGADOR:_bye_
+
Esto reinicializa las tarjetas PCIe y otros componentes y reinicia el nodo.

+

NOTE: Si se produce un problema durante el reinicio, consulte https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["BURT 1494308: Es posible que se active el apagado del entorno durante la sustitución del módulo de E/S."]

. Devuelva la controladora de la controladora asociada:
+
`storage failover giveback -ofnode target_node_name`

. Habilitar devolución automática si estaba deshabilitada:
+
`storage failover modify -node local -auto-giveback true`

. Debe realizar una de las siguientes acciones:
+
** Si ha eliminado un módulo de E/S de NIC e instalado un nuevo módulo de E/S de NIC, utilice el siguiente comando de red para cada puerto:
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** Si quitó un módulo de E/S NIC e instaló un módulo de E/S de almacenamiento, instale las bandejas NS224 y conecte los cables de las mismas, como se describe en link:../ns224/hot-add-shelf-overview.html["Flujo de trabajo de incorporación en caliente"].


. Repita estos pasos para la controladora B.


--
====