---
permalink: a70-90/io-module-replace.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace a pcie card 
summary: Para sustituir una tarjeta PCIe, debe desconectar los cables de las tarjetas, quitar los módulos SFP y QSFP de las tarjetas antes de quitar la tarjeta vertical, volver a instalar la tarjeta vertical y, a continuación, volver a instalar los módulos SFP y QSFP antes de cablear las tarjetas. 
---
= Sustituya el módulo de E/S - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice este procedimiento para sustituir un módulo de E/S fallido.

* Puede usar este procedimiento con todas las versiones de ONTAP compatibles con el sistema de almacenamiento.
* Todos los demás componentes del sistema de almacenamiento deben funcionar correctamente; de lo contrario, debe comunicarse con el soporte técnico.




== Paso 1: Apague el controlador dañado

Apague o retome el controlador dañado utilizando una de las siguientes opciones.

[role="tabbed-block"]
====
.Opción 1: La mayoría de los sistemas
--
Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

.Acerca de esta tarea
* Si dispone de un sistema SAN, debe haber comprobado los mensajes de evento  `cluster kernel-service show`) para el blade SCSI de la controladora dañada.  `cluster kernel-service show`El comando (desde el modo avanzado priv) muestra el nombre del nodo, el estado del quórum de ese nodo, el estado de disponibilidad de ese nodo y el estado operativo de ese nodo.
+
Cada proceso SCSI-blade debe quórum con los otros nodos del clúster. Todos los problemas deben resolverse antes de continuar con el reemplazo.

* Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].


.Pasos
. Si AutoSupport está habilitado, suprima la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
+

NOTE: Cuando vea _do desea desactivar la devolución automática?_, introduzca `y`.

. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
Esperando devolución...
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===


--
.Opción 2: La controladora se encuentra en un MetroCluster
--
Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

* Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].
* Si tiene una configuración MetroCluster, debe haber confirmado que el estado de configuración de MetroCluster está configurado y que los nodos están en estado normal y habilitado (`metrocluster node show`).


.Pasos
. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
Esperando devolución...
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===


--
====


== Paso 2: Sustituya un módulo I/O fallido

Para sustituir un módulo de E/S, búsquelo dentro del módulo del controlador y siga la secuencia específica de pasos.

. En la parte frontal del chasis, utilice los pulgares para empujar con firmeza cada unidad hasta que sienta una parada positiva. De este modo se garantiza que las unidades se encuentren firmemente asentadas en el plano medio del chasis.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[Unidad drw a800 asentada IEPOPS 960]

. Vaya a la parte posterior del chasis. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Desconecte la alimentación tirando del módulo del controlador hacia fuera unas tres pulgadas:
+

NOTE: Si el sistema de almacenamiento dispone de fuentes de alimentación de CC (PSU), desconecte el bloque de cables de alimentación de las PSU.

+
.. Presione los dos pestillos de bloqueo hacia abajo y, a continuación, gire ambos pestillos hacia abajo al mismo tiempo.
.. Extraiga el módulo del controlador unas 3 pulgadas del chasis para desconectar la alimentación.


. Desconecte cualquier cableado del módulo de E/S de destino.
+
Asegúrese de etiquetar los cables para saber de dónde proceden.

. Gire hacia abajo la bandeja de gestión de cables tirando de los botones del interior de la bandeja de gestión de cables y girándola hacia abajo.
. Retire el módulo de E/S del módulo del controlador:
+

NOTE: En la siguiente ilustración, se muestra la extracción de un módulo de E/S horizontal y vertical. Normalmente, solo eliminará un módulo de E/S.

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Retire el módulo de E/S.]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Número de llamada 1,width=30px"]
 a| 
Botón de bloqueo de leva

|===
+
.. Pulse el botón de bloqueo de leva.
+
El pestillo de leva se aleja del módulo del controlador.

.. Gire el pestillo de la leva hacia abajo hasta el tope. Para los módulos horizontales, gire la leva hacia fuera del módulo hasta el tope.
.. Retire el módulo del módulo del controlador enganchando el dedo en la abertura de la palanca de leva y sacando el módulo del módulo del controlador.
+
Asegúrese de realizar un seguimiento de la ranura en la que se encontraba el módulo de E/S.



. Coloque el módulo de E/S a un lado.
. Instale el módulo de E/S de repuesto en la ranura de destino:
+
.. Alinee el módulo de E/S con los bordes de la ranura.
.. Deslice suavemente el módulo en la ranura hasta el fondo dentro del módulo del controlador y, a continuación, gire el pestillo de leva completamente hacia arriba para bloquear el módulo en su lugar.


. Conecte el cable al módulo de E/S.
. Repita los pasos de extracción e instalación para reemplazar módulos adicionales para la controladora.
. Vuelva a instalar el módulo del controlador en el chasis.
+

NOTE: Si dispone de suministros de alimentación de CC, vuelva a conectar los bloques de cables en las PSU.

. Gire la bandeja de gestión de cables a la posición bloqueada.




== Paso 3: Reinicie el controlador

Después de sustituir un módulo de I/o, debe reiniciar el módulo de la controladora.


NOTE: Si el nuevo módulo de E/S no es el mismo modelo que el módulo con errores, primero debe reiniciar el BMC.

.Pasos
. Reinicie el BMC si el módulo de sustitución no es el mismo modelo que el módulo antiguo:
+
.. Desde el aviso del CARGADOR, cambie al modo de privilegios avanzado: _SET PRIVILEGE ADVANCED_
.. Reinicie BMC: _Sp reboot_


. En el símbolo del sistema DEL CARGADOR, reinicie el nodo: _Bye_
+

NOTE: De este modo, se reinicializan las tarjetas de I/O y otros componentes y se reinicia el nodo.

+

NOTE: Asegúrese de salir del modo de mantenimiento después de completar la conversión.

. Devuelva el nodo a su funcionamiento normal: _Storage failover giveback -ofnode impaired_node_name_
. Si se ha deshabilitado la devolución automática, vuelva a habilitarla: _Storage failover modify -node local -auto-giveback true_




== Paso 4: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Retorno de artículo  sustituciones"] para obtener más información.
