---
permalink: afx-2k/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, replace the boot media 
summary: Antes de sustituir el soporte de arranque en tu sistema de almacenamiento afx 2k, asegúrate de cumplir los requisitos necesarios para que la sustitución sea exitosa. Esto incluye comprobar que tienes el soporte de arranque de recambio correcto, confirmar que no hay puertos de clúster defectuosos en el controlador y determinar si Onboard Key Manager o External Key Manager están habilitados. 
---
= Requisitos para sustituir el soporte de arranque - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el soporte de arranque en tu sistema de almacenamiento AFX 2K, asegúrate de cumplir con los requisitos necesarios para una sustitución exitosa. Esto incluye verificar que tienes el soporte de arranque de recambio correcto, confirmar que no hay puertos de clúster defectuosos en el controlador y determinar si Onboard Key Manager (OKM) o External Key Manager (EKM) está habilitado.

Antes de sustituir el soporte de arranque, asegúrese de revisar los siguientes requisitos.

[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====
* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El controlador _drinated_ es el controlador en el que está realizando tareas de mantenimiento.
** El controlador _heated_ es el compañero de alta disponibilidad del controlador dañado.


* No debe haber puertos de clúster defectuosos en la controladora dañada.


.El futuro
Después de revisar los requisitos para reemplazar el medio de arranque, debelink:bootmedia-shutdown.html["apague la controladora"] .
