---
permalink: a900/bootmedia_encryption_preshutdown_checks.html 
sidebar: sidebar 
keywords:  
summary: Antes de apagar la controladora con deterioro y comprobar el estado de las claves de cifrado integradas, debe comprobar el estado de la controladora con deterioro, deshabilitar la devolución automática del control y comprobar la versión de ONTAP que el sistema está ejecutando. 
---
= Compruebe la compatibilidad y el estado de la clave de cifrado: AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Paso 1: Compruebe si su versión de ONTAP es compatible con el cifrado de volúmenes de NetApp

Compruebe si su versión de ONTAP es compatible con el cifrado de volúmenes de NetApp (NVE). Esta información es crucial para descargar la imagen ONTAP correcta.

. Determine si la versión de ONTAP admite el cifrado ejecutando el siguiente comando:
+
`version -v`

+
Si la salida incluye `1Ono-DARE`, NVE no es compatible con la versión del clúster.

. Según si NVE es compatible con el sistema, realice una de las siguientes acciones:
+
** Si NVE es compatible, descargue la imagen ONTAP con NetApp Volume Encryption.
** Si NVE no es compatible, descargue la imagen ONTAP *sin* Cifrado de volumen NetApp.






== Paso 2: Determine si es seguro apagar el controlador

Para apagar de forma segura una controladora, primero identifique si el gestor de claves externo (EKM) o el gestor de claves incorporado (OKM) están activos. A continuación, verifique el administrador de claves en uso, muestre la información de clave adecuada y realice acciones en función del estado de las claves de autenticación.

. Determine qué gestor de claves está activado en el sistema:
+
[cols="1a,2a"]
|===
| Versión de ONTAP | Ejecute este comando 


 a| 
ONTAP 9.14.1 o posterior
 a| 
`security key-manager keystore show`

** Si EKM está activado, `EKM` aparece en la salida del comando.
** Si OKM está activado, `OKM` aparece en la salida del comando.
** Si no hay ningún gestor de claves activado, `No key manager keystores configured` aparece en el resultado del comando.




 a| 
ONTAP 9.13.1 o anterior
 a| 
`security key-manager show-key-store`

** Si EKM está activado, `external` aparece en la salida del comando.
** Si OKM está activado, `onboard` aparece en la salida del comando.
** Si no hay ningún gestor de claves activado, `No key managers configured` aparece en el resultado del comando.


|===
. En función de si hay configurado un gestor de teclas en el sistema, seleccione una de las siguientes opciones.
+
[role="tabbed-block"]
====
.No se ha configurado ningún gestor de claves
--
Puede apagar el controlador defectuoso de forma segura. Vaya a link:bootmedia-shutdown.html["apague el controlador dañado"].

--
.Se ha configurado el gestor de claves externo o incorporado
--
.. Introduzca el siguiente comando query para mostrar el estado de las claves de autenticación en su administrador de claves.
+
`security key-manager key query`

.. Compruebe la salida del valor de `Restored` la columna para su gestor de claves.
+
Esta columna indica si las claves de autenticación del gestor de claves (EKM u OKM) se han restaurado correctamente.



--
====


. En función de si el sistema utiliza el Administrador de claves externo o el Administrador de claves incorporado, seleccione una de las siguientes opciones.
+
[role="tabbed-block"]
====
.Gestor de claves externo
--
En función del valor de salida mostrado en la `Restored` columna, siga los pasos adecuados.

[cols="1a,2a"]
|===
| Valor de salida en `Restored` la columna | Siga estos pasos... 


 a| 
`true`
 a| 
Puede apagar el controlador defectuoso de forma segura. Vaya a link:bootmedia-shutdown.html["apague el controlador dañado"].



 a| 
Cualquier otra cosa que no sea `true`
 a| 
.. Restaure las claves de autenticación de gestión de claves externas en todos los nodos del clúster mediante el siguiente comando:
+
`security key-manager external restore`

+
Si el comando falla, póngase en contacto con http://mysupport.netapp.com/["Soporte de NetApp"^].

.. Compruebe que `Restored` la columna se muestre `true` para todas las claves de autenticación introduciendo  `security key-manager key query`el comando.
+
Si todas las claves de autenticación son `true`, puede apagar de forma segura el controlador defectuoso. Vaya a link:bootmedia-shutdown.html["apague el controlador dañado"].



|===
--
.Gestión de claves incorporada
--
En función del valor de salida mostrado en la `Restored` columna, siga los pasos adecuados.

[cols="1a,2a"]
|===
| Valor de salida en `Restored` la columna | Siga estos pasos... 


 a| 
`true`
 a| 
Realice una copia de seguridad manual de la información de OKM.

.. Vaya al modo avanzado introduciendo `set -priv advanced` y, a continuación, introdúzcalo `Y` cuando se le solicite.
.. Introduzca el siguiente comando para mostrar la información de gestión de claves:
+
`security key-manager onboard show-backup`

.. Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados.
+
Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.

.. Puede apagar el controlador defectuoso de forma segura. Vaya a link:bootmedia-shutdown.html["apague el controlador dañado"].




 a| 
Cualquier otra cosa que no sea `true`
 a| 
.. Introduzca el comando SYNC del gestor de claves de seguridad incorporado:
+
`security key-manager onboard sync`

.. Introduzca los 32 caracteres y la clave de acceso alfanumérica de gestión de claves incorporada cuando se le solicite.
+
Si no se puede proporcionar la contraseña, póngase en contacto con http://mysupport.netapp.com/["Soporte de NetApp"^].

.. Compruebe que `Restored` se muestra la columna `true` para todas las claves de autenticación:
+
`security key-manager key query`

.. Compruebe que se muestra el `Key Manager` tipo `onboard`y, a continuación, realice una copia de seguridad manual de la información de OKM.
.. Introduzca el comando para mostrar la información de backup para la gestión de claves:
+
`security key-manager onboard show-backup`

.. Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados.
+
Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.

.. Puede apagar el controlador defectuoso de forma segura. Vaya a link:bootmedia-shutdown.html["apague el controlador dañado"].


|===
--
====

