---
permalink: asa800/install-videos.html 
sidebar: sidebar 
keywords: asa a800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Vídeos - ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

."Animación - instalación y configuración de un A800 de AFF
video::2a61ed74-a0ce-46c3-86d2-ab4b013c0030[panopto]

NOTE: El ASA A800 utiliza el mismo procedimiento de instalación que el sistema AFF A800.



== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]