---
permalink: a200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, replace the chassis 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir un chasis AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF A200, revisa los requisitos para que la sustitución sea exitosa. El procedimiento de sustitución del chasis mueve todas las fuentes de alimentación, las unidades y los módulos de controlador del chasis averiado al chasis de reemplazo, y es disruptivo.

.Antes de empezar
Todos los demás componentes del sistema deben funcionar correctamente; si no, póngase en contacto con el soporte técnico.

.Acerca de esta tarea
* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover todas las unidades y módulos o módulos de controladora al nuevo chasis, y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

