---
permalink: a200/maintain-overview.html 
sidebar: sidebar 
keywords: aff A220 maintenance, maintenance, repairing a200, repairing aff a200, replace aff a200 components, replace aff a200 components 
summary: Mantenga el hardware de AFF A200 
---
= Infórmate sobre el mantenimiento de un sistema de almacenamiento AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para el sistema de almacenamiento AFF A200, puede realizar procedimientos de mantenimiento en los componentes siguientes.



[[boot-media]]
== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



[[caching-module]]
== Módulo de almacenamiento en caché

Es necesario sustituir el módulo de almacenamiento en caché de la controladora cuando el sistema registra un único mensaje de AutoSupport (ASUP) que el módulo se ha desconectado.



[[chassis]]
== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



[[controller]]
== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



[[dimm]]
== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



[[drive]]
== Unidad

Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



[[nvem-battery]]
== Batería de NVEM

Se incluye una batería con una controladora y conserva los datos almacenados en caché si falla la alimentación de CA.



[[power-supply]]
== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



[[real-time-clock-battery]]
== Batería de reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
