---
permalink: a220/bootmedia-recovery-image-boot-non-2n-mcc.html 
sidebar: sidebar 
keywords: aff 220, boot, recovery, image, restore, file, system, environmental, varible, manual, manual boot recovery 
summary: Debe iniciar la imagen ONTAP desde la unidad USB, restaurar el sistema de archivos y verificar las variables ambientales. El sistema AFF A220 solo admite procedimientos de recuperación de medios de arranque manuales. 
---
= Inicie la imagen de recuperación - AFF A220
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
El sistema AFF A220 solo admite procedimientos de recuperación de medios de arranque manuales.

Debe arrancar la imagen de ONTAP desde la unidad USB, restaurar el sistema de archivos y verificar las variables del entorno.

.Pasos
. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Restaure el sistema de archivos var:
+
[cols="1,2"]
|===
| Si el sistema tiene... | Realice lo siguiente... 


 a| 
Una conexión de red
 a| 
.. Pulse `y` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Configure la controladora en buen estado como nivel de privilegio avanzado: `set -privilege advanced`
.. Ejecute el comando restore backup: `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Devuelva la controladora al nivel de administrador: `set -privilege admin`
.. Pulse `y` cuando se le solicite que utilice la configuración restaurada.
.. Pulse `y` cuando se le solicite reiniciar la controladora.




 a| 
No hay conexión de red
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.



|===
. Asegurarse de que las variables medioambientales estén establecidas de la manera esperada:
+
.. Lleve la controladora al aviso del CARGADOR.
.. Compruebe la configuración de la variable de entorno con el `printenv` comando.
.. Si una variable de entorno no está establecida como se espera, modifíquela con el `setenv __environment-variable-name__ __changed-value__` comando.
.. Guarde los cambios mediante `savenv` comando.


. El siguiente depende de la configuración del sistema:
+
** Si su sistema tiene configurado el gestor de claves incorporado, NSE o NVE, vaya a. xref:bootmedia-encryption-restore.adoc[Restaure OKM, NSE y NVE según sea necesario]
** Si su sistema no tiene configurado el gestor de claves incorporado, NSE o NVE, complete los pasos en esta sección.


. Desde el aviso del CARGADOR, introduzca el `boot_ontap` comando.
+
[cols="1,2"]
|===
| Si ve... | Realice lo siguiente... 


 a| 
La solicitud de inicio de sesión de
 a| 
Vaya al siguiente paso.



 a| 
Esperando devolución...
 a| 
.. Inicie sesión en el controlador asociado.
.. Confirme que la controladora de destino está lista para la devolución con el `storage failover show` comando.


|===
. Conecte el cable de la consola al controlador asociado.
. Respalde la controladora con el `storage failover giveback -fromnode local` comando.
. En el símbolo del sistema del clúster, compruebe las interfaces lógicas con el `net int -is-home false` comando.
+
Si alguna interfaz se muestra como "falsa", vuelva a revertir dichas interfaces a su puerto de inicio utilizando el `net int revert` comando.

. Mueva el cable de la consola al controlador reparado y ejecute el `version -v` Comando para comprobar las versiones de ONTAP.
. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.

