---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de los sistemas de hardware de ONTAP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en los sistemas de hardware de ONTAP
      url: "/whats-new.html"
    - title: Compatibilidad de software y hardware de ONTAP
      url: "/supported-platforms.html"
    - title: Fin de soporte
      url: "/eoa-hardware.html"
  - title: Inicio rápido
    url: "/get-up-and-run.html"
  - title: Sistemas AFF
    url: "/aff-landing/index.html"
    entries:
    - title: Sistemas A-Series
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: Sistemas C-Series
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
      - section: c800
  - title: Sistemas AFX
    url: "/afx/index.html"
    entries:
    - title: Instalar y configurar
      url: "/afx/afx-install-setup.html"
    - title: Mantener
      pdf-filename: AFX Mantener
      url: "/afx-landing-maintain/index.html"
      entries:
      - title: Información general de mantenimiento
        url: "/afx-1k/maintain-overview.html"
      - title: Soporte de arranque
        pdf-filename: Medio de arranque AFX 1K
        entries:
        - title: Flujo de trabajo de sustitución de medios de arranque
          url: "/afx-1k/bootmedia-replace-workflow.html"
        - title: Revise los requisitos
          url: "/afx-1k/bootmedia-replace-requirements.html"
        - title: Apague el controlador
          url: "/afx-1k/bootmedia-shutdown.html"
        - title: Sustituir el soporte de arranque
          url: "/afx-1k/bootmedia-replace.html"
        - title: Restaurar el medio de arranque
          url: "/afx-1k/bootmedia-recovery-image-boot.html"
        - title: Devolución de pieza fallida a NetApp
          url: "/afx-1k/bootmedia-complete-rma.html"
      - title: Chasis
        pdf-filename: Chasis AFX A1K
        entries:
        - title: Flujo de trabajo de reemplazo del chasis
          url: "/afx-1k/chassis-replace-workflow.html"
        - title: Revise los requisitos
          url: "/afx-1k/chassis-replace-requirements.html"
        - title: Prepárese para reemplazar
          url: "/afx-1k/chassis-replace-prepare.html"
        - title: Apague el controlador
          url: "/afx-1k/chassis-replace-shutdown.html"
        - title: Sustituya el chasis
          url: "/afx-1k/chassis-replace-move-hardware.html"
        - title: Reemplazo completo de chasis
          url: "/afx-1k/chassis-replace-complete-system-restore-rma.html"
      - title: Controladora
        pdf-filename: Controlador AFX 1K
        entries:
        - title: Flujo de trabajo de reemplazo de la controladora
          url: "/afx-1k/controller-replace-workflow.html"
        - title: Revise los requisitos
          url: "/afx-1k/controller-replace-requirements.html"
        - title: Apague el controlador dañado
          url: "/afx-1k/controller-replace-shutdown.html"
        - title: Sustituya la controladora
          url: "/afx-1k/controller-replace-move-hardware.html"
        - title: Restaure la configuración del sistema
          url: "/afx-1k/controller-replace-system-config-restore-and-verify.html"
        - title: Proporcione a la controladora
          url: "/afx-1k/controller-replace-recable-reassign-disks.html"
        - title: Reemplazo completo de controladoras
          url: "/afx-1k/controller-replace-restore-system-rma.html"
      - title: DIMM
        url: "/afx-1k/dimm-replace.html"
      - title: Ventilador
        url: "/afx-1k/fan-replace.html"
      - title: NVRAM
        url: "/afx-1k/nvram-replace.html"
      - title: Batería de NV
        url: "/afx-1k/nvdimm-battery-replace.html"
      - title: Módulo de I/O.
        pdf-filename: Módulo de E/S AFX 1K
        entries:
        - title: Descripción general del módulo I/O.
          url: "/afx-1k/io-module-overview.html"
        - title: Agregue módulo de E/S.
          url: "/afx-1k/io-module-add.html"
        - title: Sustituya el módulo de E/S.
          url: "/afx-1k/io-module-replace.html"
      - title: Suministro de alimentación
        url: "/afx-1k/power-supply-replace.html"
      - title: Batería del reloj en tiempo real
        url: "/afx-1k/rtc-battery-replace.html"
      - title: Módulo de gestión del sistema
        url: "/afx-1k/system-management-replace.html"
  - title: Sistemas ASA
    url: "/allsan-landing/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Sistemas ASA r2
    url: "/asa-r2/index.html"
    entries:
    - title: Instalar y configurar
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: Mantener
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: Sistemas FAS
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Sistemas de fin de disponibilidad
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: asa-c250
    - section: asa-c400
    - section: asa-c800
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: Otros modelos
      url: "/other/other-models.html"
  - title: Bandejas de unidades
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: nx224
    - section: sas3
  - title: Kits de armarios y rieles
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit de guías de dos parantes AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Armario del sistema de 42U 1280 mm
      entries:
      - title: Prepare la instalación del armario
        entries:
        - title: Características del armario
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Herramientas/equipo necesarios
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Requisitos de espacio y dimensiones del armario
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Tipos y especificaciones de PDU admitidos
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Desembale el armario del sistema
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Instale el armario
        entries:
        - title: Descripción general
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Instale el kit de interconexión del armario
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Instale el kit de perno hacia abajo
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Instale los rieles de soporte
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Instale el equipo
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Encienda el armario
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Reemplace PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Puerta delantera del armario de marcha atrás
        entries:
        - title: Lo que necesita
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Retire el distintivo iluminado
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Retire la puerta del armario
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Mueva la fuente de alimentación y el cableado de la insignia
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Bisagra de la puerta de retroceso y cierre de bloqueo
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Vuelva a instalar la puerta y el indicador luminoso
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Procedimientos de sustitución por componente
    url: "/fru-reference/index.html"
    entries:
    - title: Soporte de arranque
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: Módulo de almacenamiento en caché
      url: "/fru-reference/caching-module-fru-links.html"
    - title: Chasis
      url: "/fru-reference/chassis-fru-links.html"
    - title: Controladora
      url: "/fru-reference/controller-fru-links.html"
    - title: Módulo de potencia DCPM
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: Unidad
      url: "/fru-reference/drive-fru-links.html"
    - title: Ventilador
      url: "/fru-reference/fan-fru-links.html"
    - title: Módulo de I/O.
      url: "/fru-reference/io-module-fru-links.html"
    - title: Módulo LED
      url: "/fru-reference/led-module-fru-links.html"
    - title: Entresuelo
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: Batería NVMEM/ NVRAM
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: Módulo de NVRAM
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: NSM
      url: "/fru-reference/nsm-fru-links.html"
    - title: Tarjetas PCI y risers
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: Suministro de alimentación
      url: "/fru-reference/power-supply-fru-links.html"
    - title: Batería RTC
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: Módulo de gestión del sistema
      url: "/fru-reference/system-management-fru-links.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
