---
settings:
  search: ontap-systems
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de los sistemas de hardware de ONTAP
    url: "/index.html"
  - title: Notas de la versión
    url: "/rel-notes.html"
  - title: Manos a la obra
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Póngase en marcha
      url: "/get-up-and-run.html"
  - title: Sistemas A-Series de AFF
    url: "/aff-aseries/index.html"
    entries:
    - section: a150
    - section: a200
    - section: a250
    - section: a400
    - section: a700
    - section: a800
    - section: a900
  - title: Sistemas C-Series de AFF
    url: "/aff-cseries/index.html"
    entries:
    - section: c190
    - section: c250
    - section: c400
    - section: c800
  - title: Sistemas A-Series de ASA
    url: "/allsan-a-series/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Sistemas C-Series de ASA
    url: "/allsan-c-series/index.html"
    entries:
    - section: asa-c250
    - section: asa-c-400
    - section: asa-c800
  - title: Sistemas FAS
    url: "/fas/index.html"
    entries:
    - section: fas500f
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9000
    - section: fas9500
  - title: Sistemas de fin de disponibilidad
    url: "/endofavail/index.html"
    entries:
    - section: a220
    - section: a300
    - section: a320
    - section: a700s
    - section: fas2600
    - section: fas8200
    - section: other
  - title: Bandejas de unidades
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: sas3
  - title: Kits de armarios y rieles
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit de guías de dos parantes AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Armario del sistema de 42U 1280 mm
      entries:
      - title: Prepare la instalación del armario
        entries:
        - title: Características del armario
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Herramientas/equipo necesarios
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Requisitos de espacio y dimensiones del armario
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Tipos y especificaciones de PDU admitidos
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Desembale el armario del sistema
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Instale el armario
        entries:
        - title: Descripción general
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Instale el kit de interconexión del armario
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Instale el kit de perno hacia abajo
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Instale los rieles de soporte
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Instale el equipo
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Encienda el armario
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Reemplace PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Puerta delantera del armario de marcha atrás
        entries:
        - title: Lo que necesita
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Retire el distintivo iluminado
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Retire la puerta del armario
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Mueva la fuente de alimentación y el cableado de la insignia
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Bisagra de la puerta de retroceso y cierre de bloqueo
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Vuelva a instalar la puerta y el indicador luminoso
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
