---
sidebar: sidebar 
permalink: supported-platforms.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Obtenga información sobre la versión de ONTAP compatible con la plataforma o la bandeja. 
---
= Compatibilidad de software y hardware de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Los sistemas de almacenamiento de ONTAP son compatibles con varias versiones del software ONTAP. Obtenga más información sobre las versiones de ONTAP compatibles con los sistemas de almacenamiento y las bandejas de unidades.

El soporte completo de configuración y las limitaciones de los sistemas de hardware de ONTAP están disponibles en  https://hwu.netapp.com["Hardware Universe de NetApp"]. Los detalles sobre problemas conocidos, limitaciones y precauciones de actualización en el software ONTAP 9 están disponibles en https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP 9"].

[role="tabbed-block"]
====
.Sistemas AFF
--
Los sistemas AFF A-Series y AFF C-Series proporcionan una plataforma sólida de escalabilidad horizontal adaptada para entornos virtualizados. Pueden ponerse en marcha como sistemas independientes o como niveles de alto rendimiento en configuraciones de NetApp ONTAP. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Obtenga más información acerca de los sistemas AFF"].

Los sistemas AFF A-Series y AFF C-Series se admiten a partir de las versiones de ONTAP siguientes.

ONTAP 9.16.1::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* A800 de AFF


--


--
.Sistemas ASA r2
--
Los sistemas R2 de ASA ofrecen una solución de hardware y software unificada que crea una experiencia simplificada específica para las necesidades de los clientes de SAN exclusivamente. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].

Los sistemas ASA R2 son compatibles a partir de las siguientes versiones de ONTAP.

ONTAP 9.16.1::
+
--
* ASA A20
* ASA A30
* ASA A50
* ASA C30


--
ONTAP 9.16.0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.Sistemas ASA
--
Los sistemas ASA A-Series y ASA C-Series proporcionan una experiencia SAN simplificada y dedicada que ofrece disponibilidad continua de datos para bases de datos de misión crítica para la empresa y otras cargas de trabajo SAN mediante el protocolo iSCSI o la certificación FCP. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Obtenga más información sobre los sistemas ASA"].

Los sistemas ASA son compatibles a partir de las siguientes versiones de ONTAP.

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9.7::
+
--
* ASA AFF A400


--


--
.Sistemas FAS
--
Los sistemas FAS proporcionan almacenamiento secundario seguro y eficiente, la solución definitiva para la clasificación en niveles, el backup y la recuperación ante desastres. link:https://www.netapp.com/data-storage/fas/["Obtenga más información acerca de los sistemas FAS"].

Los sistemas FAS son compatibles a partir de las siguientes versiones de ONTAP.

ONTAP 9.16.1::
+
--
* FAS50


--
ONTAP 9.15.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.Bandejas de unidades
--
Las bandejas de unidades están diseñadas específicamente para sistemas NetApp AFF, ASA y FAS, y ayudan a ofrecer el rendimiento, la resiliencia y la flexibilidad que necesita su transformación digital.

Las bandejas de unidades están disponibles desde las siguientes versiones de ONTAP.

ONTAP 9.16.1:: NS224 TB con módulos de NSM100B TB
ONTAP 9.6:: Bandeja NS224 con módulos de NSM100 TB


--
====