---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, fas, aff systems 
summary: Obtenga información sobre las nuevas funciones para sistemas FAS y AFF. 
---
= Novedades de los sistemas FAS y AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga información sobre las nuevas funciones para sistemas FAS y AFF.



== Nueva compatibilidad con el adaptador

[cols="4*"]
|===
| Número de pieza del adaptador | Descripción | Categoría | Comienzo disponible 


 a| 
https://["X91148A"]
 a| 
Roce QSFP28 de 100 GbE y 2 puertos
 a| 
* Reducida
* Redes
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://["X91122A"]
 a| 
Roce QSFP28 de 25 GbE para 2 puertos
 a| 
* Redes
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://["X9170A"]
 a| 
Módulo SSD de NVMe (1 TB)
 a| 
Dispositivo de volcado de memoria
 a| 
ONTAP 9.8

|===


== Nuevo soporte de conmutador

[cols="25h,~,~"]
|===
| Interruptores | Descripción | Comienzo disponible 


 a| 
https://["Switch Cisco de 36 puertos 100 GbE (X190200)"]
 a| 
Admite una infraestructura compartida (clúster, alta disponibilidad y almacenamiento conectado a switches) en la misma pareja de switches Cisco Nexus 9336C-FX2, incluida la compatibilidad con configuraciones de IP de MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
https://["Switch Cisco de 36 puertos 100 GbE (X190200 y X190210)"]
 a| 
Compatibilidad con switches de interconexión de clúster Cisco Nexus 9336C-FX2 y switches de almacenamiento para las controladoras AFF/FAS, así como para la conectividad de los datos de interfaz.
 a| 
ONTAP 9.8



 a| 
https://["Conmutador Broadcom BES-53248 (X190005 y X190005R)"]
 a| 
Compatibilidad con el switch de interconexión de clúster Broadcom BES-53248 para controladoras AFF/FAS con puertos de 40 GbE.
 a| 
ONTAP 9.8



 a| 
https://["Switch Cisco de 36 puertos 100 GbE (X190200)"] https://["Switch Cisco de 32 puertos 100 GbE (X190100 y X190100R)"]
 a| 
El switch Cisco Nexus 100 GbE se puede utilizar como switch de almacenamiento dedicado para conectar las bandejas de unidades NVMe NS224 a las siguientes plataformas:

* ASA A800/AFF A800 de AFF
* ASA A700/AFF de AFF
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://["Conmutador Broadcom BES-53248 (X190005 y X190005R)"]
 a| 
Compatibilidad con el switch de interconexión de clústeres BES-53248 de Broadcom para controladoras AFF/FAS con puertos de 10 GbE.
 a| 
ONTAP 9.5P8

|===


== Compatibilidad con nuevas plataformas

[cols="2*"]
|===
| Plataformas (con enlaces a hojas de datos) | Comienzo disponible 


 a| 
https://["FAS9500"]
 a| 
ONTAP 9.10.1P3 y 9.11.1



 a| 
https://["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://["A800 de AFF ASA"]
 a| 
ONTAP 9.8



 a| 
https://["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://["A700 de AFF ASA"]
 a| 
ONTAP 9.7



 a| 
https://["C190 de AFF"]
 a| 
ONTAP 9.6



 a| 
https://["AFF A320"]
 a| 
ONTAP 9.6

|===


== Nueva compatibilidad de bandejas

[cols="2*"]
|===
| Bandejas | Comienzo disponible 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== Nuevas actualizaciones de hardware

[cols="25h,~,~"]
|===
| Funcionalidad | Descripción y dónde obtener más información | Comienzo disponible 


 a| 
Compatibilidad de plataformas ampliada para bandejas de unidades NS224
 a| 
Las siguientes plataformas admiten bandejas de unidades NS224:

* ASA A800/AFF A800 de AFF
* ASA A700/AFF de AFF
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9.8



 a| 
Adición en caliente de bandejas SAS de 12 GB a pilas de almacenamiento SAS de 6 GB
 a| 
Ahora se admite una transición de velocidad única de 6 GB a 12 GB en una pila de almacenamiento SAS. Esto permite la ampliación del almacenamiento de las pilas de 6 GB existentes con bandejas de 12 GB.

https://["Bandejas añadidas en caliente con módulos IOM12 a una pila de bandejas con módulos IOM6"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===


== Nuevas mejoras de actualización de hardware

Los procedimientos de actualización de hardware se han simplificado en ONTAP 9.8 con la introducción de la función de colocación automática de puertos. Al actualizar un sistema con ONTAP 9.8, debe utilizar el procedimiento correcto para tener en cuenta la función de ubicación del puerto.

Consulte la siguiente tabla para ver los procedimientos de actualización disponibles. Consulte cada guía para obtener más detalles para determinar si el procedimiento es adecuado.

Para obtener más información sobre procedimientos específicos de MetroCluster, consulte https://["Seleccione un método de actualización o actualización"].

[cols="4*"]
|===
| Versión de ONTAP | Ubicación | No disruptivas | Compatible con MetroCluster 


 a| 
de 9.8 a 9.0.x
 a| 
https://["Guía exprés de actualización del hardware de la controladora"] (Moviendo el almacenamiento físico existente)
 a| 
No
 a| 
No



 a| 
https://["Guía exprés de actualización del hardware de la controladora"] (Mover volúmenes a nuevo almacenamiento)
 a| 
Sí
 a| 
No



 a| 
9.8
 a| 
https://["Utilizar comandos «system Controller replace» para actualizar el hardware de la controladora que ejecuta ONTAP 9.8"]
 a| 
Sí
 a| 
Sí (FC)



 a| 
9.8
 a| 
https://["Utilice la reubicación de agregados para actualizar manualmente el hardware de la controladora que ejecuta ONTAP 9.8 o posterior"]
 a| 
Sí
 a| 
Sí (FC)



 a| 
9.7 a 9.5
 a| 
https://["Utilizar comandos «system Controller replace» para actualizar el hardware de la controladora que ejecuta ONTAP 9.5 a ONTAP 9.7"]
 a| 
Sí
 a| 
Sí (FC)



 a| 
9.7 y anteriores
 a| 
https://["Actualizar controladoras con reubicación de agregados a Actualizar manualmente hardware de controladora que ejecuta ONTAP 9.7 y versiones anteriores"]
 a| 
Sí
 a| 
Sí (FC)

|===