---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Obtenga información sobre las nuevas plataformas para sistemas de hardware de ONTAP. 
---
= Novedades en los sistemas de hardware de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de los sistemas de hardware de ONTAP.



== Mayo de 2025



=== ASA C30

El nuevo sistema ASA C30 extiende las capacidades de gestión de datos inteligentes, integrales y de alto rendimiento a más clientes y cargas de trabajo.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].



== Abril de 2025



=== FAS50

El sistema FAS50 ofrece el menor coste por gigabyte para el almacenamiento secundario y link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html["almacén cibernético seguro"]un mayor rendimiento para cargas de trabajo secundarias con backups más rápidos, mayor tasa de IOPS y una baja latencia de 5–10ms ms.

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Obtenga más información acerca de los sistemas FAS"].



== Febrero de 2025



=== ASA A20, ASA A30 y ASA A50

Los sistemas de gama básica ASA A20 y ASA A30 y A50 de gama media hacen que el almacenamiento basado en bloques esté disponible para empresas de cualquier tamaño para aplicaciones de misión crítica, como bases de datos y máquinas virtuales.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].



== Diciembre de 2024



=== AFF A20, AFF A30 y AFF A50

Los nuevos sistemas de hardware A20, A30 y A50 de AFF amplían las capacidades de gestión de datos inteligentes y completas de alto rendimiento a más clientes y cargas de trabajo.

Los sistemas ofrecen detección de ransomware basada EN ML en tiempo real, integración fluida del cloud y rendimiento sin igual para cargas de trabajo críticas como IA, VMware, bases de datos y análisis con soporte para almacenamiento de bloques, archivos y objetos.

link:https://www.netapp.com/data-storage/aff-a-series/["Obtenga más información sobre los sistemas A-Series de AFF"].



=== AFF C30, AFF C60 y AFF C80

Los nuevos sistemas de hardware AFF C30, AFF C60 y AFF C80 ofrecen a las empresas un mayor acceso a los beneficios de rendimiento y eficiencia del flash, al proporcionar 1,5PB PB de capacidad de almacenamiento líderes en el sector en puestas en marcha de dos racks.

La solución ofrece una densidad excepcional con unidades de 60TB TB, mayor rendimiento y una mejor flexibilidad de I/O.

link:https://www.netapp.com/data-storage/aff-c-series/["Obtenga más información sobre los sistemas C-Series de AFF"].



=== Bandeja de unidades NS224 con módulos de bandeja NSM100B

Mejore las funcionalidades de su centro de datos con el NS224 y el nuevo módulo de expansión del almacenamiento NSM100B NVMe. Diseñado como sustituto directo para el módulo NSM100, el nuevo módulo de bandeja NSM100B se integra sin problemas en su configuración existente. Es compatible con configuraciones de conexión directa y de conexión por switch de bandejas NS224, lo que proporciona una flexibilidad excepcional para optimizar la eficiencia y escalabilidad de su sistema de almacenamiento.



== Septiembre de 2024



=== Sistemas ASA r2

Los nuevos sistemas de hardware ASA R2 (ASA A1K, ASA A70 y ASA A90) ofrecen una solución de hardware y software unificada que crea una experiencia simplificada específica para las necesidades de los clientes exclusivos de SAN.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].



=== FAS70 y FAS90

Los nuevos sistemas de hardware FAS70 y FAS90 ofrecen un almacenamiento de backup asequible pero de alto rendimiento, lo que permite un cibervault seguro para la recuperación de ataques de ransomware.

link:https://www.netapp.com/data-storage/fas/["Obtenga más información acerca de los sistemas FAS"].
