---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, fas, aff systems 
summary: Obtenga más información sobre las nuevas funciones de los sistemas AFF, ASA y FAS. 
---
= Novedades en los sistemas AFF, ASA y FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga más información sobre las nuevas funciones de los sistemas AFF, ASA y FAS.



== Compatibilidad con nuevas plataformas

[cols="2*"]
|===
| Plataformas (con enlaces a hojas de datos) | Comienzo disponible 


 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9,13.P11



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA y versiones posteriores de ONTAP

[NOTE]
====
Estas plataformas no son compatibles con ONTAP 9.13.1 RC1.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
No intente instalar o arrancar el sistema de almacenamiento AFF A150 con una versión no compatible de ONTAP. Si intenta instalar o iniciar el sistema con una versión no compatible de ONTAP, ONTAP lo permitirá (ONTAP no bloqueará el intento). El resultado es que su sistema de almacenamiento A150 de AFF se presentara como un sistema de almacenamiento FAS2750.

==== a| 
ONTAP 9.13.1 y versiones posteriores de ONTAP

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["A800 de AFF ASA"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["A700 de AFF ASA"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/us/media/ds-3989.pdf["C190 de AFF"]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===


== Nuevo soporte de conmutador

[cols="20,65,15"]
|===
| Interruptores | Descripción | Comienzo disponible 


 a| 
https://hwu.netapp.com/Switch/Index["SWITCH NVIDIA IP SN2100"]
 a| 
El switch de almacenamiento NVIDIA IP SN2100 es compatible con configuraciones IP de MetroCluster que usan las plataformas A900/FAS9500.
 a| 
ONTAP 9.12.1



 a| 
https://hwu.netapp.com/Switch/Index["SWITCH NVIDIA IP SN2100 (X190006)"]
 a| 
El switch de almacenamiento NVIDIA IP SN2100 es compatible con las configuraciones IP de MetroCluster que utilizan las siguientes plataformas:

* FAS500f/AFF A250
* FAS8300/AFF A400
* FAS8700
* FAS9000/AFF A700
* A800 de AFF

 a| 
ONTAP 9.10.1P3



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 puertos 100 GbE (X190200)"]
 a| 
Admite una infraestructura compartida (clúster, alta disponibilidad y almacenamiento conectado a switches) en la misma pareja de switches Cisco Nexus 9336C-FX2, incluida la compatibilidad con configuraciones de IP de MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 puertos 100 GbE (X190200 y X190210)"]
 a| 
Compatibilidad con switches de interconexión de clúster Cisco Nexus 9336C-FX2 y switches de almacenamiento para las controladoras AFF/FAS, así como para la conectividad de los datos de interfaz.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Conmutador Broadcom BES-53248 (X190005 y X190005R)"]
 a| 
Compatibilidad con el switch de interconexión de clúster Broadcom BES-53248 para controladoras AFF/FAS con puertos de 40 GbE.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 puertos 100 GbE (X190200)"] https://hwu.netapp.com/Switch/Index["Switch Cisco de 32 puertos 100 GbE (X190100 y X190100R)"]
 a| 
El switch Cisco Nexus 100 GbE se puede utilizar como switch de almacenamiento dedicado para conectar las bandejas de unidades NVMe NS224 a las siguientes plataformas:

* ASA A800/AFF A800 de AFF
* ASA A700/AFF de AFF
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Conmutador Broadcom BES-53248 (X190005 y X190005R)"]
 a| 
Compatibilidad con el switch de interconexión de clústeres BES-53248 de Broadcom para controladoras AFF/FAS con puertos de 10 GbE.
 a| 
ONTAP 9.5P8

|===


== Nueva compatibilidad con el adaptador

[cols="4*"]
|===
| Número de pieza del adaptador | Descripción | Categoría | Comienzo disponible 


 a| 
https://hwu.netapp.com/adapter/index["X91148A"]
 a| 
Roce QSFP28 de 100 GbE y 2 puertos
 a| 
* Reducida
* Redes
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
Roce QSFP28 de 25 GbE para 2 puertos
 a| 
* Redes
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
Módulo SSD de NVMe (1 TB)
 a| 
Dispositivo de volcado de memoria
 a| 
ONTAP 9.8

|===


== Nueva compatibilidad de bandejas

[cols="2*"]
|===
| Bandejas | Comienzo disponible 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== Nuevas actualizaciones de hardware

[cols="25h,~,~"]
|===
| Funcionalidad | Descripción y dónde obtener más información | Comienzo disponible 


 a| 
Compatibilidad de plataformas ampliada para bandejas de unidades NS224
 a| 
Las siguientes plataformas admiten bandejas de unidades NS224:

* ASA A800/AFF A800 de AFF
* ASA A700/AFF de AFF
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9.8



 a| 
Adición en caliente de bandejas SAS de 12 GB a pilas de almacenamiento SAS de 6 GB
 a| 
Ahora se admite una transición de velocidad única de 6 GB a 12 GB en una pila de almacenamiento SAS. Esto permite la ampliación del almacenamiento de las pilas de 6 GB existentes con bandejas de 12 GB.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Bandejas añadidas en caliente con módulos IOM12 a una pila de bandejas con módulos IOM6"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===