---
permalink: asa400/install-videos.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Vídeos - ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

.Animación: Instrucciones de instalación y configuración de AFF A400
video::6cbbcb96-fe92-4040-a004-ab2001624dd7[panopto]

NOTE: El ASA A400 utiliza el mismo procedimiento de instalación que el sistema AFF A400.



== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]