---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: Antes de sustituir el medio de arranque en su sistema AFF C80, asegúrese de contar con el dispositivo de arranque de reemplazo correcto, acceso al firmware del sistema y al software ONTAP y una copia de seguridad de los datos de configuración esenciales. 
---
= Requisitos de sustitución de soportes de arranque: AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el medio de arranque en su sistema AFF C80, asegúrese de contar con el dispositivo de arranque de reemplazo correcto, acceso al firmware del sistema y al software ONTAP y una copia de seguridad de los datos de configuración esenciales.

Revise los siguientes requisitos.

* Debe tener una unidad flash USB, formateada a FAT32, con la cantidad de almacenamiento adecuada para guardar el `image_xxx.tgz` archivo.
* Debe copiar `image_xxx.tgz` el archivo en la unidad flash USB para su uso posterior en este procedimiento.
* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El controlador _drinated_ es el controlador en el que está realizando tareas de mantenimiento.
** El controlador _heated_ es el compañero de alta disponibilidad del controlador dañado.



