---
permalink: c80/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a1k, prerequisite, replace the controller module 
summary: Antes de sustituir la controladora en su sistema AFF C80, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto. 
---
= Requisitos para sustituir el controlador - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir la controladora en su sistema AFF C80, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto.

Revise los requisitos para sustituir el módulo del controlador.

* Todas las bandejas de unidades deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* No utilice este procedimiento para las actualizaciones de la controladora; consulte la https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Seleccione el procedimiento de actualización del hardware de la controladora"] para obtener orientación.
* Si su sistema tiene una configuración MetroCluster, debe revisar https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"] para determinar si debe usar este procedimiento.
* Debe sustituir el componente con errores por la unidad reemplazable del sector (FRU) que ha recibido de NetApp.
* Debe sustituir un módulo de controladora por un módulo de controladora del mismo tipo de modelo. No puede actualizar su sistema simplemente reemplazando el módulo del controlador.
* No es posible cambiar ninguna unidad o bandeja de unidades como parte de este procedimiento.
* Debido a que el dispositivo de inicio está ubicado en el módulo de administración del sistema que está instalado en la parte posterior del sistema, no es necesario mover el dispositivo de arranque al reemplazar un módulo de controlador.
* Es importante que aplique los comandos de estos pasos en los sistemas correctos:
+
** El controlador _drinated_ es el controlador que se va a sustituir.
** El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
** El controlador _heated_ es el controlador que sobrevive.


* Siempre debe capturar la salida de consola de la controladora en un archivo de registro de texto.
+
Esto proporciona un registro del procedimiento para poder solucionar los problemas que puedan surgir durante el proceso de reemplazo.



.El futuro
Después de haber revisado los requisitos para reemplazar su controlador AFF C80, es necesario link:controller-replace-shutdown.html["apague el controlador defectuoso"].
