---
permalink: c80/install-hardware.html 
sidebar: sidebar 
keywords: aff c80, install hardware, telco rack 
summary: Instale su sistema de almacenamiento en un armario o rack de telecomunicaciones. 
---
= Instale la tornillería - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de prepararse para instalar el sistema de almacenamiento AFF C80, instale el hardware para el sistema. En primer lugar, instale los kits de guías. A continuación, instale y proteja su sistema de almacenamiento en un armario o rack de telecomunicaciones.

Omita este paso si el armario está rellenado previamente.

.Antes de empezar
* Asegúrese de tener las instrucciones incluidas en el kit de guías.
* Tenga en cuenta los problemas de seguridad asociados con el peso del sistema de almacenamiento y el estante.
* Comprenda que el flujo de aire a través del sistema de almacenamiento entra desde la parte frontal donde se instalan las tapas de la cubierta protectora o de los extremos y sale de la parte posterior donde se encuentran los puertos.


.Pasos
. Instale los kits de rieles para el sistema de almacenamiento y las bandejas según sea necesario, siguiendo las instrucciones incluidas con los kits.
. Instale y proteja su sistema de almacenamiento en el armario o el rack de telecomunicaciones:
+
.. Coloque el sistema de almacenamiento en los rieles situados en el centro del armario o rack de telecomunicaciones, y luego apoye el sistema de almacenamiento desde la parte inferior y deslícelo en su lugar.
.. Asegúrese de que las clavijas guía del armario o del bastidor de telecomunicaciones estén aisladas en las ranuras de guía del chasis.
.. Fije el sistema de almacenamiento al armario o al rack de telecomunicaciones con los tornillos de montaje incluidos.


. Conecte el panel frontal a la parte frontal del sistema de almacenamiento.
. Conecte los dispositivos de gestión de cables a la parte posterior del sistema de almacenamiento.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Instale el dispositivo de gestión de cables]

. Instale y fije la bandeja según sea necesario.
+
.. Coloque la parte posterior de la bandeja en los rieles, y luego sostenga la bandeja desde la parte inferior y deslícela en el armario o rack de telecomunicaciones.
+
Si va a instalar varias bandejas, coloque la primera bandeja directamente encima de las controladoras. Coloque la segunda bandeja directamente debajo de las controladoras. Repita este patrón para todas las bandejas adicionales.

.. Fije la bandeja al armario o al rack Telco con los tornillos de montaje incluidos.
+
.El futuro
Después de haber instalado el hardware para su sistema AFF C80, ustedlink:install-cable.html["Conecte los cables del hardware del sistema de almacenamiento AFF C80"].




