---
permalink: fas2700/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: fas2700, aff a220, replace, boot, media, image, nondisruptive, disruptive, replacement, fat32, usb, manual, manual boot recovery 
summary: 'Obtenga información sobre el reemplazo de medios de arranque en un sistema FAS2700 y comprenda los diferentes métodos de reemplazo. El medio de arranque almacena archivos de imagen de arranque primarios y secundarios que el sistema utiliza durante el inicio. Dependiendo de la configuración de su red, puede realizar un reemplazo no disruptivo (par HA conectado a la red) o un reemplazo disruptivo (requiere dos reinicios).' 
---
= Descripción general del reemplazo del medio de arranque - FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga información sobre el reemplazo de medios de arranque en un sistema FAS2700 y comprenda los diferentes métodos de reemplazo.

El medio de arranque almacena archivos de imagen de arranque primarios y secundarios que el sistema utiliza durante el inicio. Dependiendo de la configuración de su red, puede realizar un reemplazo no disruptivo (par HA conectado a la red) o un reemplazo disruptivo (requiere dos reinicios).

El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca. En función de la configuración de red, puede realizar una sustitución no disruptiva o disruptiva.

[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====
Debe tener una unidad flash USB, formateada a FAT32, con la cantidad de almacenamiento adecuada para guardar el `image_xxx.tgz` archivo.

También debe copiar el `image_xxx.tgz` Archivo a la unidad flash USB para su uso posterior en este procedimiento.

* Ambos métodos no disruptivos y disruptivos para reemplazar medios de arranque requieren restaurar el `var` sistema de archivos:
+
** Para poder realizar sustituciones de forma no disruptiva, el par de alta disponibilidad debe estar conectado a una red para restaurar el `var` sistema de archivos.
** Para el reemplazo disruptivo, no es necesaria una conexión de red para restaurar el `var` el sistema de archivos, pero el proceso requiere dos reinicios.


* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en el nodo correcto:
+
** El nodo _drinated_ es el nodo en el que realiza tareas de mantenimiento.
** El _heated node_ es el partner de alta disponibilidad del nodo dañado.



