---
permalink: fas2700/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas2700, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Antes de sustituir el chasis de tu sistema FAS2700, revisa los requisitos necesarios para que la sustitución sea exitosa. El procedimiento de sustitución del chasis mueve todas las fuentes de alimentación, las unidades y los módulos controladores del chasis con problemas al chasis de reemplazo, y es una operación disruptiva. 
---
= Revisa los requisitos antes de sustituir el chasis de tu FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema FAS2700, revisa los requisitos necesarios para que la sustitución sea exitosa. El procedimiento de sustitución del chasis mueve todas las fuentes de alimentación, las unidades y los módulos controladores del chasis con problemas al chasis de reemplazo, y es una operación disruptiva.

Para sustituir el chasis, debe mover las fuentes de alimentación, las unidades de disco duro y el módulo o los módulos de la controladora del chasis dañado al nuevo chasis, y cambiar el chasis dañado del bastidor del equipo o del armario del sistema por el nuevo chasis del mismo modelo que el chasis dañado.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover todas las unidades y módulos o módulos de controladora al nuevo chasis, y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos controladoras, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

