---
sidebar: sidebar 
permalink: fru-reference/io-module-fru-links.html 
keywords: I/O module, field replaceable units, FRU, I/O module replacement 
summary: Encuentre los procedimientos de reemplazo de módulos de E/S para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos de E/S paso a paso para sistemas AFF, ASA y FAS para ayudarlo a localizar rápidamente el procedimiento correcto para su modelo específico. 
---
= Procedimientos de reemplazo de módulos de E/S por familia de plataformas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encuentre los procedimientos de reemplazo de módulos de E/S para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos de E/S paso a paso para sistemas AFF, ASA y FAS para ayudarlo a localizar rápidamente el procedimiento correcto para su modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a1k/io-module-replace.html["AFF A1K"]
* link:../a20-30-50/io-module-replace.html["AFF A20/30/50"]
* link:../a70-90/io-module-replace.html["AFF A70/90"]
* link:../c30-60/io-module-replace.html["AFF C30/60"]
* link:../c80/io-module-replace.html["AFF C80"]


--
.Sistemas ASA
--
* link:../asa-r2-a1k/io-module-replace.html["ASA A1K"]
* link:../asa-r2-a20-30-50/io-module-replace.html["ASA A20/30/50"]
* link:../asa-r2-70-90/io-module-replace.html["ASA 70/90"]
* link:../asa-r2-c30/io-module-replace.html["ASA C30"]


--
.Sistemas FAS
--
* link:../fas50/io-module-replace.html["FAS50"]
* link:../fas-70-90/io-module-replace.html["FAS70/90"]


--
====