---
sidebar: sidebar 
permalink: fru-reference/nvdimm-fru-links.html 
keywords: NVDIMM, field replaceable units, FRU, NVDIMM replacement 
summary: Encuentre los procedimientos de reemplazo de NVDIMM para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de NVDIMM paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico. 
---
= Procedimientos de reemplazo de NVDIMM por familia de plataformas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encuentre los procedimientos de reemplazo de NVDIMM para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de NVDIMM paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a320/nvdimm-replace.html["AFF A320"]
* link:../a400/nvdimm-replace.html["AFF A400"]
* link:../a800/nvdimm-replace.html["A800 de AFF"]
* link:../c400/nvdimm-replace.html["AFF C400"]
* link:../c800/nvdimm-replace.html["AFF C800"]


--
.Sistemas ASA
--
* link:../asa400/nvdimm-replace.html["ASA A400"]
* link:../asa800/nvdimm-replace.html["ASA A800"]
* link:../asa-c400/nvdimm-replace.html["ASA C400"]
* link:../asa-c800/nvdimm-replace.html["ASA C800"]


--
.Sistemas FAS
--
* link:../fas8300/nvdimm-replace.html["FAS8300"]


--
====