---
sidebar: sidebar 
permalink: fru-reference/nvram-module-fru-links.html 
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement 
summary: Encuentre los procedimientos de reemplazo del módulo NVRAM para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos NVRAM paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico. 
---
= Procedimientos de reemplazo del módulo NVRAM por familia de plataformas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encuentre los procedimientos de reemplazo del módulo NVRAM para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos NVRAM paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a1k/nvram-replace.html["AFF A1K"]
* link:../a70-90/nvram-replace.html["AFF A70/90"]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html["A700 de AFF"]
* link:../a700s/nvram-or-nvram-dimm-replacement.html["A700s de AFF"]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html["AFF A900"]
* link:../c80/nvram-replace.html["AFF C80"]


--
.Sistemas ASA
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html["ASA A900"]
* link:../asa-r2-a1k/nvram-replace.html["ASA A1K"]
* link:../asa-r2-70-90/nvram-replace.html["ASA 70/90"]


--
.Sistemas FAS
--
* link:../fas-70-90/nvram-replace.html["FAS70/90"]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html["FAS9000"]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html["FAS9500"]


--
====