---
sidebar: sidebar 
permalink: fru-reference/pci-cards-fru-links.html 
keywords: PCI cards, risers, field replaceable units, FRU, PCI replacement 
summary: Encuentre procedimientos de reemplazo de tarjetas PCI y elevadores para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de tarjetas PCI y elevadores paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico. 
---
= Procedimientos de reemplazo de tarjetas PCI y risers por familia de plataformas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encuentre procedimientos de reemplazo de tarjetas PCI y elevadores para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de tarjetas PCI y elevadores paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a300/pci-cards-and-risers-replace.html["AFF A300"]
* link:../a320/pci-cards-and-risers-replace.html["AFF A320"]
* link:../a400/pci-cards-and-risers-replace.html["AFF A400"]
* link:../a700/pci-cards-and-risers-replace.html["A700 de AFF"]
* link:../a700s/pci-cards-and-risers-replace.html["A700s de AFF"]
* link:../a800/pci-cards-and-risers-replace.html["A800 de AFF"]
* link:../c400/pci-cards-and-risers-replace.html["AFF C400"]
* link:../c800/pci-cards-and-risers-replace.html["AFF C800"]


--
.Sistemas ASA
--
* link:../asa400/pci-cards-and-risers-replace.html["ASA A400"]
* link:../asa800/pci-cards-and-risers-replace.html["ASA A800"]
* link:../asa-c400/pci-cards-and-risers-replace.html["ASA C400"]
* link:../asa-c800/pci-cards-and-risers-replace.html["ASA C800"]


--
.Sistemas FAS
--
* link:../fas2800/pci-cards-and-risers-replace.html["FAS2800"]
* link:../fas8200/pci-cards-and-risers-replace.html["FAS8200"]
* link:../fas8300/pci-cards-and-risers-replace.html["FAS8300"]
* link:../fas9000/pci-cards-and-risers-replace.html["FAS9000"]


--
====