---
sidebar: sidebar 
permalink: fru-reference/system-management-fru-links.html 
keywords: system management module, field replaceable units, FRU, system management replacement 
summary: Encuentre los procedimientos de reemplazo del módulo de administración del sistema para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos de gestión del sistema paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico. 
---
= Procedimientos de reemplazo del módulo de gestión del sistema por familia de plataformas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encuentre los procedimientos de reemplazo del módulo de administración del sistema para su sistema de almacenamiento NetApp organizados por familia de plataformas.  Esta referencia proporciona enlaces directos a flujos de trabajo de reemplazo de módulos de gestión del sistema paso a paso para sistemas AFF, ASA y FAS para ayudarlo a encontrar rápidamente el procedimiento correcto para su modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a1k/system-management-replace.html["AFF A1K"]
* link:../a70-90/system-management-replace.html["AFF A70/90"]
* link:../c80/system-management-replace.html["AFF C80"]


--
.Sistemas ASA
--
* link:../asa-r2-a1k/system-management-replace.html["ASA A1K"]
* link:../asa-r2-70-90/system-management-replace.html["ASA 70/90"]


--
.Sistemas FAS
--
* link:../fas-70-90/system-management-replace.html["FAS70/90"]


--
====