---
permalink: platform-supplemental/42u-1280mm-remove-door.html 
sidebar: sidebar 
keywords: remove, system, cabinet, door, side, panel, illuminate, badge, component, reverse, door, remove the system cabinet door 
summary: Debe retirar la puerta del armario del sistema y los paneles laterales para mover el distintivo y los componentes iluminados y para invertir la puerta. 
---
= Retire la puerta del armario del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe retirar la puerta del armario del sistema y los paneles laterales para mover el distintivo y los componentes iluminados y para invertir la puerta.

. Abra la puerta del armario del sistema si aún no está abierta.
. Realice las acciones adecuadas en función de si sus armarios están conectados con el kit de interconexión.
+
[cols="1,2"]
|===
| Si el armario del sistema es... | Realice lo siguiente... 


 a| 
No está conectado a otro armario del sistema
 a| 
Vaya al paso siguiente.



 a| 
Conectado a otro armario del sistema con un kit de interconexión
 a| 
Retire los cuatro soportes del kit de interconexión y coloque los soportes y tornillos en un lugar seguro.

|===
. Desbloquee los dos paneles laterales, desconecte los cables de conexión a tierra de los paneles laterales y, a continuación, extráigalos y déjelos a un lado.
. Desconecte el cable de conexión a tierra de la toma de tierra situada en la parte superior de la puerta.
. Desatornille el conjunto de cable y la lengüeta de conexión a tierra del bastidor del armario del sistema y colóquelo a un lado.
. Desenrosque el conjunto de la lengüeta de conexión a tierra de la puerta del armario del sistema y colóquelo a un lado.
. Levante el pasador de la bisagra superior hasta que salga de la parte inferior de la bisagra.
. Incline suavemente la parte superior de la puerta para separarla del bastidor del armario del sistema y, a continuación, suelte el pasador de bisagra.
. Levante la puerta de la bisagra inferior y coloque la puerta a un lado.

