---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: Debe conectar los componentes del sistema a las PDU, enrutar los cables PDU a las fuentes de alimentación de CA, conectarlos a las fuentes de alimentación y encender el sistema. 
---
= Encienda el armario del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conectar los componentes del sistema a las PDU, enrutar los cables PDU a las fuentes de alimentación de CA, conectarlos a las fuentes de alimentación y encender el sistema.

Debe tener circuitos de alimentación separados disponibles para cada PDU del armario del sistema.

. Conecte el equipo a las PDU y asegúrese de conectar las fuentes de alimentación de cada componente a una PDU en lados opuestos del armario del sistema.
. Introduzca los cables de alimentación de la PDU a través de una abertura en el armario del sistema.
+
Utilice una de las siguientes aperturas:

+
** La parte superior del armario del sistema
** Entre la parte inferior de la puerta trasera y el bastidor del armario del sistema
** A través de la abertura del suelo y debajo del armario del sistema


. Apague los interruptores de alimentación o los disyuntores de las PDU.
. Conecte cada cable de alimentación de la PDU a fuentes de alimentación de CA individuales que estén en circuitos de CA separados.
. Encienda los interruptores de alimentación o los disyuntores a las PDU.
. Encienda la alimentación de sus componentes y, a continuación, arranque el sistema.
. Cierre y bloquee las puertas del armario del sistema.

