---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: El armario del sistema consta de paneles laterales, puertas delanteras y traseras, un kit opcional de desatornillado, un kit de interconexión opcional, PDU para su equipo y un sistema integrado de gestión de cables. 
---
= Características del armario del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El armario del sistema consta de paneles laterales, puertas delanteras y traseras, un kit opcional de desatornillado, un kit de interconexión opcional, PDU para su equipo y un sistema integrado de gestión de cables.

[cols="1,2"]
|===
| Función | Descripción 


 a| 
Paneles laterales
 a| 
Los armarios del sistema tienen paneles laterales bloqueables, extraíbles e intercambiables.



 a| 
Puertas delanteras y traseras perforadas
 a| 
Los armarios del sistema tienen puertas delanteras y traseras desmontables con un mecanismo de liberación rápida. La puerta delantera es reversible y las puertas traseras están divididas. Ambas puertas están perforadas para refrigerar.



 a| 
Clave común
 a| 
Esta llave desbloquea las puertas delanteras, las puertas traseras y los paneles laterales.



 a| 
Kit de repuestos
 a| 
Este kit está dentro del armario del sistema, conectado a la puerta del armario. Contiene los siguientes componentes:

* Cuatro tornillos piloto Phillips de 10-32 x 0.75 pulgadas
* Cuatro tuercas de jaula de 10-32
* Una herramienta de inserción de tuercas de jaula
* Dos copias principales




 a| 
Acceso por cable
 a| 
Los pasantes de cables están integrados en la parte superior e inferior del armario, así como entre la parte inferior de la puerta trasera y el bastidor.



 a| 
Gestión de cables
 a| 
El gancho para la gestión de cables y las correas se conectan a la estructura del armario del sistema a intervalos iguales.



 a| 
Rieles de soporte
 a| 
La cantidad de rieles de soporte que reciba depende de la configuración. El armario vacío del sistema se envía sin rieles de soporte instalados.

* Para los armarios de sistema configurados, se incluye un kit de raíl fijo con el armario del sistema para admitir los soportes de retención traseros 80xx, FAS8200 y DS4486.
* Los armarios de sistema de envío rápido no incluyen el kit de raíl fijo adicional.




 a| 
Paneles de relleno
 a| 
El número y el tamaño de los paneles de limpieza que recibe depende de su configuración. El armario vacío del sistema se envía sin paneles de limpieza instalados.



 a| 
Kit de perno hacia abajo
 a| 
Este kit opcional le permite fijar el armario del sistema a la planta central de datos. El kit no está diseñado para la estabilidad sísmica.

* Cuatro soportes atornillados
* Cuatro soportes espaciadores
* Seis pernos de cabeza hexagonal M8x20 mm y arandelas




 a| 
Kit de interconexión
 a| 
Este kit opcional le permite conectar varios armarios de sistema entre sí.

* Los soportes de interconexión
+
** Un juego de cuatro soportes de interconexión para conectar los armarios del sistema con paneles laterales en
** Un juego de cuatro soportes de interconexión para conectar los armarios del sistema con los paneles laterales apagados


* Cuatro tornillos M12x20 Torx-30 utilizados en el armario del sistema con paneles laterales activados.
* Ocho tornillos avellanados M6x10 Torx-30 utilizados en el armario del sistema con paneles laterales apagados.




 a| 
Kit de rieles de soporte
 a| 
Si ha pedido rieles de soporte adicionales con su armario del sistema, cada kit contiene un raíl de soporte izquierdo y uno derecho.


NOTE: Los raíles de soporte y el kit están diseñados para ajustarse únicamente al armario del sistema de 42U de 1280 mm de NetApp. No utilice los raíles ni un kit de raíl de otros armarios del sistema porque no están diseñados para su uso en el armario del sistema de 42U de 1280 mm.

* Un riel de soporte izquierdo y derecho
* Dos tornillos por riel para fijar el riel al bastidor del armario del sistema




 a| 
Llave de vaso
 a| 
La llave de la media luna se utiliza para retirar los soportes de sujeción del palé de embalaje, ajustar las patas de nivelación del armario del sistema e instalar los soportes del kit de perno, si se solicita.

|===