---
permalink: platform-supplemental/sldiag-use-cli-help.html 
sidebar: sidebar 
keywords: command-line, syntax, command, line, name, follow, question, mark, how to use online command-line help 
summary: 'Puede obtener ayuda de sintaxis de línea de comandos desde la línea de comandos introduciendo el nombre del comando seguido de Help o el signo de interrogación \(?\).' 
---
= Cómo utilizar la ayuda en línea de la línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener la ayuda de sintaxis de línea de comandos desde la línea de comandos introduciendo el nombre del comando seguido de Help o el signo de interrogación (?).

Las fuentes o símbolos utilizados en la ayuda de sintaxis son los siguientes:

* *palabra clave*
+
Especifica el nombre de un comando o una opción que se debe introducir como se muestra.

* *< > (menor que, mayor que los símbolos)*
+
Especifique que debe sustituir la variable identificada dentro de los símbolos por un valor.

* *| (tubería)*
+
Indica que debe elegir uno de los elementos a cada lado de la tubería.

* *[ ] (corchetes)*
+
Indique que el elemento dentro de los soportes es opcional.

* *{ } (llaves)*
+
Indique que el elemento dentro de las llaves es necesario.



También puede escribir el signo de interrogación en la línea de comandos para obtener una lista de todos los comandos disponibles en el nivel actual de administración (administrativa o avanzada).

En el siguiente ejemplo, se muestra el resultado de introducir el comando de ayuda del entorno en la línea de comandos del sistema de almacenamiento. El resultado del comando muestra la ayuda de la sintaxis de los comandos de entorno.

[listing]
----
toaster> environment help
Usage: environment status |
[status] [shelf [<adapter>]] |
[status] [shelf_log] |
[status] [shelf_stats] |
[status] [shelf_power_status] |
[status] [chassis [all | list-sensors | Fan | Power | Temp | Power Supply | RTC Battery | NVRAM4-temperature-7 | NVRAM4-battery-7]]
----