---
permalink: platform-supplemental/sldiag-system-panic-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, storage, system, suffer, panic, identify, cause, run system panic diagnostic 
summary: La ejecución de diagnósticos una vez que el sistema de almacenamiento sufre una caída del sistema puede ayudarle a identificar la posible causa de la alarma. 
---
= Ejecutar diagnósticos de alerta del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La ejecución de diagnósticos una vez que el sistema de almacenamiento sufre una caída del sistema puede ayudarle a identificar la posible causa de la alarma.

. En el símbolo del sistema de almacenamiento, cambie al símbolo del sistema del CARGADOR: `halt`
. Introduzca el siguiente comando en el símbolo del sistema del CARGADOR: `boot_diags`
+

NOTE: Este comando se debe ejecutar desde el símbolo del sistema DEL CARGADOR para que los diagnósticos de nivel del sistema funcionen correctamente. El comando boot_diags inicia controladores especiales diseñados específicamente para diagnósticos de sistema.

. Ejecute los diagnósticos de todos los dispositivos introduciendo el siguiente comando: `sldiag device run`
. Para ver el estado de la prueba, introduzca el siguiente comando: `sldiag device status`
+
El sistema de almacenamiento proporciona la siguiente salida mientras se siguen ejecutando las pruebas:

+
[listing]
----
There are still test(s) being processed.
----
+
Una vez completadas todas las pruebas, recibirá la siguiente respuesta predeterminada:

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. Identifique la causa de la alarma del sistema introduciendo el comando siguiente: `sldiag device status -long -state failed`
+
El siguiente ejemplo muestra cómo se muestra el estado completo de los fallos en una prueba que se ejecuta sin el hardware adecuado:

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| Si el diagnóstico del sistema prueba... | Realice lo siguiente... 


 a| 
Se completaron sin fallos
 a| 
No hay problemas de hardware y el sistema de almacenamiento vuelve al aviso de.

.. Borre los registros de estado introduciendo el siguiente comando: `sldiag device clearstatus`
.. Compruebe que se borra el registro introduciendo el siguiente comando: `sldiag device status`
+
Se muestra la siguiente respuesta predeterminada:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Para salir del modo de mantenimiento, introduzca el siguiente comando: `halt`
.. Introduzca el siguiente comando en el símbolo del sistema del cargador para arrancar el sistema de almacenamiento: `boot_ontap`Ha completado el diagnóstico de nivel del sistema.




 a| 
Se produjeron algunos fallos en las pruebas
 a| 
Determine la causa del problema.

.. Para salir del modo de mantenimiento, introduzca el siguiente comando: `halt`
.. Realice un apagado correcto y desconecte las fuentes de alimentación.
.. Compruebe que ha observado todos los aspectos identificados a la hora de ejecutar diagnósticos de nivel de sistema, que los cables estén conectados de forma segura y que los componentes de hardware estén instalados correctamente en el sistema de almacenamiento.
.. Vuelva a conectar las fuentes de alimentación y encienda el sistema de almacenamiento.
.. Repita los pasos del 1 al 5 de _ejecutar diagnósticos de pánico del sistema_.


|===


Si los fallos persisten después de repetir los pasos, deberá sustituir el hardware.
