---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: Diagnósticos de nivel de sistema ofrece una interfaz de línea de comandos para pruebas que buscan y determinan problemas de hardware en los sistemas de almacenamiento admitidos. Utilice diagnósticos de nivel de sistema para confirmar que un componente específico funciona correctamente o para ayudar a identificar componentes defectuosos. 
---
= Introducción al diagnóstico de nivel de sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diagnósticos de nivel de sistema ofrece una interfaz de línea de comandos para pruebas que buscan y determinan problemas de hardware en los sistemas de almacenamiento admitidos. Utilice diagnósticos de nivel de sistema para confirmar que un componente específico funciona correctamente o para ayudar a identificar componentes defectuosos.

El diagnóstico de nivel de sistema solo está disponible para los sistemas de almacenamiento compatibles. La introducción de diagnósticos de nivel de sistema en la interfaz de línea de comandos de sistemas de almacenamiento no compatibles genera un mensaje de error.

Se ejecuta un diagnóstico de nivel de sistema después de una de las siguientes situaciones habituales de solución de problemas:

* Instalación inicial del sistema
* Adición o sustitución de componentes de hardware
* Alerta en el sistema provocada por errores no identificados de hardware
* El acceso a un dispositivo específico pasa a ser intermitente o el dispositivo deja de estar disponible
* El tiempo de respuesta del sistema es lento


Para ejecutar diagnósticos de nivel de sistema, debe estar ejecutando Data ONTAP porque necesita acceder a la opción *modo de mantenimiento boot* de Data ONTAP. Hay varios enfoques para obtener esta opción, pero este es el enfoque recomendado adoptado en los procedimientos documentados en esta guía. Es posible que algunos componentes de hardware de su sistema requieran un enfoque específico; esto se documentará en el folleto correspondiente de unidad reemplazable del sector (FRU). Esta guía no proporciona definiciones detalladas de comandos, subcomandos, pruebas o condiciones específicos.

Una vez introducido el comando, las pruebas se ejecutan en segundo plano y el resultado pasado o fallido de las pruebas se registra en el registro interno basado en memoria, que tiene un tamaño fijo. Algunas pruebas son utilidades y simplemente se completará en lugar de pasarse o falló. Después de realizar las pruebas adecuadas, los procedimientos descritos en esta guía le ayudarán a generar el informe de estado. Una vez que los resultados de la prueba muestran que el diagnóstico de nivel de sistema se ha completado correctamente, se recomienda borrar el registro.

En caso de errores de prueba, los informes de estado ayudarán al soporte técnico a hacer las recomendaciones apropiadas. El fallo se podría resolver reinstalando la FRU, garantizando que los cables estén conectados o activando pruebas específicas recomendadas por el soporte técnico y, a continuación, volviendo a ejecutar dichas pruebas. Si no se puede resolver el error, hay un error de hardware y el hardware afectado debe sustituirse.

No hay mensajes de error que requieran definiciones o explicaciones adicionales.
