---
permalink: a320/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff, a320, locate, boot, media, controller, module, direction, replace, replace the boot media, manual, manual boot recovery 
summary: Debes ubicar el medio de arranque en el módulo del controlador y luego seguir las instrucciones para reemplazarlo. El sistema AFF A320 solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque. 
---
= Descripción general de la sustitución de medios de arranque - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema AFF A320 solo admite procedimientos de recuperación de medios de arranque manuales.

El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca. En función de la configuración de red, puede realizar una sustitución no disruptiva o disruptiva.

Debe tener una unidad flash USB, formateada a FAT32, con la cantidad de almacenamiento adecuada para guardar el `image_xxx.tgz` archivo.

También debe copiar el `image_xxx.tgz` Archivo a la unidad flash USB para su uso posterior en este procedimiento.

* Ambos métodos no disruptivos y disruptivos para reemplazar medios de arranque requieren restaurar el `var` sistema de archivos:
+
** Para poder realizar sustituciones de forma no disruptiva, el par de alta disponibilidad debe estar conectado a una red para restaurar el `var` sistema de archivos.
** Para el reemplazo disruptivo, no es necesaria una conexión de red para restaurar el `var` el sistema de archivos, pero el proceso requiere dos reinicios.


* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en el nodo correcto:
+
** El nodo _drinated_ es el nodo en el que realiza tareas de mantenimiento.
** El _heated node_ es el partner de alta disponibilidad del nodo dañado.



