---
permalink: a320/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir el chasis de un AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF A320, revisa los requisitos necesarios para que la sustitución sea exitosa. El procedimiento mueve todos los ventiladores y módulos de controlador del chasis averiado al chasis de reemplazo y es disruptivo.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe suponiendo que se mueven los módulos de la controladora al nuevo chasis y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

