---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: Mueva los ventiladores, las unidades de disco duro y el módulo o los módulos del controlador del chasis dañado al nuevo chasis, y cambie el chasis dañado del bastidor del equipo o del armario del sistema con el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Sustituya el hardware - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mueva los ventiladores, las unidades de disco duro y el módulo o los módulos del controlador del chasis dañado al nuevo chasis, y cambie el chasis dañado del bastidor del equipo o del armario del sistema con el nuevo chasis del mismo modelo que el chasis dañado.



== Paso 1: Extraiga los módulos de la controladora

Para sustituir el chasis, debe quitar los módulos de la controladora del chasis antiguo.

. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Suelte los retenes del cable de alimentación y, a continuación, desenchufe los cables de las fuentes de alimentación.
. Afloje el gancho y la correa de bucle que sujetan los cables al dispositivo de administración de cables y, a continuación, desconecte los cables del sistema y los SFP (si fuera necesario) del módulo del controlador, manteniendo un seguimiento del lugar en el que estaban conectados los cables.
+
Deje los cables en el dispositivo de administración de cables de manera que cuando vuelva a instalar el dispositivo de administración de cables, los cables estén organizados.

. Retire y retire los dispositivos de administración de cables de los lados izquierdo y derecho del módulo del controlador.
. Extraiga el módulo de la controladora del chasis:
+
.. Inserte el índice en el mecanismo de bloqueo a ambos lados del módulo del controlador.
.. Presione hacia abajo la lengüeta naranja de la parte superior del mecanismo de bloqueo hasta que se separe el pasador de bloqueo del chasis.
+
El gancho del mecanismo de bloqueo debe estar casi en vertical y debe estar alejado del pasador del chasis.

.. Tire suavemente del módulo del controlador unas pulgadas hacia usted para que pueda agarrar los lados del módulo del controlador.
.. Con ambas manos, tire suavemente del módulo del controlador para sacarlo del chasis y configúrelo en una superficie plana y estable.


. Repita estos pasos para el otro módulo de controladora del chasis.




== Paso 2: Mueva los ventiladores

Para mover los módulos de ventilador al chasis de reemplazo al reemplazar el chasis, debe realizar una secuencia específica de tareas.

. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Retire el bisel (si es necesario) con dos manos, sujetando las aberturas de cada lado del bisel y tirando de él hacia usted hasta que el bisel se suelte de los espárragos de bolas del bastidor del chasis.
. Presione hacia abajo el pestillo de liberación en la palanca de leva del módulo del ventilador y luego gire el asa de leva hacia abajo.
+
El módulo del ventilador se mueve un poco lejos del chasis.

. Tire del módulo del ventilador hacia fuera del chasis, asegurándose de que lo apoya con la mano libre para que no se balancee del chasis.
+

CAUTION: Los módulos del ventilador son cortos. Apoye siempre la parte inferior del módulo de ventilador con la mano libre para que no se caiga repentinamente del chasis y le haga daño.

. Apartar el módulo de ventilador.
. Repita los pasos anteriores con los módulos de ventilador restantes.
. Inserte el módulo de ventilador en el chasis de repuesto alineándolo con la abertura y, a continuación, deslizándolo en el chasis.
. Empuje firmemente el asa de leva del módulo del ventilador de modo que quede asentado completamente en el chasis.
+
El asa de leva se eleva ligeramente cuando el módulo del ventilador está completamente asentado.

. Gire el asa de leva hasta su posición cerrada, asegurándose de que el pestillo de liberación de la palanca de leva haga clic en la posición bloqueada.
+
El LED del ventilador debe estar verde después de que el ventilador esté asentado y haya girado hasta la velocidad de funcionamiento.

. Repita estos pasos para los módulos de ventilador restantes.




== Paso 3: Sustituya un chasis desde el bastidor del equipo o el armario del sistema

Debe quitar el chasis existente del rack del equipo o armario del sistema antes de poder instalar el chasis de reemplazo.

. Quite los tornillos de los puntos de montaje del chasis.
. Con dos personas, deslice el chasis antiguo fuera de los rieles del rack en un armario del sistema o rack del equipo y, a continuación, colóquelo aparte.
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Con dos personas, instale el chasis de reemplazo en el rack o armario del sistema de equipamiento guiando el chasis hacia los rieles para rack en un armario del sistema o rack del equipo.
. Deslice el chasis completamente en el bastidor del equipo o en el armario del sistema.
. Fije la parte frontal del chasis al rack del equipo o al armario del sistema con los tornillos que quitó del chasis antiguo.
. Si todavía no lo ha hecho, instale el panel frontal.




== Paso 4: Instale los módulos del controlador

Después de instalar los módulos de la controladora en el nuevo chasis, debe arrancar a un estado en el que pueda ejecutar la prueba de diagnóstico.

Para los pares de alta disponibilidad con dos módulos de controladora en el mismo chasis, la secuencia en la que se instala el módulo de controladora es especialmente importante porque intenta reiniciarse tan pronto como lo coloca por completo en el chasis.

. Alinee el extremo del módulo del controlador con la abertura del chasis y, a continuación, empuje suavemente el módulo del controlador hasta la mitad del sistema.
+

NOTE: No inserte completamente el módulo de la controladora en el chasis hasta que se le indique hacerlo.

. Vuelva a conectar la consola al módulo del controlador y, a continuación, vuelva a conectar el puerto de administración.
. Enchufe los cables de alimentación en las fuentes de alimentación y vuelva a instalar los retenes del cable de alimentación.
. Complete la reinstalación del módulo del controlador:
+
.. Asegúrese de que los brazos del pestillo están bloqueados en la posición extendida.
.. Con los brazos del pestillo, empuje el módulo del controlador hacia el compartimiento del chasis hasta que se detenga.
.. Presione y sostenga las lengüetas naranjas en la parte superior del mecanismo de bloqueo.
.. Empuje suavemente el módulo de la controladora en el compartimento del chasis hasta que quede alineado con los bordes del chasis.
+

NOTE: Los brazos del mecanismo de bloqueo se deslizan en el chasis.

+
El módulo de la controladora comienza a arrancar tan pronto como se asienta completamente en el chasis.

.. Suelte los pestillos para bloquear el módulo del controlador en su lugar.
.. Recuperar la fuente de alimentación.
.. Si aún no lo ha hecho, vuelva a instalar el dispositivo de administración de cables.
.. Interrumpa el proceso de arranque normal pulsando `Ctrl-C`.


. Repita los pasos anteriores para instalar la segunda controladora en el chasis nuevo.

