---
permalink: a320/maintain-overview.html 
sidebar: sidebar 
keywords: aff A4320 maintenance, maintenance, repairing A320, repairing asa A320, replace  A300 components, replace A320 components 
summary: Mantén el hardware del AFF A320 
---
= Infórmate sobre el mantenimiento de tu sistema de almacenamiento AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para el sistema de almacenamiento AFF A320, puede realizar procedimientos de mantenimiento en los componentes siguientes.



[[boot-media]]
== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



[[chassis]]
== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



[[controller]]
== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



[[dimm]]
== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



[[fan]]
== Ventilador

El ventilador enfría el controlador.



[[nvdimm]]
== NVDIMM

 The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown.


[[nvdimm-battery]]
== Batería NVDIMM

Una batería NVDIMM es responsable de mantener la alimentación al módulo NVDIMM.



[[pcie]]
== PCIe

Una tarjeta PCIe (interconexión de componentes periféricos express) es una tarjeta de expansión que se conecta a la ranura PCIe de la placa base.



[[power-supply]]
== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



[[real-time-clock-battery]]
== Batería de reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
