---
permalink: fas500f/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: fas500f, replace the boot media 
summary: 'El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema \(imagen de arranque\) que el sistema utiliza cuando arranca.' 
---
= Descripción general de la sustitución del soporte de arranque - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca.

Debe tener una unidad flash USB, formateada a MBR/FAT32, con la cantidad de almacenamiento adecuada para contener el `image_xxx.tgz` archivo.

* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El controlador _drinated_ es el controlador en el que está realizando tareas de mantenimiento.
** El controlador _heated_ es el compañero de alta disponibilidad del controlador dañado.



