---
permalink: fas500f/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas500f, replace the chassis 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Descripción general de la sustitución del chasis - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sustituir el chasis, debe mover el panel frontal, los módulos de controladora y las unidades NVMe desde el chasis dañado hasta el chasis de reemplazo y, a continuación, quitar el chasis dañado del rack del equipo o armario del sistema e instalar el chasis de reemplazo en su lugar.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover el panel frontal, las unidades NVMe y los módulos de controladora al nuevo chasis, y que el chasis de reemplazo es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

