---
permalink: fas500f/overview.html 
sidebar: sidebar 
keywords: FAS500f specifications, FAS500f specs, NetApp FAS500f, FAS500f hardware 
summary: Especificaciones clave para el sistema de almacenamiento FAS500f 
---
= Especificaciones principales de FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A continuación se indican algunas especificaciones del FAS500f. Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para una lista completa de las especificaciones del FAS500f. Esta página refleja un único par de alta disponibilidad.



=== Especificaciones principales de FAS500f

Configuración de la plataforma: Par HA de chasis único FAS500f

Capacidad bruta máxima: 1,1016 PB

Memoria: 128.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

ONTAP versión: 9.16.1P2

Ranuras de expansión PCIe: 4

Versión mínima de ONTAP : ONTAP 9.8RC1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 12 | 13,2 PB / 11,7 PiB | 1536 GB 


| SAN | 6 | 6,6 PB / 5,9 PiB | 768 GB 


| Par HA |  | 1,1 PB / 1,0 PiB | 128,0000 
|===


=== IO



==== E/S integrada

|===


| Protocolo | Puertos 


| Ethernet de 25 Gbps | 4 


| Ethernet de 10 Gbps | 4 
|===


==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 4 


| Ethernet de 25 Gbps | 20 


| Ethernet de 10 Gbps | 4 


| FC 32 Gbps | 16 


| NVMe/FC 32 Gbps | 16 


|  | 0 


| SAS de 12 Gbps | 8 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB de 12 Mbps | 4 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 2642 BTU/h
* Potencia en el peor de los casos: 3476 BTU/h
* Peso: 54,3 lb 24,6 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19" (17,6" 44,7 cm)
* Profundidad: 21,38" (54,3 cm)
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °C (50 °F a 95 °F) a una altitud de hasta 3048 m (10 000 pies); humedad relativa del 8 % al 80 %, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12192 m (40000 pies) 10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 7,2; Presión sonora (LpAm) (posición de transeúntes): 69,1 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes; Administración en banda SAS a través de conexiones SAS para estantes externos;
