---
permalink: c400/install-videos.html 
sidebar: sidebar 
keywords: aff c400, aff, c400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Vídeos - AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.

Si dispone de una configuración MetroCluster, utilice el contenido de instalación de MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentación de MetroCluster"^]



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

.Animación: Instrucciones de instalación y configuración del AFF C400
video::8e392453-beac-4db7-8088-aff1005e1f90[panopto]


== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]