---
permalink: a800/overview.html 
sidebar: sidebar 
keywords: AFF A800 specifications, AFF A800 specs, NetApp AFF A800, AFF A800 hardware 
summary: Especificaciones clave para el grupo de plataformas A800 
---
= Especificaciones clave del AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el sistema de almacenamiento AFF A800 en un solo par de alta disponibilidad. Visite NetApp Hardware Universe (HWU) para conocer las especificaciones completas de este sistema de almacenamiento.



== Especificaciones clave del AFF A800

* Configuración de la plataforma: AFF A800, par HA de chasis único
* Capacidad bruta máxima: 6,6096 PB
* Memoria: 1280.0000 GB
* Factor de forma: chasis 4U con 2 controladores HA y 48 ranuras de unidad
* Versión de ONTAP : ONTAP: 9.16.1P2
* Ranuras de expansión PCIe: 10
* Versión mínima de ONTAP : ONTAP 9.4RC1




== Máximos de escalamiento

* Tipo: NAS; Pares HA: 12; Capacidad bruta: 79,3 PB / 70,4 PiB; Memoria máxima: 15360 GB
* Tipo: SAN; Pares HA: 6; Capacidad bruta: 39,7 PB / 35,2 PiB; Memoria máxima: 7680 GB
* Tipo: Par HA; Capacidad bruta: 6,6 PB / 5,9 PiB; Memoria máxima: 1280,0000




== E/S



=== E/S integrada

* Protocolo: Ethernet 100 Gbps; Puertos: 4




=== E/S total

* Protocolo: Ethernet 100 Gbps; Puertos: 20
* Protocolo: Ethernet 25 Gbps; Puertos: 16
* Protocolo: Ethernet 10 Gbps; Puertos: 32
* Protocolo: FC 32 Gbps; Puertos: 32
* Protocolo: NVMe/FC 32 Gbps; Puertos: 32
* Puertos: 0
* Puertos: 0
* Protocolo: SAS 12 Gbps; Puertos: 32




=== Puertos de gestión

* Protocolo: Ethernet 1 Gbps; Puertos: 4
* Protocolo: RS-232 115 Kbps; Puertos: 4
* Protocolo: USB 12 Mbps; Puertos: 4




== Redes de almacenamiento compatibles

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NFSv3/RDMA
* NFSv4/RDMA
* NVMe/FC
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1




== Especificaciones del entorno del sistema

* Potencia típica: 6626 BTU/h
* Potencia en el peor de los casos: 8417 BTU/h
* Peso: 132,5 lb 60,1 kg
* Altura: 4U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad: 34,5” (36,6” con soporte para gestión de cables)
* Temperatura/altitud/humedad de funcionamiento: 5 °C a 40 °C (41 °F a 104 °F) a una altitud de hasta 3048 m (10 000 pies); humedad relativa del 8 % al 90 %, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12192 m (40000 pies) 10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0 Presión sonora (LpAm) (posiciones de transeúntes): 62,8 dB




== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidad

* Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP
* Controladores redundantes intercambiables en caliente
* Fuentes de alimentación redundantes intercambiables en caliente
* Gestión en banda de SAS a través de conexiones SAS para estanterías externas

