---
permalink: asa-c800/install-setup.html 
sidebar: sidebar 
keywords: asa c800, initial configuration options 
summary: Elige el método de instalación que mejor se adapte a tus necesidades para configurar un sistema ASA C800, ya sea mediante instrucciones gráficas rápidas, tutoriales en vídeo o guías detalladas paso a paso. 
---
= Elige cómo instalar un sistema de almacenamiento ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Elige el método de instalación que mejor se adapte a tus necesidades para configurar un sistema ASA C800, ya sea mediante instrucciones gráficas rápidas, tutoriales en vídeo o guías detalladas paso a paso.

* link:../asa-c800/install-quick-guide.html["Pasos rápidos"]
+
Un PDF imprimible de instrucciones paso a paso con enlaces directos a contenido adicional.

* link:../asa-c800/install-videos.html["Pasos de vídeo"]
+
Instrucciones paso a paso de vídeo.

* link:../asa-c800/install-detailed-guide.html["Pasos detallados"]
+
Instrucciones paso a paso en línea con enlaces directos a contenido adicional.



Si el sistema está en una configuración IP de MetroCluster, consulte https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Instale la configuración IP de MetroCluster"^] instrucciones.
