---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 'Antes de reemplazar el medio de arranque en su sistema de almacenamiento ASA C30, asegúrese de cumplir con los requisitos y consideraciones necesarios para un reemplazo exitoso. Esto incluye verificar que tenga el medio de arranque de reemplazo correcto, confirmar que el puerto e0S (llave e0M) del controlador dañado funcione correctamente y determinar si el Administrador de claves integrado (OKM) o el Administrador de claves externo (EKM) están habilitados.' 
---
= Requisitos para sustituir el soporte de arranque - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reemplazar el medio de arranque en su sistema de almacenamiento ASA C30, asegúrese de cumplir con los requisitos y consideraciones necesarios para un reemplazo exitoso. Esto incluye verificar que tenga el medio de arranque de reemplazo correcto, confirmar que el puerto e0S (llave e0M) del controlador dañado funcione correctamente y determinar si el Administrador de claves integrado (OKM) o el Administrador de claves externo (EKM) están habilitados.

* Debe sustituir el componente con errores por un componente FRU de reemplazo con la misma capacidad que recibió de NetApp.
* El puerto e0S (llave e0M) se utiliza para la comunicación entre los dos controladores durante el proceso de recuperación de arranque automático. Asegúrese de que el puerto e0S del controlador dañado funcione correctamente.
* Para OKM, necesita el contenido del archivo de contraseña de OKM.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** archivo /cfcard/kmip/servers.cfg.
** archivo /cfcard/kmip/certs/client.crt.
** archivo /cfcard/kmip/certs/client.key.
** Archivo /cfcard/kmip/certs/ca.pem.


* Es fundamental aplicar los comandos al controlador correcto cuando se reemplaza el medio de arranque dañado:
+
** El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
** El _controlador saludable_ es el socio HA del controlador dañado.




.El futuro
Después de revisar los requisitos de soporte de arranque, usted link:bootmedia-shutdown-bmr.html["apague la controladora"].
