---
permalink: asa-r2-c30/maintain-overview.html 
sidebar: sidebar 
keywords: asa c30, maintenance, maintenance 
summary: Mantener el hardware de su sistema de almacenamiento C30 de ASA para garantizar la fiabilidad a largo plazo y un rendimiento óptimo. Lleve a cabo tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, ya que esto ayuda a evitar el tiempo de inactividad y la pérdida de datos. 
---
= Descripción general del mantenimiento de hardware - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantener el hardware de su sistema de almacenamiento C30 de ASA para garantizar la fiabilidad a largo plazo y un rendimiento óptimo. Lleve a cabo tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, ya que esto ayuda a evitar el tiempo de inactividad y la pérdida de datos.

Los procedimientos de esta sección suponen que el sistema de almacenamiento ASA C30 ya se ha implementado como un nodo de almacenamiento en el entorno ONTAP.



== Componentes del sistema

Para el sistema de almacenamiento ASA C30, puede realizar procedimientos de mantenimiento en los componentes siguientes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Medios de arranque: recuperación automatizada"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar.  Durante la recuperación automatizada, el sistema recupera la imagen de arranque del nodo asociado y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen en el medio de arranque de reemplazo.

El proceso de recuperación automática del medio de arranque solo es compatible con ONTAP 9.17.1 y versiones posteriores. Si su sistema de almacenamiento ejecuta una versión anterior de ONTAP, utilice el link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"] .



 a| 
link:bootmedia-replace-workflow.html["Medios de arranque: recuperación manual"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar la imagen desde una unidad USB y restaurar la configuración desde el nodo asociado.



 a| 
link:chassis-replace-workflow.html["Chasis"]
 a| 
El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



 a| 
link:controller-replace-workflow.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades y ejecuta el software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un módulo de memoria dual en línea (DIMM) es un tipo de memoria del ordenador. Se instalan para agregar memoria del sistema a una placa base de la controladora.



 a| 
link:drive-replace.html["Unidad"]
 a| 
Una unidad es un dispositivo que ofrece el almacenamiento físico necesario para datos.



 a| 
link:fan-replace.html["Ventilador"]
 a| 
Un ventilador enfría la controladora y las unidades.



 a| 
link:io-module-overview.html["Módulo de I/O."]
 a| 
El módulo de E/S (módulo de entrada/salida) es un componente de hardware que actúa como intermediario entre el controlador y varios dispositivos o sistemas que necesitan intercambiar datos con el controlador.



 a| 
link:nvdimm-battery-replace.html["Batería de NV"]
 a| 
La batería de la memoria no volátil (NV) es responsable de suministrar alimentación a los componentes de NVMEM mientras los datos en tránsito se separan a la memoria flash tras un corte de alimentación.



 a| 
link:power-supply-replace.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



 a| 
link:rtc-battery-replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.

|===