---
permalink: a250/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a250, replace the boot media 
summary: 'El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema \(imagen de arranque\) que el sistema utiliza cuando arranca.' 
---
= Descripción general de la sustitución de medios de arranque - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca.

.Antes de empezar
* Debe tener una unidad flash USB, formateada a MBR/FAT32, con la cantidad de almacenamiento adecuada para contener el `image_xxx.tgz` archivo.
* También debe copiar el `image_xxx.tgz` Archivo a la unidad flash USB para su uso posterior en este procedimiento.


.Acerca de esta tarea
* Ambos métodos no disruptivos y disruptivos para reemplazar medios de arranque requieren restaurar el `var` sistema de archivos:
+
** Para poder realizar sustituciones de forma no disruptiva, el par de alta disponibilidad debe estar conectado a una red para restaurar el `var` sistema de archivos.
** Para el reemplazo disruptivo, no es necesaria una conexión de red para restaurar el `var` el sistema de archivos, pero el proceso requiere dos reinicios.


* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El nodo _drinated_ es la controladora en la que realiza tareas de mantenimiento.
** El nodo _heated_ es el compañero de alta disponibilidad de la controladora dañada.



