---
permalink: a250/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a250, verify and set HA state, run diagnostics, complete the replacement process 
summary: Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. 
---
= Completar el proceso de restauración y sustitución - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit.



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

Debe verificar el estado de alta disponibilidad del chasis y, si es necesario, actualizar el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis: `ha-config modify chassis _HA-state_`
+
El valor de la condición de alta disponibilidad puede ser uno de los siguientes:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Confirme que el ajuste ha cambiado: `ha-config show`


. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.
. Vuelva a instalar el bisel en la parte delantera del sistema.




== Paso 2: Ejecutar el diagnóstico

Después de sustituir un componente del sistema, deberá ejecutar pruebas de diagnóstico de ese componente.

El sistema debe estar en el aviso del CARGADOR para iniciar los diagnósticos.

Todos los comandos de los procedimientos de diagnóstico se emiten desde la controladora en la que se sustituye el componente.

. Si la controladora que se va a realizar mantenimiento no se encuentra en el símbolo del sistema del CARGADOR, reinicie la controladora: `system node halt -node node_name`
+
Tras emitir el comando, debe esperar hasta que el sistema se detenga en el símbolo del sistema del CARGADOR.

. En el aviso DEL CARGADOR, acceda a los controladores especiales diseñados específicamente para que los diagnósticos del sistema funcionen correctamente: `boot_diags`
. Seleccione *Scan System* en el menú que aparece para activar la ejecución de las pruebas de diagnóstico.
. Seleccione *sistema de prueba* en el menú que aparece.
. Proceda según el resultado del paso anterior:
+
** Si la prueba falla, corrija el fallo y vuelva a ejecutar la prueba.
** Si la prueba no ha informado de ningún fallo, seleccione Reiniciar en el menú para reiniciar el sistema.






== Paso 3: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Retorno de artículo  sustituciones"] para obtener más información.
