---
permalink: a250/index.html 
sidebar: sidebar 
keywords: aff A250 maintenance, maintenance, repairing A250, repairing aff A250, replace aff A250 components, replace aff A250 components 
summary: Mantenga el hardware de ASA A250 
---
= Mantener el hardware de AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para el sistema de almacenamiento AFF A250, puede realizar procedimientos de mantenimiento en los componentes siguientes.



== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



== Unidad

Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



== Ventilador

El ventilador enfría el controlador.



== Tarjeta mezzanine

Una tarjeta Mezzanine es una placa de circuito impreso que se conecta directamente a otra tarjeta enchufable.



== Batería de NVEM

Se incluye una batería en la controladora y conserva los datos en caché si falla la alimentación de CA.



== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



== Batería del reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
