---
permalink: fas8200/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: fas8200, boot the recovery image, manual, manual boot recovery 
summary: Arranque la imagen de recuperación de ONTAP desde la unidad USB en un sistema FAS8200 para restaurar el medio de arranque. El sistema FAS8200 solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque. 
---
= Arranque la imagen de recuperación: FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arranque la imagen de recuperación de ONTAP desde la unidad USB en un sistema FAS8200 para restaurar el medio de arranque. Este procedimiento incluye arrancar desde la unidad flash USB, restaurar el sistema de archivos, verificar las variables ambientales y devolver el controlador al funcionamiento normal, con pasos específicos que varían dependiendo de si el sistema está en una configuración MetroCluster de dos nodos.

El sistema FAS8200 solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque.



== Opción 1: La mayoría de los sistemas

: Debe arrancar la imagen ONTAP desde la unidad USB, restaurar el sistema de archivos y comprobar las variables de entorno.

Este procedimiento se aplica a los sistemas que no están en una configuración MetroCluster de dos nodos.

.Pasos
. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Restaure el sistema de archivos var:
+
[cols="1,2"]
|===
| Si el sistema tiene... | Realice lo siguiente... 


 a| 
Una conexión de red
 a| 
.. Pulse `y` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Configure la controladora en buen estado como nivel de privilegio avanzado: `set -privilege advanced`
.. Ejecute el comando restore backup: `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Devuelva la controladora al nivel de administrador: `set -privilege admin`
.. Pulse `y` cuando se le solicite que utilice la configuración restaurada.
.. Pulse `y` cuando se le solicite reiniciar la controladora.




 a| 
No hay conexión de red
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.



|===
. Asegurarse de que las variables medioambientales estén establecidas de la manera esperada:
+
.. Lleve la controladora al aviso del CARGADOR.
.. Compruebe la configuración de la variable de entorno con el `printenv` comando.
.. Si una variable de entorno no está establecida como se espera, modifíquela con el `setenv __environment-variable-name__ __changed-value__` comando.
.. Guarde los cambios mediante `savenv` comando.


. El siguiente depende de la configuración del sistema:
+
** Si su sistema tiene configurado el gestor de claves incorporado, NSE o NVE, vaya a. xref:bootmedia-encryption-restore.adoc[Restaure OKM, NSE y NVE según sea necesario]
** Si su sistema no tiene configurado el gestor de claves incorporado, NSE o NVE, complete los pasos en esta sección.


. Desde el aviso del CARGADOR, introduzca el `boot_ontap` comando.
+
[cols="1,2"]
|===
| Si ve... | Realice lo siguiente... 


 a| 
La solicitud de inicio de sesión de
 a| 
Vaya al siguiente paso.



 a| 
Esperando devolución...
 a| 
.. Inicie sesión en el controlador asociado.
.. Confirme que la controladora de destino está lista para la devolución con el `storage failover show` comando.


|===
. Conecte el cable de la consola al controlador asociado.
. Respalde la controladora con el `storage failover giveback -fromnode local` comando.
. En el símbolo del sistema del clúster, compruebe las interfaces lógicas con el `net int -is-home false` comando.
+
Si alguna interfaz se muestra como "falsa", vuelva a revertir dichas interfaces a su puerto de inicio utilizando el `net int revert` comando.

. Mueva el cable de la consola al controlador reparado y ejecute el `version -v` Comando para comprobar las versiones de ONTAP.
. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.




== Opción 2: La controladora está en un MetroCluster de dos nodos

Debe arrancar la imagen de ONTAP desde la unidad USB y comprobar las variables de entorno.

Este procedimiento se aplica a los sistemas de una configuración MetroCluster de dos nodos.

.Pasos
. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Después de instalar la imagen, inicie el proceso de restauración:
+
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Pulse `y` cuando se le pida que reinicie para empezar a utilizar el software recién instalado.
+
Debe estar preparado para interrumpir el proceso de arranque cuando se le solicite.



. Cuando se inicie el sistema, pulse `Ctrl-C` después de ver la `Press Ctrl-C for Boot Menu` Mensaje. Y cuando aparezca el menú Inicio, seleccione la opción 6.
. Compruebe que las variables de entorno están establecidas de la forma esperada.
+
.. Lleve el nodo al aviso DEL CARGADOR.
.. Compruebe la configuración de la variable de entorno con el `printenv` comando.
.. Si una variable de entorno no está establecida como se espera, modifíquela con el `setenv __environment-variable-name__ __changed-value__` comando.
.. Guarde los cambios mediante `savenv` comando.
.. Reiniciar el nodo.



