---
permalink: fas8200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the chassis 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir el chasis de tu FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sustituir el chasis, debe mover las fuentes de alimentación, los ventiladores y los módulos de controladora del chasis dañado al nuevo chasis y cambiar el chasis dañado del rack del equipo o del armario del sistema por el nuevo chasis del mismo modelo que el chasis dañado.

El resto de componentes del sistema deben funcionar correctamente. Si no es así, ponte en contacto con soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover el módulo o los módulos de la controladora al nuevo chasis y que el chasis es un nuevo componente de NetApp.
* Este procedimiento provoca interrupciones. En un clúster de dos controladores, tienes una interrupción total del servicio y, en un clúster de varios nodos, una interrupción parcial.

