---
permalink: fas8200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the chassis 
summary: Antes de sustituir el chasis en un sistema FAS8200, comprueba que el resto de componentes funcionen correctamente y que el chasis de sustitución sea un componente nuevo de NetApp del mismo modelo. El procedimiento requiere trasladar las fuentes de alimentación, los ventiladores y los módulos controladores al nuevo chasis y es disruptivo, provocando una interrupción total del servicio en un clúster de dos controladores o una interrupción parcial en un clúster de varios nodos. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis en un sistema FAS8200, comprueba que el resto de componentes funcionen correctamente y que el chasis de sustitución sea un componente nuevo de NetApp del mismo modelo. El procedimiento requiere trasladar las fuentes de alimentación, los ventiladores y los módulos controladores al nuevo chasis y es disruptivo, provocando una interrupción total del servicio en un clúster de dos controladores o una interrupción parcial en un clúster de varios nodos.

El resto de componentes del sistema deben funcionar correctamente. Si no es así, ponte en contacto con soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover el módulo o los módulos de la controladora al nuevo chasis y que el chasis es un nuevo componente de NetApp.
* Este procedimiento provoca interrupciones. En un clúster de dos controladores, tienes una interrupción total del servicio y, en un clúster de varios nodos, una interrupción parcial.

