---
permalink: fas8200/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, prerequisite, replace the controller module 
summary: Debe revisar los requisitos previos del procedimiento de reemplazo y seleccionar el correcto para su versión del sistema operativo ONTAP. 
---
= Descripción general de la sustitución del módulo del controlador - FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe revisar los requisitos previos del procedimiento de reemplazo y seleccionar el correcto para su versión del sistema operativo ONTAP.

* Todas las bandejas de unidades deben funcionar correctamente.
* Si el sistema es un sistema FlexArray o tiene una licencia V_StorageAttach, debe consultar los pasos adicionales necesarios antes de realizar este procedimiento.
* Si su sistema está en un par ha, el controlador en buen estado debe ser capaz de tomar el controlador que se va a sustituir (denominado en este procedimiento el "'controlador dañado'").
* Si su sistema está en una configuración MetroCluster, debe revisar la sección https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"] para determinar si debe utilizar este procedimiento.
+
Si este es el procedimiento que debe utilizar, tenga en cuenta que el procedimiento de sustitución de una controladora en una configuración MetroCluster de cuatro u ocho controladoras es el mismo que el de una pareja de alta disponibilidad. No es necesario realizar pasos específicos de MetroCluster porque el fallo está limitado a un par de alta disponibilidad y pueden utilizarse comandos de recuperación tras fallos del almacenamiento para proporcionar un funcionamiento no disruptivo durante el reemplazo.

* Este procedimiento incluye los pasos para reasignar las unidades de forma automática o manual al controlador _reader_, en función de la configuración del sistema.
+
Debe realizar la reasignación de las unidades de acuerdo con las instrucciones del procedimiento.

* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Debe sustituir un módulo de controlador por un módulo de controlador del mismo tipo de modelo. No puede actualizar su sistema simplemente reemplazando el módulo del controlador.
* No es posible cambiar ninguna unidad o bandeja de unidades como parte de este procedimiento.
* En este procedimiento, el dispositivo de arranque pasa del controlador dañado al controlador _regrel_ de modo que el controlador _regrel_ se arranque en la misma versión de ONTAP que el módulo de controlador antiguo.
* Todas las tarjetas PCIe que se hayan movido del módulo de controladora antiguo al módulo de controladora nuevo o se hayan añadido del inventario de las instalaciones del cliente existente deben contar con la compatibilidad del módulo de controladora de reemplazo.
+
https://hwu.netapp.com["Hardware Universe de NetApp"]

* Es importante que aplique los comandos de estos pasos en los sistemas correctos:
+
** El controlador _drinated_ es el controlador que se va a sustituir.
** El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
** El controlador _heated_ es el controlador que sobrevive.


* Siempre debe capturar el resultado de la consola de la controladora en un archivo de texto.
+
Esto proporciona un registro del procedimiento para poder solucionar los problemas que puedan surgir durante el proceso de reemplazo.


