---
permalink: afx-1k/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shutdown the controller 
summary: Apague el controlador en su sistema de almacenamiento AFX 1K para evitar la pérdida de datos y garantizar la estabilidad del sistema al reemplazar el chasis. 
---
= Apague el controlador para reemplazar el chasis - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apague el controlador en su sistema de almacenamiento AFX 1K para evitar la pérdida de datos y garantizar la estabilidad del sistema al reemplazar el chasis.

Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, realizar una toma de control del almacenamiento del controlador para que el controlador en buen estado continúe proporcionando datos desde el almacenamiento del controlador dañado.

.Acerca de esta tarea
* Si tiene un clúster con más de cuatro nodos, debe estar en quórum.  Para ver información del clúster sobre sus nodos, utilice el `cluster show` dominio.  Para obtener más información sobre el `cluster show` comando, verlink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Ver detalles a nivel de nodo en un clúster ONTAP"^] .
* Si el clúster no está en quórum o si el estado o la elegibilidad de cualquier controlador (excepto el controlador dañado) se muestra como falso, debe corregir el problema antes de apagar el controlador dañado. Ver link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^] .


.Pasos
. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilitar la devolución automática desde la consola del controlador dañado:
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Cuando veas _¿Quieres desactivar la devolución automática?_, escribe `y` .

+
.. Si está ejecutando ONTAP versión 9.17.1 y no se puede iniciar el controlador dañado o ya está tomado, debe quitar el enlace de interconexión de alta disponibilidad del controlador en buen estado antes de iniciar el controlador dañado.  Esto evita que el controlador dañado realice la devolución automática.
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`

+

NOTE: Si no está ejecutando la versión 9.17.1 de ONTAP , omita el paso anterior y vaya al paso 3.



. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
Solicitud del sistema o solicitud de contraseña
 a| 
Tomar el control o detener el controlador dañado desde el controlador sano:
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

El parámetro _-halt true_ lleva el nodo dañado al indicador LOADER.

|===


.El futuro
Después de apagar el controlador, debe link:chassis-replace-move-hardware.html["sustituya el chasis"].
