---
permalink: afx-1k/io-module-overview.html 
sidebar: sidebar 
keywords: afx 1k, replace io module 
summary: El sistema de almacenamiento AFX 1K ofrece flexibilidad para ampliar o reemplazar módulos de E/S para mejorar la conectividad y el rendimiento de la red.  Agregar o reemplazar un módulo de E/S es esencial al actualizar las capacidades de la red o solucionar un módulo fallido. 
---
= Descripción general del módulo de E/S de adición y reemplazo - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema de almacenamiento AFX 1K ofrece flexibilidad para ampliar o reemplazar módulos de E/S para mejorar la conectividad y el rendimiento de la red.  Agregar o reemplazar un módulo de E/S es esencial al actualizar las capacidades de la red o solucionar un módulo fallido.

Puede reemplazar un módulo de E/S fallido en su sistema de almacenamiento AFX 1K con el mismo tipo de módulo de E/S o con un tipo diferente de módulo de E/S.  También puede agregar un módulo de E/S a un sistema con ranuras vacías.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
La adición de módulos adicionales puede mejorar la redundancia, lo que ayuda a garantizar que el sistema siga funcionando incluso si falla un módulo.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de E/S que falla puede restaurar el sistema a su estado operativo óptimo.



.Numeración de ranuras de E/S.
Las ranuras de E/S del controlador AFX 1K están numeradas del 1 al 11, como se muestra en la siguiente ilustración.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeración de ranuras en un controlador AFX 1K]
