---
permalink: afx-1k/maintain-overview.html 
sidebar: sidebar 
keywords: afx 1k maintenance, maintenance, repairing a1k, repairing afx 1k, replace afx 1k components, replace afx 1k components 
summary: Mantenga el hardware de su sistema de almacenamiento AFX 1K para garantizar la confiabilidad a largo plazo y un rendimiento óptimo. Realice tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, para evitar tiempos de inactividad y la pérdida de datos. 
---
= Descripción general de los procedimientos de mantenimiento - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenga el hardware de su sistema de almacenamiento AFX 1K para garantizar la confiabilidad a largo plazo y un rendimiento óptimo. Realice tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, para evitar tiempos de inactividad y la pérdida de datos.

Los procedimientos de mantenimiento suponen que el sistema de almacenamiento AFX 1K ya se ha implementado como un nodo de almacenamiento en el entorno ONTAP .



== Componentes del sistema

Para el sistema de almacenamiento AFX 1K, puede realizar procedimientos de mantenimiento en los siguientes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["Soporte de arranque"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema utiliza cuando arranca.



 a| 
link:controller-replace-workflow.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades y ejecuta el software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un módulo de memoria dual en línea (DIMM) es un tipo de memoria del ordenador. Se instalan para agregar memoria del sistema a una placa base de la controladora.



 a| 
link:fan-replace.html["Ventilador"]
 a| 
Un ventilador enfría el controlador.



 a| 
link:nvram-replace.html["Módulo de NVRAM"]
 a| 
El módulo NVRAM (memoria de acceso aleatorio no volátil) permite al controlador proteger y guardar datos en vuelo si el sistema pierde energía.  El ID del sistema se almacena en el módulo NVRAM .  Cuando se reemplaza, el controlador utiliza la nueva ID del sistema del módulo NVRAM de reemplazo.



 a| 
link:nvdimm-battery-replace.html["Batería de NV"]
 a| 
La batería NV es responsable de suministrar alimentación al módulo de NVRAM mientras los datos en tránsito se separan a la memoria flash después de un corte de alimentación.



 a| 
link:io-module-overview.html["Módulo de I/O."]
 a| 
El módulo de E/S (módulo de entrada/salida) es un componente de hardware que actúa como intermediario entre el controlador y varios dispositivos o sistemas que necesitan intercambiar datos con el controlador.



 a| 
link:power-supply-replace.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



 a| 
link:rtc-battery-replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.



 a| 
link:system-management-replace.html["Módulo de gestión del sistema"]
 a| 
El módulo de gestión del sistema proporciona la interfaz entre el controlador y una consola o portátil para el mantenimiento del controlador o del sistema. El módulo de gestión del sistema contiene el soporte de arranque y almacena el número de serie del sistema (SSN).

|===