---
permalink: asa150/install-videos.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, asa a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Pasos de vídeo - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use los siguientes vídeos para aprender a montar en rack y conectar los cables del sistema y realizar la configuración inicial del sistema.

Si tiene una configuración de MetroCluster, utilice https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentación de MetroCluster"^].

*Advertencia:* Si su sistema se instala con ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 o ONTAP 9.15,1 - 9.15.1P2 y su sistema contiene 10 o más unidades de estado sólido internas, debe tomar medidas adicionales para preparar el sistema para la instalación. Consulte Problema  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173: ADP no deja una partición raíz de repuesto en un AFF A150 con 10 o más unidades internas"^].

Instalación y cableado de hardware:: El siguiente vídeo muestra cómo instalar y conectar el sistema por cable.


.Animación: Instalación y configuración de un AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]

NOTE: El ASA A150 utiliza el mismo procedimiento de instalación que el sistema AFF A150.
