---
permalink: asa150/overview.html 
sidebar: sidebar 
keywords: ASA A150 specifications, ASA A150 specs, NetApp ASA A150, ASA A150 hardware 
summary: Especificaciones clave del sistema de almacenamiento ASA A150 
---
= Especificaciones clave del ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el ASA A150.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del ASA A150 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del ASA A150

Configuración de la plataforma: ASA A150 UTA2, par HA de chasis único

Capacidad bruta máxima: 0,5472 PB

Memoria: 64.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe:

Versión mínima de ONTAP : ONTAP 9.13.1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS |  |  |  


| SAN | 6 | 3,3 PB / 2,9 PiB | 384 GB 


| Par HA |  | 0,5 PB / 0,5 PiB | 64,0000 
|===


=== IO



==== E/S integrada

|===


| Protocolo | Puertos 


| Ethernet de 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS de 12 Gbps | 4 
|===


==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS de 12 Gbps | 4 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB de 12 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

FC; iSCSI; NVMe/TCP;



=== Especificaciones del entorno del sistema

No hay datos ambientales disponibles.



=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes; Administración en banda SAS a través de conexiones SAS;
