---
permalink: fas50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, replace the chassis 
summary: Antes de reemplazar el chasis de su sistema FAS50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el chasis de reemplazo correcto y las herramientas necesarias. 
---
= Requisitos de sustitución del chasis - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reemplazar el chasis de su sistema FAS50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el chasis de reemplazo correcto y las herramientas necesarias.

Revise los siguientes requisitos y consideraciones.



== Requisitos

* El chasis de reemplazo debe ser el mismo modelo que el chasis dañado. Este procedimiento es para un reemplazo similar, no para una actualización.
* El resto de componentes del sistema de almacenamiento deben funcionar correctamente. De lo contrario, póngase en contacto https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"] antes de continuar con este procedimiento.




== Consideraciones

* El procedimiento de sustitución del chasis es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.
* Es posible usar el procedimiento de reemplazo de chasis con todas las versiones de ONTAP compatibles con el sistema de almacenamiento.
* El procedimiento de sustitución del chasis se escribe suponiendo que va a mover el panel frontal, las unidades, los espacios vacíos de unidad y las controladoras al nuevo chasis.


.El futuro
Después de revisar los requisitos para reemplazar el chasis, debe link:chassis-replace-shutdown.html["apague las controladoras"].
