---
sidebar: sidebar 
permalink: fas50/install-requirements.html 
keywords: fas50, install, setup, cautions 
summary: Revise los requisitos del sistema de almacenamiento FAS50. 
---
= Requisitos de instalación - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise los requisitos del sistema de almacenamiento FAS50.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Peso del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.

El sistema de almacenamiento puede pesar hasta 24,4 kg (53,8 lb). Para levantar el sistema de almacenamiento, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[FAS50 icono de advertencia de peso]



=== Peso del estante

Tome las precauciones necesarias al mover o levantar su estante.

Un estante DS460C puede pesar hasta 260,4 lbs (181,1 kg). Para levantar el estante, es posible que necesite hasta cinco personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de instalación y las consideraciones de su sistema de almacenamiento,link:install-prepare.html["prepare la instalación"]
