---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: fas50, replace io module 
summary: Los sistemas de almacenamiento FAS50 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S para mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para mejorar las capacidades de la red o reparar un módulo averiado. 
---
= Descripción general del mantenimiento del módulo de E/S - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento FAS50 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S para mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para mejorar las capacidades de la red o reparar un módulo averiado.

Puede reemplazar un módulo de E/S defectuoso en su sistema de almacenamiento con el mismo tipo de módulo o con uno diferente. Puede intercambiar en caliente un clúster y un módulo de E/S de alta disponibilidad cuando su sistema de almacenamiento cumpla con los requisitos específicos. También puede agregar un módulo de E/S a un sistema de almacenamiento con ranuras disponibles.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Al agregar módulos de I/O adicionales, se puede mejorar la redundancia y ayudar a garantizar que el sistema de almacenamiento siga funcionando incluso si falla un módulo de I/O.

* link:io-module-hotswap.html["Intercambia en caliente un módulo de E/S"]
+
Puedes intercambiar en caliente ciertos módulos de E/S por un módulo de E/S equivalente para restaurar el sistema de almacenamiento a su estado de funcionamiento óptimo. El intercambio en caliente se hace sin tener que realizar una toma de control manual.

+
Para utilizar este procedimiento, su sistema de almacenamiento debe ejecutar ONTAP 9.17.1 o posterior y cumplir con los requisitos específicos del sistema.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de I/O con fallos puede restaurar el sistema de almacenamiento a su estado operativo óptimo.


