---
permalink: fas9500/chassis_replace_overview.html 
sidebar: sidebar 
keywords:  
summary: Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico. 
---
= Sustituya el chasis - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


.Antes de empezar
[role="lead"]
Para reemplazar el chasis, debe retirar las fuentes de alimentación, ventiladores, módulos de controlador, módulos de E/S, módulos DCPM, Y el módulo LED USB del chasis dañado, retire el chasis dañado del bastidor del equipo o del armario del sistema, instale el chasis de repuesto en su lugar y, a continuación, instale los componentes en el chasis de reemplazo.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

.Acerca de esta tarea
* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

