---
permalink: fas9500/chassis_replace_overview.html 
sidebar: sidebar 
keywords: fas9500, replace the chassis 
summary: Para sustituir el chasis, tienes que retirar las fuentes de alimentación, los ventiladores, los módulos controladores, los módulos de E/S, los módulos DCPM y el módulo LED USB del chasis dañado e instalarlos en el chasis de sustitución. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para reemplazar el chasis, debe retirar las fuentes de alimentación, ventiladores, módulos de controlador, módulos de E/S, módulos DCPM, Y el módulo LED USB del chasis dañado, retire el chasis dañado del bastidor del equipo o del armario del sistema, instale el chasis de repuesto en su lugar y, a continuación, instale los componentes en el chasis de reemplazo.

.Antes de empezar
El resto de componentes del sistema deben funcionar correctamente; si no es así, ponte en contacto con soporte técnico.

.Acerca de esta tarea
* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento es disruptivo. Para un clúster de dos nodos, tienes una interrupción total del servicio y una interrupción parcial en un clúster de varios nodos.

