---
permalink: fas9500/controller_replace_overview.html 
sidebar: sidebar 
keywords: FAS9500 
summary: Debe revisar los requisitos previos del procedimiento de reemplazo y seleccionar el correcto para su versión del sistema operativo ONTAP. 
---
= Sustituya el módulo del controlador - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sustituir el módulo del controlador dañado, debe apagar el controlador dañado, mover los componentes internos al módulo del controlador de recambio, instalar el módulo del controlador de recambio y reiniciar el controlador de recambio.

.Antes de empezar
Debe revisar los requisitos previos del procedimiento de reemplazo y seleccionar el correcto para su versión del sistema operativo ONTAP.

[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====
* Todas las bandejas de unidades deben funcionar correctamente.
* Si el sistema tiene una licencia V_StorageAttach, debe consultar los pasos adicionales necesarios antes de realizar este procedimiento.
* Si su sistema está en un par de alta disponibilidad, el nodo en buen estado debe ser capaz de tomar el nodo que se va a sustituir (denominado en este procedimiento el «'nodo dañado''').
* Si su sistema está en una configuración MetroCluster, debe revisar la sección https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"^] para determinar si debe utilizar este procedimiento.
+
Si este es el procedimiento que debe utilizar, tenga en cuenta que el procedimiento de sustitución de controladora para un nodo en una configuración MetroCluster de cuatro u ocho nodos es el mismo que el de una pareja de alta disponibilidad. No es necesario realizar pasos específicos de MetroCluster porque el fallo está limitado a un par de alta disponibilidad y pueden utilizarse comandos de recuperación tras fallos del almacenamiento para proporcionar un funcionamiento no disruptivo durante el reemplazo.

* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Debe sustituir un módulo de controlador por un módulo de controlador del mismo tipo de modelo. No puede actualizar su sistema simplemente reemplazando el módulo del controlador.
* No es posible cambiar ninguna unidad o bandeja de unidades como parte de este procedimiento.
* En este procedimiento, el dispositivo de arranque pasa del nodo dañado al nodo de sustitución de modo que el nodo de sustitución se arranque en la misma versión de ONTAP que el módulo de la controladora anterior.
* Es importante que aplique los comandos de estos pasos en los sistemas correctos:
+
** El nodo dañado es el nodo que se va a reemplazar.
** El nodo de sustitución es el nuevo nodo que está reemplazando el nodo dañado.
** El nodo correcto es el nodo superviviente.



