---
permalink: fas9500/nvram_module_or_nvram_dimm_replacement.html 
sidebar: sidebar 
keywords:  
summary: 'El módulo NVRAM consta de NVRAM11 y DIMM, y hasta dos módulos Flash Cache SSD NVMe (Flash Cache o módulos de almacenamiento en caché) por módulo NVRAM.' 
---
= Sustituya el módulo NVRAM y/o los módulos DIMM NVRAM - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El módulo NVRAM consta de NVRAM11 y DIMM. Puede sustituir un módulo NVRAM con fallos o los DIMM dentro del módulo NVRAM. Para sustituir un módulo NVRAM con fallos, debe quitarlo del chasis, mover los DIMM al módulo de reemplazo e instalar el módulo NVRAM de reemplazo en el chasis.

Para sustituir y el DIMM de NVRAM, debe extraer el módulo NVRAM del chasis, sustituir el DIMM con errores en el módulo y, a continuación, volver a instalar el módulo NVRAM.

.Acerca de esta tarea
Debido a que el ID del sistema se deriva del módulo NVRAM, si se reemplaza el módulo, los discos que pertenecen al sistema se reasignan a un nuevo ID del sistema.

.Antes de empezar
* Todas las bandejas de discos deben funcionar correctamente.
* Si su sistema está en un par de alta disponibilidad, el nodo del partner debe poder tomar el control del nodo asociado con el módulo NVRAM que se va a reemplazar.
* Este procedimiento usa la siguiente terminología:
+
** El nodo dañado es el nodo en el que realiza tareas de mantenimiento.
** El nodo correcto es el compañero de alta disponibilidad del nodo dañado.


* Este procedimiento incluye pasos para reasignar discos de manera automática o manual al módulo de controladora asociado al nuevo módulo NVRAM. Debe reasignar los discos cuando se le indique en el procedimiento. Si se completa la reasignación del disco antes de la devolución, pueden producirse problemas.
* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* No puede cambiar ningún disco o bandeja de discos como parte de este procedimiento.




== Paso 1: Apague el nodo dañado

Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

.Acerca de esta tarea
Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].

.Pasos
. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
`Waiting for giveback...`
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===




== Paso 2: Sustituya el módulo NVRAM

Para sustituir el módulo NVRAM, búsquelo en la ranura 6 del chasis y siga la secuencia específica de pasos.

. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Quite el módulo NVRAM de destino del chasis:
+
.. Pulse el botón de leva numerado y con letras.
+
El botón de leva se aleja del chasis.

.. Gire el pestillo de la leva hacia abajo hasta que esté en posición horizontal.
+
El módulo NVRAM se desconecta del chasis y se mueve hacia fuera unas pocas pulgadas.

.. Extraiga el módulo NVRAM del chasis tirando de las lengüetas de tiro situadas en los lados de la cara del módulo.
+
.Animación: Sustituya el módulo NVRAM
video::228cbd14-4cb2-49b5-88f1-ae78004b9d84[panopto]
+
image::../media/drw_9500_move-remove_NVRAM_module.svg[drw 9500 Move retire el módulo NVRAM]

+
[cols="20%,90%"]
|===


 a| 
image::../media/legend_icon_01.svg[icono de leyenda 01]
 a| 
Pestillo de leva de E/S numerado y con letras



 a| 
image::../media/legend_icon_02.svg[icono de leyenda 02]
 a| 
Pestillo de I/o completamente desbloqueado

|===


. Coloque el módulo NVRAM en una superficie estable y retire la cubierta del módulo NVRAM presionando el botón azul de bloqueo de la cubierta y, a continuación, mientras mantiene pulsado el botón azul, deslice la tapa fuera del módulo NVRAM.
+
image::../media/drw_9500_remove_NVRAM_module_contents.svg[drw 9500 retire el contenido del módulo NVRAM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icono de leyenda 01]
 a| 
Botón de bloqueo de la cubierta



 a| 
image::../media/legend_icon_02.svg[icono de leyenda 02]
 a| 
Lengüetas del expulsor de DIMM y DIMM

|===
. Extraiga los DIMM, de uno en uno, del módulo NVRAM antiguo e instálelos en el módulo NVRAM de repuesto.
. Cierre la cubierta del módulo.
. Instale el módulo NVRAM de repuesto en el chasis:
+
.. Alinee el módulo con los bordes de la abertura del chasis en la ranura 6.
.. Deslice suavemente el módulo dentro de la ranura hasta que el pestillo de la leva de E/S con letras y numeradas comience a acoplarse con el pasador de leva de E/S y, a continuación, empuje el pestillo de la leva de E/S hasta bloquearlo en su lugar.






== Paso 3: Sustituya un DIMM de NVRAM

Para sustituir los DIMM de NVRAM en el módulo NVRAM, debe extraer el módulo NVRAM, abrir el módulo y, a continuación, sustituir el DIMM de destino.

. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Quite el módulo NVRAM de destino del chasis:
+
.. Pulse el botón de leva numerado y con letras.
+
El botón de leva se aleja del chasis.

.. Gire el pestillo de la leva hacia abajo hasta que esté en posición horizontal.
+
El módulo NVRAM se desconecta del chasis y se mueve hacia fuera unas pocas pulgadas.

.. Extraiga el módulo NVRAM del chasis tirando de las lengüetas de tiro situadas en los lados de la cara del módulo.
+
.Animación: Sustituya el módulo NVRAM
video::228cbd14-4cb2-49b5-88f1-ae78004b9d84[panopto]
+
image::../media/drw_9500_move-remove_NVRAM_module.svg[drw 9500 Move retire el módulo NVRAM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icono de leyenda 01]
 a| 
Pestillo de leva de E/S numerado y con letras



 a| 
image::../media/legend_icon_02.svg[icono de leyenda 02]
 a| 
Pestillo de I/o completamente desbloqueado

|===


. Coloque el módulo NVRAM en una superficie estable y retire la cubierta del módulo NVRAM presionando el botón azul de bloqueo de la cubierta y, a continuación, mientras mantiene pulsado el botón azul, deslice la tapa fuera del módulo NVRAM.
+
image::../media/drw_9500_remove_NVRAM_module_contents.svg[drw 9500 retire el contenido del módulo NVRAM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icono de leyenda 01]
 a| 
Botón de bloqueo de la cubierta



 a| 
image::../media/legend_icon_02.svg[icono de leyenda 02]
 a| 
Lengüetas del expulsor de DIMM y DIMM

|===
. Localice el DIMM que se va a sustituir dentro del módulo NVRAM y, a continuación, extráigalo presionando las lengüetas de bloqueo del DIMM y extráigalo del zócalo.
. Instale el módulo DIMM de repuesto alineando el módulo DIMM con el zócalo e empuje suavemente el módulo DIMM hacia el zócalo hasta que las lengüetas de bloqueo queden trabadas en su lugar.
. Cierre la cubierta del módulo.
. Instale el módulo NVRAM en el chasis:
+
.. Alinee el módulo con los bordes de la abertura del chasis en la ranura 6.
.. Deslice suavemente el módulo dentro de la ranura hasta que el pestillo de la leva de E/S con letras y numeradas comience a acoplarse con el pasador de leva de E/S y, a continuación, empuje el pestillo de la leva de E/S hasta bloquearlo en su lugar.






== Paso 4: Reinicie la controladora después de sustituir FRU

Después de sustituir el FRU, debe reiniciar el módulo de la controladora.

. Para arrancar ONTAP desde el aviso del CARGADOR, introduzca `bye`.




== Paso 5: Verifique y configure el estado de alta disponibilidad del módulo de la controladora

Debe comprobar el `HA` estado del módulo de la controladora y, si es necesario, actualice el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento del módulo del controlador de repuesto, compruebe que todos los componentes muestran lo mismo `HA` provincia: `ha-config show`
+
[cols="1,2"]
|===
| Si el sistema está en... | El estado de alta disponibilidad de todos los componentes debería ser... 


 a| 
Un par de alta disponibilidad
 a| 
ha



 a| 
Una configuración FC de MetroCluster con cuatro nodos o más
 a| 
mcc



 a| 
Una configuración de IP de MetroCluster
 a| 
mccip

|===
. Si el estado del sistema mostrado del módulo del controlador no coincide con la configuración del sistema, defina el `HA` estado para el módulo de la controladora: `ha-config modify controller _ha-state_`
. Si el estado del sistema mostrado del chasis no coincide con la configuración del sistema, defina el `HA` estado para el chasis: `ha-config modify chassis _ha-state_`




== Paso 6: Reasignar discos

Deberá confirmar el cambio de ID del sistema cuando arranque el nodo de reemplazo y, a continuación, compruebe que se ha implementado el cambio.

Este procedimiento solo se aplica a sistemas que ejecutan ONTAP en una pareja de ha.

.Pasos
. Si el nodo de reemplazo está en modo de mantenimiento (se muestra el `*>` Prompt), salga del modo de mantenimiento y vaya al símbolo del sistema del CARGADOR: `halt`
. Desde el símbolo del sistema DEL CARGADOR en el nodo de reemplazo, arranque el nodo, introduciendo `y` Si se le solicita que anule el ID del sistema debido a que el ID del sistema no coincide.
. Espere hasta la `Waiting for giveback...` El mensaje se muestra en la consola del nodo de repuesto y, a continuación, en el nodo en buen estado, compruebe que el nuevo ID de sistema del partner se ha asignado automáticamente: `storage failover show`
+
En el resultado del comando, debería ver un mensaje que indica que el ID del sistema ha cambiado en el nodo dañado, mostrando los ID anteriores y los nuevos correctos. En el ejemplo siguiente, el nodo 2 debe ser sustituido y tiene un ID de sistema nuevo de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Desde el nodo en buen estado, compruebe que se han guardado los núcleo:
+
.. Cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Usted puede responder `Y` cuando se le solicite que continúe en el modo avanzado. Aparece el símbolo del sistema del modo avanzado (*>).

.. Guarde sus núcleo: `system node run -node local-node-name partner savecore`
.. Espere a que el `savecore` comando que se debe completar antes de emitir la devolución.
+
Puede introducir el siguiente comando para supervisar el progreso del `savecore` comando: `system node run -node local-node-name partner savecore -s`

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Proporcione al nodo:
+
.. Desde el nodo en buen estado, vuelva a asignar el almacenamiento del nodo sustituido: `storage failover giveback -ofnode replacement_node_name`
+
El nodo de sustitución recupera su almacenamiento y completa el arranque.

+
Si se le solicita que anule el ID del sistema debido a una falta de coincidencia de ID del sistema, debe introducir `y`.

+

NOTE: Si el retorno se vetó, puede considerar la sustitución de los vetos.

+
Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted["Comandos de devolución manual"^] tema para anular el veto.

.. Una vez finalizada la devolución, confirme que el par de alta disponibilidad está en buen estado y que la toma de control es posible: `storage failover show`
+
El resultado del comando Storage Failover show no debe incluir el ID del sistema cambiado en el mensaje del partner.



. Compruebe que los discos se han asignado correctamente: `storage disk show -ownership`
+
Los discos que pertenecen al nodo de reemplazo deben mostrar el nuevo ID del sistema. En el ejemplo siguiente, los discos propiedad del nodo 1 ahora muestran el nuevo ID del sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Si el sistema está en una configuración de MetroCluster, supervise el estado del nodo: `metrocluster node show`
+
La configuración de MetroCluster tarda unos minutos después del reemplazo y vuelve a su estado normal, momento en el que cada nodo mostrará un estado configurado, con mirroring DR habilitado y un modo normal. La `metrocluster node show -fields node-systemid` El resultado del comando muestra el ID del sistema antiguo hasta que la configuración de MetroCluster vuelve a ser un estado normal.

. Si el nodo está en una configuración MetroCluster, según el estado del MetroCluster, compruebe que el campo ID de inicio de recuperación ante desastres muestra el propietario original del disco si el propietario original es un nodo del sitio de desastres.
+
Esto es necesario si se cumplen las dos opciones siguientes:

+
** La configuración de MetroCluster está en estado de conmutación.
** El nodo de sustitución es el propietario actual de los discos del sitio de recuperación ante desastres.
+
Consulte https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Cambios en la propiedad de disco durante la toma de control de alta disponibilidad y el cambio de MetroCluster en una configuración MetroCluster de cuatro nodos"^] si quiere más información.



. Si su sistema está en una configuración MetroCluster, compruebe que cada nodo esté configurado: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Compruebe que existen volúmenes esperados para cada nodo: `vol show -node node-name`
. Si deshabilitó la toma de control automática al reiniciar, habilite esa función desde el nodo en buen estado: `storage failover modify -node replacement-node-name -onreboot true`




== Paso 7: Restaure el almacenamiento y la funcionalidad de cifrado de volúmenes

Para los sistemas de almacenamiento que haya configurado previamente para usar almacenamiento o cifrado de volúmenes, debe realizar pasos adicionales para ofrecer funcionalidad de cifrado ininterrumpido. Puede omitir esta tarea en sistemas de almacenamiento que no tengan el cifrado de volúmenes o almacenamiento habilitado.


NOTE: Este paso no es necesario al sustituir un DIMM.

.Pasos
. Siga uno de estos procedimientos, en función de si utiliza la gestión de claves externa o incorporada:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaure las claves de cifrado de gestión de claves incorporadas"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaure las claves de cifrado de gestión de claves externas"^]


. Restablezca el MSID de SED




== Paso 8: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Retorno de artículo  sustituciones"] para obtener más información.
