---
permalink: fas9500/power_supply_swap_out.html 
sidebar: sidebar 
keywords:  
summary: El intercambio de una fuente de alimentación implica apagar, desconectar y retirar la fuente de alimentación antigua e instalar, conectar y encender la fuente de alimentación de repuesto. 
---
= Cambie una fuente de alimentación - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El intercambio de una fuente de alimentación implica apagar, desconectar y extraer la fuente de alimentación e instalar, conectar y encender la fuente de alimentación de reemplazo.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

.Acerca de esta tarea
* Los sistemas de alimentación son redundantes y intercambiables en caliente.
* Este procedimiento se escribe para sustituir una fuente de alimentación a la vez.
+

NOTE: Se recomienda sustituir el suministro de alimentación en un plazo de dos minutos tras retirarlo del chasis. El sistema sigue funcionando, pero ONTAP envía mensajes a la consola acerca del suministro de alimentación degradado hasta que se reemplaza el suministro de alimentación.

* Existen cuatro fuentes de alimentación en el sistema.
* Las fuentes de alimentación están de alcance automático.
+

IMPORTANT: No mezcle las PSU con diferentes niveles de eficiencia. Sustituya siempre como por ejemplo.



.Pasos
. Identifique la fuente de alimentación que desea reemplazar, basándose en mensajes de error de la consola o a través de los LED de las fuentes de alimentación.
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Apague la fuente de alimentación y desconecte los cables de alimentación:
+
.. Apague el interruptor de alimentación de la fuente de alimentación.
.. Abra el retenedor del cable de alimentación y, a continuación, desconecte el cable de alimentación de la fuente de alimentación.


. Mantenga pulsado el botón terracota del asa de la fuente de alimentación y, a continuación, extraiga la fuente de alimentación del chasis.
+

CAUTION: Al extraer una fuente de alimentación, utilice siempre dos manos para soportar su peso.

+
.Animación: Extraiga/instale la PSU
video::590b3414-6ea5-42b2-b7f4-ae78004b86a4[panopto]
+
image::../media/drw_9500_remove_install_PSU_module.svg[drw 9500 retire la instalación del módulo PSU]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icono de leyenda 01]
 a| 
Botón de bloqueo

|===
. Asegúrese de que el interruptor de encendido/apagado de la nueva fuente de alimentación esté en la posición de apagado.
. Con ambas manos, sujete y alinee los bordes de la fuente de alimentación con la abertura del chasis del sistema y, a continuación, empuje suavemente la fuente de alimentación hacia el chasis hasta que encaje en su sitio.
+
Las fuentes de alimentación están codificadas y sólo se pueden instalar de una manera.

+

IMPORTANT: No ejerza demasiada fuerza al deslizar la fuente de alimentación en el sistema. Puede dañar el conector.

. Vuelva a conectar el cableado de la fuente de alimentación:
+
.. Vuelva a conectar el cable de alimentación a la fuente de alimentación.
.. Fije el cable de alimentación a la fuente de alimentación con el retenedor del cable de alimentación.
+
Una vez restaurada la alimentación de la fuente de alimentación, el LED de estado debería ser verde.



. Encienda la fuente de alimentación nueva y, a continuación, compruebe el funcionamiento de los LED de actividad del suministro de alimentación.
+
El LED de alimentación verde se ilumina cuando la fuente de alimentación está completamente insertada en el chasis y el LED de atención ámbar parpadea inicialmente, pero se apaga después de unos momentos.

. Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Retorno de artículo  sustituciones"^] para obtener más información.

