---
permalink: fas2800/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: fas2820, shut, down, impaired, controller, take, over 
summary: Apaga el controlador de tu sistema de almacenamiento FAS2820 para evitar la pérdida de datos y mantener la estabilidad del sistema durante el proceso manual de recuperación del medio de arranque. 
---
= Apaga el controlador de tu sistema FAS2820 durante el proceso de recuperación de arranque manual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apaga el controlador de tu sistema de almacenamiento FAS2820 para evitar la pérdida de datos y mantener la estabilidad del sistema durante el proceso manual de recuperación del medio de arranque.

Si su sistema de almacenamiento ejecuta ONTAP 9.17.1 o posterior, utilice ellink:bootmedia-replace-workflow-bmr.html["procedimiento de recuperación de arranque automatizado"] .  Si su sistema está ejecutando una versión anterior de ONTAP, debe utilizar el procedimiento de recuperación de arranque manual.

Completa el apagado del controlador dañado deteniéndolo en el indicador LOADER y capturando las variables de entorno de arranque. El indicador LOADER es el estado de detención seguro desde el que puedes reemplazar el medio de arranque.

.Pasos
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado muestra... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya a Quitar módulo de controlador.



 a| 
`Waiting for giveback...`
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode impaired_node_name`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===
. Desde el aviso del CARGADOR, introduzca: `printenv` para capturar todas las variables ambientales de arranque. Guarde el resultado en el archivo de registro.
+

NOTE: Es posible que este comando no funcione si el dispositivo de inicio está dañado o no funciona.



.El futuro
Después de apagar el controlador, debe link:bootmedia-replace.html["sustituya el soporte de arranque"].
