---
permalink: fas2800/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas 2800, post, boot, media, okm, nse, nve, onboard key manager, netapp storage encryption, netapp volume encryption 
summary: 'Una vez marcadas las variables de entorno, debe completar los pasos específicos de los sistemas que tienen Onboard Key Manager \(OKM\), NetApp Storage Encryption \(NSE\) o NetApp Volume Encryption \(NVE\) habilitado.' 
---
= Restaure OKM, NSE y NVE según sea necesario: FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez comprobadas las variables de entorno, debe completar los pasos específicos de los sistemas que tengan habilitado su gestión de claves incorporada (OKM), cifrado de almacenamiento de NetApp (NSE) o cifrado de volúmenes de NetApp (NVE) mediante la configuración capturada al principio de este procedimiento.


NOTE: Si NSE o NVE están habilitados junto con Onboard Key Manager, debe restaurar la configuración que capturó al principio de este procedimiento.

.Pasos
. Conecte el cable de consola a la controladora de destino.
. Utilice la `boot_ontap` Comando en el símbolo del sistema del CARGADOR para arrancar la controladora.
. Compruebe la salida de la consola:
+
[cols="1,3"]
|===
| Si la consola muestra... | Realice lo siguiente... 


 a| 
La solicitud de inicio de sesión de
 a| 
Vaya al paso 7.



 a| 
Esperando devolución...
 a| 
.. Inicie sesión en el controlador asociado.
.. Confirme que la controladora de destino está lista para la devolución con el `storage failover show` comando.


|===
. Mueva el cable de la consola a la controladora correspondiente y regrese el almacenamiento de la controladora objetivo mediante el `storage failover giveback -fromnode local -only-cfo-aggregates true local` comando.
+
** Si el comando falla debido a un disco fallido, desactive físicamente el disco que ha fallado, pero deje el disco en la ranura hasta que se reciba un reemplazo.
** Si el comando falla debido a una sesión CIFS abierta, compruebe con el cliente cómo se cierran las sesiones CIFS.
+

NOTE: Los terminación CIFS pueden provocar la pérdida de datos.

** Si el comando falla porque el partner está "no listo", espere 5 minutos para que los NVMems se sincronicen.
** Si se produce un error en el comando debido a un proceso de NDMP, SnapMirror o SnapVault, deshabilite el proceso. Consulte el centro de documentación adecuado para obtener más información.


. Espere 3 minutos y compruebe el estado de la conmutación al nodo de respaldo con el `storage failover show` comando.
. En el símbolo del sistema clustershell, introduzca el `net int show -is-home false` comando para mostrar las interfaces lógicas que no están en su controladora y puerto de inicio.
+
Si alguna interfaz aparece como `false`, vuelva a revertir estas interfaces a su puerto de inicio mediante el `net int revert -vserver Cluster -lif _nodename_` comando.

. Mueva el cable de la consola a la controladora de destino y ejecute el `version -v` Comando para comprobar las versiones de ONTAP.
. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.
. Utilice la `storage encryption disk show` en el símbolo del sistema clustershell, para revisar el resultado.
. Utilice la `security key-manager key query` Comando para mostrar los ID de claves de las claves de autenticación que se almacenan en los servidores de gestión de claves.
+
** Si la `Restored` columna = `yes/true`, ha finalizado y puede continuar con el proceso de sustitución.
** Si la `Key Manager type` = `external` y la `Restored` columna = cualquier otra cosa que no sea `yes/true`, utilice la `security key-manager external restore` Comando para restaurar los ID de claves de las claves de autenticación.
+

NOTE: Si el comando falla, póngase en contacto con el servicio de atención al cliente.

** Si la `Key Manager type` = `onboard` y la `Restored` columna = cualquier otra cosa que no sea `yes/true`, utilice la `security key-manager onboard sync` Comando para volver a sincronizar el tipo de gestor de claves.
+
Utilice la consulta de claves del administrador de claves de seguridad para verificar que el `Restored` columna = `yes/true` para todas las claves de autenticación.



. Conecte el cable de la consola al controlador asociado.
. Respalde la controladora con el `storage failover giveback -fromnode local` comando.
. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.
. Restaure AutoSupport si se deshabilitó mediante el `system node autosupport invoke -node * -type all -message MAINT=END`

