---
permalink: fas2800/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague los controladores - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apague las controladoras para poder realizar el mantenimiento del chasis.

Este procedimiento es para sistemas con configuraciones de dos nodos. Si tiene un sistema con más de dos nodos, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Cómo realizar un apagado y encendido con gracia de una pareja de alta disponibilidad en un clúster de cuatro nodos"^].

.Antes de empezar
* Detenga el acceso de todos los clientes/host a los datos del sistema de NetApp.
* Suspender trabajos de backup externo.
* Asegúrese de que dispone de los permisos y credenciales necesarios:
+
** Credenciales de administrador local para ONTAP.
** Clave de acceso para todo el clúster de gestión de claves incorporada de NetApp (OKM) si usa cifrado de almacenamiento o NVE/NAE.
** Accesibilidad de BMC para cada controladora.


* Asegúrese de que dispone de las herramientas y el equipo necesarios para la sustitución.
* Como práctica recomendada antes del cierre, debe:
+
** Realizar adicionales https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["comprobaciones de estado del sistema"].
** Actualice ONTAP a una versión recomendada para el sistema.
** Resuelva cualquier https://activeiq.netapp.com/["Alertas de estado y riesgos de Active IQ"]. Tome nota de cualquier fallo presente en el sistema, como los LED de los componentes del sistema.




.Pasos
. Inicie sesión en el clúster a través de SSH o inicie sesión desde cualquier nodo del clúster mediante un cable de consola local y un equipo portátil/consola.
. Desactive AutoSupport e indique cuánto tiempo espera que el sistema esté fuera de línea:
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identifique la dirección del SP/BMC de todos los nodos:
+
`system service-processor show -node * -fields address`

. Salga del shell de cluster: `exit`
. Inicie sesión en SP/BMC sobre SSH con la dirección IP de cualquiera de los nodos que aparecen en el resultado del paso anterior.
+
Si está utilizando una consola/portátil, inicie sesión en la controladora con las mismas credenciales de administrador del clúster.

+

NOTE: Abra una sesión SSH en cada conexión SP/BMC de modo que pueda supervisar el progreso.

. Detenga los dos nodos ubicados en el chasis dañado:
+
`system node halt -node <node>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para los clústeres que utilizan SnapMirror síncrono en modo StrictSync: `system node halt -node <node>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Introduzca *y* para cada controlador en el clúster cuando lo vea `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Espere a que cada controladora se detenga y muestre el aviso del CARGADOR.

