---
permalink: fas2800/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas2800, how to recable the system, how to reassign disks 
summary: Debe volver a poder utilizar el almacenamiento y confirmar la reasignación del disco. 
---
= Vuelva a conectar el sistema y vuelva a asignar los discos - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para completar el procedimiento de sustitución y restaurar el sistema a pleno funcionamiento, debe volver a montar el almacenamiento, confirmar la reasignación del disco, restaurar la configuración de cifrado del almacenamiento de NetApp (si fuera necesario) e instalar licencias para la nueva controladora. Debe completar una serie de tareas antes de restaurar el sistema a pleno funcionamiento.



== Paso 1: Recuperar el sistema

Vuelva a conectar los cables de las conexiones de red y almacenamiento del módulo del controlador.

.Pasos
. Vuelva a conectar el módulo del controlador a las conexiones de red y almacenamiento.
. Compruebe que el cableado sea correcto mediante el https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Descargue e instale Config Advisor.
.. Introduzca la información del sistema de destino y haga clic en Collect Data.
.. Haga clic en la ficha cableado y, a continuación, examine la salida. Asegúrese de que se muestren todas las bandejas de discos y todos los discos aparecen en el resultado, corrigiendo los problemas de cableado que encuentre.
.. Compruebe otro cableado haciendo clic en la ficha correspondiente y, a continuación, examinando el resultado de Config Advisor.






== Paso 2: Reasignar discos

Debe confirmar el cambio de ID del sistema al arrancar el controlador _reboot_ y, a continuación, comprobar que se ha implementado el cambio.

. Si el controlador _reader_ está en modo de mantenimiento (mostrando la `*>` Salga del modo de mantenimiento y vaya al símbolo del sistema del CARGADOR: `halt`
. Desde el símbolo DEL SISTEMA DEL CARGADOR en el controlador _reboot_, arranque el controlador, introduciendo `y` Si se le solicita que anule el ID del sistema debido a una discrepancia de ID del sistema:``boot_ontap``
. Espere hasta la `Waiting for giveback...` El mensaje se muestra en la consola del controlador _regrse_ y, a continuación, en el controlador en buen estado, compruebe que el nuevo ID del sistema asociado se ha asignado automáticamente: `storage failover show`
+
En el resultado del comando, debería ver un mensaje donde se indica que el ID del sistema ha cambiado en la controladora dañada, con lo que se muestran los ID anteriores y los nuevos correctos. En el ejemplo siguiente, el nodo 2 debe ser sustituido y tiene un ID de sistema nuevo de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Desde la controladora en buen estado, compruebe que se han guardado los núcleo:
+
.. Cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Usted puede responder `Y` cuando se le solicite que continúe en el modo avanzado. Aparece el símbolo del sistema del modo avanzado (*>).

.. Guarde sus núcleo: `system node run -node _local-node-name_ partner savecore`
.. Espere a que el `savecore` comando que se debe completar antes de emitir la devolución.
+
Puede introducir el siguiente comando para supervisar el progreso del comando savecoore: `system node run -node _local-node-name_ partner savecore -s`

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Devolver la controladora:
+
.. Desde la controladora en buen estado, proporcione almacenamiento a la controladora que sustituyó: `storage failover giveback -ofnode _replacement_node_name_`
+
La controladora _reader_ recupera su almacenamiento y completa el arranque.

+
Si se le solicita que anule el ID del sistema debido a una falta de coincidencia de ID del sistema, debe introducir `y`.

+

IMPORTANT: Si la devolución del control de entrada está vetada, resuelva el problema de veto. Si el veto no es crítico para resolverlo, puede anular el veto.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Busque el contenido de Configuración de alta disponibilidad para su versión de ONTAP 9"]

.. Una vez finalizada la devolución, confirme que el par de alta disponibilidad está en buen estado y que la toma de control es posible: `storage failover show`
+
La salida de `storage failover show` El comando no debe incluir el ID del sistema cambiado en el mensaje del partner.



. Compruebe que los discos se han asignado correctamente: `storage disk show -ownership`
+
Los discos que pertenecen al controlador _regrel_ deben mostrar el nuevo ID del sistema. En el ejemplo siguiente, los discos propiedad del nodo 1 ahora muestran el nuevo ID del sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

