---
permalink: fas2800/maintain-overview.html 
sidebar: sidebar 
keywords: fas2800 maintenance, maintenance, repairing, repairing fas2800, replace fas2800 components, replace fas2800 components 
summary: Mantener el hardware de FAS2820 
---
= Mantener el hardware de FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Realice el mantenimiento del hardware de su sistema de almacenamiento FAS2820 para garantizar la fiabilidad a largo plazo y un rendimiento óptimo. Realice tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, para evitar tiempos de inactividad y la pérdida de datos.

Los procedimientos de mantenimiento suponen que el sistema de almacenamiento FAS2820 ya se ha implementado como un nodo de almacenamiento en el entorno ONTAP .



== Componentes del sistema

Para el sistema de almacenamiento FAS2820, puede realizar procedimientos de mantenimiento en los componentes siguientes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Medios de arranque: recuperación automatizada"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar.  Durante la recuperación automatizada, el sistema recupera la imagen de arranque del nodo asociado y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen en el medio de arranque de reemplazo. El proceso de recuperación automática del medio de arranque solo es compatible con ONTAP 9.17.1 y versiones posteriores. Si su sistema de almacenamiento ejecuta una versión anterior de ONTAP, utilice el link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"] .



 a| 
link:bootmedia-replace-workflow.html["Medios de arranque: recuperación manual"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar. Durante la recuperación manual, inicia el sistema de almacenamiento desde una unidad USB y restaura manualmente la imagen y la configuración del sistema de archivos.  Si su sistema de almacenamiento ejecuta ONTAP 9.17.1 y posterior, utilice ellink:bootmedia-replace-workflow-bmr.html["procedimiento de recuperación de arranque automatizado"] .



 a| 
link:caching-module-replace.html["Módulo de almacenamiento en caché"]
 a| 
Es necesario sustituir el módulo de almacenamiento en caché de la controladora cuando el sistema registra un único mensaje de AutoSupport (ASUP) que el módulo se ha desconectado.



 a| 
link:chassis-replace-overview.html["Chasis"]
 a| 
El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



 a| 
link:controller-replace-overview.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



 a| 
link:drive-replace.html["Unidad"]
 a| 
Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



 a| 
link:nvmem-nvram-battery-replace.html["Batería NVMEM"]
 a| 
Se incluye una batería en la controladora y conserva los datos en caché si falla la alimentación de CA.



 a| 
link:pci-cards-and-risers-replace.html["Tarjeta mezzanine"]
 a| 
Una tarjeta Mezzanine es una tarjeta de expansión que está diseñada para insertarse en una ranura especializada en la placa base y contiene las tarjetas de E/S.



 a| 
link:power-supply-swap-out.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



 a| 
link:rtc-battery-replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.

|===