---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2800, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: El intercambio de una fuente de alimentación implica apagar, desconectar y retirar la fuente de alimentación dañada e instalar, conectar y encender la fuente de alimentación de reemplazo. 
---
= Cambie una fuente de alimentación - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El intercambio de una fuente de alimentación implica apagar, desconectar y retirar la fuente de alimentación dañada e instalar, conectar y encender la fuente de alimentación de reemplazo.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Los sistemas de alimentación son redundantes y intercambiables en caliente.
* Este procedimiento se escribe para sustituir una fuente de alimentación a la vez.
+

NOTE: Se recomienda sustituir el suministro de alimentación en un plazo de dos minutos tras retirarlo del chasis. El sistema sigue funcionando, pero ONTAP envía mensajes a la consola acerca del suministro de alimentación degradado hasta que se reemplaza el suministro de alimentación.

* Las fuentes de alimentación están de alcance automático.


.Animación: Sustituya la fuente de alimentación
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.Pasos
. Identifique la fuente de alimentación que desea reemplazar, basándose en mensajes de error de la consola o a través de los LED de las fuentes de alimentación.
. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Apague la fuente de alimentación y desconecte los cables de alimentación:
+
.. Apague el interruptor de alimentación de la fuente de alimentación.
.. Abra el retenedor del cable de alimentación y, a continuación, desconecte el cable de alimentación de la fuente de alimentación.
.. Desconecte el cable de alimentación de la fuente de alimentación.


. Apriete el pestillo del mango de la leva de la fuente de alimentación y, a continuación, abra el asa de la leva para liberar completamente la fuente de alimentación del plano medio.
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[drw 2850 Sustituya la fuente de alimentación IEOPS 702]

. Utilice el asa de leva para extraer la fuente de alimentación del sistema.
+

CAUTION: Al extraer una fuente de alimentación, utilice siempre dos manos para soportar su peso.

. Asegúrese de que el interruptor de encendido/apagado de la nueva fuente de alimentación esté en la posición de apagado.
. Con ambas manos, sujete y alinee los bordes de la fuente de alimentación con la abertura del chasis del sistema y, a continuación, empuje suavemente la fuente de alimentación hacia el chasis con el asa de leva.
+
Las fuentes de alimentación están codificadas y sólo se pueden instalar de una manera.

+

NOTE: No ejerza demasiada fuerza al deslizar la fuente de alimentación en el sistema. Puede dañar el conector.

. Cierre el asa de la leva de forma que el pestillo encaje en la posición de bloqueo y la fuente de alimentación esté completamente asentada.
. Vuelva a conectar el cableado de la fuente de alimentación:
+
.. Vuelva a conectar el cable de alimentación a la fuente de alimentación y a la fuente de alimentación.
.. Fije el cable de alimentación a la fuente de alimentación con el retenedor del cable de alimentación.


+
Una vez restaurada la alimentación de la fuente de alimentación, el LED de estado debería ser verde.

. Encienda la fuente de alimentación nueva y, a continuación, compruebe el funcionamiento de los LED de actividad del suministro de alimentación.
+
Los LED del sistema de alimentación se encienden cuando el suministro de alimentación se conecta.

. Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"^] la página para obtener más información.

