---
permalink: asa250/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a250, replace the boot media 
summary: Antes de reemplazar el soporte de arranque en tu sistema ASA A250, asegúrate de cumplir con los requisitos necesarios para un reemplazo exitoso. 
---
= Requisitos para la recuperación automática de medios de arranque - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el medio de arranque de tu ASA A250, asegúrate de que cumples los requisitos necesarios para que la sustitución sea exitosa. Esto incluye verificar que tienes el medio de arranque de reemplazo correcto, confirmar que el puerto e0S (e0M wrench) del controlador afectado no está defectuoso y determinar si Onboard Key Manager (OKM) o External Key Manager (EKM) están habilitados.

El proceso automatizado de recuperación de medios de arranque solo se admite en ONTAP 9.18.1 y versiones posteriores. Si tu sistema de almacenamiento está ejecutando una versión anterior de ONTAP, usa el link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"].

* Debe sustituir el componente con errores por un componente FRU de reemplazo con la misma capacidad que recibió de NetApp.
* Verifique que el puerto e0M (llave) en el controlador dañado esté conectado y no esté defectuoso.
+
El puerto e0M se utiliza para comunicarse entre los dos controladores durante el proceso de recuperación de arranque automatizado.

* Para OKM, necesita la frase de contraseña de todo el clúster y también los datos de respaldo.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** archivo /cfcard/kmip/servers.cfg.
** archivo /cfcard/kmip/certs/client.crt.
** archivo /cfcard/kmip/certs/client.key.
** Archivo /cfcard/kmip/certs/ca.pem.


* Es fundamental aplicar los comandos al controlador correcto cuando se reemplaza el medio de arranque dañado:
+
** El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
** El _controlador saludable_ es el socio HA del controlador dañado.




.El futuro
Después de revisar los requisitos de soporte de arranque, usted link:bootmedia-shutdown-bmr.html["apague la controladora"].
