---
permalink: asa250/overview.html 
sidebar: sidebar 
keywords: ASA A250 specifications, ASA A250 specs, NetApp ASA A250, ASA A250 hardware 
summary: Especificaciones clave del sistema de almacenamiento ASA A250 
---
= Especificaciones clave del ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el ASA A250.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del ASA A250 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del ASA A250

Configuración de la plataforma: ASA A250 100 V, par HA de chasis único

Capacidad bruta máxima: 0,7344 PB

Memoria: 128.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 4

Versión mínima de ONTAP : ONTAP 9.13.1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS |  |  |  


| SAN | 6 | 4,4 PB / 3,9 PiB | 768 GB 


| Par HA |  | 0,7 PB / 0,7 PiB | 128,0000 
|===


=== IO



==== E/S integrada

|===


| Protocolo | Puertos 


| Ethernet de 25 Gbps | 4 


| Ethernet de 10 Gbps | 4 
|===


==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 4 


| Ethernet de 25 Gbps | 12 


| Ethernet de 10 Gbps | 4 


| FC 32 Gbps | 8 


| NVMe/FC 32 Gbps | 8 


|  | 0 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB de 12 Mbps | 4 
|===


=== Redes de almacenamiento compatibles

FC; iSCSI; NVMe/FC; NVMe/TCP;



=== Especificaciones del entorno del sistema

No hay datos ambientales disponibles.



=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de gestión de placa base (BMC) basado en Ethernet e interfaz de gestión ONTAP ; Controladores redundantes intercambiables en caliente; Fuentes de alimentación redundantes intercambiables en caliente; Gestión en banda de SAS a través de conexiones SAS para estantes externos; [//] 2025-10-15 ontap-systems-internal/issues/1357
