---
permalink: c30-60/c60-key-specifications.html 
sidebar: sidebar 
keywords: AFF C60 specifications, AFF C60 specs, AFF C60 capacity, AFF C60 memory, AFF C60 I/O, AFF C60 compliance 
summary: Especificaciones clave del AFF C60 
---
= Especificaciones clave del AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el sistema de almacenamiento AFF C60 en un solo par de alta disponibilidad.  Visite NetApp Hardware Universe (HWU) para conocer las especificaciones completas de este sistema de almacenamiento.



== Especificaciones del AFF C60 de un vistazo

* Configuración de la plataforma: AFF C60, par HA de chasis único
* Capacidad bruta máxima: 7,3680 PB
* Memoria: 128.0000 GB
* Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades
* Versión de ONTAP : ONTAP: 9.16.1P2
* Ranuras de expansión PCIe: 8
* Versión mínima de ONTAP : ONTAP 9.16.1RC1




== Máximos de escalamiento

* Tipo: NAS; Pares HA: 4; Capacidad bruta: 29,5 PB / 26,2 PiB; Memoria máxima: 512 GB
* Tipo: SAN; Pares HA: 4; Capacidad bruta: 29,5 PB / 26,2 PiB; Memoria máxima: 512 GB
* Tipo: Par HA; Capacidad bruta: 7,4 PB / 6,5 PiB; Memoria máxima: 128,0000




== E/S



=== E/S integrada

No hay datos de E/S integrados.



=== E/S total

* Protocolo: Ethernet 100 Gbps; Puertos: 16
* Protocolo: Ethernet 25 Gbps; Puertos: 24
* Protocolo: Ethernet 10 Gbps; Puertos: 24
* Protocolo: FC 64 Gbps; Puertos: 24
* Protocolo: NVMe/FC 64 Gbps; Puertos: 24
* Puertos: 0




=== Puertos de gestión

* Protocolo: Ethernet 1 Gbps; Puertos: 2
* Protocolo: RS-232 115 Kbps; Puertos: 4
* Protocolo: USB 600 Mbps; Puertos: 2




== Redes de almacenamiento compatibles

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1




== Especificaciones del entorno del sistema

* Potencia típica: 2892 BTU/h
* Potencia en el peor de los casos: 4445 BTU/h
* Peso: 60,7 lb 27,5 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad:
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °C (50 °F a 95 °F) a una altitud de hasta 3048 m (10 000 pies); humedad relativa del 8 % al 80 %, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12192 m (40000 pies) 10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0 Presión sonora (LpAm) (posiciones de transeúntes): 70,5 dB




== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidad

* Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP
* Controladores redundantes intercambiables en caliente
* Fuentes de alimentación redundantes intercambiables en caliente

