---
permalink: c30-60/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, prerequisite, replace the controller module 
summary: Antes de sustituir la controladora en su sistema AFF C30 o AFF C60, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto. 
---
= Requisitos para sustituir la controladora: AFF C30 y AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir la controladora en su sistema AFF C30 o AFF C60, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto.

Revise los requisitos y las consideraciones del procedimiento de reemplazo de la controladora.



== Requisitos

* Todas las bandejas deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* Si su sistema está en una configuración MetroCluster, debe revisar la sección https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"] para determinar si debe utilizar este procedimiento.
* Debe sustituir una controladora por una controladora del mismo tipo de modelo. No se puede actualizar el sistema simplemente reemplazando la controladora.
* No es posible cambiar ninguna unidad o bandeja como parte de este procedimiento.
* Siempre debe capturar la salida de consola de la controladora en un archivo de registro de texto.
+
La salida de la consola le proporciona un registro del procedimiento que puede utilizar para solucionar los problemas que pueda encontrar durante el proceso de reemplazo.





== Consideraciones

Es importante aplicar los comandos de este procedimiento a la controladora correcta:

* El controlador _drinated_ es el controlador que se va a sustituir.
* El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
* El controlador _heated_ es el controlador que sobrevive.


.El futuro
Después de haber revisado los requisitos para reemplazar el controlador dañado, debe link:controller-replace-shutdown.html["apague el controlador defectuoso"].
