---
sidebar: sidebar 
permalink: c30-60/install-requirements.html 
keywords: aff c30, aff c60, install, setup, cautions 
summary: Revise el equipo necesario y las precauciones de elevación de su plataforma y estantes. 
---
= Requisitos y consideraciones de instalación: AFF C30 y AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulte los requisitos y consideraciones de su sistema de almacenamiento AFF C30 o AFF C60.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Peso del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.

Un sistema de almacenamiento A20, A30 o A50 puede pesar hasta 27,9 kg (61,5 lb). Para levantar el sistema de almacenamiento, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20,A30,or an A50 weight caution icon]



=== Peso del estante

Tome las precauciones necesarias al mover o levantar su estante.

Un estante NS224 con NSM100B módulos puede pesar hasta 56,8 lbs (25,8 kg). Para levantar el estante, utilice dos personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 con NSM100b precaución de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de instalación y las consideraciones de su sistema de almacenamiento,link:install-prepare.html["prepare la instalación"]
