---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module 
summary: Los sistemas de almacenamiento AFF C30 y AFF C60 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado. 
---
= Descubre cómo añadir y sustituir módulos de E/S en tu sistema de almacenamiento AFF C30 o AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento AFF C30 y AFF C60 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado.

Puedes sustituir un módulo de E/S averiado de tu sistema de almacenamiento por otro del mismo tipo o por uno diferente. Puedes intercambiar en caliente un módulo de E/S de clúster y HA cuando tu sistema de almacenamiento cumpla requisitos específicos. También puedes añadir un módulo de E/S a un sistema de almacenamiento con ranuras disponibles.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Al agregar módulos de I/O adicionales, se puede mejorar la redundancia y ayudar a garantizar que el sistema de almacenamiento siga funcionando incluso si falla un módulo de I/O.

* link:io-module-hotswap.html["Intercambia en caliente un módulo de E/S"]
+
El intercambio en caliente de determinados módulos de E/S por otros equivalentes puede restablecer el estado óptimo de funcionamiento del sistema de almacenamiento. El intercambio en caliente se realiza sin necesidad de llevar a cabo una toma de control manual.

+
Para utilizar este procedimiento, su sistema de almacenamiento debe ejecutar ONTAP 9.17.1 o posterior y cumplir con los requisitos específicos del sistema.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de I/O con fallos puede restaurar el sistema de almacenamiento a su estado operativo óptimo.


