---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module 
summary: Los sistemas de almacenamiento AFF C30 y AFF C60 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado. 
---
= Descripción general del mantenimiento del módulo de E/S - AFF C30 y AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento AFF C30 y AFF C60 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado.

Puede reemplazar un módulo de E/S defectuoso en su sistema de almacenamiento con el mismo tipo de módulo o con uno diferente. Puede intercambiar en caliente un clúster y un módulo de E/S de alta disponibilidad cuando su sistema de almacenamiento cumpla con los requisitos específicos. También puede agregar un módulo de E/S a un sistema de almacenamiento con ranuras disponibles.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Al agregar módulos de I/O adicionales, se puede mejorar la redundancia y ayudar a garantizar que el sistema de almacenamiento siga funcionando incluso si falla un módulo de I/O.

* link:io-module-hotswap-ha-slot4.html["Intercambio en caliente de un clúster y un módulo de E/S de alta disponibilidad"]
+
El intercambio en caliente de un clúster y un módulo de E/S de alta disponibilidad (HA) fallidos puede restaurar el sistema de almacenamiento a su estado operativo óptimo. El intercambio en caliente se realiza sin necesidad de tomar el control manual del controlador dañado.

+
Para utilizar este procedimiento, su sistema de almacenamiento debe ejecutar ONTAP 9.17.1 o posterior y cumplir con los requisitos específicos del sistema.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de I/O con fallos puede restaurar el sistema de almacenamiento a su estado operativo óptimo.


