---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module 
summary: Los sistemas AAF C30 y AFF C60 ofrecen flexibilidad en la expansión o sustitución de módulos de E/S para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido. 
---
= Descripción general del módulo de E/S ADD y SUSTITUTE - AFF C30 y AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas AFF C30 y AFF C60 ofrecen flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Al agregar módulos de I/O adicionales, se puede mejorar la redundancia y ayudar a garantizar que el sistema de almacenamiento siga funcionando incluso si falla un módulo de I/O.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de I/O con fallos puede restaurar el sistema de almacenamiento a su estado operativo óptimo.


