---
permalink: a20-30-50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the chassis 
summary: Antes de sustituir el chasis de tu sistema de almacenamiento AFF A20, AFF A30 o AFF A50, verifica que cumples los requisitos necesarios para que la sustitución sea exitosa. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, que tienes el chasis de reemplazo correcto y que cuentas con las herramientas necesarias. 
---
= Revisa los requisitos antes de sustituir un chasis AFF A20, AFF A30 o AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema de almacenamiento AFF A20, AFF A30 o AFF A50, verifica que cumples los requisitos necesarios para que la sustitución sea exitosa. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, que tienes el chasis de reemplazo correcto y que cuentas con las herramientas necesarias.

Revise los siguientes requisitos y consideraciones.



[[requirements]]
== Requisitos

* El chasis de reemplazo debe ser el mismo modelo que el chasis dañado. Este procedimiento es para un reemplazo similar, no para una actualización.
* El resto de componentes del sistema de almacenamiento deben funcionar correctamente. De lo contrario, póngase en contacto https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"] antes de continuar con este procedimiento.




[[considerations]]
== Consideraciones

* El procedimiento de sustitución del chasis es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.
* Es posible usar el procedimiento de reemplazo de chasis con todas las versiones de ONTAP compatibles con el sistema de almacenamiento.
* El procedimiento de sustitución del chasis se escribe suponiendo que va a mover el panel frontal, las unidades, los espacios vacíos de unidad y las controladoras al nuevo chasis.


.El futuro
Después de revisar los requisitos para reemplazar el chasis, debe link:chassis-replace-shutdown.html["apague las controladoras"].
