---
permalink: a20-30-50/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: Para restaurar el sistema a su funcionamiento completo, debe verificar los LIF, comprobar el estado del clúster y devolver la parte con error a NetApp. 
---
= Sustitución de controladoras completa: AFF A20, AFF A30 y AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para restaurar el sistema de almacenamiento a pleno funcionamiento, debe verificar las LIF, comprobar el estado del clúster y devolver la parte con error a NetApp.



== Paso 1: Verifique las LIF y compruebe el estado del clúster

Antes de devolver el nodo de sustitución al servicio, compruebe que las interfaces lógicas estén en sus puertos principales, compruebe el estado del clúster y restablezca la devolución automática.

.Pasos
. Compruebe que las interfaces lógicas están reportando a sus puertos y servidores domésticos: `network interface show -is-home false`
+
Si alguna de las interfaces lógicas aparece como false, revertiéndela a sus puertos de inicio: `network interface revert -vserver * -lif *`

. Compruebe el estado del clúster. Consulte https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Cómo realizar una comprobación del estado de un clúster con un script en ONTAP"^] el artículo de la base de conocimientos para obtener más información.
. Si la devolución automática está desactivada, vuelva a habilitarla: `storage failover modify -node local -auto-giveback true`




== Paso 2: Devuelve la parte fallida a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
