---
permalink: a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, prerequisite, replace the controller module 
summary: Antes de reemplazar el controlador en su sistema de almacenamiento AFF A20, AFF A30 o AFF A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso.  Esto incluye verificar que todos los demás componentes del sistema estén funcionando correctamente, verificar que tenga el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto. 
---
= Requisitos para sustituir la controladora: AFF A20, AFF A30 y AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reemplazar el controlador en su sistema de almacenamiento AFF A20, AFF A30 o AFF A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso.  Esto incluye verificar que todos los demás componentes del sistema estén funcionando correctamente, verificar que tenga el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto.

Revise los requisitos y las consideraciones del procedimiento de reemplazo de la controladora.

[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====


== Requisitos

* Todas las bandejas deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* Si su sistema está en una configuración MetroCluster, debe revisar la sección https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"] para determinar si debe utilizar este procedimiento.
* Debe sustituir una controladora por una controladora del mismo tipo de modelo. No se puede actualizar el sistema simplemente reemplazando la controladora.
* No es posible cambiar ninguna unidad o bandeja como parte de este procedimiento.




== Consideraciones

Es importante aplicar los comandos de este procedimiento a la controladora correcta:

* El controlador _drinated_ es el controlador que se va a sustituir.
* El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
* El controlador _heated_ es el controlador que sobrevive.


.El futuro
Después de que haya revisado los requisitos para reemplazar el controlador dañado, debe link:controller-replace-shutdown.html["apague el controlador defectuoso"].
