---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: Los sistemas de almacenamiento AFF A20, AFF A30 y AFF A50 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado. 
---
= Descripción general del mantenimiento del módulo de E/S: AFF A20, AFF A30 y AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento AFF A20, AFF A30 y AFF A50 ofrecen flexibilidad para ampliar o reemplazar módulos de E/S y mejorar la conectividad y el rendimiento de la red. Añadir, intercambiar en caliente o reemplazar un módulo de E/S es esencial para actualizar las capacidades de la red o reparar un módulo averiado.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Puedes agregar módulos de E/S para mejorar la redundancia, ayudando a asegurar que el sistema de almacenamiento permanezca operativo incluso si falla un módulo de E/S. Puedes agregar módulos de E/S cuando hay ranuras disponibles o cuando todas las ranuras están completamente ocupadas.

* link:io-module-hotswap.html["Intercambia en caliente un módulo de E/S"]
+
Puedes intercambiar en caliente ciertos módulos de E/S por un módulo de E/S equivalente para restaurar el sistema de almacenamiento a su estado de funcionamiento óptimo. El intercambio en caliente se hace sin tener que realizar una toma de control manual.

+
Para usar este procedimiento, tu sistema de almacenamiento debe estar ejecutando ONTAP 9.17.1 o una versión posterior y cumplir requisitos específicos para la versión de ONTAP que esté ejecutando tu sistema.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
Puedes sustituir un módulo de E/S averiado para restaurar el sistema de almacenamiento a su estado de funcionamiento óptimo. Este procedimiento requiere una toma de control manual del controlador con el módulo de E/S averiado.


