---
permalink: a20-30-50/overview.html 
sidebar: sidebar 
keywords: AFF A20 A30 A50 specifications, AFF A20 A30 A50 specs, AFF A20 A30 A50 capacity, AFF A20 A30 A50 memory, AFF A20 A30 A50 I/O, AFF A20 A30 A50 compliance 
summary: Especificaciones clave para el grupo de plataformas A20-30-50 
---
= Especificaciones clave para el grupo de plataformas A20-30-50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el grupo de plataformas A20-30-50.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de especificaciones.  Esta página es un reflejo de un único par de alta disponibilidad.



== AFF A50



=== Especificaciones clave del AFF A50

Configuración de la plataforma: AFF A50, par HA de chasis único

Capacidad bruta máxima: 4.0392 PB

Memoria: 256.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 8

Versión mínima de ONTAP : ONTAP 9.16.1RC1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 12 | 48,5 PB / 43,0 PiB | 3072 GB 


| SAN | 6 | 24,2 PB / 21,5 PiB | 1536 GB 


| Par HA |  | 4,0 PB / 3,6 PiB | 256,0000 
|===


=== IO



==== E/S integrada

No hay datos de E/S integrados.



==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 16 


| Ethernet de 25 Gbps | 24 


| Ethernet de 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS de 12 Gbps | 16 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 3076 BTU/h
* Potencia en el peor de los casos: 4860 BTU/h
* Peso: 60,7 lb/27,5 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad:
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °Cbr/50 °F a br/95 °F) abr/= 3048mbr/= 10000 pies) de elevación; 8 % a 80 %br/humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0; br/Presión sonora (LpAm) (posiciones de transeúntes): 70,5 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes; Administración en banda SAS a través de conexiones SAS para estantes externos;



== AFF A20



=== Especificaciones clave del AFF A20

Configuración de la plataforma: AFF A20, par HA de chasis único

Capacidad bruta máxima: 4.0392 PB

Memoria: 128.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 8

Versión mínima de ONTAP : ONTAP 9.16.1RC1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 3 | 12,1 PB / 10,8 PiB | 384 GB 


| SAN | 3 | 12,1 PB / 10,8 PiB | 384 GB 


| Par HA |  | 4,0 PB / 3,6 PiB | 128,0000 
|===


=== IO



==== E/S integrada

No hay datos de E/S integrados.



==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 12 


| Ethernet de 25 Gbps | 32 


| Ethernet de 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS de 12 Gbps | 16 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 2489 BTU/h
* Potencia en el peor de los casos: 3890 BTU/h
* Peso: 60,7 lb/27,5 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad:
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °Cbr/50 °F a br/95 °F) abr/= 3048mbr/= 10000 pies) de elevación; 8 % a 80 %br/humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0; br/Presión sonora (LpAm) (posiciones de transeúntes): 70,5 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes; Administración en banda SAS a través de conexiones SAS para estantes externos;

 [//] 2025-10-15 ontap-systems-internal/issues/1357


== AFF A30



=== Especificaciones clave del AFF A30

Configuración de la plataforma: AFF A30, par HA de chasis único

Capacidad bruta máxima: 4.0392 PB

Memoria: 128.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 8

Versión mínima de ONTAP : ONTAP 9.16.1RC1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 4 | 16,2 PB / 14,3 PiB | 512 GB 


| SAN | 4 | 16,2 PB / 14,3 PiB | 512 GB 


| Par HA |  | 4,0 PB / 3,6 PiB | 128,0000 
|===


=== IO



==== E/S integrada

No hay datos de E/S integrados.



==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 16 


| Ethernet de 25 Gbps | 24 


| Ethernet de 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS de 12 Gbps | 16 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 2892 BTU/h
* Potencia en el peor de los casos: 4445 BTU/h
* Peso: 60,7 lb/27,5 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad:
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °Cbr/50 °F a br/95 °F) abr/= 3048mbr/= 10000 pies) de elevación; 8 % a 80 %br/humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0; br/Presión sonora (LpAm) (posiciones de transeúntes): 70,5 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes; Administración en banda SAS a través de conexiones SAS para estantes externos;
