---
permalink: c250/controller-replace-shutdown.html 
sidebar: sidebar 
keywords: aff c250, shut down the impaired controller 
summary: Para apagar el módulo del controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador en buen estado siga sirviendo datos del almacenamiento del controlador dañado. 
---
= Apague el módulo del controlador dañado AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apaga el controlador de tu sistema de almacenamiento AFF C250 para evitar la pérdida de datos y asegurar la estabilidad del sistema cuando reemplaces el controlador.

Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, tomar el control para que el controlador sano siga sirviendo datos del almacenamiento del controlador dañado.

.Acerca de esta tarea
* Si dispone de un sistema SAN, debe haber comprobado los mensajes de evento  `cluster kernel-service show`) para el blade SCSI de la controladora dañada.  `cluster kernel-service show`El comando (desde el modo avanzado priv) muestra el nombre del nodo, link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["estado del quórum"] de ese nodo, el estado de disponibilidad de ese nodo y el estado operativo de ese nodo.
+
Cada proceso SCSI-blade debe quórum con los otros nodos del clúster. Todos los problemas deben resolverse antes de continuar con el reemplazo.

* Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].


.Pasos
. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Desactivar devolución automática:
+
.. Ingrese el siguiente comando desde la consola del controlador en buen estado:
+
`storage failover modify -node _impaired_node_name_ -auto-giveback false`

.. Ingresar `y` cuando vea el mensaje "¿Desea desactivar la devolución automática?"


. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
Esperando devolución...
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña
 a| 
Retome o detenga el controlador dañado del controlador en buen estado:

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

El parámetro _-halt true_ lleva al símbolo del sistema de Loader.

|===


.El futuro
Después de apagar el controlador, necesitas link:controller-replace-move-hardware.html["Sustituya el controlador"]
