---
permalink: c250/install-setup.html 
sidebar: sidebar 
keywords: aff c250, install, setup, initial configuration 
summary: Elige entre pasos rápidos, pasos detallados o vídeos explicativos para instalar y configurar un sistema de almacenamiento AFF C250. 
---
= Flujo de trabajo de instalación y configuración de AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Elige entre instrucciones rápidas, instrucciones detalladas o vídeos tutoriales para instalar y configurar un sistema de almacenamiento AFF C250, en función de tu formato preferido y tu nivel de experiencia.

* link:../c250/install-quick-guide.html["Pasos rápidos"]
+
Un PDF imprimible de instrucciones paso a paso con enlaces directos a contenido adicional.

* link:../c250/install-videos.html["Pasos de vídeo"]
+
Instrucciones paso a paso de vídeo.

* link:../c250/install-detailed-guide.html["Pasos detallados"]
+
Instrucciones paso a paso en línea con enlaces directos a contenido adicional.



Si el sistema está en una configuración IP de MetroCluster, consulte https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Instale la configuración IP de MetroCluster"^] instrucciones.
