---
permalink: c250/maintain-overview.html 
sidebar: sidebar 
keywords: aff c250 maintenance, maintenance, repairing c250, repairing aff c250, replace aff c250 components, replace aff c250 components 
summary: Mantén el hardware del AFF C250 
---
= Mantener el hardware de AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantén el hardware de tu sistema de almacenamiento AFF C250 para asegurar la fiabilidad a largo plazo y un rendimiento óptimo. Realiza tareas de mantenimiento periódicas, como reemplazar componentes defectuosos, ya que esto ayuda a prevenir el tiempo de inactividad y la pérdida de datos.

Los procedimientos de mantenimiento asumen que el sistema de almacenamiento AFF C250 ya ha sido desplegado como nodo de almacenamiento en el entorno ONTAP.



== Componentes del sistema

Para el sistema de almacenamiento AFF C250, puede realizar procedimientos de mantenimiento en los componentes siguientes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Medios de arranque: recuperación automatizada"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de ONTAP que el sistema de almacenamiento usa para arrancar. Durante la recuperación automatizada, el sistema recupera la imagen de arranque del nodo asociado y ejecuta automáticamente la opción adecuada del menú de arranque para instalar la imagen en tu medio de arranque de reemplazo. El proceso de recuperación automatizada del medio de arranque solo se admite en ONTAP 9.18.1 y versiones posteriores. Si tu sistema de almacenamiento está ejecutando una versión anterior de ONTAP, usa link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"].



 a| 
link:bootmedia-replace-workflow.html["Medios de arranque: recuperación manual"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de ONTAP que el sistema de almacenamiento usa para arrancar. Durante la recuperación manual, arrancas el sistema de almacenamiento desde una unidad USB y restauras manualmente la imagen del sistema de archivos y la configuración. Si tu sistema de almacenamiento está ejecutando ONTAP 9.18.1 y versiones posteriores, usa el link:bootmedia-replace-workflow-bmr.html["procedimiento de recuperación de arranque automatizado"].



 a| 
link:chassis-replace-workflow.html["Chasis"]
 a| 
El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



 a| 
link:controller-replace-workflow.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



 a| 
link:drive-replace.html["Unidad"]
 a| 
Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



 a| 
link:fan-replace.html["Ventilador"]
 a| 
El ventilador enfría el controlador.



 a| 
link:mezzanine-replace.html["Tarjeta mezzanine"]
 a| 
La tarjeta Mezzanine es una placa de circuito impreso que se conecta directamente a otra tarjeta enchufable.



 a| 
link:nvmem-nvram-battery-replace.html["Batería NVMEM"]
 a| 
La batería NVMEM es responsable de preservar los datos almacenados en caché si falla la alimentación de CA.



 a| 
link:power-supply-replace.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



 a| 
link:rtc-battery-replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.

|===