---
permalink: asa-r2-a1k/bootmedia-recovery-image-boot-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, boot the recovery image 
summary: Debe arrancar la imagen de ONTAP desde la unidad USB, restaurar el sistema de archivos y verificar las variables del entorno. 
---
= Recuperación automática de arranque - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restaurar la imagen en el soporte de arranque desde el controlador asociado mediante el proceso de recuperación automática al arranque.

Seleccione la opción de recuperación automatizada de nodo único que se ajuste a la configuración.

[role="tabbed-block"]
====
.Opción 1: Recuperación sin cifrado
--
Puede restaurar la imagen de ONTAP (recuperación del medio de arranque) desde el nodo del partner mediante `boot_recovery -partner` el comando en las plataformas ASA R2 que ejecuten ONTAP 9.16,0 y versiones posteriores.

.Antes de empezar
Cuando arranca un nodo y el soporte de arranque de dicho nodo está dañado, verá los siguientes mensajes y el proceso de arranque con stop en el símbolo del sistema de Loader:

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
Si ve este mensaje, debe restaurar la imagen de ONTAP

.Pasos
. En el símbolo del sistema DE Loader, introduzca el comando _boot_recovery -partner_.
+
La pantalla mostrará el mensaje `Starting boot media recovery (BMR) process press Ctrl-C to abort...` y comenzará las comprobaciones iniciales.

. Supervise el proceso como Loader configura los puertos del clúster local y ejecuta netboot a través `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`de .
+
Una vez que netboot se está ejecutando, `Starting BMR ...` se muestra en la pantalla y el proceso completa el proceso de instalación.

+
.. Si Key Manager no está configurado, verá el siguiente mensaje:
+
....
key manager is not configured. Exiting.
....
.. Si aparece el siguiente mensaje, Onboard Key Manager (OKM) está configurado:
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
Vaya a para completar el proceso de recuperación.

.. Si ve el siguiente mensaje, External Key Manager (EKM) está configurado. Vaya al tema de EKM y complete el proceso de recuperación:
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. Supervisar el proceso BMR a medida que ejecuta la restauración de la configuración de copia de seguridad, el archivo env, mdb y rdb desde el partner.
. El nodo se reinicia y la BMR se completa cuando observe lo siguiente:


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....
--
.Opción 2: Recuperación con el gestor de claves incorporado presente
--
Es posible restaurar la imagen ONTAP (recuperación del medio de arranque) desde el nodo asociado mediante `boot_recovery -partner` las plataformas ASA R2 que ejecutan ONTAP 9.16,0 y versiones posteriores.

.Antes de empezar
Cuando arranca un nodo y el soporte de arranque de dicho nodo está dañado, verá los siguientes mensajes y el proceso de arranque con stop en el símbolo del sistema de Loader:

....

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

....
Si ve este mensaje, debe restaurar la imagen de ONTAP

.Pasos
. En el símbolo del sistema DE Loader, introduzca el comando _boot_recovery -partner_.
+
La pantalla mostrará el mensaje `Starting boot media recovery (BMR) process press Ctrl-C to abort...` e iniciará las comprobaciones iniciales y la instalación de los archivos de recuperación de arranque.

+
.. Si Onboard Key Manager (OKM) está configurado, verá lo siguiente:
+
....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....


. Introduzca _y_ en la petición de datos.
. Introduzca la clave de acceso del gestor de claves incorporado cuando lo vea `Enter the passphrase for onboard key management:`
. Introduzca de nuevo la frase de contraseña del gestor de claves incorporado cuando se le solicite que confirme la clave de acceso.
+
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
+
Verá lo siguiente cuando se complete el proceso de recuperación:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.
....
. Supervisar el proceso BMR a medida que ejecuta la restauración de la configuración de copia de seguridad, el archivo env, mdb y rdb desde el partner.
+
Cuando se completa la restauración, el nodo se reinicia para completar el proceso.



--
.Opción 3: Recuperación con External Key Manager presente
--
Es posible restaurar la imagen ONTAP (recuperación del medio de arranque) desde el nodo asociado mediante `boot_recovery -partner` las plataformas ASA R2 que ejecutan ONTAP 9.16,0 y versiones posteriores.

Cuando arranca un nodo y el soporte de arranque de dicho nodo está dañado, verá los siguientes mensajes y el proceso de arranque con stop en el símbolo del sistema de Loader:

....

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....
Si ve este mensaje, debe restaurar la imagen de ONTAP.

.Pasos
. En el símbolo del sistema DE Loader, introduzca el comando _boot_recovery -partner_.
+
La pantalla mostrará el mensaje `Starting boot media recovery (BMR) process press Ctrl-C to abort...` e iniciará las comprobaciones iniciales y la instalación de los archivos de recuperación de arranque.

+
.. Si External Key Manager (EKM) está configurado, aparecerá lo siguiente:
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}
....
.. Introduzca _y_ si se ha configurado un gestor de claves.
+
....
key manager is configured.
Entering Bootmenu Option 11...
....


+
La opción bootmenu 11 solicitará al usuario toda la información de configuración de EKM para que los archivos de configuración puedan ser reconstruidos.

. Introduzca la configuración de EKM en cada petición de datos.
+
*NOTA:* La mayor parte de esta información fue ingresada cuando EKM fue originalmente habilitado. Debe introducir la misma información que se introdujo durante la configuración inicial de EKM.

. Compruebe que `Keystore UUID` los y `Cluster UUID` son correctos.
+
.. En el nodo del partner, recupere el UUID de clúster con  `cluster identity show`el comando.
.. En el nodo asociado, recupere el UUID de almacén de claves con el `vserver show -type admin` comando y `key-manager keystore show -vserver <nodename>` el comando.
.. Introduzca los valores para UUID del almacén de claves y UUID de clúster cuando se le solicite.
+
*NOTA:* Si el nodo asociado no está disponible, el UUID de almacén de claves y el UUID de clúster se pueden obtener de la clave Mroot-AK ubicada en el servidor de claves configurado.

+
Verifique `x-NETAPP-ClusterName: <cluster name>` para el UUID de clúster y `x-NETAPP-KeyUsage: "MROOT-AK"` los atributos de UUID de almacén de claves a fin de asegurarse de tener las claves correctas.



. Supervise la recuperación y restauración de Mroot-AK en el nodo ONTAP.
. Si el proceso no puede restaurar la clave, verá el siguiente mensaje y deberá configurar e0M desde el shell del sistema de menús:
+
....
ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>

....
+
.. Ejecute `boot_recovery -partner` el comando en el nodo de recuperación.
.. Cuando se le solicite que realice (y o n) las opciones para EKM, seleccione _n_ para todos.
+
Después de seleccionar la opción _n_ para las indicaciones de 8, el sistema se detendrá en el menú de inicio.

.. Recopile la información del archivo /cfcard/kmip/servers.cfg de otro nodo del clúster. Usted recopilará la siguiente información:
+
*** La dirección del servidor KMIP.
*** El puerto KMIP.
*** UUID del almacén de claves.
*** Una copia del certificado de cliente del archivo /cfcard/kmip/certs/client.crt.
*** Una copia de la clave de cliente del archivo /cfcard/kmip/certs/client.key.
*** Una copia de las CA del servidor KMIP del archivo /cfcard/kmip/certs/CA.pem.


.. Introduzca systemshell desde el menú de inicio introduciendo _systemshell_ en el prompt.
.. Configure la red desde el menú systemshell para e0M, máscara de red y puerta de enlace.
.. Salga del menú systemshell con el comando _exit_.
.. Verá el menú de arranque. Seleccione la opción `11` para continuar con la restauración de EKM.
.. Responda `y` a las siguientes preguntas e introduzca la información obligatoria que haya recopilado anteriormente cuando se le solicite:
+
*** ¿Tiene una copia del archivo /cfcard/kmip/certs/client.crt? {s/n}
*** ¿Tiene una copia del archivo /cfcard/kmip/certs/client.key? {s/n}
*** ¿Tiene una copia del archivo /cfcard/kmip/certs/ca.pem? {s/n}
*** ¿Tiene una copia del archivo /cfcard/kmip/servers.cfg? {s/n}




. Si la clave se restaura correctamente, el proceso de recuperación continúa y reinicia el nodo.


--
====