---
permalink: asa-r2-a1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: asa r2 a1k, how to recable the system, how to reassign disks 
summary: Reinicie el sistema. 
---
= Devuelva el controlador - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Transfiera la propiedad de los recursos de almacenamiento de nuevo a la controladora de reemplazo.

.Pasos
. Si el sistema de almacenamiento tiene cifrado configurado, debe restaurar la funcionalidad de almacenamiento o cifrado de volúmenes mediante el siguiente procedimiento para reiniciar el sistema:
+
.. Inicie en el menú y ejecute la opción 10
.. Introduzca la frase de contraseña y realice una copia de seguridad de los datos y, a continuación, realice un arranque normal. Consulte https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["Restaure las claves de cifrado de gestión de claves incorporadas"].
.. Realice el retorno al nodo primario solo de CFO
.. Realice Onboard Sync y verifique que SVM-KEK está establecido en true. Consulte https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["Giveback después de que el reemplazo MB falla - la operación fue vetada por keymanager"]
.. Giveback SFO, (sin fuerza)


. Si el sistema no tiene el cifrado configurado, realice el siguiente procedimiento para reiniciar el sistema:
+
.. Inicie en el menú y ejecute la opción 1.
.. Devolver la controladora:
.. Desde la controladora en buen estado, proporcione almacenamiento a la controladora que sustituyó: `storage failover giveback -ofnode _replacement_node_name_`
+
La controladora _reader_ recupera su almacenamiento y completa el arranque.

+

NOTE: Si el retorno se vetó, puede considerar la sustitución de los vetos.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Busque el contenido de Configuración de alta disponibilidad para su versión de ONTAP 9"]

.. Una vez finalizada la devolución, confirme que el par de alta disponibilidad está en buen estado y que la toma de control es posible: `storage failover show`


. Compruebe que los volúmenes esperados estén presentes para cada controladora: `vol show -node node-name`
. Si deshabilitó la toma de control automática al reiniciar, habilite esa función desde la controladora en buen estado: `storage failover modify -node replacement-node-name -onreboot true`
. Si AutoSupport está habilitado, restaurar/desactivar la creación automática de casos mediante el `system node autosupport invoke -node * -type all -message MAINT=END` comando.

