---
permalink: asa-r2-a1k/io-module-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace io module 
summary: El sistema A1K de ASA ofrece flexibilidad en la expansión o sustitución de los módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido 
---
= Descripción general del módulo de E/S ADD y SUSTITUTE - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema A1K de ASA ofrece flexibilidad en la expansión o sustitución de los módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

Puede sustituir un módulo de I/O con fallo en el sistema de almacenamiento ASA A1K por el mismo tipo de módulo de I/O o por otro tipo de módulo de I/O diferente. También puede agregar un módulo de E/S a un sistema con ranuras vacías.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
La adición de módulos adicionales puede mejorar la redundancia, lo que ayuda a garantizar que el sistema siga funcionando incluso si falla un módulo.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de E/S que falla puede restaurar el sistema a su estado operativo óptimo.


