---
permalink: asa-r2-a1k/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a1k maintenance, maintenance, repairing a1k, repairing asa a1k, replace asa a1k components, replace asa a1k components 
summary: Mantenga el hardware de ASA R2 A1K 
---
= Mantener el hardware de ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba realizar procedimientos de mantenimiento en el hardware. En esta sección se incluyen los procedimientos específicos para el mantenimiento de los componentes del sistema ASA A1K.

En los procedimientos de esta sección se asume que el sistema A1K ya se ha puesto en marcha como nodo de almacenamiento en el entorno ONTAP.



== Componentes del sistema

Para el sistema de almacenamiento ASA A1K, puede realizar procedimientos de mantenimiento en los componentes siguientes.

[cols="30,70"]
|===


 a| 
link:bootmedia-overview.html["Soporte de arranque: Recuperación manual"]

link:bootmedia-overview-bmr.html["Soporte de arranque: Recuperación automatizada"]
 a| 
Puede sustituir manualmente un soporte de arranque fallido mediante el módulo USB para la imagen de arranque.

La sustitución de soportes de arranque automatizada usa la imagen de arranque del nodo del partner y ejecuta automáticamente la opción de menú de arranque correspondiente para instalar la imagen de arranque en el soporte de arranque de reemplazo.



 a| 
link:controller-replace-workflow.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla el almacenamiento, las tarjetas de E/S y ejecuta el software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un módulo de memoria dual en línea (DIMM) es un tipo de memoria del ordenador. Se instalan para agregar memoria del sistema a una placa base de la controladora.



 a| 
link:fan-replace.html["Ventilador"]
 a| 
Un ventilador enfría el controlador.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
La NVRAM (memoria de acceso aleatorio no volátil) es un módulo que permite a la controladora proteger y guardar datos en movimiento si el sistema sufre un corte de alimentación. El ID del sistema reside en el módulo de NVRAM. Cuando se sustituye, la controladora asume el nuevo ID del sistema desde el módulo NVRAM de reemplazo.



 a| 
link:nvdimm-battery-replace.html["Batería de NV"]
 a| 
La batería NV es responsable de suministrar alimentación al módulo de NVRAM mientras los datos en tránsito se separan a la memoria flash después de un corte de alimentación.



 a| 
link:io-module-overview.html["Módulo de I/O."]
 a| 
El módulo de E/S (módulo de entrada/salida) es un componente de hardware que actúa como intermediario entre el controlador y varios dispositivos o sistemas que necesitan intercambiar datos con el controlador.



 a| 
link:power-supply-replace.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



 a| 
link:rtc-battery-replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.



 a| 
link:system-management-replace.html["Módulo de gestión del sistema"]
 a| 
El módulo de gestión del sistema proporciona la interfaz entre el controlador y una consola o portátil para el mantenimiento del controlador o del sistema. El módulo de gestión del sistema contiene el soporte de arranque y almacena el número de serie del sistema (SSN).

|===