= Paso 1: Recuperar el sistema
:allow-uri-read: 


Para completar el procedimiento de sustitución y restaurar el sistema a pleno funcionamiento, debe volver a montar el almacenamiento, confirmar la reasignación del disco, restaurar la configuración de cifrado del almacenamiento de NetApp (si fuera necesario) e instalar licencias para la nueva controladora. Debe completar una serie de tareas antes de restaurar el sistema a pleno funcionamiento.



== Paso 1: Recuperar el sistema

Compruebe las conexiones de red y almacenamiento del módulo del controlador.

.Pasos
. Compruebe que el cableado sea correcto mediante el https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Descargue e instale Config Advisor.
.. Introduzca la información del sistema de destino y haga clic en Collect Data.
.. Haga clic en la ficha cableado y, a continuación, examine la salida. Asegúrese de que se muestren todas las bandejas de discos y todos los discos aparecen en el resultado, corrigiendo los problemas de cableado que encuentre.
.. Compruebe otro cableado haciendo clic en la ficha correspondiente y, a continuación, examinando el resultado de Config Advisor.






== Paso 2: Reasignar discos

Si el sistema de almacenamiento está en un par de alta disponibilidad, el ID del sistema del nuevo módulo de controladora se asigna automáticamente a los discos cuando se produce la devolución al final del procedimiento. En un sistema independiente, debe reasignar manualmente el ID a los discos.

Debe utilizar el procedimiento correcto para su configuración:

[cols="1,2"]
|===
| Redundancia de la controladora | A continuación, use este procedimiento... 


 a| 
Pareja de HA
 a| 
<<Opción 1: Comprobar el cambio de ID del sistema en un sistema de alta disponibilidad>>



 a| 
Independiente
 a| 
<<Opción 2: Reasignar manualmente el ID del sistema en un sistema independiente en ONTAP>>

|===


=== Opción 1: Comprobar el cambio de ID del sistema en un sistema de alta disponibilidad

Debe confirmar el cambio de ID del sistema al arrancar el controlador _reboot_ y, a continuación, comprobar que se ha implementado el cambio.

Este procedimiento solo se aplica a sistemas que ejecutan ONTAP en una pareja de ha.

. Si el controlador _reader_ está en modo de mantenimiento (mostrando la `*>` Salga del modo de mantenimiento y vaya al símbolo del sistema del CARGADOR: `halt`
. Desde el símbolo DEL SISTEMA DEL CARGADOR en el controlador _reboot_, arranque el controlador, introduciendo `y` Si se le solicita que anule el ID del sistema debido a una discrepancia de ID del sistema:``boot_ontap``
. Espere hasta la `Waiting for giveback...` El mensaje se muestra en la consola del controlador _regrse_ y, a continuación, en el controlador en buen estado, compruebe que el nuevo ID del sistema asociado se ha asignado automáticamente: `storage failover show`
+
En el resultado del comando, debería ver un mensaje donde se indica que el ID del sistema ha cambiado en la controladora dañada, con lo que se muestran los ID anteriores y los nuevos correctos. En el ejemplo siguiente, el nodo 2 debe ser sustituido y tiene un ID de sistema nuevo de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Desde la controladora en buen estado, compruebe que se han guardado los núcleo:
+
.. Cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Usted puede responder `Y` cuando se le solicite que continúe en el modo avanzado. Aparece el símbolo del sistema del modo avanzado (*>).

.. Guarde sus núcleo: `system node run -node _local-node-name_ partner savecore`
.. Espere a que el comando "avecore" se complete antes de emitir la devolución.
+
Puede introducir el siguiente comando para supervisar el progreso del comando savecoore: `system node run -node _local-node-name_ partner savecore -s`

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Si el sistema de almacenamiento tiene configurado el cifrado de volúmenes o el almacenamiento, debe restaurar la funcionalidad de cifrado de volúmenes o almacenamiento usando uno de los siguientes procedimientos, en función de si usa la gestión de claves externa o incorporada:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaure las claves de cifrado de gestión de claves incorporadas"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaure las claves de cifrado de gestión de claves externas"^]


. Devolver la controladora:
+
.. Desde la controladora en buen estado, proporcione almacenamiento a la controladora que sustituyó: `storage failover giveback -ofnode _replacement_node_name_`
+
La controladora _reader_ recupera su almacenamiento y completa el arranque.

+
Si se le solicita que anule el ID del sistema debido a una falta de coincidencia de ID del sistema, debe introducir `y`.

+

NOTE: Si el retorno se vetó, puede considerar la sustitución de los vetos.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Busque el contenido de Configuración de alta disponibilidad para su versión de ONTAP 9"]

.. Una vez finalizada la devolución, confirme que el par de alta disponibilidad está en buen estado y que la toma de control es posible: `storage failover show`
+
La salida de `storage failover show` El comando no debe incluir el ID del sistema cambiado en el mensaje del partner.



. Compruebe que los discos se han asignado correctamente: `storage disk show -ownership`
+
Los discos que pertenecen al controlador _regrel_ deben mostrar el nuevo ID del sistema. En el ejemplo siguiente, los discos propiedad del nodo 1 ahora muestran el nuevo ID del sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----




=== Opción 2: Reasignar manualmente el ID del sistema en un sistema independiente en ONTAP

En un sistema independiente, debe reasignar manualmente los discos al ID del sistema de la nueva controladora antes de devolver el sistema a su estado de funcionamiento normal.

.Acerca de esta tarea

NOTE: Este procedimiento se aplica sólo a sistemas que se encuentran en una configuración independiente.

.Pasos
. Si todavía no lo ha hecho, reinicie el nodo _reboot_, interrumpa el proceso de arranque pulsando Ctrl-C y, a continuación, seleccione la opción de arrancar en el modo de mantenimiento en el menú que se muestra.
. Debe entrar `Y` Cuando se le solicite que anule el ID del sistema debido a una discrepancia de ID del sistema.
. Ver los ID del sistema: `disk show -a`
. Debe tomar nota del ID del sistema antiguo, que se muestra como parte de la columna propietario del disco.
+
En el ejemplo siguiente se muestra el ID anterior del sistema de 118073209:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118073209)  Pool0  J8XJE9LC       system-1  (118073209)
disk_name    system-1  (118073209)  Pool0  J8Y478RC       system-1  (118073209)
.
.
.

----
. Reasignar propiedad de disco mediante la información de ID del sistema obtenida del comando Disk show: `disk reassign -s old system ID disk reassign -s 118073209`
. Compruebe que los discos se han asignado correctamente: `disk show -a`
+
Los discos que pertenecen al nodo de reemplazo deben mostrar el nuevo ID del sistema. En el siguiente ejemplo, se muestran ahora los discos propiedad del sistema-1 el nuevo ID del sistema, 118065481:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
.
.
.

----
. Si el sistema de almacenamiento tiene configurado el cifrado de volúmenes o el almacenamiento, debe restaurar la funcionalidad de cifrado de volúmenes o almacenamiento usando uno de los siguientes procedimientos, en función de si usa la gestión de claves externa o incorporada:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaure las claves de cifrado de gestión de claves incorporadas"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaure las claves de cifrado de gestión de claves externas"^]


. Arrancar el nodo: `boot_ontap`

