= Paso 1: Recuperar el sistema
:allow-uri-read: 


Continúe con el procedimiento de sustitución presentando el almacenamiento y confirmando la reasignación del disco.



== Paso 1: Recuperar el sistema

Verifique las conexiones de red y almacenamiento del módulo controlador mediante https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .

.Pasos
. Descargue e instale Config Advisor.
. Introduzca la información del sistema de destino y haga clic en Collect Data.
. Haga clic en la ficha cableado y, a continuación, examine la salida. Asegúrese de que se muestren todas las bandejas de discos y todos los discos aparecen en el resultado, corrigiendo los problemas de cableado que encuentre.
. Compruebe otro cableado haciendo clic en la ficha correspondiente y, a continuación, examinando el resultado de Config Advisor.




== Paso 2: Reasignar discos

El procedimiento que utilice dependerá de la configuración de redundancia de su controlador.

[role="tabbed-block"]
====
.Opción 1: par HA
--
=== Verificar el cambio de ID del sistema en un sistema HA

Si el sistema de almacenamiento está en un par de alta disponibilidad, el ID del sistema del nuevo módulo de controladora se asigna automáticamente a los discos cuando se produce la devolución al final del procedimiento. Debe confirmar el cambio de ID del sistema al arrancar el nodo _reboot_ y, a continuación, comprobar que se ha implementado el cambio.

Este procedimiento solo se aplica a sistemas que ejecutan ONTAP en una pareja de ha.

. Si el nodo _reader_ está en modo de mantenimiento (mostrando la `*>` Salga del modo de mantenimiento y vaya al símbolo del sistema del CARGADOR: `halt`
. Desde el símbolo del sistema DEL CARGADOR en el nodo _reboot_, arranque el nodo, introduzca `y` Si se le solicita que anule el ID del sistema debido a que el ID del sistema no coincide.``boot_ontap``
. Espere hasta la `Waiting for giveback...` El mensaje se muestra en la consola del nodo _regrel_ y, a continuación, en el nodo en buen estado, compruebe que el nuevo ID de sistema asociado se ha asignado automáticamente: `storage failover show`
+
En el resultado del comando, debería ver un mensaje que indica que el ID del sistema ha cambiado en el nodo dañado, mostrando los ID anteriores y los nuevos correctos. En el ejemplo siguiente, el nodo 2 debe ser sustituido y tiene un ID de sistema nuevo de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. Desde el nodo en buen estado, compruebe que se han guardado los núcleo:
+
.. Cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Usted puede responder `Y` cuando se le solicite que continúe en el modo avanzado. Aparece el símbolo del sistema del modo avanzado (*>).

.. Guarde sus núcleo: `system node run -node _local-node-name_ partner savecore`
.. Espere a que el comando "avecore" se complete antes de emitir la devolución.
+
Puede introducir el siguiente comando para supervisar el progreso del comando savecoore: `system node run -node _local-node-name_ partner savecore -s`

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Si el sistema de almacenamiento tiene configurado el cifrado de volúmenes o el almacenamiento, debe restaurar la funcionalidad de cifrado de volúmenes o almacenamiento usando uno de los siguientes procedimientos, en función de si usa la gestión de claves externa o incorporada:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaure las claves de cifrado de gestión de claves incorporadas"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaure las claves de cifrado de gestión de claves externas"^]


. Proporcione al nodo:
+
.. Desde el nodo en buen estado, vuelva a asignar el almacenamiento del nodo sustituido: `storage failover giveback -ofnode _replacement_node_name_`
+
El nodo _regrsustituya_ recupera su almacenamiento y completa el arranque.

+
Si se le solicita que anule el ID del sistema debido a una falta de coincidencia de ID del sistema, debe introducir `y`.

+

NOTE: Si el retorno se vetó, puede considerar la sustitución de los vetos.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Busque la Guía de configuración de alta disponibilidad para su versión de ONTAP 9"]

.. Una vez finalizada la devolución, confirme que el par de alta disponibilidad está en buen estado y que la toma de control es posible: `storage failover show`
+
La salida de `storage failover show` El comando no debe incluir el ID del sistema cambiado en el mensaje del partner.



. Compruebe que los discos se han asignado correctamente: `storage disk show -ownership`
+
Los discos que pertenecen al nodo _regrel_ deberían mostrar el nuevo ID del sistema. En el ejemplo siguiente, los discos propiedad del nodo 1 ahora muestran el nuevo ID del sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Si el sistema está en una configuración de MetroCluster, supervise el estado del nodo: `metrocluster node show`
+
La configuración de MetroCluster tarda unos minutos después del reemplazo y vuelve a su estado normal, momento en el que cada nodo mostrará un estado configurado, con mirroring DR habilitado y un modo normal. La `metrocluster node show -fields node-systemid` El resultado del comando muestra el ID del sistema antiguo hasta que la configuración de MetroCluster vuelve a ser un estado normal.

. Si el nodo está en una configuración MetroCluster, según el estado del MetroCluster, compruebe que el campo ID de inicio de recuperación ante desastres muestra el propietario original del disco si el propietario original es un nodo del sitio de desastres.
+
Esto es necesario si se cumplen las dos opciones siguientes:

+
** La configuración de MetroCluster está en estado de conmutación.
** El nodo _regrse_ es el propietario actual de los discos del sitio de recuperación ante desastres.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Cambios en la propiedad de disco durante la toma de control de alta disponibilidad y el cambio de MetroCluster en una configuración MetroCluster de cuatro nodos"]



. Si su sistema está en una configuración MetroCluster, compruebe que cada nodo esté configurado: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Compruebe que existen volúmenes esperados para cada nodo: `vol show -node node-name`
. Si deshabilitó la toma de control automática al reiniciar, habilite esa función desde el nodo en buen estado: `storage failover modify -node replacement-node-name -onreboot true`


--
.Opción 2: MetroCluster de dos nodos
--
=== Reasignar manualmente el ID del sistema en sistemas en una configuración de MetroCluster de dos nodos

En una configuración de MetroCluster de dos nodos que ejecuta ONTAP, debe reasignar los discos manualmente al ID del sistema de la nueva controladora antes de devolver el sistema a la condición de funcionamiento normal.

.Acerca de esta tarea
Este procedimiento solo se aplica a sistemas de una configuración MetroCluster de dos nodos que ejecutan ONTAP.

Debe asegurarse de emitir los comandos en este procedimiento en el nodo correcto:

* El nodo _drinated_ es el nodo en el que realiza tareas de mantenimiento.
* El nodo _regrUSTITUCION_ es el nuevo nodo que reemplazó al nodo dañado como parte de este procedimiento.
* El nodo _heated_ es el compañero de recuperación ante desastres del nodo dañado.


.Pasos
. Si todavía no lo ha hecho, reinicie el nodo _regrel_, interrumpa el proceso de arranque introduciendo `Ctrl-C`Y, a continuación, seleccione la opción para iniciar el modo de mantenimiento en el menú que se muestra.
+
Debe entrar `Y` Cuando se le solicite que anule el ID del sistema debido a una discrepancia de ID del sistema.

. Vea los ID del sistema antiguos del nodo en buen estado: ``metrocluster node show -fields node-systemid`,dr-partner-systemid'
+
En este ejemplo, Node_B_1 es el nodo antiguo, con el ID de sistema antiguo de 118073209:

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. Vea el nuevo ID del sistema en el símbolo del sistema del modo de mantenimiento en el nodo dañado: `disk show`
+
En este ejemplo, el nuevo ID del sistema es 118065481:

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. Reasigne la propiedad de disco (para sistemas FAS) mediante la información de ID de sistema obtenida del comando disk show: `disk reassign -s old system ID`
+
En el caso del ejemplo anterior, el comando es: `disk reassign -s 118073209`

+
Usted puede responder `Y` cuando se le solicite continuar.

. Compruebe que los discos se han asignado correctamente: `disk show -a`
+
Compruebe que los discos que pertenecen al nodo _regrisage_ muestran el nuevo ID del sistema para el nodo _regrisage_. En el siguiente ejemplo, los discos propiedad del sistema-1 ahora muestran el nuevo ID del sistema, 118065481:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. Desde el nodo en buen estado, compruebe que se han guardado los núcleo:
+
.. Cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Usted puede responder `Y` cuando se le solicite que continúe en el modo avanzado. Aparece el símbolo del sistema del modo avanzado (*>).

.. Compruebe que se han guardado los núcleo: `system node run -node _local-node-name_ partner savecore`
+
Si el resultado del comando indica que savecore está en curso, espere a que savecore se complete antes de emitir el retorno. Puede controlar el progreso del savecore mediante el `system node run -node _local-node-name_ partner savecore -s command`.</info>.

.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`


. Si el nodo _reader_ está en modo de mantenimiento (mostrando el símbolo del sistema *>), salga del modo de mantenimiento y vaya al símbolo del sistema DEL CARGADOR: `halt`
. Arranque el nodo _reboot_: `boot_ontap`
. Una vez que el nodo _reader_ haya arrancado completamente, lleve a cabo una conmutación de estado: `metrocluster switchback`
. Compruebe la configuración de MetroCluster: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Compruebe el funcionamiento de la configuración de MetroCluster en Data ONTAP:
+
.. Compruebe si hay alertas de estado en ambos clústeres: `system health alert show`
.. Confirme que el MetroCluster está configurado y en modo normal: `metrocluster show`
.. Realizar una comprobación de MetroCluster: `metrocluster check run`
.. Mostrar los resultados de la comprobación de MetroCluster: `metrocluster check show`
.. Ejecute Config Advisor. Vaya a la página Config Advisor del sitio de soporte de NetApp en https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor/["support.netapp.com/NOW/download/tools/config_advisor/"].
+
Después de ejecutar Config Advisor, revise el resultado de la herramienta y siga las recomendaciones del resultado para solucionar los problemas detectados.



. Simular una operación de switchover:
+
.. Desde el símbolo del sistema de cualquier nodo, cambie al nivel de privilegio avanzado: `set -privilege advanced`
+
Debe responder con `y` cuando se le solicite que continúe en el modo avanzado y vea el símbolo del sistema del modo avanzado (*>).

.. Lleve a cabo la operación de regreso con el parámetro -Simulate: `metrocluster switchover -simulate`
.. Vuelva al nivel de privilegio de administrador: `set -privilege admin`




--
====