= Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis
:allow-uri-read: 


Para completar la sustitución del chasis, debe realizar tareas específicas.



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

Debe verificar el estado de alta disponibilidad del chasis y, si es necesario, actualizar el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis: `ha-config modify chassis _ha-state_`
+
El valor de la condición de alta disponibilidad puede ser uno de los siguientes:

+
*** ha
*** no ha




. Confirme que el ajuste ha cambiado: `ha-config show`
. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.




== Paso 2: Abra el sistema

. Si no lo ha hecho, vuelva a conectar los cables de alimentación a las PSU.
. Encienda las fuentes de alimentación cambiando el interruptor de balancín a *ON* y espere a que los controladores se enciendan por completo.
. Compruebe si hay alguna luz de fallo en la parte delantera y trasera del chasis y las controladoras después del encendido.
. Conéctese a la dirección IP de SP o BMC de los nodos a través de SSH. Esta será la misma dirección utilizada para apagar los nodos.
. Realice comprobaciones de estado adicionales, como se describe en https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP"^]
. Vuelva a activar AutoSupport (finalice el mensaje de la ventana de mantenimiento):
`system node autosupport invoke -node * -type all -message MAINT=end`


[]
====

NOTE: Como práctica recomendada, debe realizar lo siguiente:

* Resuelva cualquier https://activeiq.netapp.com/["Alertas de estado y riesgos de Active IQ"^] (Active IQ tardará tiempo en procesar los mensajes de AutoSupport posteriores al encendido; se espera un retraso en los resultados)
* Ejecución https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* Compruebe el estado del sistema mediante https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP"^]


====


== Paso 3: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Retorno de artículo  sustituciones"] para obtener más información.
