= Paso 1: Extraiga el módulo del controlador
:allow-uri-read: 


Para sustituir la controladora, debe extraer la controladora dañada, mover los componentes FRU del módulo de controladora dañado al módulo de controladora de repuesto, instalar el módulo de controladora de repuesto en el chasis y, a continuación, arrancar el sistema en modo de mantenimiento.



== Paso 1: Extraiga el módulo del controlador

Debe quitar el módulo de la controladora del chasis cuando sustituya el módulo de la controladora o sustituya un componente dentro del módulo de la controladora.

. En la parte frontal del chasis, utilice los pulgares para empujar con firmeza cada unidad hasta que sienta una parada positiva. De este modo se garantiza que las unidades se encuentren firmemente asentadas en el plano medio del chasis.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[Unidades de disco de asiento]

. Compruebe que el LED de estado situado en la ranura 4/5 de la parte posterior del módulo del controlador defectuoso está apagado. Busque el icono de NV.
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[Gráfico de ubicación del LED de estado y atención de NVRAM]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Número de llamada 1, ancho=30px"]
 a| 
LED de estado de NVRAM



 a| 
image:../media/legend_icon_02.svg["Número de llamada 1, ancho=30px"]
 a| 
LED de alerta de NVRAM

|===
+

NOTE: Si el LED de estado de NVRAM está parpadeando, puede significar que el módulo de la controladora no se ha desconectado o detenido correctamente (datos no comprometidos). Si el módulo de controlador asociado no ha asumido correctamente el módulo de controlador defectuoso, póngase en contacto con https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"] antes de continuar con este procedimiento.

+
El comportamiento general del LED de estado de NVRAM en el módulo del controlador defectuoso es el siguiente:

+
** El LED de estado de NVRAM parpadea cuando se extrae alimentación del módulo de la controladora y el sistema de almacenamiento se encuentra en estado «esperando devolución», o cuando el módulo de la controladora no se desconecta o se detiene correctamente (datos no comprometidos).
** El LED de estado de NVRAM parpadea cuando el módulo de la controladora se retira del chasis y puede significar que el módulo de la controladora no se desconecta o se detiene correctamente (datos no comprometidos). Confirme que el módulo del controlador ha tomado correctamente el control del módulo del controlador asociado o que el módulo del controlador defectuoso muestra `waiting for giveback`. A continuación, se puede ignorar el LED parpadeante (y el módulo del controlador se puede extraer del chasis).


. Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
. Desconecte los cables de la fuente de alimentación del módulo del controlador de las fuentes de alimentación (PSU) del módulo del controlador.
+

NOTE: Si el sistema tiene alimentación de CC, desconecte el bloque de alimentación de las PSU.

. Desconecte los cables del sistema y los módulos SFP y QSFP (si es necesario) del módulo del controlador, realizando un seguimiento de dónde se conectaron los cables.
+
Deje los cables en el dispositivo de administración de cables de manera que cuando vuelva a instalar el dispositivo de administración de cables, los cables estén organizados.

. Retire el dispositivo de gestión de cables del módulo del controlador.
. Presione los dos pestillos de bloqueo hacia abajo y, a continuación, gire ambos pestillos hacia abajo al mismo tiempo.
+
El módulo de la controladora se mueve ligeramente fuera del chasis.

+
image::../media/drw_a70-90_pcm_remove_replace_ieops-1365.svg[Gráfico de extracción del controlador]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Número de llamada 1, ancho=30px"]
| Un pestillo de bloqueo 


 a| 
image:../media/legend_icon_02.svg["Número de llamada 2, ancho=30px"]
 a| 
Pasador de bloqueo

|===
. Deslice el módulo del controlador fuera del chasis y colóquelo sobre una superficie plana y estable.
+
Asegúrese de que admite la parte inferior del módulo de la controladora cuando la deslice para sacarlo del chasis.





== Paso 2: Mueva las fuentes de alimentación

Mueva los suministros de alimentación a la controladora de reemplazo.

. Gire el mango de la leva de forma que pueda utilizarse para extraer la fuente de alimentación del módulo del controlador mientras presiona la lengüeta de bloqueo.
+

CAUTION: El suministro de alimentación es corto. Utilice siempre dos manos para apoyarlo cuando lo extraiga del módulo del controlador de modo que no se mueva repentinamente del módulo del controlador y le herir.

+
image::../media/drw_a70-90_psu_remove_replace_ieops-1368.svg[Retirada de PSU]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
| Lengüeta de bloqueo de PSU de terracota 


 a| 
image::../media/legend_icon_02.svg[Número de llamada 2]
 a| 
Suministro de alimentación

|===
. Mueva la fuente de alimentación al nuevo módulo de controlador y, a continuación, instálela.
. Con ambas manos, sujete y alinee los bordes de la fuente de alimentación con la abertura del módulo del controlador y, a continuación, empuje suavemente la fuente de alimentación en el módulo del controlador hasta que la lengüeta de bloqueo encaje en su sitio.
+
Las fuentes de alimentación sólo se acoplarán correctamente al conector interno y se bloquearán de una manera.

+

NOTE: Para evitar dañar el conector interno, no ejerza demasiada fuerza al deslizar la fuente de alimentación hacia el sistema.





== Paso 3: Mueva los ventiladores

Mueva los módulos de ventiladores al módulo de controlador de reemplazo.

. Retire el módulo del ventilador pinzando las lengüetas de bloqueo del lado del módulo del ventilador y, a continuación, levante el módulo del ventilador para extraerlo del módulo del controlador.
+
image::../media/drw_a70-90_fan_remove_replace_ieops-1366.svg[Quite los ventiladores]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
 a| 
Lengüetas de bloqueo del ventilador



 a| 
image::../media/legend_icon_02.svg[Número de llamada 2]
 a| 
Módulo de ventilador

|===
. Mueva el módulo de ventilador al módulo de controlador de repuesto y, a continuación, instale el módulo de ventilador alineando sus bordes con la abertura del módulo de controlador y, a continuación, deslice el módulo de ventilador hacia el módulo de controlador hasta que los pestillos de bloqueo encajen en su lugar.
. Repita estos pasos para los módulos de ventilador restantes.




== Paso 4: Mueva la batería de NV

Mueva la batería de NV al módulo de controladora de repuesto.

. Abra la cubierta del conducto de aire en el centro del módulo del controlador y localice la batería NV.
+
image::../media/drw_a70-90_remove_replace_nvmembat_ieops-1369.svg[Mueva la batería NV]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
| Conducto de aire de la batería NV 


 a| 
image::../media/legend_icon_02.svg[Número de llamada 2]
 a| 
Enchufe del paquete de baterías NV

|===
+
*ATENCIÓN:* El módulo NV led parpadea mientras separa el contenido de la memoria flash cuando detiene el sistema. Una vez finalizado el destete, el LED se apaga.

. Levante la batería para acceder al enchufe de la batería.
. Apriete el clip de la cara del enchufe de la batería para liberarlo de la toma y, a continuación, desenchufe el cable de la batería de la toma.
. Levante la batería del conducto de aire y del módulo del controlador.
. Mueva la batería al módulo de controlador de repuesto e instálelo en el módulo de controlador de repuesto:
+
.. Abra el conducto de aire de la batería NV en el módulo de controlador de reemplazo.
.. Enchufe la clavija de la batería a la toma y asegúrese de que la clavija se bloquea en su lugar.
.. Inserte la batería en la ranura y presione firmemente la batería para asegurarse de que está bloqueada en su lugar.
.. Cierre el conducto de aire de la batería NV.






== Paso 5: Mover los DIMM del sistema

Mueva los módulos DIMM al módulo de controlador de reemplazo.

. Abra el conducto de aire del controlador en la parte superior del controlador.
+
.. Inserte los dedos en los huecos de los extremos del conducto de aire.
.. Levante el conducto de aire y gírelo hacia arriba hasta el tope.


. Localice los DIMM del sistema en la placa base.
+
image::../media/drw_a70_90_dimm_ieops-1513.svg[Asignación de DIMM]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
| DIMM del sistema 
|===
. Tenga en cuenta la orientación del DIMM en el socket para poder insertar el DIMM en el módulo de controlador de reemplazo en la orientación adecuada.
. Extraiga el DIMM de su ranura empujando lentamente las dos lengüetas expulsoras del DIMM a ambos lados del DIMM y, a continuación, extraiga el DIMM de la ranura.
+

NOTE: Sujete con cuidado el módulo DIMM por los bordes para evitar la presión sobre los componentes de la placa de circuitos DIMM.

. Localice la ranura en el módulo de controlador de reemplazo en el que va a instalar el módulo DIMM.
. Inserte el módulo DIMM directamente en la ranura.
+
El módulo DIMM encaja firmemente en la ranura, pero debe entrar fácilmente. Si no es así, realinee el DIMM con la ranura y vuelva a insertarlo.

+

NOTE: Inspeccione visualmente el módulo DIMM para comprobar que está alineado de forma uniforme y completamente insertado en la ranura.

. Empuje con cuidado, pero firmemente, en el borde superior del DIMM hasta que las lengüetas expulsoras encajen en su lugar sobre las muescas de los extremos del DIMM.
. Repita estos pasos para los módulos DIMM restantes.
. Cierre el conducto de aire del controlador.




== Paso 6: Mueva los módulos de E/S.

Mueva los módulos de E/S al módulo de controlador de reemplazo.

image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Retire el módulo de E/S.]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
| Palanca de leva del módulo de E/S. 
|===
. Desconecte cualquier cableado del módulo de E/S de destino.
+
Asegúrese de etiquetar los cables para saber de dónde proceden.

. Gire el ARM de gestión de cables hacia abajo tirando de los botones del interior del ARM de gestión de cables y girándolo hacia abajo.
. Retire los módulos de E/S del módulo del controlador:
+
.. Pulse el botón de bloqueo de leva del módulo de E/S de destino.
.. Gire el pestillo de la leva hacia abajo hasta el tope. Para los módulos horizontales, gire la leva hacia fuera del módulo hasta el tope.
.. Retire el módulo del módulo del controlador enganchando el dedo en la abertura de la palanca de leva y sacando el módulo del módulo del controlador.
+
Asegúrese de realizar un seguimiento de la ranura en la que se encontraba el módulo de E/S.

.. Instale el módulo de E/S de repuesto en el módulo de controlador de sustitución deslizando suavemente el módulo de E/S en la ranura hasta que el pestillo de leva de E/S comience a acoplarse con el pasador de leva de E/S y, a continuación, empuje el pestillo de leva de E/S completamente hacia arriba para bloquear el módulo en su sitio.


. Repita estos pasos para mover los módulos I/O restantes, excepto los módulos de las ranuras 6 y 7, al módulo de controlador de reemplazo.
+

NOTE: Para mover los módulos de E/S de las ranuras 6 y 7, debe mover el portador que contiene estos módulos de E/S del módulo de controlador defectuoso al módulo de controlador de reemplazo.

. Mueva el portador que contiene los módulos de E/S en las ranuras 6 y 7 al módulo de controlador de reemplazo:
+
.. Pulse el botón de la palanca situada en el extremo derecho de la palanca del soporte. ..Deslice el portador fuera del módulo del controlador dañado. Insértelo en el módulo del controlador de reemplazo en la misma posición que estaba en el módulo del controlador dañado.
.. Empuje suavemente el soporte hasta el fondo en el módulo de controlador de repuesto hasta que encaje en su sitio.






== Paso 7: Mueva el módulo de gestión del sistema

Mueva el módulo Gestión del sistema al módulo de controlador de reemplazo.

image::../media/drw_a70-90_sys-mgmt_replace_ieops-1373.svg[Sustituya el módulo Gestión del sistema]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Número de llamada 1]
 a| 
Bloqueo de leva del módulo de gestión del sistema



 a| 
image::../media/legend_icon_02.svg[Número de llamada 2]
 a| 
Botón de bloqueo del soporte de arranque



 a| 
image::../media/legend_icon_03.svg[Número de llamada 3]
 a| 
Módulo de gestión del sistema de sustitución

|===
. Retire el módulo de gestión del sistema del módulo del controlador defectuoso:
+
.. Pulse el botón de la leva de gestión del sistema.
.. Gire la palanca de leva completamente hacia abajo.
.. Enrolle el dedo en la palanca de leva y tire del módulo para extraerlo del sistema.


. Instale el módulo de gestión del sistema en el módulo de controlador de sustitución en la misma ranura en la que estaba en el módulo de controlador dañado:
+
.. Alinee los bordes del módulo de gestión del sistema con la apertura del sistema y empújelo suavemente en el módulo del controlador.
.. Deslice suavemente el módulo en la ranura hasta que el pestillo de leva comience a acoplarse con el pasador de leva de E/S y, a continuación, gire el pestillo de leva completamente hacia arriba para bloquear el módulo en su sitio.






== Paso 8: Mueva el módulo NVRAM

Mueva el módulo NVRAM al módulo de la controladora de reemplazo.

image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[Retire el módulo NVRAM12 y los DIMM]

[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Número de llamada 1,width=30px"]
| Botón de bloqueo de leva 


 a| 
image:../media/legend_icon_02.svg["Número de llamada 2,width=30px"]
 a| 
Lengüeta de bloqueo de DIMM

|===
. Retire el módulo NVRAM del módulo del controlador defectuoso:
+
.. Pulse el botón de bloqueo de leva.
+
El botón de leva se aleja del chasis.

.. Gire el pestillo de leva hasta el tope.
.. Retire el módulo NVRAM de la carcasa enganchando el dedo en la abertura de la palanca de leva y tirando del módulo para sacarlo de la carcasa.


. Instale el módulo NVRAM en la ranura 4/5 del módulo de controladora de reemplazo:
+
.. Alinee el módulo con los bordes de la abertura del chasis en la ranura 4/5.
.. Deslice suavemente el módulo en la ranura hasta el fondo y, a continuación, empuje el pestillo de leva completamente hacia arriba para bloquear el módulo en su sitio.






== Paso 9: Instale el módulo del controlador

Vuelva a instalar el módulo del controlador y reinícielo.

. Asegúrese de que el conducto de aire esté completamente cerrado girándolo hacia abajo hasta el tope.
+
Debe quedar a ras de la chapa metálica del módulo del controlador.

. Alinee el extremo del módulo del controlador con la abertura del chasis y, a continuación, empuje suavemente el módulo del controlador hasta la mitad del sistema.
+

NOTE: No inserte completamente el módulo de la controladora en el chasis hasta que se le indique hacerlo.

. Recuperar el sistema, según sea necesario.
+
Si ha quitado los transceptores (QSFP o SFP), recuerde reinstalarlos si utiliza cables de fibra óptica.

. Complete la reinstalación del módulo del controlador:
+
.. Empuje firmemente el módulo de la controladora en el chasis hasta que se ajuste al plano medio y esté totalmente asentado.
+
Los pestillos de bloqueo se elevan cuando el módulo del controlador está completamente asentado.



+

NOTE: No ejerza una fuerza excesiva al deslizar el módulo del controlador hacia el chasis para evitar dañar los conectores.

+
.. Gire los pestillos de bloqueo hacia arriba hasta la posición de bloqueo.


. Conecte los cables de alimentación en las fuentes de alimentación.
+

NOTE: Si dispone de fuentes de alimentación de CC, vuelva a conectar el bloque de alimentación a las fuentes de alimentación después de que el módulo del controlador esté completamente asentado en el chasis.

+
El módulo del controlador arranca cuando se restaura la alimentación. Si arranca en el aviso del CARGADOR, reinicie la controladora con `boot_ontap` el comando.

. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.
. Si AutoSupport está habilitado, restaurar/desactivar la creación automática de casos mediante el `system node autosupport invoke -node * -type all -message MAINT=END` comando.
. Si aún no lo ha hecho, vuelva a instalar el dispositivo de gestión de cables y conecte de nuevo el controlador.

