= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Sin cifrado
--
Devuelva el almacenamiento a la controladora afectada a su funcionamiento normal.

.Pasos
. En el símbolo del sistema Loader, introduzca `boot_ontap`.
. Pulse <enter> cuando se detengan los mensajes de la consola.
+
** Si ve la petición de datos _login_, vaya al siguiente paso al final de esta sección.
** Si ve _Waiting for giveback_, pulse la clave <enter>, inicie sesión en el nodo partner y vaya al paso siguiente al final de esta sección.


. Devuelva la controladora afectada a su funcionamiento normal devolviendo su almacenamiento:
+
`storage failover giveback -ofnode _impaired_node_name_`.

. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback true`.

. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`.



--
.Cifrado OKM
--
Restablezca el cifrado integrado y devuelva la controladora a su funcionamiento normal.

.Pasos
. Desde el aviso del CARGADOR, introduzca:
+
`boot_ontap maint`

. Inicie en el menú ONTAP desde el indicador de Loader `boot_ontap menu` y seleccione la opción 10.
. Introduzca la frase de contraseña de OKM. Puede obtener esta frase de contraseña del cliente, o póngase en contacto con https://support.netapp.com["Soporte de NetApp"].
+

NOTE: Se le pedirá dos veces la contraseña.

. Introduzca los datos de la clave de backup cuando se le solicite.
. En el menú de inicio, introduzca la opción `1` para el arranque normal.
. Pulse <enter> cuando aparezca _Waiting for giveback_.
. Mueva el cable de la consola al nodo asociado e inicie sesión como `admin`.
. Devolver solo los agregados de CFO (el agregado raíz):
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`

+
Si encuentra errores, póngase en contacto con https://support.netapp.com["Soporte de NetApp"].

. Espere 5 minutos una vez que finalice el informe de devolución y compruebe el estado de conmutación por error y el estado de restauración:
+
`storage failover show` y `storage failover show-giveback`.

. Mueva el cable de la consola al nodo de reemplazo e introduzca:
+
`security key-manager onboard sync`

+

NOTE: Se le pedirá la clave de acceso de OKM para todo el clúster.

. Compruebe el estado de las teclas con el siguiente comando:
+
`security key-manager key query -key-type svm-KEK`.

+
Si la columna _restored_ muestra cualquier cosa que no sea _true_, póngase en contacto con https://support.netapp.com["Soporte de NetApp"].

. Devuelva la controladora afectada a su funcionamiento normal devolviendo su almacenamiento:
+
`storage failover giveback -ofnode _impaired_node_name_`.

. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback true`.

. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`.



--
.Cifrado EKM
--
Restablezca el cifrado y vuelva a poner la controladora en funcionamiento normal.

.Pasos
. Si el volumen raíz está cifrado con External Key Manager y el cable de la consola está conectado al nodo de reemplazo, introduzca `boot_ontap menu` y seleccione la opción `11`.
. Responda `y` o `n` a las siguientes preguntas:
+
¿Tiene una copia del archivo /cfcard/kmip/certs/client.crt? {s/n}

+
¿Tiene una copia del archivo /cfcard/kmip/certs/client.key? {s/n}

+
¿Tiene una copia del archivo /cfcard/kmip/certs/ca.pem? {s/n}

+
O.

+
¿Tiene una copia del archivo /cfcard/kmip/servers.cfg? {s/n}

+
¿Conoce la dirección del servidor KMIP? {s/n}

+
¿Conoce el puerto KMIP? {s/n}

+

NOTE: Póngase en contacto con https://support.netapp.com["Soporte de NetApp"] si tiene problemas.

. Proporcione la información para:
+
** El contenido del archivo del certificado de cliente (client.crt).
** Contenido del archivo de clave de cliente (client.key).
** El contenido del archivo de CA (CA.pem) del servidor KMIP.
** La dirección IP del servidor KMIP.
** El puerto del servidor KMIP.


. Una vez que el sistema se procese, verá el menú de inicio. Seleccione '1' para el arranque normal.
. Compruebe el estado de toma de control:
+
`storage failover show`.

. Devuelva el controlador deteriorado al funcionamiento normal devolviendo su almacenamiento: `storage failover giveback -ofnode _impaired_node_name_`.
. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback true`.

. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`.



--
====