= Paso 1: Arranque las controladoras y devuelva las controladoras
:allow-uri-read: 




== Paso 1: Arranque las controladoras y devuelva las controladoras

Después de que se reinicien las controladoras, arranque ONTAP y devuelva las controladoras.

.Pasos
. Compruebe la salida de la consola:
+
.. Si la controladora arranca en el símbolo del SISTEMA DE Loader, reinicie la controladora con `boot_ontap` el comando.
.. Si la consola aparece `waiting for giveback` después del reinicio, inicie sesión en la controladora asociada y compruebe que la controladora reemplazada esté lista para el retorno con `storage failover show` el comando.


. Realice la devolución del control:
+
.. Conecte el cable de la consola al controlador asociado.
.. Devuelva la controladora con `storage failover giveback -fromnode local` el comando.






== Paso 2: Verifique el estado del sistema de almacenamiento

Después de que la controladora haya devuelto el almacenamiento, debe comprobar el estado general con https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].

.Pasos
. Una vez finalizada la devolución, ejecute Active IQ Config Advisor para comprobar el estado del sistema de almacenamiento.
. Corrija los problemas que encuentre.




== Paso 3: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
