= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Sin cifrado
--
Devuelva el almacenamiento a la controladora afectada a su funcionamiento normal.

.Pasos
. Desde el indicador LOADER, ingrese
+
`boot_ontap`

. Pulse <enter> cuando se detengan los mensajes de la consola.
+
** Si ve la petición de datos _login_, vaya al siguiente paso al final de esta sección.
** Si no ve el mensaje de inicio de sesión, presione la tecla <Entrar>; si aún no aparece, inicie sesión en el nodo asociado.


. Devuelva solo la raíz con la opción override-destination-checks:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: El siguiente comando solo está disponible en el nivel de privilegio del modo Diagnóstico.  Para obtener más información sobre los niveles de privilegio, consultelink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Comprenda los niveles de privilegio para los comandos CLI de ONTAP"^] .

+
Si encuentra errores, póngase en contacto con https://support.netapp.com["Soporte de NetApp"].

. Espere 5 minutos después de que se complete el informe de devolución, luego verifique el estado de conmutación por error y devolución:
+
`storage failover show`y `storage failover show-giveback`

+

NOTE: El siguiente comando solo está disponible en el nivel de privilegio del modo Diagnóstico.

. Si se desconectaron los enlaces de interconexión de HA, vuelva a conectarlos:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. Devuelva la controladora afectada a su funcionamiento normal devolviendo su almacenamiento:
+
`storage failover giveback -ofnode _impaired_node_name_`

. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback-of true`

. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.Cifrado OKM
--
Restablezca el cifrado integrado y devuelva la controladora a su funcionamiento normal.

.Pasos
. Desde el aviso del CARGADOR, introduzca:
+
`boot_ontap maint`

. Inicie en el menú ONTAP desde el indicador de Loader `boot_ontap menu` y seleccione la opción 10.
. Introduzca la frase de contraseña de OKM. Puede obtener esta frase de contraseña del cliente, o póngase en contacto con https://support.netapp.com["Soporte de NetApp"].
+

NOTE: Se le pedirá dos veces la contraseña.

. Introduzca los datos de la clave de backup cuando se le solicite.
. En el menú de inicio, introduzca la opción `1` para el arranque normal.
. Mueva el cable de la consola al nodo asociado e ingrese el siguiente inicio de sesión:
+
`admin`

. Devuelva solo la raíz con la opción override-destination-checks:
+
`storage  failover giveback -ofnode impaired-node -only-root true -override-destination-checks true`

+

NOTE: El siguiente comando solo está disponible en el nivel de privilegio del modo Diagnóstico.  Para obtener más información sobre los niveles de privilegio, consultelink:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Comprenda los niveles de privilegio para los comandos CLI de ONTAP"^] .

+
Si encuentra errores, póngase en contacto con https://support.netapp.com["Soporte de NetApp"].

. Espere 5 minutos después de que se complete el informe de devolución, luego verifique el estado de conmutación por error y devolución:
+
`storage failover show`y `storage failover show-giveback`

+

NOTE: El siguiente comando solo está disponible en el nivel de privilegio del modo Diagnóstico.

. Mueva el cable de la consola al nodo de reemplazo e ingrese lo siguiente:
+
`security key-manager onboard sync`

+

NOTE: Se le pedirá la clave de acceso de OKM para todo el clúster.

. Compruebe el estado de las teclas con el siguiente comando:
+
`security key-manager key query -key-type svm-KEK`

+
Si la columna _restored_ muestra cualquier cosa que no sea _true_, póngase en contacto con https://support.netapp.com["Soporte de NetApp"].

. Devuelva la controladora afectada a su funcionamiento normal devolviendo su almacenamiento:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
.. Si se desconectaron los enlaces de interconexión de HA, vuelva a conectarlos para reanudar la recuperación automática:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback-of true`

. Si AutoSupport está habilitado, restaure o desactive la creación automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====