= Paso 1: Verifique la configuración de alta disponibilidad
:allow-uri-read: 




== Paso 1: Verifique la configuración de alta disponibilidad

Debe comprobar el `HA` estado del módulo de la controladora y, si es necesario, actualice el estado para que coincida con la configuración del sistema.

. Arranque en modo de mantenimiento: `boot_ontap maint`
+
.. Introduzca `y` cuando vea _Continue with boot?_.
+
Si aparece el mensaje de advertencia _System ID mismatch_, introduzca `y`.



. Introduzca `sysconfig -v` y capture el contenido de la pantalla.
+

NOTE: Si ve _PERSONALITY MISMATCH_ póngase en contacto con el servicio de atención al cliente.

. En `sysconfig -v` la salida, compare la información de la tarjeta del adaptador con las tarjetas y las ubicaciones de la controladora de reemplazo.




== Paso 2: Verifique la lista de discos

. Compruebe que el adaptador enumera las rutas a todos los discos:
+
`storage show disk -p`

+
Si observa algún problema, compruebe el cableado y vuelva a colocar los cables.

. Salir del modo de mantenimiento:
+
`halt`


