= 
:allow-uri-read: 


Puede restaurar la imagen de ONTAP (recuperación del medio de arranque) desde el nodo del partner mediante `boot_recovery -partner` el comando en las plataformas ASA R2 que ejecuten ONTAP 9.16,0 y versiones posteriores.

.Antes de empezar
Cuando arranca un nodo y el soporte de arranque de dicho nodo está dañado, verá los siguientes mensajes y el proceso de arranque con stop en el símbolo del sistema de Loader:

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
Si ve este mensaje, debe restaurar la imagen de ONTAP

.Pasos
. En el símbolo del sistema DE Loader, introduzca el comando _boot_recovery -partner_.
+
La pantalla mostrará el mensaje `Starting boot media recovery (BMR) process press Ctrl-C to abort...` y comenzará las comprobaciones iniciales.

. Supervise el proceso como Loader configura los puertos del clúster local y ejecuta netboot a través `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`de .
+
Una vez que netboot se está ejecutando, `Starting BMR ...` se muestra en la pantalla y el proceso completa el proceso de instalación.

+
.. Si Key Manager no está configurado, verá el siguiente mensaje:
+
....
key manager is not configured. Exiting.
....
.. Si aparece el siguiente mensaje, Onboard Key Manager (OKM) está configurado:
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
Vaya a para completar el proceso de recuperación.

.. Si ve el siguiente mensaje, External Key Manager (EKM) está configurado. Vaya al tema de EKM y complete el proceso de recuperación:
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. Supervisar el proceso BMR a medida que ejecuta la restauración de la configuración de copia de seguridad, el archivo env, mdb y rdb desde el partner.
. El nodo se reinicia y la BMR se completa cuando observe lo siguiente:


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....