= 
:allow-uri-read: 


Revise los siguientes requisitos.

[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====
* Debe sustituir el medio de arranque con errores por un medio de arranque de reemplazo que recibió desde NetApp.
* Los puertos del clúster se utilizan para la comunicación entre los dos controladores durante el proceso de recuperación de arranque automático. Asegúrese de que los puertos del clúster del controlador dañado funcionen correctamente.
* Para OKM, necesita la frase de contraseña de todo el clúster y también los datos de respaldo.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/cliente.clave
** /cfcard/kmip/certs/CA.pem


* Comprenda la terminología del controlador utilizada en este procedimiento:
+
** El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
** El _controlador saludable_ es el socio HA del controlador dañado.



