= 
:allow-uri-read: 


[NOTE]
====
NetApp recomienda encarecidamente que habilites el registro de consola en los dispositivos con los que estás trabajando y que realices las siguientes acciones al llevar a cabo este procedimiento:

* Deja AutoSupport activado durante tu mantenimiento. Esto permite que el soporte de NetApp reciba información de diagnóstico si ocurren problemas.
* Habilita el registro de sesión para cualquier sesión CLI. Esto crea un registro completo de todos los comandos y la salida del sistema durante la actividad de mantenimiento. Para obtener orientación sobre cómo habilitar el registro de sesión, consulta https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con los sistemas ONTAP"^].


====
.unidad flash USB
* Asegúrese de tener una unidad flash USB formateada en FAT32.
* El USB debe tener suficiente capacidad de almacenamiento para contener el  `image_xxx.tgz` archivo.


.Preparación de archivos
Copiar el  `image_xxx.tgz` Archivo a la memoria USB. Este archivo se usará al transferir la imagen de ONTAP mediante la memoria USB.

Desde la imagen de ONTAP extraída, copia la carpeta `EFI` al directorio raíz de la unidad flash USB.

.Reemplazo de componentes
Reemplace el componente fallado con el componente de reemplazo proporcionado por NetApp.

.Identificación del controlador
Es fundamental aplicar los comandos al controlador correcto cuando se reemplaza el medio de arranque dañado:

* El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
* El _controlador saludable_ es el socio HA del controlador dañado.

