= Paso 1: Restaurar el administrador de claves
:allow-uri-read: 




== Paso 1: Restaurar el administrador de claves

Debe completar los pasos específicos de los sistemas que tengan habilitado el gestor de claves incorporado (OKM), el cifrado de almacenamiento de NetApp (NSE) o el cifrado de volúmenes de NetApp (NVE) mediante la configuración capturada al principio de este procedimiento.


NOTE: Si se habilitan NSE o NVE junto con el gestor de claves incorporado o externo, debe restaurar la configuración capturada al principio de este procedimiento.

.Pasos
. Conecte el cable de consola a la controladora de destino.
. Seleccione una de las siguientes opciones para restaurar la configuración del administrador de claves incorporado desde el menú de arranque ONATP.


[role="tabbed-block"]
====
.Opción 1: Sistemas con configuración del servidor de gestión de claves incorporada
--
Restaure la configuración del Administrador de claves integrado (OKM) desde el menú de inicio de ONTAP.

.Antes de empezar
* Asegúrese de que dispone de la siguiente información al restaurar la configuración de OKM:
+
** Se ha introducido la clave de acceso para todo el clúster https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["al tiempo que habilita la gestión de claves incorporada"].
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Información de backup del gestor de claves incorporado"].


* Realice el https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Cómo comprobar el backup de gestión de claves incorporada y la clave de acceso para todo el clúster"] procedimiento antes de continuar.


.Pasos
. Conecte el cable de consola a la controladora de destino.
. En el menú de arranque ONTAP, seleccione la opción apropiada:
+
[cols="1a,2a"]
|===
| Versión de ONTAP | Seleccione esta opción 


 a| 
ONTAP 9.8 o posterior
 a| 
Seleccione la opción 10.

|===


--
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
[]
====
A| ONTAP 9.7 y anteriores A| Seleccione la opción oculta `recover_onboard_keymanager`

====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
[]
====
|===


| + . Confirme que desea continuar con el proceso de recuperación. + .Mostrar indicador de ejemplo [%Collapsible] 
|===
====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

[]
====
. Introduzca dos veces la clave de acceso para todo el clúster.
+
Al introducir la frase de acceso, la consola no mostrará ninguna entrada.



====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

[]
====
+

. Introduzca la información de backup.
+
.. Pegue todo el contenido desde la línea de COPIA DE SEGURIDAD DE INICIO hasta la línea de COPIA DE SEGURIDAD FINAL.




====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
[]
====
. Pulse la tecla ENTER dos veces al final de la entrada.
+
El proceso de recuperación finaliza.



====
....

Enter the backup data:

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
[]
====
+ ADVERTENCIA: No proceda si la salida mostrada es otra cosa que `Successfully recovered keymanager secrets` . Realice la solución de problemas para corregir el error.

. Seleccione la opción 1 en el menú de arranque para continuar arrancando en ONTAP.


====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
[]
====
. Confirme que la consola de la controladora muestre lo siguiente:
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

. Desde el nodo asociado, restaure la controladora del partner:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`.

. Después de arrancar solo con CFO Aggregate, ejecute el siguiente comando:
+
`security key-manager onboard sync` comando.

. Introduzca la clave de acceso en todo el clúster para la instancia de Onboard Key Manager.


====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
[]
====
+ NOTA: Si la sincronización se realiza correctamente, se devuelve la petición de datos del clúster sin mensajes adicionales. Si la sincronización falla, aparecerá un mensaje de error antes de volver al símbolo del sistema del clúster. No continúe hasta que se corrija el error y la sincronización se ejecute correctamente.

. Asegúrese de que todas las claves estén sincronizadas:
+
`security key-manager key query -restored false`.

+
`There are no entries matching your query.`

+

NOTE: No deberían aparecer resultados al filtrar por false en el parámetro restaurado.

. Devolución del nodo desde el partner:
+
`storage failover giveback -fromnode local`

. Restaure la devolución automática, si la deshabilitó, introduciendo el siguiente comando:
+
`storage failover modify -node local -auto-giveback true`

. Si AutoSupport está habilitado, restaure la creación automática de casos introduciendo el siguiente comando:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--

--
Restaure la configuración del gestor de claves externo desde el menú de inicio de ONATP.

.Antes de empezar
Necesitará la siguiente información para restaurar la configuración del gestor de claves externo (EKM):

* Una copia del archivo /cfcard/kmip/servers.cfg de otro nodo de cluster o de la siguiente información:
+
** La dirección del servidor KMIP.
** El puerto KMIP.
** Una copia del archivo /cfcard/kmip/certs/client.crt de otro nodo del clúster o del certificado de cliente.
** Una copia del archivo /cfcard/kmip/certs/client.key de otro nodo de clúster o la clave de cliente.
** Una copia del archivo /cfcard/kmip/certs/CA.pem de otro nodo del clúster o de las CA del servidor KMIP.




.Pasos
. Conecte el cable de consola a la controladora de destino.
. Seleccione la opción 11 en el menú de inicio de ONTAP.


====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
[]
====
+

. Cuando se le solicite, confirme que ha recopilado la información obligatoria.


====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
[]
====
+

====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
[]
====
+

. Cuando se le solicite, introduzca la información del cliente y del servidor.


====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
[]
====
+ .Mostrar ejemplo

====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
MIIDvjCCAqagAwIBAgICN3gwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNVBAYTAlVT
MRMwEQYDVQQIEwpDYWxpZm9ybmlhMQwwCgYDVQQHEwNTVkwxDzANBgNVBAoTBk5l
MSUbQusvzAFs8G3P54GG32iIRvaCFnj2gQpCxciLJ0qB2foiBGx5XVQ/Mtk+rlap
Pk4ECW/wqSOUXDYtJs1+RB+w0+SHx8mzxpbz3mXF/X/1PC3YOzVNCq5eieek62si
Fp8=
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAoU1eajEG6QC2h2Zih0jEaGVtQUexNeoCFwKPoMSePmjDNtrU
MSB1SlX3VgCuElHk57XPdq6xSbYlbkIb4bAgLztHEmUDOkGmXYAkblQ=
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
MIIEizCCA3OgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBjzELMAkGA1UEBhMCVVMx
7yaumMQETNrpMfP+nQMd34y4AmseWYGM6qG0z37BRnYU0Wf2qDL61cQ3/jkm7Y94
EQBKG1NY8dVyjphmYZv+
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
​​​​....


====

. The recovery process completes.


+
.Show example prompt
[%collapsible]
====
....
El sistema está preparado para utilizar gestores de claves externos. Intentando recuperar claves de los servidores de claves.... [Aug 29 21:06:28]: 0x808806100: 0: DEBUG: kmip2::main: [InitOpenssl]:460: Realizando la inicialización de OpenSSL recuperó correctamente los secretos del gestor de claves.

....



. Select option 1 from the boot menu to continue booting into ONTAP.

+
....
****
* Seleccione la opción '(1) Normal Boot.' para completar el proceso de recuperación. *


****
(1) Arranque normal. (2) Arranque sin /etc/rc. (3) Cambiar contraseña. (4) Limpiar la configuración e inicializar todos los discos. (5) Arranque en el modo de mantenimiento. (6) Actualizar flash desde la configuración de copia de seguridad. (7) Instale primero el nuevo software. (8) Reiniciar nodo. (9) Configurar creación avanzada de particiones de unidades. (10) Configurar secretos de recuperación del gestor de claves incorporado. (11) Configure el nodo para la gestión de claves externas. Selección (1-11)? 1

....
====
+


. Restore automatic giveback, if you disabled it, by entering the following command:
+
`storage failover modify -node local -auto-giveback true` command.

. If AutoSupport is enabled, restore automatic case creation by entering  the following command:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


--

====

== Step 2: Complete the boot media replacement

Complete the boot media replacement process after the normal boot by completing final checks and giving back storage.

. Check the console output:
+
[%header,cols="1,3"]
|===
| If the console displays...| Then...
a|
The login prompt
a|
Go to Step 6.
a|
Waiting for giveback...
a|

 .. Log into the partner controller.
 .. Confirm the target controller is ready for giveback with the _storage failover show_ command.

|===

. Move the console cable to the partner controller and give back the target controller storage using the _storage failover giveback -fromnode local -only-cfo-aggregates true_ command.

 ** If the command fails because of a failed disk, physically disengage the failed disk, but leave the disk in the slot until a replacement is received.

 ** If the command fails because the partner is "not ready", wait 5 minutes for the HA subsystem to synchronize between the partners.
 ** If the command fails because of an NDMP, SnapMirror, or SnapVault process, disable the process. See the appropriate Documentation Center for more information.
. Wait 3 minutes and check the failover status with the _storage failover show_ command.
. At the clustershell prompt, enter the _network interface show -is-home false_ command to list the logical interfaces that are not on their home controller and port.
+
If any interfaces are listed as `false`, revert those interfaces back to their home port using the _net int revert -vserver Cluster -lif _nodename_ command.

. Move the console cable to the target controller and run the _version -v_ command to check the ONTAP versions.

. Use the `storage encryption disk show` to review the output.
. Use the _security key-manager key query_ command to display the key IDs of the authentication keys that are stored on the key management servers.
 ** If the `Restored` column = `yes/true`, you are done and can proceed to complete the replacement process.
 ** If the `Key Manager type` = `external` and the `Restored` column = anything other than `yes/true`, use the _security key-manager external restore_ command to restore the key IDs of the authentication keys.
+
NOTE: If the command fails, contact Customer Support.

 ** If the `Key Manager type` = `onboard` and the `Restored` column = anything other than `yes/true`, use the _security key-manager onboard sync_ command to synchronize the missing onboard keys on the repaired node.
+
Use the _security key-manager key query_ command to verify that the `Restored` column = `yes/true` for all authentication keys.

. Connect the console cable to the partner controller.
. Give back the controller using the `storage failover giveback -fromnode local` command.
. Restore automatic giveback if you disabled it by using the _storage failover modify -node local -auto-giveback true_ command.
. If AutoSupport is enabled, restore/unsuppress automatic case creation by using the _system node autosupport invoke -node * -type all -message MAINT=END_ command.
....