= Verifique la configuración de NVE
:allow-uri-read: 


Antes de apagar la controladora dañada, debe comprobar si el sistema tiene habilitado el cifrado de volúmenes de NetApp (NVE) o el cifrado de almacenamiento de NetApp (NSE). Si es así, debe comprobar la configuración.

.Pasos
. Conecte el cable de la consola al controlador dañado.
. Compruebe si el cifrado de volúmenes está configurado para cualquier volumen del clúster: `volume show -is-encrypted true`
+
Si algún volumen aparece en la salida, NVE se configura y debe verificar la configuración NVE. Si no aparece ningún volumen en la lista, compruebe si NSE está configurado.

. Compruebe si NSE está configurado: `storage encryption disk show`
+
** Si el resultado del comando incluye los detalles de la unidad con información sobre el modo y el identificador de claves, se configura NSE y se debe verificar la configuración de NSE.
** Si NVE y NSE no están configurados, es seguro apagar el controlador afectado.






== Verifique la configuración de NVE

.Pasos
. Muestre los ID de claves de las claves de autenticación que se almacenan en los servidores de gestión de claves: `security key-manager query`
+
** Si la `Restored` la columna muestra `yes` y se muestran todos los gestores de claves `available`, es seguro apagar el controlador dañado.
** Si la `Restored` columna muestra cualquier otra cosa que no sea `yes`o si aparece algún gestor de claves `unavailable`, necesita completar algunos pasos adicionales.
** Si ve el mensaje este comando no es compatible con la gestión de claves incorporada, debe completar algunos pasos adicionales.


. Si la `Restored` columna mostrada cualquier otra cosa que no sea `yes`o si aparece algún gestor de claves `unavailable`:
+
.. Recupere y restaure todas las claves de autenticación y los ID de clave asociados: `security key-manager restore -address *`
+
Si el comando falla, póngase en contacto con el soporte de NetApp.

+
http://["mysupport.netapp.com"]

.. Compruebe que el `Restored` la columna muestra `yes` para todas las claves de autenticación y que se muestran todos los gestores de claves `available`: `security key-manager query`
.. Apague el controlador dañado.


. Si vio el mensaje este comando no es compatible cuando la gestión de claves incorporada está habilitada, muestre las claves almacenadas en el gestor de claves incorporado: `security key-manager key show -detail`
+
.. Si la `Restored` la columna muestra `yes` realice un backup manual de la información de gestión de claves incorporada:
+
*** Vaya al modo de privilegios avanzado e introduzca `y` cuando se le solicite continuar: `set -priv advanced`
*** Introduzca el comando para mostrar la información de backup de OKM: `security key-manager backup show`
*** Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
*** Volver al modo admin: `set -priv admin`
*** Apague el controlador dañado.


.. Si la `Restored` columna muestra cualquier otra cosa que no sea `yes`:
+
*** Ejecute el asistente de configuración Key-Manager: `security key-manager setup -node target/impaired node name`
+

NOTE: Introduzca la clave de acceso de gestión de claves incorporada del cliente en el símbolo del sistema de. Si no se puede proporcionar la frase de contraseña, póngase en contacto con http://["mysupport.netapp.com"]

*** Compruebe que el `Restored` la columna muestra `yes` para toda la clave de autenticación: `security key-manager key show -detail`
*** Vaya al modo de privilegios avanzado e introduzca `y` cuando se le solicite continuar: `set -priv advanced`
*** Introduzca el comando para mostrar la información de backup de OKM: `security key-manager backup show`
*** Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
*** Volver al modo admin: `set -priv admin`
*** Puede apagar la controladora de forma segura.








== Verifique la configuración de NSE

.Pasos
. Muestre los ID de claves de las claves de autenticación que se almacenan en los servidores de gestión de claves: `security key-manager query`
+
** Si la `Restored` la columna muestra `yes` y se muestran todos los gestores de claves `available`, es seguro apagar el controlador dañado.
** Si la `Restored` columna muestra cualquier otra cosa que no sea `yes`o si aparece algún gestor de claves `unavailable`, necesita completar algunos pasos adicionales.
** Si ve el mensaje este comando no es compatible con la gestión de claves incorporada, debe completar algunos pasos adicionales


. Si la `Restored` columna mostrada cualquier otra cosa que no sea `yes`o si aparece algún gestor de claves `unavailable`:
+
.. Recupere y restaure todas las claves de autenticación y los ID de clave asociados: `security key-manager restore -address *`
+
Si el comando falla, póngase en contacto con el soporte de NetApp.

+
http://["mysupport.netapp.com"]

.. Compruebe que el `Restored` la columna muestra `yes` para todas las claves de autenticación y que se muestran todos los gestores de claves `available`: `security key-manager query`
.. Apague el controlador dañado.


. Si vio el mensaje este comando no es compatible cuando la gestión de claves incorporada está habilitada, muestre las claves almacenadas en el gestor de claves incorporado: `security key-manager key show -detail`
+
.. Si la `Restored` la columna muestra `yes`, realice una copia de seguridad manual de la información de administración de claves integrada:
+
*** Vaya al modo de privilegios avanzado e introduzca `y` cuando se le solicite continuar: `set -priv advanced`
*** Introduzca el comando para mostrar la información de backup de OKM:  `security key-manager backup show`
*** Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
*** Volver al modo admin: `set -priv admin`
*** Apague el controlador dañado.


.. Si la `Restored` columna muestra cualquier otra cosa que no sea `yes`:
+
*** Ejecute el asistente de configuración Key-Manager: `security key-manager setup -node target/impaired node name`
+

NOTE: Introduzca la frase de contraseña de OKM del cliente en la solicitud. Si no se puede proporcionar la frase de contraseña, póngase en contacto con http://["mysupport.netapp.com"]

*** Compruebe que el `Restored` la columna muestra `yes` para todas las claves de autenticación: `security key-manager key show -detail`
*** Vaya al modo de privilegios avanzado e introduzca `y` cuando se le solicite continuar: `set -priv advanced`
*** Introduzca el comando para realizar un backup de la información de OKM: ``security key-manager backup show``
+

NOTE: Asegúrese de que la información de OKM se guarda en su archivo de registro. Esta información será necesaria en situaciones de desastre en las que OKM podría necesitar recuperación manual.

*** Copie el contenido de la información de la copia de seguridad en un archivo o registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
*** Volver al modo admin: `set -priv admin`
*** Puede apagar el controlador de forma segura.





