= Requisitos
:allow-uri-read: 




== Requisitos

* Debe sustituir el componente con errores por un componente FRU de reemplazo con la misma capacidad que recibió de NetApp.
* El puerto e0S (llave e0M) de la controladora dañada no puede estar defectuoso.
+
El puerto e0S se utiliza para la recuperación automática del arranque.

* Para OKM, necesita el contenido del archivo de contraseña de OKM.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** archivo /cfcard/kmip/servers.cfg.
** archivo /cfcard/kmip/certs/client.crt.
** archivo /cfcard/kmip/certs/client.key.
** Archivo /cfcard/kmip/certs/ca.pem.






== Consideraciones

* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El controlador _drinated_ es el controlador en el que está realizando tareas de mantenimiento.
** El controlador _heated_ es el compañero de alta disponibilidad del controlador dañado.


* Si es necesario, puede encender los LED de ubicación del chasis de la plataforma (azules) para ayudar a localizar físicamente la plataforma afectada. Inicie sesión en BMC mediante SSH e introduzca `system location-led _on_` el comando.
+
Un chasis de plataforma tiene tres LED de ubicación: Uno en el panel de visualización del operador y otro en cada controlador. Los LED de ubicación permanecen encendidos durante 30 minutos.

+
Puede desactivarlos introduciendo `system location-led _off_` el comando. Si no está seguro de si los LED están encendidos o apagados, puede comprobar su estado introduciendo `system location-led show` el comando.


