= Requisitos
:allow-uri-read: 


Debe revisar los requisitos y consideraciones del procedimiento de reemplazo de la controladora.



== Requisitos

* Todas las bandejas deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* Debe sustituir una controladora por una controladora del mismo tipo de modelo. No se puede actualizar el sistema simplemente reemplazando la controladora.
* No es posible cambiar ninguna unidad o bandeja como parte de este procedimiento.
* Siempre debe capturar la salida de consola de la controladora en un archivo de registro de texto.
+
La salida de la consola le proporciona un registro del procedimiento que puede utilizar para solucionar los problemas que pueda encontrar durante el proceso de reemplazo.





== Consideraciones

* Es importante aplicar los comandos de este procedimiento a la controladora correcta:
+
** El controlador _drinated_ es el controlador que se va a sustituir.
** El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
** El controlador _heated_ es el controlador que sobrevive.



