= 
:allow-uri-read: 


Puede sustituir una unidad con error de forma no disruptiva mientras hay I/o en curso.

.Antes de empezar
* El sistema de almacenamiento debe admitir la unidad que está instalando.
+
https://hwu.netapp.com["Hardware Universe de NetApp"^]

* Si la autenticación de unidad de autocifrado (SED) está habilitada, debe usar las instrucciones de sustitución de SED en la documentación de ONTAP.
+
Las instrucciones de la documentación de ONTAP describen los pasos adicionales que debe realizar antes y después de reemplazar una SED.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Información general del cifrado de NetApp con la interfaz de línea de comandos"^]

* Todos los demás componentes del sistema de almacenamiento deben funcionar correctamente. De lo contrario, debe ponerse en contacto https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"] antes de continuar con este procedimiento.
* Compruebe que la unidad que desea quitar tenga error.
+
Para verificar que la unidad presenta errores, ejecute el `storage disk show -broken` comando. La unidad con error se muestra en la lista de unidades con errores. Si no lo hace, debe esperar y volver a ejecutar el comando.

+

NOTE: Según el tipo y la capacidad de la unidad, la unidad puede tardar hasta varias horas en aparecer en la lista de unidades con errores.



.Acerca de esta tarea
* Al sustituir una unidad con error, debe esperar 70 segundos entre la retirada de la unidad y la inserción de la unidad de reemplazo para permitir que el sistema de almacenamiento reconozca que se ha quitado una unidad.
* La práctica recomendada es tener la versión actual del paquete de cualificación de discos (DQP) instalada antes de intercambiar en caliente una unidad.
+
Si tiene instalada la versión actual del DQP, el sistema podrá reconocer y utilizar unidades recién cualificadas. Esto evita mensajes de eventos del sistema sobre la información no actualizada de la unidad y la prevención de la partición de unidades, ya que no se reconocen las unidades. El DQP también notifica el firmware de la unidad no actual.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["Descargas de NetApp: Paquete de cualificación de disco"^]

* La práctica recomendada es tener versiones actuales del firmware del módulo de bandeja NVMe (NSM) y del firmware de la unidad en el sistema antes de reemplazar los componentes de FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Descargas de NetApp: Firmware de bandeja de discos"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Descargas de NetApp: Firmware de la unidad de disco"^]

+
[NOTE]
====
No revierte el firmware a una versión que no admite la bandeja y sus componentes.

====
* El firmware de la unidad se actualiza automáticamente (sin interrupciones) en las unidades nuevas con versiones de firmware no actuales.
+

NOTE: Las comprobaciones del firmware de la unidad se realizan cada dos minutos.

* Si es necesario, puede encender los LED de ubicación del sistema de almacenamiento (azul) para ayudar a localizar físicamente el sistema de almacenamiento afectado. Inicie sesión en BMC mediante SSH e introduzca `system location-led _on_` el comando.
+
Un sistema de almacenamiento tiene tres LED de ubicación: Uno en el panel de visualización del operador y otro en cada controlador. Los LED de ubicación permanecen encendidos durante 30 minutos.

+
Puede desactivarlos introduciendo `system location-led _off_` el comando. Si no está seguro de si los LED están encendidos o apagados, puede comprobar su estado introduciendo `system location-led show` el comando.


