= 
:allow-uri-read: 


Prepare el sistema de almacenamiento y la ranura del módulo de E/S 4 para que sea seguro quitar el clúster fallido y el módulo de E/S de alta disponibilidad:

.Pasos
. Puesta a tierra apropiadamente usted mismo.
. Desconecte el cableado del clúster fallido y del módulo de E/S de HA.
+
Asegúrese de etiquetar los cables para que más adelante en este procedimiento pueda volver a conectarlos a los mismos puertos.

. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
Por ejemplo, el siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas:

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. Desactivar devolución automática:
+
.. Ingrese el siguiente comando desde la consola del controlador dañado:
+
`storage failover modify -node local -auto-giveback false`

.. Ingresar `y` cuando vea el mensaje "¿Desea desactivar la devolución automática?"


. Prepare el clúster fallido y el módulo HA en la ranura 4 para su extracción quitándolos del servicio y apagándolos:
+
.. Introduzca el siguiente comando:
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. Ingresar `y` cuando veas el mensaje _¿Quieres continuar?_
+
Por ejemplo, el siguiente comando prepara el módulo en la ranura 4 del nodo 2 (el controlador dañado) para su eliminación y muestra un mensaje que indica que es seguro eliminarlo:

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. Verifique que el clúster fallido y el módulo HA en la ranura 4 estén apagados:
+
`system controller slot module show`

+
La salida debería mostrar  `_powered-off_` en la columna de estado del módulo fallido en la ranura 4.


