= Paso 1: Preparar el sitio
:allow-uri-read: 




== Paso 1: Preparar el sitio

Para instalar el sistema de almacenamiento, asegúrese de que el sitio y el gabinete o rack que planea utilizar cumplan las especificaciones de su configuración.

.Pasos
. Utilice https://hwu.netapp.com["Hardware Universe de NetApp"^] esta herramienta para confirmar que su centro cumple los requisitos ambientales y eléctricos de su sistema de almacenamiento.
. Asegúrese de que dispone de espacio de rack adecuado:
+
** 4U en una configuración de alta disponibilidad para el sistema de almacenamiento
** 2U por cada bandeja de almacenamiento NS224


+
*NOTA:* Vea link:https://hwu.netapp.com["Hardware Universe de NetApp"^]los requisitos de espacio de rack para otros estantes de almacenamiento compatibles.

. Instale los switches de red necesarios.
+
Consulte la https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentación de los switches"^] para obtener instrucciones de instalación y link:https://hwu.netapp.com["Hardware Universe de NetApp"^] para obtener información sobre compatibilidad.





== Paso 2: Desempaquetar las cajas

Después de asegurarse de que el sitio y el gabinete o rack que planea utilizar para su sistema de almacenamiento cumplen con las especificaciones requeridas, desembale todas las cajas y compare el contenido con los artículos en la hoja de embalaje.

.Pasos
. Abra cuidadosamente todas las cajas y coloque el contenido de una manera organizada.
. Compara el contenido que has desempaquetado con la lista de la hoja de embalaje.
+

NOTE: Usted puede obtener su lista de embalaje escaneando el código QR en el lado de la caja de envío.

+
Los siguientes elementos son algunos de los contenidos que puede ver en las cajas.

+
Asegúrese de que todo lo que hay en las cajas coincide con la lista de la hoja de embalaje. Si hay alguna discrepancia, anótelas para realizar otras acciones.

+
[cols="12,9,4"]
|===


| *Hardware* | *Cables* |  


 a| 
** Frontal
** Dispositivo de gestión de cables
** Sistema de almacenamiento
** Kits de rieles con instrucciones (opcional)
** Bandeja de almacenamiento

 a| 
** Cables Ethernet de gestión (cables RJ-45)
** Cables de red
** Cables de alimentación
** Cables de almacenamiento (si ha pedido almacenamiento adicional)
** Cable de puerto serie USB-C.

|  
|===




== Paso 3: Registre el sistema de almacenamiento

Una vez que se asegura de que su sitio cumple los requisitos de las especificaciones del sistema de almacenamiento y comprueba que posee todas las piezas solicitadas, debe registrar su sistema.

.Pasos
. Busque el número de serie del sistema de almacenamiento.
+
Puede encontrar el número en la hoja de embalaje, en el correo electrónico de confirmación o en el módulo de gestión del sistema del controlador después de desempaquetarlo.

+
image::../media/drw_ssn_label.svg[Ejemplo del número de serie del sistema]

. Vaya a la http://mysupport.netapp.com/["Sitio de soporte de NetApp"^].
. Determine si necesita registrar el sistema de almacenamiento:
+
[cols="1a,2a"]
|===
| Si usted es un... | Siga estos pasos... 


 a| 
Cliente existente de NetApp
 a| 
.. Inicie sesión con su nombre de usuario y contraseña.
.. Selecciona *Sistemas* > *Mis sistemas*.
.. Confirme que el nuevo número de serie aparece en la lista.
.. De lo contrario, siga las instrucciones para nuevos clientes de NetApp.




 a| 
Nuevo cliente de NetApp
 a| 
.. Haga clic en *Registrar ahora* y cree una cuenta.
.. Selecciona *Sistemas* > *Registrar sistemas*.
.. Introduzca el número de serie del sistema de almacenamiento y los detalles solicitados.


Una vez aprobado el registro, puede descargar el software necesario. El proceso de aprobación puede llevar hasta 24 horas.

|===

