= Equipo necesario para la instalación
:allow-uri-read: 




== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Peso del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.



=== Peso del estante

Tome las precauciones necesarias al mover o levantar su estante.

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]

