= Equipo necesario para la instalación
:allow-uri-read: 




== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas de almacenamiento son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Pesos del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.

[role="tabbed-block"]
====
.A1K
--
Un sistema de almacenamiento A1K puede pesar hasta 28,5 kg (62,83 lbs). Para levantar el sistema, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K Icono de precaución de elevación]

--
.A70 y A90
--
Un sistema de almacenamiento A70 o un sistema de almacenamiento A90 pueden pesar hasta 68,8 kg (151,68 lbs). Para levantar el sistema, se necesitan cuatro personas o un elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]

--
====


=== Pesos de los estantes de almacenamiento

Un estante de almacenamiento NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante de almacenamiento, se necesitan dos personas o un elevador hidráulico. Conserve todos los componentes en la bandeja de almacenamiento (tanto delantera como trasera) para evitar que se desequilibre el peso de bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]

