= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Sistemas AFF
--
Los modelos AFF A-Series y C-Series son una plataforma sólida de escalado horizontal creada para entornos virtualizados y se pueden poner en marcha como un sistema independiente o un nivel de alto rendimiento en una configuración de NetApp ONTAP. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Obtenga más información sobre los sistemas AFF"].

.AFF A20, AFF A30, AFF A50
Disponible a partir de ONTAP 9.16.1

.AFF C30 y AFF C60
Disponible a partir de ONTAP 9.16.1

.AFF A1K, AFF A70 y AFF A90
Disponible a partir de ONTAP 9.15.1

.AFF A150
Disponible empezando con ONTAP 9.13.1, ONTAP 9.12.1P1, ONTAP 9.11.1P8, ONTAP 9.10.1P12

.AFF A900
Disponible a partir de ONTAP 9.10.1

.AFF A250 y AFF A800
Disponible a partir de ONTAP 9,8

.AFF A400
Disponible a partir de ONTAP 9,7

.AFF C250, AFF C400, AFF C800
Disponible a partir de ONTAP 9.12.1P1, ONTAP 9.13.1 GA

--
.Sistemas ASA r2
--
Los sistemas R2 de ASA ofrecen una solución de hardware y software unificada que crea una experiencia simplificada específica para las necesidades de los clientes de SAN exclusivamente. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].

.ASA A1K, ASA A70, ASA A90
Disponible a partir de ONTAP 9.16.0

--
.Sistemas ASA
--
Los modelos ASA A-Series y C-Series ofrecen una experiencia SAN simplificada y dedicada que ofrece disponibilidad continua de datos para bases de datos de misión crítica para la empresa y otras cargas de trabajo SAN que utilizan el protocolo iSCSI o la certificación FCP. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Obtenga más información sobre los sistemas ASA"].

.ASA A150, ASA A250, ASA A400, ASA A900
Disponible a partir de ONTAP 9.13.1

.ASA C250, C400, C800
Disponible a partir de ONTAP 9.13.1P1

--
.Sistemas FAS
--
Los sistemas FAS proporcionan almacenamiento secundario seguro y eficiente, la solución definitiva para la clasificación en niveles, el backup y la recuperación ante desastres. link:https:://www.netapp.com/data-storage/fas/["Obtenga más información acerca de los sistemas FAS"].

.FAS70 y FAS90
Disponible a partir de ONTAP 9.15.1

.FAS9500
Disponible a partir de ONTAP 9.11.1, ONTAP 9.10.1P3

.FAS8300 y FAS700
Disponible a partir de ONTAP 9,7

.FAS2820
Disponible a partir de ONTAP 9.13.1

.FAS2700
Disponible a partir de ONTAP 9.13.1

--
====