---
permalink: c190/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff c190, shutdown the controllers 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague las controladoras - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe apagar la controladora o la controladora del chasis antes de moverlos al nuevo chasis.

.Acerca de esta tarea
* Si tiene un clúster con más de dos controladoras, debe estar quórum. Si el clúster no está en quórum o si se muestra una controladora en buen estado `false` para la elegibilidad y la salud, debe corregir el problema antes de apagar el controlador dañado; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].
* Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`



.Pasos
. Si su sistema tiene dos módulos de controladora, desactive el par de alta disponibilidad.
+
[cols="1,2"]
|===
| Si su sistema utiliza Clustered ONTAP con... | Realice lo siguiente... 


 a| 
Dos controladoras en el clúster
 a| 
`cluster ha modify -configured false`

`storage failover modify -node node0 -enabled false`



 a| 
Más de dos controladoras en el clúster
 a| 
`storage failover modify -node node0 -enabled false`

|===
. Detenga el controlador, pulse `y` cuando se le pida que confirme la detención: `system node halt -node _node_name_`
+
El mensaje de confirmación tiene el aspecto siguiente:

+
[listing]
----
Warning: This operation will cause controller "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the controller goes out of service and one more controller goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: Debe realizar un apagado correcto del sistema antes de sustituir el chasis para evitar perder datos no escritos en la memoria no volátil (NVMEM/NVRAM). Dependiendo del sistema, si el LED de NVMEM/NVRAM parpadea, hay contenido en el NVMEM/NVRAM que no se ha guardado en el disco. Es necesario reiniciar la controladora y comenzar desde el principio de este procedimiento. Si se repite los intentos para apagar correctamente la controladora, tenga en cuenta que se podrían perder datos que no se han guardado en el disco.

. Cuando sea aplicable, detenga la segunda controladora para evitar un posible mensaje de error de quórum en una configuración de par de alta disponibilidad: `system node halt -node _second_node_name_ -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true`
+
Responda `y` cuando se le solicite.


