---
permalink: c190/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff c190, replace the chassis 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF C190, revisa los requisitos para que la sustitución sea exitosa. El procedimiento de sustitución del chasis requiere mover todas las unidades, fuentes de alimentación y módulos de controlador del chasis con problemas al chasis de reemplazo, y es una operación disruptiva.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover todas las unidades y módulos o módulos de controladora al nuevo chasis, y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

