---
permalink: c190/chassis-replace-complete-rma.html 
sidebar: sidebar 
keywords: aff c190, verify and set HA state 
summary: Debe comprobar el estado de alta disponibilidad del chasis. 
---
= Restaurar y verificar la configuración: AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe comprobar el estado de alta disponibilidad del chasis.



== Paso 1: Verificar y configurar el estado de alta disponibilidad del chasis

Debe verificar el estado de alta disponibilidad del chasis y, si es necesario, actualizar el estado para que coincida con la configuración del sistema.

. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis:
+
`*ha-config show*`

+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis:
+
`*ha-config modify chassis _HA-state_*`

+
Valor para `_HA-state_` puede ser uno de los siguientes:

+
*** `ha`
*** `non-ha`


.. Confirme que el ajuste ha cambiado:
+
`*ha-config show*`



. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.
. Reinicie el sistema.




== Paso 2: Devuelve la parte fallida a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
