---
permalink: c190/maintain-overview.html 
sidebar: sidebar 
keywords: c190 maintenance, maintenance, repairing c190, repairing c190, replace c190 components, replace c190 components 
summary: Mantenga el hardware de AFF C190 
---
= Infórmate sobre el mantenimiento de tu sistema de almacenamiento AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Realiza el mantenimiento del hardware de tu sistema de almacenamiento AFF C190 para asegurar la fiabilidad a largo plazo y un rendimiento óptimo. Haz tareas de mantenimiento periódicas, como reemplazar componentes defectuosos, para evitar tiempos de inactividad y pérdida de datos.



[[boot-media]]
== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



[[chassis]]
== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



[[controller]]
== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



[[dimm]]
== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



[[drive]]
== Unidad

Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



[[fan]]
== Ventilador

El ventilador enfría el controlador.



[[nvmem-battery]]
== Batería NVMEM

El controlador incluye una batería y proporciona la alimentación de respaldo si falla la alimentación de CA.



[[power-supply]]
== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



[[real-time-clock-battery]]
== Batería del reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
