---
permalink: a700/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: aff a700, fas9000, boot, recovery, image, two, node, metrocluster, configuration 
summary: El procedimiento para arrancar el nodo dañado desde la imagen de recuperación depende de si el sistema está en una configuración de MetroCluster de dos nodos. 
---
= Inicie la imagen de recuperación - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El procedimiento para arrancar el nodo dañado desde la imagen de recuperación depende de si el sistema está en una configuración de MetroCluster de dos nodos.



== Opción 1: Inicia la imagen de recuperación en la mayoría de los sistemas

Debe arrancar la imagen de ONTAP desde la unidad USB, restaurar el sistema de archivos y verificar las variables del entorno.

Este procedimiento se aplica a los sistemas que no están en una configuración MetroCluster de dos nodos.

.Pasos
. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Restaure el `var` sistema de archivos:
+
[cols="1,2"]
|===
| Si el sistema tiene... | Realice lo siguiente... 


 a| 
Una conexión de red
 a| 
.. Pulse `y` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Configure el nodo en buen estado como nivel de privilegio avanzado: `set -privilege advanced`
.. Ejecute el comando restore backup: `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Devuelva el nodo al nivel de administrador: `set -privilege admin`
.. Pulse `y` cuando se le solicite que utilice la configuración restaurada.
.. Pulse `y` cuando se le solicite reiniciar el nodo.




 a| 
No hay conexión de red
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.





 a| 
No hay conexión de red y está en una configuración de IP de MetroCluster
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Espere a que se conecten las conexiones de almacenamiento iSCSI.
+
Puede continuar después de ver los siguientes mensajes:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.



|===
. Asegurarse de que las variables medioambientales estén establecidas de la manera esperada:
+
.. Lleve el nodo al aviso DEL CARGADOR.
.. Compruebe la configuración de la variable de entorno con el `printenv` comando.
.. Si una variable de entorno no está establecida como se espera, modifíquela con el `setenv __environment-variable-name__ __changed-value__` comando.
.. Guarde los cambios mediante `savenv` comando.


. El siguiente depende de la configuración del sistema:
+
** Si su sistema tiene configurado el gestor de claves incorporado, NSE o NVE, vaya a. xref:bootmedia-encryption-restore.adoc[Restaure OKM, NSE y NVE según sea necesario]
** Si su sistema no tiene configurado el gestor de claves incorporado, NSE o NVE, complete los pasos en esta sección.


. Desde el aviso del CARGADOR, introduzca el `boot_ontap` comando.
+
[cols="1,2"]
|===
| *Si ve... | Entonces...* 


 a| 
La solicitud de inicio de sesión de
 a| 
Vaya al siguiente paso.



 a| 
Esperando devolución...
 a| 
.. Inicie sesión en el nodo del partner.
.. Confirme que el nodo de destino está listo para la devolución con el `storage failover show` comando.


|===
. Conecte el cable de consola al nodo compañero.
. Vuelva a dar el nodo mediante el `storage failover giveback -fromnode local` comando.
. En el símbolo del sistema del clúster, compruebe las interfaces lógicas con el `net int -is-home false` comando.
+
Si alguna interfaz se muestra como "falsa", vuelva a revertir dichas interfaces a su puerto de inicio utilizando el `net int revert` comando.

. Mueva el cable de consola al nodo reparado y ejecute el `version -v` Comando para comprobar las versiones de ONTAP.
. Restaure la devolución automática si la ha desactivado mediante el `storage failover modify -node local -auto-giveback true` comando.




== Opción 2: Arrancar la imagen de recuperación en una configuración MetroCluster de dos nodos

Debe arrancar la imagen de ONTAP desde la unidad USB y comprobar las variables de entorno.

Este procedimiento se aplica a los sistemas de una configuración MetroCluster de dos nodos.

.Pasos
. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Después de instalar la imagen, inicie el proceso de restauración:
+
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Pulse `y` cuando se le pida que reinicie para empezar a utilizar el software recién instalado.
+
Debe estar preparado para interrumpir el proceso de arranque cuando se le solicite.



. Cuando se inicie el sistema, pulse `Ctrl-C` después de ver la `Press Ctrl-C for Boot Menu` Mensaje. Y cuando aparezca el menú Inicio, seleccione la opción 6.
. Compruebe que las variables de entorno están establecidas de la forma esperada.
+
.. Lleve el nodo al aviso DEL CARGADOR.
.. Compruebe la configuración de la variable de entorno con el `printenv` comando.
.. Si una variable de entorno no está establecida como se espera, modifíquela con el `setenv __environment-variable-name__ __changed-value__` comando.
.. Guarde los cambios mediante `savenv` comando.
.. Reiniciar el nodo.



