---
permalink: a700/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, replace, boot, media, primary, secondary, image, disruptive, nondisruptive 
summary: 'El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca. En función de la configuración de red, puede realizar una sustitución no disruptiva o disruptiva.' 
---
= Descripción general de la sustitución de medios de arranque: A700 y FAS9000 de AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El soporte de arranque almacena un conjunto principal y secundario de archivos del sistema (imagen de arranque) que el sistema utiliza cuando arranca. En función de la configuración de red, puede realizar una sustitución no disruptiva o disruptiva.

Debe tener una unidad flash USB, formateada a FAT32, con la cantidad de almacenamiento adecuada para guardar el `image_xxx.tgz`.

También debe copiar el `image_xxx.tgz` Archivo a la unidad flash USB para su uso posterior en este procedimiento.

* Ambos métodos no disruptivos y disruptivos para reemplazar medios de arranque requieren restaurar el `var` sistema de archivos:
+
** Para reemplazar de forma no disruptiva, el par de alta disponibilidad no requiere una conexión a una red para restaurar el `var` sistema de archivos. El par de alta disponibilidad de un único chasis tiene una conexión e0S interna, que se utiliza para la transferencia `var` config. entre ellos.
** Para el reemplazo disruptivo, no es necesaria una conexión de red para restaurar el `var` el sistema de archivos, pero el proceso requiere dos reinicios.


* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en el nodo correcto:
+
** El nodo _drinated_ es el nodo en el que realiza tareas de mantenimiento.
** El _heated node_ es el partner de alta disponibilidad del nodo dañado.




Si necesita reemplazar el soporte de arranque secundario mientras el soporte de arranque principal está instalado y en buen estado, póngase en contacto con el soporte de NetApp y mencione el https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["Cómo reemplazar el dispositivo de arranque secundario de un AFF A700s"^] artículo de la base de conocimientos.
