---
permalink: a700/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir un chasis AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF A700, revisa los requisitos para que la sustitución sea exitosa. El procedimiento de sustitución del chasis consiste en trasladar todos los componentes del chasis averiado al chasis de recambio y es una operación disruptiva.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

