---
permalink: fas-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the boot media 
summary: Antes de reemplazar el medio de arranque en su sistema de almacenamiento FAS70 o FAS90, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso. 
---
= Requisitos para la recuperación automatizada de medios de arranque: FAS70 y FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reemplazar el medio de arranque en su sistema de almacenamiento FAS70 o FAS90, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso. Esto incluye verificar que tenga el medio de arranque de reemplazo correcto, confirmar que los puertos del clúster en la controladora dañada funcionen correctamente y determinar si el Administrador de claves integrado (OKM) o el Administrador de claves externo (EKM) están habilitados.

El proceso de recuperación automática del medio de arranque solo es compatible con ONTAP 9.17.1 y versiones posteriores. Si su sistema de almacenamiento ejecuta una versión anterior de ONTAP, utilice el link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"] .

Revise los siguientes requisitos.

* Debe sustituir el medio de arranque con errores por un medio de arranque de reemplazo que recibió desde NetApp.
* Los puertos del clúster se utilizan para la comunicación entre los dos controladores durante el proceso de recuperación de arranque automático. Asegúrese de que los puertos del clúster del controlador dañado funcionen correctamente.
* Para OKM, necesita la frase de contraseña de todo el clúster y también los datos de respaldo.
* Para EKM, necesita copias de los siguientes archivos del nodo asociado:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/cliente.clave
** /cfcard/kmip/certs/CA.pem


* Es fundamental aplicar los comandos al controlador correcto cuando se reemplaza el medio de arranque dañado:
+
** El _controlador dañado_ es el controlador en el que está realizando mantenimiento.
** El _controlador saludable_ es el socio HA del controlador dañado.




.El futuro
Después de revisar los requisitos de soporte de arranque, usted link:bootmedia-shutdown-bmr.html["apague la controladora"].
