---
permalink: fas-70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: aff a1k, replace the chassis 
summary: Prepárese para reemplazar el chasis dañado en su sistema FAS70 y FAS90 identificando el chasis dañado, verificando los componentes de reemplazo y etiquetando los cables y los módulos del controlador. 
---
= Prepárese para reemplazar el chasis - FAS70 y FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepárese para reemplazar el chasis dañado en su sistema FAS70 o FAS90 identificando el chasis dañado, verificando los componentes de reemplazo y etiquetando los cables y el módulo del controlador.



== Paso 1: Localice y supervise su sistema

Debe abrir una sesión de consola y guardar los registros de sesiones para futuras referencias, así como encender el LED de ubicación del sistema para encontrar el chasis dañado.

.Pasos
. Conéctese al puerto de la consola de serie para la interfaz con el sistema y supervisarlo.
. Busque y encienda el LED de ubicación de la controladora:
+
.. Utilice `system controller location-led show` el comando para mostrar el estado actual del LED de ubicación.
.. Cambie el estado del LED de ubicación a ON:
+
`system controller location-led modify -node _node1_ -state on`

+
El LED de ubicación permanece encendido durante 30 minutos.







== Paso 2: Verifique los componentes de reemplazo

Debe verificar que ha recibido los componentes necesarios, quitarlos del empaque y guardar el empaque.

.Pasos
. Antes de abrir el embalaje, debe mirar la etiqueta del embalaje y verificar:
+
** Número de pieza del componente.
** Descripción de la pieza.
** Cantidad en la caja.


. Quite el contenido del paquete y utilice el paquete para devolver el componente con errores a NetApp.




== Paso 3: Etiquetar los cables

Debe etiquetar los cables antes de quitarlos de los módulos de E/S en la parte posterior del sistema.

.Pasos
. Etiquete todos los cables asociados con el sistema de almacenamiento. Esto facilita el recableado más adelante en este procedimiento.
. Si aún no está correctamente conectado a tierra, asígnese a tierra.


.El futuro
Una vez que se haya preparado para reemplazar el hardware del chasis FAS70 o FAS90, debelink:chassis-replace-shutdown.html["apague la controladora"] .
