---
permalink: fas-70-90/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: fas70, fas90, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Compruebe que la configuración de alta disponibilidad de la controladora esté activa y funcione correctamente en el sistema de almacenamiento FAS70 o FAS90, y confirme que los adaptadores del sistema enumeran todas las rutas a los discos. 
---
= Restaurar y verificar la configuración del sistema: FAS70 y FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Compruebe que la configuración de alta disponibilidad de la controladora esté activa y funcione correctamente en el sistema de almacenamiento FAS70 o FAS90, y confirme que los adaptadores del sistema enumeran todas las rutas a los discos.



== Paso 1: Verifique la configuración de alta disponibilidad

Debe comprobar el `HA` estado del módulo de la controladora y, si es necesario, actualice el estado para que coincida con la configuración del sistema.

.Pasos
. Arranque en modo de mantenimiento: `boot_ontap maint`
+
.. Introduzca `y` cuando vea _Continue with boot?_.
+
Si aparece el mensaje de advertencia _System ID mismatch_, introduzca `y`.



. Introduzca `sysconfig -v` y capture el contenido de la pantalla.
+

NOTE: Si ve _PERSONALITY MISMATCH_ póngase en contacto con el servicio de atención al cliente.

. En `sysconfig -v` la salida, compare la información de la tarjeta del adaptador con las tarjetas y las ubicaciones de la controladora de reemplazo.
. Compruebe que todos los componentes muestran el mismo `HA` estado: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado del módulo del controlador no coincide con la configuración del sistema, defina el `HA` estado del módulo del controlador: `ha-config modify controller ha`
+
El valor del estado de alta disponibilidad puede ser uno de los siguientes:

+
** `ha`
** `mcc` (no compatible)
** `mccip` (No compatible con sistemas ASA)
** `non-ha` (no compatible)


. Confirme que el ajuste ha cambiado: `ha-config show`




== Paso 2: Verifique la lista de discos

.Pasos
. Compruebe que el adaptador enumera las rutas de acceso a todos los discos con el `storage show disk -p`.
+
Si observa algún problema, compruebe el cableado y vuelva a colocar los cables.

. Salir del modo de mantenimiento `halt`: .


.El futuro
Después de restaurar y verificar la configuración del sistema para su sistema FAS70 o FAS90, debe hacerlolink:controller-replace-recable-reassign-disks.html["devuelva la controladora"].
