---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: Revise el equipo necesario y las precauciones de elevación de su plataforma y estantes. 
---
= Requisitos de instalación - FAS70 y FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento FAS70 o FAS90 y las bandejas de almacenamiento.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Peso del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento.

Un sistema de almacenamiento FAS70 o FAS90 puede pesar hasta 28,5 kg (62,83 lbs). Para levantar el sistema, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[FAS70 y FAS90 Icono de precaución de elevación]



=== Peso del estante

Tome las precauciones necesarias al mover o levantar su estante.

Un estante NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante, utilice dos personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 Cuidado de elevación]

Un estante DS460C puede pesar hasta 260,4 lbs (181,1 kg). Para levantar la bandeja de almacenamiento, es posible que necesite hasta cinco personas o un elevador hidráulico. Conserve todos los componentes en la bandeja de almacenamiento (tanto delantera como trasera) para evitar que se desequilibre el peso de bandeja.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de hardware, usted link:install-prepare.html["Prepárese para instalar el sistema de almacenamiento FAS70 o FAS90"].
