---
permalink: asa900/bootmedia_recovery_image.html 
sidebar: sidebar 
keywords:  
summary: El procedimiento para arrancar la controladora con deterioro de la imagen de recuperación depende de si el sistema está en una configuración MetroCluster de dos nodos. 
---
= Inicie la imagen de recuperación - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe arrancar la imagen de ONTAP desde la unidad USB, restaurar el sistema de archivos y verificar las variables del entorno.

. Desde el símbolo DEL SISTEMA DEL CARGADOR, arranque la imagen de recuperación desde la unidad flash USB: `boot_recovery`
+
La imagen se descarga desde la unidad flash USB.

. Cuando se le solicite, introduzca el nombre de la imagen o acepte la imagen predeterminada que se muestra dentro de los corchetes de la pantalla.
. Restaure el sistema de archivos var:
+
[cols="1,2"]
|===
| Si el sistema tiene... | Realice lo siguiente... 


 a| 
Una conexión de red
 a| 
.. Pulse `y` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Pulse `y` cuando se le solicite sobrescribir `/etc/ssh/ssh_host_ecdsa_key`.
.. Pulse `y` cuando se le solicite que confirme si la copia de seguridad de la restauración se realizó correctamente.
.. Pulse `Y` cuando se le solicite la copia de configuración restaurada.
.. Configure la controladora dañada al nivel de privilegio avanzado: `set -privilege advanced`
.. Ejecute el comando restore backup: `system node restore-backup -node local -target-address impaired_node_IP_address`
.. Devuelva la controladora dañada al nivel admin: `set -privilege admin`
.. Pulse `y` cuando se le solicite que utilice la configuración restaurada.
.. Pulse `y` cuando se le solicite reiniciar la controladora dañada.




 a| 
No hay conexión de red
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.





 a| 
No hay conexión de red y está en una configuración de IP de MetroCluster
 a| 
.. Pulse `n` cuando se le solicite que restaure la configuración de copia de seguridad.
.. Reinicie el sistema cuando el sistema lo solicite.
.. Espere a que se conecten las conexiones de almacenamiento iSCSI.
+
Puede continuar después de ver los siguientes mensajes:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Seleccione la opción *Actualizar flash desde la configuración de copia de seguridad* (flash de sincronización) en el menú que se muestra.
+
Si se le solicita que continúe con la actualización, pulse `y`.



|===
. Asegurarse de que las variables medioambientales estén establecidas de la manera esperada:
+
.. Lleve la controladora dañada al aviso DEL CARGADOR.
.. Compruebe la configuración de la variable de entorno con el comando printenv.
.. Si una variable de entorno no está definida como se esperaba, modifíquela con el comando setenvEnvironment_variable_name Changed_value.
.. Guarde los cambios con el comando saveenv.


. El siguiente depende de la configuración del sistema:
+
** Si su sistema tiene configurado el gestor de claves incorporado, NSE o NVE, vaya a. xref:bootmedia_encryption_restore.adoc[Pasos de sustitución de medios posteriores al arranque para OKM, NSE y NVE]
** Si su sistema no tiene configurado el gestor de claves incorporado, NSE o NVE, complete los pasos en esta sección.


. Desde el aviso DEL CARGADOR, introduzca el comando boot_ontap.
+
[cols="1,2"]
|===
| Si ve... | Realice lo siguiente... 


 a| 
La solicitud de inicio de sesión de
 a| 
Vaya al siguiente paso.



 a| 
Esperando devolución...
 a| 
.. Inicie sesión en el controlador asociado.
.. Confirme que el destino está listo para la devolución con el `storage failover show` comando.


|===
. Conecte el cable de la consola al controlador asociado.
. Dé vuelta a la controladora con el comando de recuperación tras fallos del almacenamiento -fromnode local.
. En el símbolo del sistema del clúster, compruebe las interfaces lógicas con el comando net int -is-home false.
+
Si alguna de las interfaces se muestra como "false", vuelva a revertir dichas interfaces a su puerto de inicio utilizando el comando net int revert.

. Mueva el cable de la consola al apagado reparado o retome el controlador dañado siguiendo el procedimiento adecuado para su configuración. Y ejecute el comando version -v para comprobar las versiones de ONTAP.
. Restaure la devolución automática si la deshabilitó con el comando Storage Failover modify -node local -auto-giveback true.

