---
permalink: asa900/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: ASA a900, shutdown the controllers 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague los controladores - ASA A900
:allow-uri-read: 




== Apague los controladores - ASA A900

[role="lead"]
Este procedimiento es para sistemas con configuraciones de dos nodos. Para obtener más información sobre el cierre correcto al realizar el mantenimiento de un cluster, consulte https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Apagar y encender sin problemas la Guía de resolución del sistema de almacenamiento: Base de conocimientos de NetApp"].

.Antes de empezar
* Asegúrese de que dispone de los permisos y credenciales necesarios:
+
** Credenciales de administrador local para ONTAP.
** Accesibilidad de BMC para cada controlador.


* Asegúrese de que dispone de las herramientas y el equipo necesarios para la sustitución.


.Pasos
. Inicie sesión en el clúster a través de SSH o inicie sesión desde cualquier nodo del clúster mediante un cable de consola local y un equipo portátil/consola.
. Detenga el acceso de todos los clientes/host a los datos del sistema de NetApp.
. Suspender trabajos de backup externo.
. Si AutoSupport está habilitado, suprima la creación de casos e indique cuánto tiempo espera que el sistema esté sin conexión:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identifique la dirección SP/BMC de todos los nodos del clúster:
+
`system service-processor show -node * -fields address`

. Salga del shell de cluster:
+
`exit`

. Inicia sesión en el SP/BMC de cada controlador usando la dirección IP identificada en el paso anterior:
+
** Si inicias sesión desde el BMC por SSH, conéctate usando la dirección SP/BMC (por ejemplo, `ssh admin@<SP/BMC_address>`), luego ingresa el comando `system console` y autentícate.
** Si estás usando una consola local o un portátil conectado directamente al controlador, inicia sesión con las mismas credenciales de administrador del clúster.


. Detenga los dos nodos ubicados en el chasis dañado:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para los clústeres que utilizan SnapMirror síncrono en modo StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Ingrese *y* para cada controlador en el clúster cuando vea:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Espere a que cada controladora se detenga y muestre el aviso del CARGADOR.

