---
permalink: asa900/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: ASA a900, shutdown the controllers 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague los controladores - ASA A900
:allow-uri-read: 




== Apague los controladores - ASA A900

[role="lead"]
Este procedimiento es solamente para configuraciones de 2 nodos que no sean de MetroCluster. Si tiene un sistema con más de dos nodos, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Cómo realizar un apagado y encendido con gracia de una pareja de alta disponibilidad en un clúster de 4 nodos"^].

.Antes de empezar
Necesita:

* Credenciales de administrador local para ONTAP.
* Clave de acceso para todo el clúster de gestión de claves incorporada de NetApp (OKM) si usa cifrado de almacenamiento o NVE/NAE.
* Accesibilidad de BMC para cada controladora.
* Detenga el acceso de todos los clientes/host a los datos del sistema de NetApp.
* Suspender trabajos de backup externo.
* Herramientas y equipos necesarios para la sustitución.



NOTE: Si el sistema es un StorageGRID de NetApp o ONTAP S3 que se utiliza como nivel de cloud de FabricPool, consulte la https://kb.netapp.com/onprem/ontap/hardware/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage#["Apague y encienda sin problemas su Guía de resolución del sistema de almacenamiento"] después de realizar este procedimiento.


NOTE: Si utiliza SSD, consulte https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU490["SU490: (Impacto: Crítico) Mejores prácticas para las SSD: Evite el riesgo de un fallo de unidad y de pérdida de datos si se apaga durante más de dos meses"]

Como práctica recomendada antes del cierre, debe:

* Realizar adicionales https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["comprobaciones de estado del sistema"].
* Actualice ONTAP a una versión recomendada para el sistema.
* Resuelva cualquier https://activeiq.netapp.com/["Alertas de estado y riesgos de Active IQ"]. Tome nota de cualquier fallo presente en el sistema, como los LED de los componentes del sistema.


.Pasos
. Inicie sesión en el clúster a través de SSH o inicie sesión desde cualquier nodo del clúster mediante un cable de consola local y un equipo portátil/consola.
. Desactive AutoSupport e indique cuánto tiempo espera que el sistema esté fuera de línea:
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identifique la dirección del SP/BMC de todos los nodos:
+
`system service-processor show -node * -fields address`

. Salga del shell de cluster: `exit`
. Inicie sesión en SP/BMC sobre SSH con la dirección IP de cualquiera de los nodos que aparecen en el resultado del paso anterior.
+
Si está usando una consola o portátil, inicie sesión en la controladora con las mismas credenciales de administrador de clúster.

+

NOTE: Abra una sesión SSH en cada conexión SP/BMC de modo que pueda supervisar el progreso.

. Detenga los 2 nodos ubicados en el chasis dañado:
+
`system node halt -node <node>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para los clústeres que utilizan SnapMirror síncrono en modo StrictSync: `system node halt -node <node>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Introduzca *y* para cada controlador en el clúster cuando lo vea `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Espere a que cada controladora se detenga y muestre el aviso del CARGADOR.

