---
permalink: asa900/install_videos.html 
sidebar: sidebar 
keywords: ASA A900 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Pasos de vídeo - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

.Animación: Instrucciones de instalación y configuración de AFF A900
video::4c222e90-864b-4435-9405-adf200112f3e[panopto]

NOTE: El ASA A900 utiliza el mismo procedimiento de instalación que el sistema AFF A900.



== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]