---
permalink: asa900/maintain-overview.html 
sidebar: sidebar 
keywords: asa A900 maintenance, maintenance, repairing asa A900, repairing asa A900, replace asa A900 components, replace asa A900 components 
summary: Mantenga el hardware de ASA A900 
---
= Mantener el hardware de ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenga el hardware de su sistema de almacenamiento ASA A900 para garantizar confiabilidad a largo plazo y un rendimiento óptimo. Realice tareas de mantenimiento periódicas, como la sustitución de componentes defectuosos, para evitar tiempos de inactividad y la pérdida de datos.

Los procedimientos de mantenimiento asumen que el sistema de almacenamiento ASA A900 ya se ha implementado como un nodo de almacenamiento en el entorno ONTAP .



== Componentes del sistema

Para el sistema de almacenamiento ASA A900, puede realizar procedimientos de mantenimiento en los componentes siguientes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Medios de arranque: recuperación automatizada"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar.  Durante la recuperación automatizada, el sistema recupera la imagen de arranque del nodo asociado y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen en el medio de arranque de reemplazo. El proceso de recuperación automática del medio de arranque solo es compatible con ONTAP 9.17.1 y versiones posteriores. Si su sistema de almacenamiento ejecuta una versión anterior de ONTAP, utilice el link:bootmedia-replace-workflow.html["procedimiento de recuperación de arranque manual"] .



 a| 
link:bootmedia-replace-workflow.html["Medios de arranque: recuperación manual"]
 a| 
El medio de arranque almacena un conjunto primario y secundario de archivos de imagen ONTAP que el sistema de almacenamiento utiliza para arrancar. Durante la recuperación manual, inicia el sistema de almacenamiento desde una unidad USB y restaura manualmente la imagen y la configuración del sistema de archivos.  Si su sistema de almacenamiento ejecuta ONTAP 9.17.1 y posterior, utilice ellink:bootmedia-replace-workflow-bmr.html["procedimiento de recuperación de arranque automatizado"] .



 a| 
link:chassis_replace_overview.html["Chasis"]
 a| 
El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



 a| 
link:controller_replace_overview.html["Controladora"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



 a| 
link:dimm_replace.html["DIMM"]
 a| 
Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM"]
 a| 
El DCPM (módulo de alimentación del controlador de separación) contiene la batería NVRAM11.



 a| 
link:fan_swap_out.html["Ventilador"]
 a| 
El ventilador enfría el controlador.



 a| 
link:pci_cards_and_risers_replace.html["Módulo de I/O."]
 a| 
El módulo de E/S (módulo de entrada/salida) es un componente de hardware que actúa como intermediario entre el controlador y varios dispositivos o sistemas que necesitan intercambiar datos con el controlador.



 a| 
link:led_module_replace.html["LED USB"]
 a| 
El módulo USB LED proporciona conectividad a los puertos de la consola y al estado del sistema.



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
El módulo NVRAM (memoria de acceso aleatorio no volátil) permite que el controlador retenga datos durante los ciclos de encendido o reinicios del sistema, mientras que el DIMM NVRAM mantiene la configuración de la NVRAM .



 a| 
link:power_supply_swap_out.html["Suministro de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una controladora.



 a| 
link:rtc_battery_replace.html["Batería del reloj en tiempo real"]
 a| 
Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.

|===