---
permalink: asa900/overview.html 
sidebar: sidebar 
keywords: ASA A900 specifications, ASA A900 specs, NetApp ASA A900, ASA A900 hardware 
summary: Especificaciones clave del sistema de almacenamiento ASA A900 
---
= Especificaciones clave del ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el ASA A900.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del ASA A900 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del ASA A900

Configuración de la plataforma: ASA A900, par HA de chasis único

Capacidad bruta máxima: 14,6880 PB

Memoria: 2048.0000 GB

Factor de forma: chasis 8U con 2 controladores HA

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 20

Versión mínima de ONTAP : ONTAP 9.13.1



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS |  |  |  


| SAN | 6 | 88,1 PB / 78,3 PiB | 12288 GB 


| Par HA |  | 14,7 PB / 13,0 PiB | 2048,0000 
|===


=== IO



==== E/S integrada

No hay datos de E/S integrados.



==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 32 


| Ethernet de 25 Gbps | 64 


| Ethernet de 10 Gbps | 64 


| FC 32 Gbps | 64 


| NVMe/FC 32 Gbps | 64 


|  | 0 


| SAS de 12 Gbps | 64 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 6 


| USB de 12 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

FC; iSCSI; NVMe/FC; NVMe/TCP;



=== Especificaciones del entorno del sistema

* Potencia típica: 8004 BTU/h
* Potencia en el peor de los casos: 9937 BTU/h
* Peso: 220,5 lbbr/100,0 kg
* Altura: 8U
* Ancho: compatible con rack IEC de 19” (17,7” 45,0 cm)
* Profundidad: 28,8” (36,8” con soporte para gestión de cables)
* Temperatura/altitud/humedad de funcionamiento: 10 °C a 35 °Cbr/50 °F a br/95 °F) abr/= 3048mbr/= 10000 pies) de elevación; 8 % a 80 %br/humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 7,4; br/Presión sonora (LpAm) (posiciones de transeúntes): 65,0 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores redundantes intercambiables en caliente; Fuentes de alimentación redundantes intercambiables en caliente; Administración en banda de SAS a través de conexiones SAS; [//] 2025-10-15 ontap-systems-internal/issues/1357
