---
permalink: a150/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Tú reemplazas un chasis defectuoso por un chasis nuevo del mismo modelo que el chasis defectuoso. 
---
= Revisa los requisitos antes de sustituir el chasis de tu sistema AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF A150, asegúrate de cumplir con los requisitos necesarios para que la sustitución sea exitosa. Esto incluye verificar que todos los demás componentes del sistema funcionen correctamente y entender que el procedimiento es disruptivo y requiere apagar ambos controladores.

Para sustituir el chasis, debe mover las fuentes de alimentación, las unidades de disco duro y el módulo o los módulos de la controladora del chasis dañado al nuevo chasis, y cambiar el chasis dañado del bastidor del equipo o del armario del sistema por el nuevo chasis del mismo modelo que el chasis dañado.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover todas las unidades y módulos o módulos de controladora al nuevo chasis, y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos controladoras, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

