---
permalink: a150/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague los controladores - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apague o retome el controlador dañado siguiendo el procedimiento adecuado para su configuración.



== Opción 1: Mayoría de las configuraciones

Este procedimiento es para sistemas con configuraciones de dos nodos. Para obtener más información sobre el cierre correcto al realizar el mantenimiento de un cluster, consulte https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Apagar y encender sin problemas la Guía de resolución del sistema de almacenamiento: Base de conocimientos de NetApp"].

.Antes de empezar
* Asegúrese de que dispone de los permisos y credenciales necesarios:
+
** Credenciales de administrador local para ONTAP.
** Accesibilidad de BMC para cada controlador.


* Asegúrese de que dispone de las herramientas y el equipo necesarios para la sustitución.


.Pasos
. Inicie sesión en el clúster a través de SSH o inicie sesión desde cualquier nodo del clúster mediante un cable de consola local y un equipo portátil/consola.
. Detenga el acceso de todos los clientes/host a los datos del sistema de NetApp.
. Suspender trabajos de backup externo.
. Si AutoSupport está habilitado, suprima la creación de casos e indique cuánto tiempo espera que el sistema esté sin conexión:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identifique la dirección SP/BMC de todos los nodos del clúster:
+
`system service-processor show -node * -fields address`

. Salga del shell de cluster:
+
`exit`

. Inicia sesión en el SP/BMC de cada controlador usando la dirección IP identificada en el paso anterior:
+
** Si inicias sesión desde el BMC por SSH, conéctate usando la dirección SP/BMC (por ejemplo, `ssh admin@<SP/BMC_address>`), luego ingresa el comando `system console` y autentícate.
** Si estás usando una consola local o un portátil conectado directamente al controlador, inicia sesión con las mismas credenciales de administrador del clúster.


. Detenga los dos nodos ubicados en el chasis dañado:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para los clústeres que utilizan SnapMirror síncrono en modo StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Ingrese *y* para cada controlador en el clúster cuando vea:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Espere a que cada controladora se detenga y muestre el aviso del CARGADOR.




== Opción 2: La controladora está en una configuración MetroCluster


NOTE: No use este procedimiento si el sistema está en una configuración de MetroCluster de dos nodos.

Toma el control y detén el controlador dañado para que el controlador sano continúe sirviendo datos desde el almacenamiento del controlador dañado. Para hacer esto, suprimes la creación automática de casos en AutoSupport, deshabilitas la devolución automática y llevas el controlador dañado al prompt LOADER. El prompt LOADER es el estado detenido seguro desde el cual puedes reemplazar la FRU.

* Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].
* Si tiene una configuración MetroCluster, debe haber confirmado que el estado de configuración de MetroCluster está configurado y que los nodos están en estado normal y habilitado (`metrocluster node show`).


.Pasos
. Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
Esto evita que se abran casos de soporte automático durante tu ventana de mantenimiento planificada. La duración máxima de la supresión es de 72 horas. Si tu mantenimiento termina antes de tiempo, puedes volver a habilitar la creación de casos invocando un mensaje AutoSupport con `MAINT=END`. Para más información, consulta https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Cómo suprimir la creación automática de casos durante las ventanas de mantenimiento programadas"^].

+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas:

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Deshabilite la devolución automática de la consola de la controladora en buen estado: `storage failover modify –node local -auto-giveback false`
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado está mostrando... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya al paso siguiente.



 a| 
Esperando devolución...
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode _impaired_node_name_`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===

