---
permalink: a150/install-quick-guide.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, quick, guide, graphic, instructions, install, rack, cable 
summary: Esta guía da instrucciones gráficas para una instalación típica de su sistema desde el montaje en rack y el cableado hasta la puesta en marcha inicial del sistema. 
---
= Guía rápida - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*Advertencia:* Si su sistema se instala con ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 o ONTAP 9.15,1 - 9.15.1P2 y su sistema contiene 10 o más unidades de estado sólido internas, debe tomar medidas adicionales para preparar el sistema para la instalación. Consulte Problema  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173: ADP no deja una partición raíz de repuesto en un AFF A150 con 10 o más unidades internas"^].

Las instrucciones de instalación y configuración proporcionan instrucciones gráficas para una instalación típica de su sistema, desde el bastidor y el cableado hasta la puesta en marcha inicial del sistema. Utilice esta guía si está familiarizado con la instalación de sistemas de NetApp.

Utilice el enlace: link:../media/PDF/Jan_2024_Rev2_AFFA150_ISI_IEOPS-1480.pdf["Instrucciones de instalación y configuración del sistema AFF A150"^]


NOTE: El ASA A150 utiliza el mismo procedimiento de instalación que el sistema AFF A150.
