---
permalink: a150/install-setup.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, install, setup, initial configuration 
summary: Instale y configure el sistema. 
---
= Empezar desde aquí: Elija la experiencia de instalación y configuración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la mayoría de las configuraciones, puede elegir entre diferentes formatos de contenido.

* link:../a150/install-quick-guide.html["Pasos rápidos"]
+
Un PDF imprimible de instrucciones paso a paso con enlaces directos a contenido adicional.

* link:../a150/install-videos.html["Pasos de vídeo"]
+
Instrucciones paso a paso de vídeo.

* link:../a150/install-detailed-guide.html["Pasos detallados"]
+
Instrucciones paso a paso en línea con enlaces directos a contenido adicional.



Si el sistema está en una configuración IP de MetroCluster, consulte https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Instale la configuración IP de MetroCluster"] instrucciones.

*Advertencia:* Si su sistema se instala con ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 o ONTAP 9.15,1 - 9.15.1P2 y su sistema contiene 10 o más unidades de estado sólido internas, debe tomar medidas adicionales para preparar el sistema para la instalación. Consulte Problema  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173: ADP no deja una partición raíz de repuesto en un AFF A150 con 10 o más unidades internas"^].
