---
permalink: a150/install-videos.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, aff a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Videos - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.

Si dispone de una configuración MetroCluster, utilice el contenido de instalación de MetroCluster.

https://["Documentación de MetroCluster"^]



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

.Animación: Instalación y configuración de un AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]


== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]