---
permalink: a150/maintain-overview.html 
sidebar: sidebar 
keywords: aff A150 maintenance, maintenance, repairing a150, repairing aff a150, replace aff a150 components, replace aff a150 components 
summary: Mantén el hardware del AFF A150 
---
= Infórmate sobre el mantenimiento de un sistema de almacenamiento AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Realiza el mantenimiento del hardware de tu sistema de almacenamiento AFF A150 para asegurar la fiabilidad a largo plazo y un rendimiento óptimo. Haz tareas de mantenimiento periódicas, como reemplazar componentes defectuosos, para ayudar a evitar tiempos de inactividad y la pérdida de datos.



[[boot-media]]
== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



[[chassis]]
== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



[[controller]]
== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



[[dimm]]
== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



[[drive]]
== Unidad

Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



[[nvram-battery]]
== Batería NVRAM

Se incluye una batería con una controladora y conserva los datos almacenados en caché si falla la alimentación de CA.



[[power-supply]]
== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



[[real-time-clock-battery]]
== Batería de reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
