---
permalink: a150/overview.html 
sidebar: sidebar 
keywords: AFF A150 specifications, AFF A150 specs, NetApp AFF A150, AFF A150 hardware 
summary: Especificaciones clave del sistema de almacenamiento AFF A150 
---
= Especificaciones clave del AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el AFF A150.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del AFF A150 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del AFF A150

Configuración de la plataforma: AFF A150 UTA2, par HA de chasis único

Capacidad bruta máxima: 0,5472 PB

Memoria: 64.0000 GB

Factor de forma: chasis 2U con 2 controladores HA y 24 ranuras para unidades

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe:

Versión mínima de ONTAP : ONTAP 9.10.1P12



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 12 | 6,6 PB / 5,8 PiB | 768 GB 


| SAN | 6 | 3,3 PB / 2,9 PiB | 384 GB 


| Par HA |  | 0,5 PB / 0,5 PiB | 64,0000 
|===


=== IO



==== E/S integrada

|===


| Protocolo | Puertos 


| Ethernet de 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS de 12 Gbps | 4 
|===


==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS de 12 Gbps | 4 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB de 12 Mbps | 2 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; FCoE; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 1209 BTU/h
* Potencia en el peor de los casos: 1676 BTU/h
* Peso: 60,8 lb<br/>27,6 kg
* Altura: 2U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad: 19,0” (24,1” con soporte para gestión de cables)
* Temperatura/altitud/humedad de funcionamiento: 5 °C a 45 °C<br/>41 °F a <br/>113 °F) a<br/>><= 3048 m<br/>><= 10 000 pies) de altitud; 8 % a 90 %<br/>de humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 6,9; Presión sonora (LpAm) (posición de transeúntes): 51,0 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores redundantes intercambiables en caliente; Fuentes de alimentación redundantes intercambiables en caliente; Administración en banda de SAS a través de conexiones SAS; [//] 2025-10-15 ontap-systems-internal/issues/1357
