---
permalink: asa-c400/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: asa-c400, replace the boot media 
summary: Antes de reemplazar el medio de arranque en su sistema ASA C400, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso. Esto incluye asegurarse de tener una unidad flash USB con la capacidad de almacenamiento adecuada y verificar que tenga el dispositivo de arranque de reemplazo correcto. 
---
= Requisitos para la recuperación manual del medio de arranque - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reemplazar el medio de arranque en su sistema ASA C400, asegúrese de cumplir con los requisitos necesarios para un reemplazo exitoso. Esto incluye asegurarse de tener una unidad flash USB con la capacidad de almacenamiento adecuada y verificar que tenga el dispositivo de arranque de reemplazo correcto.

Si su sistema de almacenamiento ejecuta ONTAP 9.17.1 o posterior, utilice ellink:bootmedia-replace-workflow-bmr.html["procedimiento de recuperación de arranque automatizado"] .  Si su sistema está ejecutando una versión anterior de ONTAP, debe utilizar el proceso de recuperación de arranque manual.

.El futuro
Después de revisar los requisitos para reemplazar el soporte de arranque, debe link:bootmedia-encryption-preshutdown-checks.html["compruebe la compatibilidad y el estado de la clave de cifrado en el soporte de arranque"].
