---
permalink: asa-r2-70-90/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, overview, the boot media 
summary: La recuperación de soportes de arranque para su sistema de almacenamiento ASA A70 o ASA A90 utiliza la imagen de arranque del nodo del partner y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen de arranque en el soporte de arranque de reemplazo. 
---
= Descripción general de la recuperación de medios de arranque - ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La recuperación de soportes de arranque para su sistema de almacenamiento ASA A70 o ASA A90 utiliza la imagen de arranque del nodo del partner y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen de arranque en el soporte de arranque de reemplazo.

Cuando encuentre mensajes de error de arranque similares a los que se muestran a continuación, debe sustituir el soporte de arranque y restaurar la imagen ONTAP desde el nodo asociado.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....