---
permalink: asa-r2-70-90/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, pre-shutdown checks for onboard encryption keys 
summary: Antes de apagar la controladora con deterioro y comprobar el estado de las claves de cifrado integradas, debe comprobar el estado de la controladora con deterioro, deshabilitar la devolución automática del control y comprobar la versión de ONTAP que el sistema está ejecutando. 
---
= Compruebe las claves de cifrado integradas: ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de apagar la controladora con deterioro y comprobar el estado de las claves de cifrado integradas, debe comprobar el estado de la controladora con deterioro, deshabilitar la devolución automática del control y comprobar la versión de ONTAP que se está ejecutando.

Si tiene un clúster con más de dos nodos, debe estar en quórum. Si el clúster no tiene quórum o si una controladora en buen estado muestra falso según su condición, debe corregir el problema antes de apagar la controladora dañada; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].



== Compruebe NVE o NSE en los sistemas

Antes de apagar la controladora deteriorada, debe verificar si el sistema tiene el administrador de claves de seguridad habilitado o discos cifrados.



== Verifique la configuración del gestor de claves de seguridad

.Pasos
. Determine si Key Manager está activo con el comando _security key-manager keystore show_. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap-cli/security-key-manager-keystore-show.html["Almacén de claves de seguridad gestor de claves mostrar página DEL COMANDO MAN"^]
+

NOTE: Es posible que tenga tipos de gestor de claves adicionales. Los tipos son `KMIP` `AKV`, y `GCP`. El proceso de confirmación de estos tipos es el mismo que el de confirmación `external` o `onboard` el de los tipos de gestor de claves.

+
** Si no se muestra ninguna salida, vaya a link:bootmedia-shutdown.html["apague el controlador dañado"] para apagar el nodo defectuoso.
** Si el comando muestra resultados, el sistema tiene `security key-manager` activo y necesita mostrar el `Key Manager` tipo y el estado.


. Visualice la información de los activos `Key Manager` mediante el comando _security key-manager key query_.
+
** Si aparece el `Key Manager` tipo `external` y aparece la `Restored` columna `true`, es seguro apagar el controlador defectuoso.
** Si aparece el `Key Manager` tipo `onboard` y aparece la `Restored` columna `true`, deberá realizar algunos pasos adicionales.
** Si aparece el `Key Manager` tipo `external` y la `Restored` columna muestra cualquier otra cosa que no sea `true`, deberá realizar algunos pasos adicionales.
** Si aparece el `Key Manager` tipo `onboard` y la `Restored` columna muestra cualquier otra cosa que no sea `true`, deberá realizar algunos pasos adicionales.


. Si aparece el `Key Manager` tipo `onboard` y aparece la `Restored` columna `true`, realice una copia de seguridad manual de la información de OKM:
+
.. Introduzca `y` cuando se le solicite continuar: `set -priv advanced`
.. Introduzca el comando para mostrar la información de gestión de claves: _Security key-manager onboard show-backup_
.. Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
.. Puede apagar el controlador defectuoso de forma segura.


. Si aparece el `Key Manager` tipo `onboard` y la `Restored` columna muestra cualquier cosa que no sea `true`:
+
.. Introduzca el comando sync del gestor de claves de seguridad incorporado: _Security key-manager onboard sync_
+

NOTE: Introduzca la clave de acceso 32 caracteres alfanumérica integrada en el símbolo del sistema. Si no se puede proporcionar la contraseña, comuníquese con el soporte de NetApp. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. Compruebe que `Restored` se muestra la columna `true` para todas las claves de autenticación: `security key-manager key query`
.. Compruebe que se muestra el `Key Manager` tipo `onboard`y, a continuación, realice una copia de seguridad manual de la información de OKM.
.. Introduzca el comando para mostrar la información de backup de gestión de claves: _Security key-manager onboard show-backup_
.. Copie el contenido de la información de la copia de seguridad en un archivo o archivo de registro separados. Lo necesitará en escenarios de desastres donde podría necesitar una recuperación manual de OKM.
.. Puede apagar el controlador de forma segura.


. Si aparece el `Key Manager` tipo `external` y la `Restored` columna muestra cualquier cosa que no sea `true`:
+
.. Restaure las claves de autenticación de gestión de claves externas a todos los nodos del clúster: `security key-manager external restore`
+
Si el comando falla, póngase en contacto con el soporte de NetApp en http://mysupport.netapp.com/["mysupport.netapp.com"^].

.. Compruebe que la `Restored` columna se muestra `true` para todas las claves de autenticación: _Security key-manager key query_
.. Puede apagar el controlador defectuoso de forma segura.



