---
permalink: asa-r2-70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, replace the chassis 
summary: Se sustituye un chasis deficiente por el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Requisitos de sustitución del chasis: ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise los requisitos para reemplazar un chasis defectuoso.

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.

Antes de sustituir el chasis, asegúrese de revisar los siguientes requisitos.

* Asegúrese de que todos los demás componentes del sistema funcionan correctamente; de lo contrario, póngase en contacto con http://mysupport.netapp.com/["Sitio de soporte de NetApp"^] para obtener ayuda.
* Obtenga credenciales de administrador local para ONTAP si no las tiene.
* Asegúrese de que dispone de las herramientas y el equipo necesarios para la sustitución.
* Puede usar el procedimiento de reemplazo de chasis con todas las versiones de ONTAP compatibles con el sistema.
* El procedimiento de sustitución del chasis se escribe suponiendo que va a mover el panel frontal, las unidades NVMe y los módulos de controladora al nuevo chasis, y que el chasis de reemplazo es un nuevo componente de NetApp.
* *El procedimiento de reemplazo del chasis es disruptivo.* En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.


.El futuro
Después de revisar los requisitos de reemplazo del chasis, debe link:chassis-replace-prepare.html["prepare el reemplazo del chasis"].
