---
permalink: asa-r2-70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, prepare to replace the chassis 
summary: Prepárese para sustituir el chasis deficiente en su sistema ASA A70 o ASA A90 identificando el chasis dañado, verificando los componentes de reemplazo y etiquetando los cables y los módulos de la controladora. 
---
= Prepárese para reemplazar el chasis: ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepárese para reemplazar el chasis dañado en su sistema ASA A70 o ASA A90 identificando el chasis dañado, verificando los componentes de reemplazo y etiquetando los cables y módulos de controlador.

.Pasos
. Conéctese al puerto de la consola de serie para la interfaz con el sistema y supervisarlo.
. Enciende el LED de ubicación del controlador:
+
.. Utilice el `system controller location-led show` comando para mostrar el estado actual del LED de ubicación.
.. Encienda el LED de ubicación:
+
`system controller location-led modify -node _node1_ -state on`

+
El LED de ubicación permanece encendido durante 30 minutos.



. Antes de abrir el envase, examine la etiqueta del envase y verifique lo siguiente:
+
** Número de pieza del componente
** Descripción de la pieza
** Cantidad en la caja


. Retire el contenido del embalaje y guarde el embalaje para devolver el componente defectuoso a NetApp.
. Etiquete todos los cables conectados al sistema de almacenamiento.  Esto garantiza un recableado adecuado más adelante en este procedimiento.
. Conéctate con la tierra si aún no lo estás.


.El futuro
Tras prepararse para sustituir el chasis ASA A70 o ASA A90,link:chassis-replace-shutdown.html["apague las controladoras"] .
