---
permalink: asa-r2-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Para restaurar el sistema a su funcionamiento completo, debe verificar los LIF, comprobar el estado del clúster y devolver la parte con error a NetApp. Póngase en contacto con el servicio de asistencia técnica en https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"], 888-463-8277 (Norteamérica), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacífico) si necesita el número RMA o ayuda adicional con el procedimiento de sustitución.' 
---
= Sustitución de controladora completa: ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para completar el reemplazo de la controladora de su sistema ASA A70 o ASA A90, primero restaure la configuración de cifrado de almacenamiento de NetApp (si es necesario). A continuación, confirme que las interfaces lógicas (LIF) informan a sus puertos principales y realizan una comprobación del estado del clúster. Finalmente, devuelva la pieza defectuosa a NetApp.



== Paso 1: Verifique las LIF y compruebe el estado del clúster

Antes de devolver el nodo de sustitución al servicio, compruebe que las interfaces lógicas estén en sus puertos principales, compruebe el estado del clúster y restablezca la devolución automática.

.Pasos
. Verifique que las interfaces lógicas estén reportando a su servidor local y puertos:
+
`network interface show -is-home false`

+
Si alguna interfaz lógica aparece como falsa, rediríjala a sus puertos originales:

+
`network interface revert -vserver * -lif *`

. Comprueba el estado de tu clúster.  Ver el https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Cómo realizar una comprobación del estado de un clúster con un script en ONTAP"^] Artículo de la base de conocimientos.
. Si la devolución automática está desactivada, vuelva a habilitarla:
+
`storage failover modify -node local -auto-giveback true`





== Paso 2: Devuelve la parte fallida a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
