---
permalink: asa-r2-70-90/drive-replace.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, replace the drives 
summary: Reemplace una unidad en el sistema ASA A70 o ASA A90 cuando se produzca un error en una unidad o requiera una actualización. Este proceso implica identificar la unidad defectuosa, extraerla de forma segura e instalar una nueva unidad para garantizar un acceso continuo a los datos y el rendimiento del sistema. 
---
= Sustituya la unidad SSD -ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reemplace una unidad en el sistema ASA A70 o ASA A90 cuando se produzca un error en una unidad o requiera una actualización. Este proceso implica identificar la unidad defectuosa, extraerla de forma segura e instalar una nueva unidad para garantizar un acceso continuo a los datos y el rendimiento del sistema.

Puede sustituir una unidad SSD con errores sin interrupciones mientras hay operaciones de I/o en curso.

Cuando falla una unidad, la plataforma registra un mensaje de advertencia en la consola del sistema que indica qué unidad ha fallado. Además, tanto el LED de fallo del panel de visualización del operador como el LED de fallo de la unidad averiada se iluminan.

.Antes de empezar
* Siga las prácticas recomendadas e instale la versión actual del paquete de cualificación de disco (DQP) antes de sustituir una unidad.
* Identifique la unidad de disco que ha fallado ejecutando el `storage disk show -broken` desde la consola del sistema.
+
La unidad con error se muestra en la lista de unidades con errores. Si no lo hace, debe esperar y volver a ejecutar el comando.

+

NOTE: La unidad puede tardar hasta varias horas en aparecer en la lista de unidades con error.

* Determine si la autenticación SED está habilitada.
+
La forma en que reemplace el disco depende de cómo se utilice la unidad de disco. Si la autenticación SED está activada, debe utilizar las instrucciones de sustitución de SED en https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["Guía completa de cifrado de NetApp para ONTAP 9"]. Estas instrucciones describen los pasos adicionales que debe realizar antes y después de reemplazar una SED.

* Asegúrese de que su plataforma admite la unidad de sustitución. Consulte https://hwu.netapp.com["Hardware Universe de NetApp"].
* Asegúrese de que todos los demás componentes del sistema funcionan correctamente; de lo contrario, debe ponerse en contacto con el soporte técnico.


.Acerca de esta tarea
El firmware de la unidad se actualiza automáticamente (sin interrupciones) en las unidades nuevas con versiones de firmware no actuales.

Al sustituir varias unidades de disco, debe esperar 70 segundos entre la extracción de cada unidad de disco con errores y la inserción de la unidad de disco de reemplazo para que el sistema de almacenamiento pueda reconocer la existencia de cada disco nuevo.

.Pasos
. Puesta a tierra apropiadamente usted mismo.
. Identifique físicamente la unidad con error.
+
Cuando falla una unidad, el sistema registra un mensaje de advertencia en la consola del sistema que indica qué unidad falló. Además, el LED de atención (ámbar) del panel de la pantalla del operador de la bandeja de unidades y la unidad con error se iluminan.

+

NOTE: El LED de actividad (verde) en una unidad con error puede estar iluminado (fijo), lo que indica que la unidad tiene alimentación, pero no debe parpadear, lo que indica actividad de I/O. Una unidad con error no tiene actividad de I/O.

. Quite la unidad con error:
+
.. Pulse el botón de liberación de la cara de la unidad para abrir la palanca de la leva.
.. Deslice la unidad para sacarla de la estantería con el mango de la leva y apoye la unidad con la otra mano.


. Espere al menos 70 segundos antes de insertar la unidad de reemplazo.
+
Esto permite al sistema reconocer que se ha quitado una unidad.

. Inserte la unidad de reemplazo:
+
.. Con la palanca de leva en posición abierta, utilice ambas manos para insertar el mando de sustitución.
.. Presione hasta que la unidad se detenga.
.. Cierre el asa de la leva para que la unidad quede completamente asentada en el plano medio y el asa encaje en su lugar.
+
Asegúrese de cerrar el mango de leva lentamente para que quede alineado correctamente con la cara de la transmisión.



. Verifique que el LED de actividad de la unidad (verde) esté iluminado.
+
Cuando el LED de actividad de la unidad está sólido, significa que la unidad tiene alimentación. Cuando el LED de actividad de la unidad parpadea, significa que la unidad tiene alimentación y I/o está en curso. Si el firmware de la unidad se actualiza automáticamente, el LED parpadea.

. Si desea reemplazar otra unidad, repita los pasos 2 a 6.
. Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit.
+
Póngase en contacto con el soporte técnico en https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"], 888-463-8277 (Norteamérica), 00-800-44-638277 (Europa), o +800-800-80-800 (Asia/Pacífico) si necesita el número RMA o ayuda adicional con el procedimiento de reemplazo.


