---
permalink: asa-r2-70-90/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90,  ASA A70, replace io module 
summary: Los sistemas ASA A70 y ASA A90 ofrecen flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido. 
---
= Descripción general de la adición y sustitución de un módulo de E/S - ASA A70 y ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas ASA A70 y ASA A90 ofrecen flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

Puede sustituir un módulo de I/O con fallo en el sistema de almacenamiento ASA A70 o ASA A90 por el mismo tipo de módulo de I/O, o por otro tipo de módulo de I/O diferente. También puede agregar un módulo de E/S a un sistema con ranuras vacías.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
La adición de módulos adicionales puede mejorar la redundancia, lo que ayuda a garantizar que el sistema siga funcionando incluso si falla un módulo.

* link:io-module-hotswap.html["Intercambia en caliente un módulo de E/S"]
+
Puedes intercambiar en caliente ciertos módulos de E/S por un módulo de E/S equivalente para restaurar el sistema de almacenamiento a su estado de funcionamiento óptimo. El intercambio en caliente se hace sin tener que realizar una toma de control manual.

+
Para usar este procedimiento, tu sistema de almacenamiento debe estar ejecutando ONTAP 9.18.1.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de E/S que falla puede restaurar el sistema a su estado operativo óptimo.



.Numeración de ranuras de E/S.
Las ranuras de I/O de las controladoras ASA A70 y ASA A90 están numeradas del 1 al 11, como se muestra en la ilustración siguiente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeración de ranuras en controladoras ASA A70 y AFF A90]
