---
permalink: c800/overview.html 
sidebar: sidebar 
keywords: AFF C800 specifications, AFF C800 specs, NetApp AFF C800, AFF C800 hardware 
summary: Especificaciones clave del sistema de almacenamiento AFF C800 
---
= Especificaciones clave del AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las siguientes son especificaciones seleccionadas para el AFF C800.  Visita https://hwu.netapp.com["Hardware Universe de NetApp"^] (HWU) para obtener una lista completa de las especificaciones del AFF C800 .  Esta página es un reflejo de un único par de alta disponibilidad.



=== Especificaciones clave del AFF C800

Configuración de la plataforma: AFF C800, par HA de chasis único

Capacidad bruta máxima: 7,3680 PB

Memoria: 1280.0000 GB

Factor de forma: chasis 4U con 2 controladores HA y 48 ranuras de unidad

Versión de ONTAP : b_startONTAP: 9.16.1P2b_end

Ranuras de expansión PCIe: 10

Versión mínima de ONTAP : ONTAP 9.10.1P15



=== Máximos de escalamiento

|===


| Tipo | Pares HA | Capacidad bruta | Memoria máxima 


| NAS | 12 | 88,4 PB / 78,5 PiB | 15360 GB 


| SAN | 6 | 44,2 PB / 39,3 PiB | 7680 GB 


| Par HA |  | 7,4 PB / 6,5 PiB | 1280,0000 
|===


=== IO



==== E/S integrada

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 4 
|===


==== E/S total

|===


| Protocolo | Puertos 


| Ethernet de 100 Gbps | 20 


| Ethernet de 25 Gbps | 16 


| Ethernet de 10 Gbps | 32 


| FC 32 Gbps | 32 


| NVMe/FC 32 Gbps | 32 


|  | 0 


|  | 0 
|===


==== Puertos de gestión

|===


| Protocolo | Puertos 


| Ethernet de 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB de 12 Mbps | 4 
|===


=== Redes de almacenamiento compatibles

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificaciones del entorno del sistema

* Potencia típica: 6626 BTU/h
* Potencia en el peor de los casos: 8417 BTU/h
* Peso: 132,5 lbbr/60,1 kg
* Altura: 4U
* Ancho: compatible con rack IEC de 19” (17,6” 44,7 cm)
* Profundidad: 34,5” (36,6” con soporte para gestión de cables)
* Temperatura/altitud/humedad de funcionamiento: 5 °C a 40 °Cbr/41 °F a br/104 °F) abr/= 3048mbr/= 10000 pies) de elevación; 8 % a 90 %br/humedad relativa, sin condensación
* Temperatura/humedad sin funcionamiento: -40 °C a 70 °C (-40 °F a 158 °F) hasta 12 192 m (40 000 pies)<br/>10 % a 95 % de humedad relativa, sin condensación, en el contenedor original
* Ruido acústico: Potencia sonora declarada (LwAd): 8,0; br/Presión sonora (LpAm) (posiciones de transeúntes): 62,8 dB




=== Cumplimiento

* Certificaciones EMC/EMI: AMCA, FCC, ICES, KC, Marruecos, VCCI
* Certificaciones seguridad: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificaciones Seguridad/EMC/EMI: EAC, UKRSEPRO
* Certificaciones Seguridad/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Estándares EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Clase A, ICES-003, KS C 9832, KS C 9835
* Normas de seguridad: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n.º 60950-1, CAN/CSA C22.2 n.º 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidad

Controlador de administración de placa base (BMC) basado en Ethernet e interfaz de administración ONTAP ; Controladores intercambiables en caliente redundantes; Fuentes de alimentación intercambiables en caliente redundantes;
