---
permalink: c800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c800, verify and set HA state, complete the replacement process 
summary: Debe comprobar el estado HA del chasis y devolver la pieza fallida a NetApp, tal y como se describe en las instrucciones de RMA que se suministran con el kit. 
---
= Completar el proceso de restauración y sustitución - AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reinicie los controladores, verifique el estado del sistema y devuelva la pieza defectuosa a NetApp para completar el paso final del procedimiento de reemplazo del chasis AFF C800 .



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

.Pasos
. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis: `ha-config modify chassis _HA-state_`
+
El valor de la condición de alta disponibilidad puede ser uno de los siguientes:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Confirme que el ajuste ha cambiado: `ha-config show`


. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.
. Vuelva a instalar el bisel en la parte delantera del sistema.




== Paso 2: Verifique el estado del sistema de almacenamiento

Una vez finalizada la devolución del controlador, verifique el estado del sistema mediante https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Solucione cualquier problema detectado.



== Paso 3: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
