---
permalink: c800/install-videos.html 
sidebar: sidebar 
keywords: aff c800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.' 
---
= Videos - AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hay dos vídeos: Uno que muestra cómo montar en rack y cablear el sistema y otro que muestra un ejemplo del uso de la configuración guiada de System Manager para realizar la configuración inicial del sistema.

Si dispone de una configuración MetroCluster, utilice el contenido de instalación de MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentación de MetroCluster"^]



== Vídeo uno de dos: Instalación de hardware y cableado

En el siguiente vídeo se muestra cómo instalar y cablear el sistema nuevo.

.Animación: Instalación y configuración de un AFF C800
video::db9f506c-b08e-4b66-b781-afc40187b639[panopto]


== Vídeo dos de dos: Realizar una configuración de software integral

En el siguiente vídeo se muestra la configuración de software integral para sistemas que ejecutan ONTAP 9.2 y versiones posteriores.

video::WAE0afWhj1c?[youtube]