---
permalink: fas2600/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: fas2600, shut down the controller, manual, manual boot recovery 
summary: Apague el controlador dañado en un sistema FAS2600 después de completar las comprobaciones de cifrado. El sistema FAS2600 solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque. 
---
= Apague la controladora afectada: FAS2600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apague el controlador dañado en un sistema FAS2600 después de completar las comprobaciones de cifrado. Este procedimiento incluye llevar el controlador al indicador LOADER, capturar las variables ambientales de arranque para referencia y preparar el controlador para el reemplazo del medio de arranque.

El sistema FAS2600 solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque.

Después de completar las tareas de NVE o NSE, deberá completar el apagado de la controladora dañada.

.Pasos
. Lleve la controladora dañada al aviso DEL CARGADOR:
+
[cols="1,2"]
|===
| Si el controlador dañado muestra... | Realice lo siguiente... 


 a| 
El aviso del CARGADOR
 a| 
Vaya a Quitar módulo de controlador.



 a| 
`Waiting for giveback...`
 a| 
Pulse Ctrl-C y, a continuación, responda `y` cuando se le solicite.



 a| 
Solicitud del sistema o solicitud de contraseña (introduzca la contraseña del sistema)
 a| 
Retome o detenga el controlador dañado del controlador en buen estado: `storage failover takeover -ofnode impaired_node_name`

Cuando el controlador dañado muestre esperando devolución..., pulse Ctrl-C y, a continuación, responda `y`.

|===
. Desde el aviso del CARGADOR, introduzca: `printenv` para capturar todas las variables ambientales de arranque. Guarde el resultado en el archivo de registro.
+

NOTE: Es posible que este comando no funcione si el dispositivo de inicio está dañado o no funciona.


