---
permalink: fas2600/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas2600, replace the chassis 
summary: Antes de sustituir el chasis de tu sistema FAS2600, revisa los requisitos para trasladar los componentes al chasis de recambio e instalarlo en el bastidor del equipo o en el armario del sistema. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema FAS2600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema FAS2600, revisa los requisitos para trasladar las fuentes de alimentación, los discos duros y el módulo o módulos controladores del chasis averiado al nuevo, y para intercambiar el chasis averiado en el bastidor o armario del sistema por uno nuevo del mismo modelo.

El resto de componentes del sistema deben funcionar correctamente. Si no es así, ponte en contacto con soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover todas las unidades y módulos o módulos de controladora al nuevo chasis, y que el chasis es un nuevo componente de NetApp.
* Este procedimiento provoca interrupciones. En un clúster de dos nodos, tienes una interrupción total del servicio, y en un clúster de varios nodos, tienes una interrupción parcial.


video::FcitUi3YEyI[youtube]