---
permalink: fas9000/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a700, fas9000, sysdiages, ha-config, switchback, chassis 
summary: Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. 
---
= Completar el proceso de restauración y sustitución: A700 y FAS9000 de AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe verificar el estado de alta disponibilidad del chasis, ejecutar diagnósticos y devolver la pieza con errores a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit.



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

Debe verificar el estado de alta disponibilidad del chasis y, si es necesario, actualizar el estado para que coincida con la configuración del sistema.

.Pasos
. En el modo de mantenimiento, desde cualquier módulo de controlador, muestre el estado de alta disponibilidad del módulo de controlador local y el chasis: `ha-config show`
+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema mostrado para el chasis no coincide con la configuración del sistema:
+
.. Establezca el estado de alta disponibilidad para el chasis: `ha-config modify chassis _HA-state_`
+
Valor para `HA-state` puede ser uno de los siguientes:

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Confirme que el ajuste ha cambiado: `ha-config show`


. Si aún no lo ha hecho, puede volver a obtener el resto de su sistema.
. Salir del modo de mantenimiento: `halt`
+
Aparece el aviso del CARGADOR.





== Paso 2: Ejecución de diagnósticos de nivel de sistema

Después de instalar un chasis nuevo, debe ejecutar el diagnóstico de interconexión.

Su sistema debe estar en el aviso DEL CARGADOR para iniciar los diagnósticos de nivel de sistema.

Todos los comandos de los procedimientos de diagnóstico se emiten desde el nodo en el que se sustituye el componente.

.Pasos
. Si el nodo que se va a mantener no se encuentra en el símbolo del sistema del CARGADOR, realice los siguientes pasos:
+
.. Seleccione la opción modo de mantenimiento en el menú que se muestra.
.. Después de que el nodo arranca en el modo de mantenimiento, detenga el nodo: `halt`
+
Tras emitir el comando, debe esperar hasta que el sistema se detenga en el símbolo del sistema del CARGADOR.

+

NOTE: Durante el proceso de arranque, puede responder de forma segura `y` para solicitar:



. Repita el paso anterior en el segundo nodo si está en una configuración de alta disponibilidad.
+

NOTE: Ambas controladoras deben estar en modo de mantenimiento para ejecutar la prueba de interconexión.

. En el aviso DEL CARGADOR, acceda a los controladores especiales diseñados específicamente para que los diagnósticos del sistema funcionen correctamente: `boot_diags`
+
Durante el proceso de arranque, puede responder de forma segura `y` A las indicaciones hasta que aparezca el indicador del modo de mantenimiento (*>).

. Habilite las pruebas de diagnóstico de interconexión desde el símbolo del sistema del modo de mantenimiento: `sldiag device modify -dev interconnect -sel enable`
+
Las pruebas de interconexión están deshabilitadas de forma predeterminada y deben habilitarse para ejecutarse por separado.

. Ejecute la prueba de diagnóstico de interconexión desde el símbolo del sistema del modo de mantenimiento: `sldiag device run -dev interconnect`
+
Solo debe ejecutar la prueba de interconexión desde una controladora.

. Verifique que no haya problemas de hardware como resultado de la sustitución del chasis: `sldiag device status -dev interconnect -long -state failed`
+
Los diagnósticos de nivel de sistema le devuelven al prompt si no hay errores de prueba o indican el estado completo de los errores resultantes de la prueba del componente.

. Proceda según el resultado del paso anterior.
+
[cols="1,2"]
|===
| Si el diagnóstico del sistema prueba... | Realice lo siguiente... 


 a| 
Se completaron sin fallos
 a| 
.. Borre los registros de estado: `sldiag device clearstatus`
.. Compruebe que se ha borrado el registro: `sldiag device status`
+
Se muestra la siguiente respuesta predeterminada:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Salga del modo de mantenimiento en ambas controladoras: `halt`
+
El sistema muestra el aviso del CARGADOR.

+

NOTE: Debe salir del modo de mantenimiento de ambas controladoras antes de continuar.

.. Introduzca el siguiente comando en ambas controladoras en el símbolo del sistema del CARGADOR: `bye`
.. Devolver al nodo a su funcionamiento normal:




 a| 
Con dos nodos en el clúster
 a| 
Emita los siguientes comandos: `node::> cluster ha modify -configured true`

`node::> storage failover modify -node node0 -enabled true`



 a| 
Con más de dos nodos en el clúster
 a| 
Emita este comando:``node::> storage failover modify -node node0 -enabled true``



 a| 
En una configuración MetroCluster de dos nodos
 a| 
Continúe con el próximo paso.

El procedimiento de conmutación de estado del MetroCluster se lleva a cabo en la siguiente tarea del proceso de sustitución.



 a| 
En una configuración independiente
 a| 
No tiene más pasos en esta tarea en particular.

Ha completado el diagnóstico de nivel del sistema.



 a| 
Se produjeron algunos fallos en las pruebas
 a| 
Determine la causa del problema.

.. Salir del modo de mantenimiento: `halt`
.. Realice un apagado correcto y, a continuación, desconecte las fuentes de alimentación.
.. Compruebe que ha observado todos los aspectos identificados a la hora de ejecutar diagnósticos de nivel de sistema, que los cables estén conectados de forma segura y que los componentes de hardware estén correctamente instalados en el sistema de almacenamiento.
.. Vuelva a conectar las fuentes de alimentación y encienda el sistema de almacenamiento.
.. Vuelva a ejecutar la prueba de diagnóstico de nivel del sistema.


|===




== Paso 3: Vuelva a cambiar los agregados en una configuración MetroCluster de dos nodos

Una vez que haya completado el reemplazo de FRU en una configuración de MetroCluster de dos nodos, podrá llevar a cabo la operación de conmutación de estado de MetroCluster. De este modo, la configuración vuelve a su estado operativo normal, con las máquinas virtuales de almacenamiento (SVM) sincronizada en el sitio anteriormente afectado que ahora están activas y sirviendo datos de los pools de discos locales.

Esta tarea solo se aplica a configuraciones MetroCluster de dos nodos.

.Pasos
. Compruebe que todos los nodos estén en el `enabled` provincia: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Compruebe que la resincronización se haya completado en todas las SVM: `metrocluster vserver show`
. Compruebe que las migraciones LIF automáticas que realizan las operaciones de reparación se han completado correctamente: `metrocluster check lif show`
. Lleve a cabo la conmutación de estado mediante el `metrocluster switchback` comando desde cualquier nodo del clúster superviviente.
. Compruebe que la operación de conmutación de estado ha finalizado: `metrocluster show`
+
La operación de conmutación de estado ya está en ejecución cuando un clúster está en el `waiting-for-switchback` provincia:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
La operación de conmutación de estado se completa cuando los clústeres están en el `normal` estado:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Si una conmutación de regreso tarda mucho tiempo en terminar, puede comprobar el estado de las líneas base en curso utilizando el `metrocluster config-replication resync-status show` comando.

. Restablecer cualquier configuración de SnapMirror o SnapVault.




== Paso 4: Devuelva la pieza que falló a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://["Retorno de artículo  sustituciones"] para obtener más información.
