---
permalink: fas9000/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Antes de sustituir el chasis de un sistema FAS9000, comprueba que todos los demás componentes funcionen correctamente y que el chasis de recambio sea del mismo modelo que el chasis averiado. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis en un sistema FAS9000, verifica que todos los demás componentes funcionen correctamente y que el chasis de sustitución sea del mismo modelo que el chasis defectuoso. El procedimiento es disruptivo, causando una interrupción total del servicio en un clúster de dos nodos o una interrupción parcial en un clúster de varios nodos.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

