---
permalink: fas9000/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a700, fas9000, verify, ha, state, controller, module 
summary: Tras completar el reemplazo y el arranque del hardware en modo de mantenimiento, debe verificar la configuración del sistema de bajo nivel de la controladora de reemplazo y volver a configurar los ajustes del sistema según sea necesario. 
---
= Restaurar y verificar la configuración del sistema - FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras completar el reemplazo y el arranque del hardware en modo de mantenimiento, debe verificar la configuración del sistema de bajo nivel de la controladora de reemplazo y volver a configurar los ajustes del sistema según sea necesario.



== Paso 1: Establecer y verificar la hora del sistema

Debe comprobar la hora y la fecha del módulo de la controladora de sustitución en comparación con el módulo de controladora en buen estado de un par de alta disponibilidad o con un servidor de tiempo fiable en una configuración independiente. Si la hora y la fecha no coinciden, debe reiniciarlas en el módulo del controlador de repuesto para evitar posibles interrupciones en los clientes debido a diferencias de tiempo.

.Acerca de esta tarea
Es importante que aplique los comandos en los pasos de los sistemas correctos:

* El nodo _regrUSTITUCION_ es el nuevo nodo que reemplazó al nodo dañado como parte de este procedimiento.
* El nodo _heated_ es el compañero de alta disponibilidad del nodo _regrel_.


.Pasos
. Si el nodo _reader_ no está en el aviso del CARGADOR, detenga el sistema en el símbolo del sistema del CARGADOR.
. En el nodo _Healthy_, compruebe la hora del sistema: `cluster date show`
+
La fecha y la hora se basan en la zona horaria configurada.

. En el símbolo del SISTEMA del CARGADOR, compruebe la fecha y la hora del nodo _regrel_: `show date`
+
La fecha y la hora se indican en GMT.

. Si es necesario, establezca la fecha en GMT en el nodo de reemplazo: `set date _mm/dd/yyyy_`
. Si es necesario, establezca la hora en GMT del nodo de reemplazo: `set time _hh:mm:ss_`
. En el símbolo del SISTEMA del CARGADOR, confirme la fecha y la hora del nodo _regrel_: `show date`
+
La fecha y la hora se indican en GMT.





== Paso 2: Verifique y establezca el estado de alta disponibilidad de la controladora

Debe comprobar el `HA` estado del módulo de la controladora y, si es necesario, actualice el estado para que coincida con la configuración del sistema.

.Pasos
. En el modo de mantenimiento del nuevo módulo de controlador, compruebe que todos los componentes muestran lo mismo `HA` provincia: `ha-config show`
+
El valor de la condición de alta disponibilidad puede ser uno de los siguientes:

+
** `ha`
** `mcc`
** `mcc-2n`
** `mccip`
** `non-ha`
+
... Confirme que el ajuste ha cambiado: `ha-config show`





