---
permalink: fas9000/x91148a-module-install-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, add, x91148a, storage, module, NIC, no open, slots, open slots, system 
summary: Agrega un módulo X91148A a un sistema FAS9000, ya sea reemplazando una NIC o un adaptador de almacenamiento por uno nuevo en un sistema completamente ocupado, o agregando una nueva NIC o adaptador de almacenamiento en una ranura vacía del chasis. 
---
= Infórmate sobre cómo añadir un módulo X91148A a un sistema FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Agrega un módulo X91148A a un sistema FAS9000, ya sea reemplazando una NIC o un adaptador de almacenamiento por uno nuevo en un sistema completamente ocupado, o agregando una nueva NIC o adaptador de almacenamiento en una ranura vacía del chasis.

Puede agregar un módulo de E/S al sistema sustituyendo una NIC o un adaptador de almacenamiento por uno nuevo en un sistema completamente cargado, o agregando un nuevo NIC o adaptador de almacenamiento en una ranura de chasis vacía en el sistema.

.Antes de empezar
* Consulta la  https://hwu.netapp.com["Hardware Universe de NetApp"] para asegurarte de que el nuevo módulo de E/S es compatible con tu sistema y con la versión de ONTAP que estás usando.
* Si hay varias ranuras disponibles, consulta las prioridades de las ranuras en https://hwu.netapp.com["Hardware Universe de NetApp"] y utiliza la mejor de las disponibles para tu módulo de E/S.
* Para agregar sin interrupciones un módulo de I/o, debe tomar el control del controlador de destino, quitar la cubierta de relleno de la ranura en la ranura de destino o extraer un módulo de I/o existente, agregar el módulo de I/o nuevo o de reemplazo y, a continuación, poner el controlador de destino en la posición de devolución.
* Asegúrese de que todos los demás componentes funcionan correctamente.

