---
permalink: asa-r2-a20-30-50/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, overview, automatic recovery, boot media 
summary: Obtenga información sobre el método automatizado para sustituir el soporte de arranque. 
---
= Descripción general de la recuperación de medios de arranque - ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La recuperación del medio físico de arranque utiliza la imagen de arranque del nodo asociado y ejecuta automáticamente la opción de menú de arranque adecuada para instalar la imagen de arranque en el soporte de arranque de reemplazo.

Cuando encuentre mensajes de error de arranque similares a los que se muestran a continuación, debe sustituir el soporte de arranque y restaurar la imagen ONTAP desde el nodo asociado.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....