---
permalink: asa-r2-a20-30-50/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, verify and set HA state, complete the replacement process 
summary: Compruebe el estado de alta disponibilidad del chasis y, a continuación, devuelva la pieza con error a NetApp para completar el paso final del procedimiento de sustitución del chasis ASA A20, ASA A30 y ASA A50. 
---
= Reemplazo de chasis completo: ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Compruebe el estado de alta disponibilidad del chasis y, a continuación, devuelva la pieza con error a NetApp para completar el paso final del procedimiento de sustitución del chasis ASA A20, ASA A30 y ASA A50.



== Paso 1: Verificar y establecer el estado de alta disponibilidad del chasis

Debe comprobar el estado HA del chasis y, si es necesario, actualizar el estado para que coincida con la configuración de su sistema de almacenamiento.

. En modo de mantenimiento, desde cualquiera de las controladoras, muestra el estado de alta disponibilidad de la controladora y el chasis locales:
+
`ha-config show`

+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema que se muestra para el chasis no coincide con la configuración del sistema de almacenamiento:
+
.. Establezca el estado de alta disponibilidad para el chasis:
+
`ha-config modify chassis _HA-state_`

+
El valor de HA-state debe ser _ha_.

.. Confirme que el ajuste ha cambiado:
+
`ha-config show`



. Si todavía no lo ha hecho, vuelva a conectar el resto del sistema de almacenamiento.




== Paso 2: Devuelve la parte fallida a NetApp

Devuelva la pieza que ha fallado a NetApp, como se describe en las instrucciones de RMA que se suministran con el kit. Consulte https://mysupport.netapp.com/site/info/rma["Devolución de piezas y sustituciones"] la página para obtener más información.
