---
permalink: asa-r2-a20-30-50/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Tras completar el reemplazo y el arranque del hardware en modo de mantenimiento, debe verificar la configuración del sistema de bajo nivel de la controladora de reemplazo y volver a configurar los ajustes del sistema según sea necesario. 
---
= Restaurar y comprobar la configuración del sistema: ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Compruebe que la configuración de alta disponibilidad de la controladora esté activa y funcione correctamente en el sistema de almacenamiento ASA A20, ASA A30 o ASA A50, y confirme que los adaptadores del sistema incluyan todas las rutas a los discos.



== Paso 1: Verifique la configuración de alta disponibilidad

Es necesario comprobar `HA` el estado de la controladora y, si es necesario, actualizar el estado para que coincida con la configuración del sistema de almacenamiento.

. Arranque en modo de mantenimiento:
+
`boot_ontap maint`

+
.. Introduzca `y` cuando vea _Continue with boot?_.
+
Si aparece el mensaje de advertencia _System ID mismatch_, introduzca `y`.



. Introduzca `sysconfig -v` y capture el contenido de la pantalla.
+

NOTE: Si ve _PERSONALITY MISMATCH_ póngase en contacto con el servicio de atención al cliente.

. En `sysconfig -v` la salida, compare la información de la tarjeta del adaptador con las tarjetas y las ubicaciones de la controladora de reemplazo.
. Compruebe que todos los componentes muestran el mismo `HA` estado:
+
`ha-config show`

+
El estado de alta disponibilidad debe ser el mismo para todos los componentes.

. Si el estado del sistema que se muestra en la controladora no coincide con la configuración del sistema de almacenamiento, defina el `HA` estado para la controladora:
+
`ha-config modify controller ha`

+
El valor del estado de alta disponibilidad puede ser uno de los siguientes:

+
** `ha`
** `mcc` (no compatible)
** `mccip` (No compatible con sistemas ASA)
** `non-ha` (no compatible)


. Confirme que el ajuste ha cambiado:
+
`ha-config show`





== Paso 2: Verifique la lista de discos

. Compruebe que el adaptador enumera las rutas a todos los discos:
+
`storage show disk -p`

+
Si observa algún problema, compruebe el cableado y vuelva a colocar los cables.

. Salir del modo de mantenimiento:
+
`halt`



.El futuro
Después de restaurar y verificar la configuración del sistema, es necesario link:controller-replace-recable-reassign-disks.html["devuelva la controladora"].
