---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: Antes de sustituir la controladora en su sistema ASA A20, ASA A30 o ASA A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto. 
---
= Requisitos para sustituir la controladora: ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir la controladora en su sistema ASA A20, ASA A30 o ASA A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto.

Debe revisar los requisitos y consideraciones del procedimiento de reemplazo de la controladora.



== Requisitos

* Todas las bandejas deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* Debe sustituir una controladora por una controladora del mismo tipo de modelo. No se puede actualizar el sistema simplemente reemplazando la controladora.
* No es posible cambiar ninguna unidad o bandeja como parte de este procedimiento.
* Siempre debe capturar la salida de consola de la controladora en un archivo de registro de texto.
+
La salida de la consola le proporciona un registro del procedimiento que puede utilizar para solucionar los problemas que pueda encontrar durante el proceso de reemplazo.





== Consideraciones

* Es importante aplicar los comandos de este procedimiento a la controladora correcta:
+
** El controlador _drinated_ es el controlador que se va a sustituir.
** El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
** El controlador _heated_ es el controlador que sobrevive.




.El futuro
Después de haber revisado los requisitos para reemplazar el controlador dañado, debe link:controller-replace-shutdown.html["apague el controlador defectuoso"].
