---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: Antes de sustituir la controladora en su sistema ASA A20, ASA A30 o ASA A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto. 
---
= Requisitos para sustituir la controladora: ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir la controladora en su sistema ASA A20, ASA A30 o ASA A50, asegúrese de cumplir con los requisitos necesarios para un reemplazo correcto. Esto incluye verificar que todos los demás componentes del sistema funcionan correctamente, verificar que tiene el controlador de reemplazo correcto y guardar la salida de la consola del controlador en un archivo de registro de texto.

Revise los requisitos y las consideraciones del procedimiento de reemplazo de la controladora.



== Requisitos

* Todas las bandejas deben funcionar correctamente.
* El controlador en buen estado podrá hacerse cargo del controlador que se vaya a sustituir (a que se hace referencia en el presente procedimiento como el "'controlador en deterioro"").
* Si su sistema está en una configuración MetroCluster, debe revisar la sección https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Elección del procedimiento de recuperación correcto"] para determinar si debe utilizar este procedimiento.
* Debe sustituir una controladora por una controladora del mismo tipo de modelo. No se puede actualizar el sistema simplemente reemplazando la controladora.
* No es posible cambiar ninguna unidad o bandeja como parte de este procedimiento.
* Siempre debe capturar la salida de consola de la controladora en un archivo de registro de texto.
+
La salida de la consola le proporciona un registro del procedimiento que puede utilizar para solucionar los problemas que pueda encontrar durante el proceso de reemplazo.





== Consideraciones

* Es importante aplicar los comandos de este procedimiento a la controladora correcta:
+
** El controlador _drinated_ es el controlador que se va a sustituir.
** El controlador _regrse_ es el nuevo controlador que está reemplazando el controlador dañado.
** El controlador _heated_ es el controlador que sobrevive.


* Si es necesario, puede encender los LED de ubicación del sistema de almacenamiento (azul) para ayudar a localizar físicamente el sistema de almacenamiento afectado. Inicie sesión en BMC mediante SSH e introduzca `system location-led _on_` el comando.
+
Un sistema de almacenamiento tiene tres LED de ubicación: Uno en el panel de visualización del operador y otro en cada controlador. Los LED de ubicación permanecen encendidos durante 30 minutos.

+
Puede desactivarlos introduciendo `system location-led _off_` el comando. Si no está seguro de si los LED están encendidos o apagados, puede comprobar su estado introduciendo `system location-led show` el comando.



.El futuro
Después de haber revisado los requisitos para reemplazar su controlador ASA A20, ASA A30 o ASA A50, debe link:controller-replace-shutdown.html["apague el controlador defectuoso"].
