---
permalink: asa-r2-a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90, ASA A70, replace io module 
summary: 'Debe sustituir el componente defectuoso por un componente de unidad sustituible de campo (FRU) de sustitución que haya recibido de su proveedor.' 
---
= Descripción general de la adición y sustitución de un módulo de E/S - ASA A20, ASA A30 y ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas ASA A20, ASA A30 y ASA A50 ofrecen flexibilidad en la expansión o sustitución de módulos de I/O para mejorar la conectividad y el rendimiento de la red. La adición o sustitución de un módulo de E/S es esencial al actualizar las capacidades de red o al abordar un módulo fallido.

Puede sustituir un módulo de I/O con fallo del sistema de almacenamiento con el mismo tipo de módulo de I/O o con un tipo diferente de módulo de I/O. También puede agregar un módulo de I/O a un sistema de almacenamiento con las ranuras disponibles.

* link:io-module-add.html["Agregue un módulo de E/S."]
+
Al agregar módulos de I/O adicionales, se puede mejorar la redundancia y ayudar a garantizar que el sistema de almacenamiento siga funcionando incluso si falla un módulo de I/O.

* link:io-module-replace.html["Sustituya un módulo de E/S."]
+
El reemplazo de un módulo de I/O con fallos puede restaurar el sistema de almacenamiento a su estado operativo óptimo.


