---
permalink: afx/afx-install-setup.html 
sidebar: sidebar 
keywords: afx, afx 1k, install, setup, initial configuration 
summary: Instale y configure el sistema. 
---
= Instale y configure su sistema de almacenamiento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ir a la https://docs.netapp.com/us-en/ontap-afx/index.html["Documentación de AFX"^] para aprender a instalar, usar y administrar su sistema AFX.

El https://docs.netapp.com/us-en/ontap-afx/index.html["Documentación de AFX"^] Incluye información como:

* Instrucciones de instalación y configuración
* Instrucciones de administración para configurar su sistema, como aprovisionar almacenamiento NAS, clonar datos y redimensionar el almacenamiento local.
* Instrucciones para administrar su sistema, incluida la administración del acceso de clientes, la protección de sus datos y la protección de sus datos.
* Instrucciones de supervisión y solución de problemas, incluida información sobre alertas, eventos del clúster y registros del sistema.


Los procedimientos de mantenimiento específicos para cada tipo de sistema AFX se encuentran en ellink:../afx-landing-maintain/index.html["Sección de mantenimiento del sistema AFX"] .
