---
permalink: a300/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a300, replace the chassis 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir el chasis de tu AFF A300
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema AFF A300, revisa los requisitos necesarios para que la sustitución se realice correctamente. El procedimiento consiste en trasladar todas las fuentes de alimentación, los ventiladores y los módulos controladores del chasis averiado al chasis de sustitución y es disruptivo.

Todos los demás componentes del sistema deben funcionar correctamente; si no es así, debe ponerse en contacto con el soporte técnico.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento se escribe con la suposición de que va a mover el módulo o los módulos de la controladora al nuevo chasis y que el chasis es un nuevo componente de NetApp.
* Este procedimiento es disruptivo. En el caso de un clúster de dos nodos, tendrá una interrupción del servicio completa y una interrupción parcial en un clúster de varios nodos.

