---
permalink: ns224/cable-as-switch-attached.html 
sidebar: sidebar 
keywords: ns224 nvme drive shelf cabling guide, ns224 drive shelf cabling guide, ns224 shelf cabling guide, ns224 cabling guide, switch-attach, switch-attached, switch-attached storage, cable ns224 drive shelves as switch-attached storage 
summary: 'Si tiene un sistema en el que las bandejas de unidades NS224 necesitan cablearse como almacenamiento conectado al switch \(no almacenamiento de conexión directa\), utilice la información proporcionada.' 
---
= Bandejas de cables como almacenamiento conectado a conmutador - bandejas NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un sistema en el que las bandejas de unidades NS224 deben cablearse como almacenamiento conectado al switch (no como almacenamiento de conexión directa), utilice la información proporcionada.

* Para conectar el cable de las bandejas de unidades NS224 mediante switches de almacenamiento, consulte la https://hwu.netapp.com["Hardware Universe de NetApp"^] para obtener más información. Para modelos de hardware más antiguos, también se puede encontrar información sobre el cableado del switch en la https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guía de cableado de bandeja de unidades NVMe NS224"^].
* Para instalar los switches de almacenamiento, consulte https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentación de AFF y switches FAS"^] .
* Para confirmar el hardware compatible con el modelo de plataforma, como switches y cables de almacenamiento, consulte la https://hwu.netapp.com["Hardware Universe de NetApp"^] .

