---
permalink: ns224/hot-add-aff-cable-a250-c250.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff a250, aff c250, cable 
summary: Conecta tu estantería NS224 a tu sistema AFF A250 o AFF C250 para que cada estantería tenga dos conexiones a cada controlador del par HA. 
---
= Cablea un estante NS224 a tu sistema AFF A250 o AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conecta tu estantería NS224 a tu sistema AFF A250 o AFF C250 para que cada estantería tenga dos conexiones a cada controlador del par HA.

.Acerca de esta tarea
Una vez visto desde la parte posterior del chasis de la plataforma, el puerto para tarjetas compatible con roce de la izquierda es el puerto "a" (e1a) y el puerto de la derecha es el puerto "b" (e1b).

.Pasos
. Conecte los cables de las conexiones de la bandeja:
+
.. Conecte El puerto NSM de La bandeja de cables e0a al puerto a de la ranura 1 de la controladora (e1a).
.. Conecte el cable del puerto NSM A e0b a la ranura de la controladora B del puerto b (e1b).
.. Conecte el puerto NSM B de la bandeja de cables e0a al puerto a de la ranura de la controladora B (e1a).
.. Conecte el puerto e0b NSM B de la bandeja a la controladora, puerto b (e1b) de la ranura 1. + la siguiente ilustración muestra el cableado de las bandejas cuando se completa.
+
image::../media/drw_ns224_a250_c250_f500f_1shelf_ieops-1824.svg[Cableado para un AFF/ASA A250 C250 o FAS500f con una bandeja NS224 y un conjunto de puertos de tarjeta PCIe]



. Compruebe que la bandeja añadida en caliente se ha cableado correctamente https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]mediante .
+
Si se genera algún error de cableado, siga las acciones correctivas proporcionadas.



.El futuro
Si desactivaste la asignación automática de unidades como parte de la preparación para este procedimiento, necesitas asignar manualmente la propiedad de las unidades y luego volver a habilitar la asignación automática de unidades, si es necesario. Ve a link:hot-add-aff-complete.html["Complete el hot-add"].

De lo contrario, finalizó el procedimiento de bandeja con adición en caliente.
