---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: Puede añadir en caliente una bandeja de unidades NS224 después de que su par de alta disponibilidad cumpla determinados requisitos y una vez completadas las tareas de preparación aplicables a su pareja de alta disponibilidad. 
---
= Prepárese para una incorporación en caliente: NS224 bandejas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Complete las tareas de preparación aplicables a su pareja de alta disponibilidad antes de agregar en caliente una bandeja NS224.

Cuando haya terminado con las tareas de preparación correspondientes, vaya a link:prepare-hot-add-shelf.html["Instale una bandeja para una incorporación en caliente"].



== Instale tarjetas PCIe o módulos de I/O compatibles con RoCE

Si el modelo de plataforma admite el uso de tarjetas PCIe o módulos de I/O compatibles con RoCE, su par de alta disponibilidad debe tener suficientes puertos Ethernet compatibles con RoCE para admitir el número de bandejas que está añadiendo en caliente.

.Pasos
. Para cada bandeja que añada en caliente, compruebe que existan dos puertos compatibles con RoCE en cada controladora.
+
Estos puertos pueden estar integrados en las controladoras, en tarjetas PCIe compatibles con roce, en una combinación de ambos o en módulos de I/o compatibles con roce, según lo admita el modelo de plataforma.

. Si su par de alta disponibilidad no cuenta con suficientes puertos compatibles con RoCE, instale las tarjetas PCIe o los módulos de I/O adicionales en las ranuras de controladora correctas, como se admite en el modelo de plataforma.
+
.. Identificar las ranuras de la controladora correctas para el modelo de plataforma. Consulte https://hwu.netapp.com["Hardware Universe de NetApp"^].
.. Consulte la documentación del modelo de su plataforma para obtener instrucciones de instalación de tarjetas PCIe o módulos de E/S.






== Configure los puertos compatibles con RoCE para el uso del almacenamiento

Si la pareja de alta disponibilidad tiene puertos Ethernet no dedicados compatibles con RoCE que se utilizan para añadir en caliente una bandeja NS224, debe configurar los puertos para el uso del almacenamiento (no el uso de la red).

.Antes de empezar
* Asegúrese de haber instalado tarjetas PCIe o módulos de I/O adicionales compatibles con RoCE en cada controladora.


.Acerca de esta tarea
* Para algunos modelos de plataforma, cuando se instalan una tarjeta PCIe o un módulo de I/O compatibles con RoCE en una ranura compatible en una controladora, los puertos automáticamente utilizan el almacenamiento de manera predeterminada (en lugar de redes); sin embargo, se recomienda completar el siguiente procedimiento para verificar que los puertos compatibles con RoCE estén configurados para el uso del almacenamiento.
* Si determina que los puertos no dedicados compatibles con roce de la pareja de alta disponibilidad no están configurados para su uso en el almacenamiento, se trata de un procedimiento no disruptivo para configurarlos. No es necesario reiniciar las controladoras, a menos que una o ambas controladoras se encuentren en modo de mantenimiento. En este procedimiento se asume que ninguna controladora está en modo de mantenimiento.
* Si en el futuro necesita cambiar los puertos del uso del almacenamiento al uso de redes, escriba el comando, `storage port modify -node _node_name_ -port _port_name_ -mode network`.


.Pasos
. Inicie sesión en el clúster mediante SSH o el puerto de la consola de serie.
. Introduzca el siguiente comando para verificar si los puertos no dedicados del par de alta disponibilidad están configurados para el uso del almacenamiento:
+
`storage port show`

+
** Si su par de alta disponibilidad ejecuta ONTAP 9.8 o posterior, se muestran los puertos no dedicados `storage` en la `Mode` columna.
** Si su pareja de alta disponibilidad ejecuta ONTAP 9,7, los puertos no dedicados, que se muestran `false` en la columna, también aparecen en `Is Dedicated?` `State` la columna `enabled`.
+
[NOTE]
====
Cuando los puertos no dedicados no están configurados para el uso del almacenamiento, el resultado del comando muestra lo siguiente:

*** Si su par de alta disponibilidad ejecuta ONTAP 9.8 o posterior, se muestran los puertos no dedicados `network` en la `Mode` columna.
*** Si su pareja de alta disponibilidad ejecuta ONTAP 9,7, los puertos no dedicados, que se muestran `false` en la columna, también aparecen en `Is Dedicated?`` `State` la columna `disabled`.


====


. Si los puertos no dedicados están configurados para el uso del almacenamiento, se realiza con este procedimiento.
+
De lo contrario, deberá configurar los puertos completando los siguientes pasos.

. Configure los puertos no dedicados para uso del almacenamiento, en una de las controladoras:
+
Debe repetir el comando correspondiente para cada puerto que esté configurando.

+
[cols="1,3"]
|===
| Si su par de alta disponibilidad está ejecutando... | Se usa este comando... 


 a| 
ONTAP 9.8 o posterior
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. Repita el paso anterior para el segundo controlador.
. Compruebe que los puertos no dedicados de ambas controladoras están configurados para el uso del almacenamiento: `storage port show`
+
** Si su par de alta disponibilidad ejecuta ONTAP 9.8 o posterior, se muestran los puertos no dedicados `storage` en la `Mode` columna.
** Si su pareja de alta disponibilidad ejecuta ONTAP 9,7, los puertos no dedicados, que se muestran `false` en la columna, también aparecen en `Is Dedicated?` `State` la columna `enabled`.






== Vuelva a conectar las bandejas existentes

Antes de añadir bandejas adicionales en caliente, según el modelo de plataforma, es posible que deba volver a conectar los cables de una bandeja existente (después de haber instalado las tarjetas PCIe o módulos de I/O adicionales compatibles con RoCE) en dos conjuntos de puertos en ranuras diferentes para ofrecer resiliencia frente a fallo de ranura.

.Antes de empezar
* Asegúrese de haber instalado tarjetas PCIe o módulos de I/O adicionales compatibles con RoCE en cada controladora.
* Asegúrese de que los puertos no dedicados de las tarjetas PCIe compatibles con RoCE o de los módulos de I/O instalados estén configurados para uso del almacenamiento.


.Acerca de esta tarea
* La presentación de las conexiones de puertos es un procedimiento no disruptivo si su bandeja cuenta con conectividad de alta disponibilidad multivía.
* Es posible mover un cable cada vez para mantener siempre la conectividad con la bandeja durante este procedimiento.
+

NOTE: Mover un cable no requiere tiempo de espera entre desconectar el cable de un puerto y conectarlo a otro.

* Si es necesario, consulte las ilustraciones de cableado de bandejas correspondientes al modelo de plataforma en link:cable-overview-hot-add-shelf.html["Información general sobre el cableado para una incorporación en caliente"].


.Pasos
. Vuelva a conectar las conexiones de la bandeja existente en dos conjuntos de puertos compatibles con RoCE en ranuras diferentes, según corresponda al modelo de plataforma.


* Para sistemas AFF:
+
[role="tabbed-block"]
====
.AFF A1K
--
Realice una de las siguientes acciones si va a añadir una segunda bandeja o una cuarta bandeja en caliente.


NOTE: Si cuenta con un par de alta disponibilidad AFF A1K y está agregando una tercera bandeja en caliente y instalando un tercer o cuarto módulo de I/O compatible con RoCE en cada controladora, la tercera bandeja solo se cableará a los módulos de I/O del tercer o tercer y cuarto. No es necesario volver a conectar ninguna bandeja existente.

** Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 11 y la ranura 10 de cada controladora.
+
Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 11 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 11, puerto b (e11b), a la ranura 10, puerto b (e10b).
... Repita el mismo cable y mueva la controladora B.


** Si va a agregar en caliente una cuarta bandeja, vuelva a conectar la tercera bandeja entre los módulos de I/O compatibles con RoCE en la ranura 9 y la ranura 8 de cada controladora.
+
En los subpasos se supone que la tercera bandeja se conecta mediante cable a un módulo I/O compatible con RoCE en la ranura 9 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 9, puerto b (e9b), a la ranura 8, puerto b (e8b).
... Repita el mismo cable y mueva la controladora B.




--
.AFF A70, AFF A90 o AFF C80
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 11 y la ranura 8 de cada controladora.

Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 11 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 11, puerto b (e11b), a la ranura 8, puerto b (e8b).
.. Repita el mismo cable y mueva la controladora B.


--
.AFF A800 o AFF C800
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar la primera bandeja entre los dos conjuntos de puertos compatibles con RoCE de la ranura 5 y la ranura 3 de cada controladora.

Los subpasos dan por sentado que la bandeja existente se cableó a tarjetas PCIe compatibles con roce en la ranura 5 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 5, puerto b (e5b), a la ranura 3, puerto b (e3b).
.. Repita el mismo cable y mueva la controladora B.


--
.A700 de AFF
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar la primera bandeja entre los dos conjuntos de puertos compatibles con RoCE de la ranura 3 y la ranura 7 de cada controladora.

Los subpasos dan por sentado que la bandeja existente se cableó a módulos de I/o compatibles con roce en la ranura 3 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 3, puerto b (e3b), a la ranura 7, puerto b (e7b).
.. Repita el mismo cable y mueva la controladora B.


--
.AFF A400 o AFF C400
--
Si añade una segunda bandeja en caliente, según el modelo de plataforma, realice una de las siguientes acciones:

** En el AFF A400:
+
Vuelva a conectar la primera bandeja de los dos conjuntos de puertos compatibles con RoCE, e0c/e0d internos y en la ranura 5, en cada controladora.

+
En los subpasos se asume que la bandeja existente se cablea a los puertos integrados compatibles con RoCE e0c/e0d en cada controladora.

+
... En la controladora A, mueva el cable del puerto e0d a la ranura 5 puerto b (e5b).
... Repita el mismo cable y mueva la controladora B.


** En el AFF C400:
+
Vuelva a conectar la primera bandeja de los dos conjuntos de puertos compatibles con RoCE en la ranura 4 y la ranura 5, en cada controladora.

+
Los subpasos suponen que la bandeja existente está cableada a puertos compatibles con RoCE en la ranura 4 de cada controladora.

+
... En el controlador A, mueva el cable de la ranura 4, puerto a (e4a), a la ranura 5, puerto b (e5b).
... Repita el mismo cable y mueva la controladora B.




--
.AFF A900
--
Realice una de las siguientes acciones si va a añadir una segunda bandeja o una cuarta bandeja en caliente.

** Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 2 y la ranura 10 de cada controladora.
+
Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 2 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 2, puerto b (e2b), a la ranura 10, puerto b (e10b).
... Repita el mismo cable y mueva la controladora B.


** Si va a agregar en caliente una cuarta bandeja, vuelva a conectar la tercera bandeja entre los módulos de I/O compatibles con RoCE en la ranura 1 y la ranura 11 de cada controladora.
+
En los subpasos se supone que la tercera bandeja se conecta mediante cable a un módulo I/O compatible con RoCE en la ranura 1 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 1, puerto b (e1b), a la ranura 11, puerto b (e11b).
... Repita el mismo cable y mueva la controladora B.




--
.AFF A30, AFF C30, AFF A50 o AFF C60
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 3 y la ranura 1 de cada controladora.

Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 3 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 3, puerto b (e3b), a la ranura 1, puerto b (e1b).
.. Repita el mismo cable y mueva la controladora B.


--
====


* Para sistemas ASA:
+
[role="tabbed-block"]
====
.ASA A1K
--
Realice una de las siguientes acciones si va a añadir una segunda bandeja o una cuarta bandeja en caliente.


NOTE: Si cuenta con un par de alta disponibilidad ASA A1K y está agregando una tercera bandeja en caliente y instalando un tercer o cuarto módulo de I/O compatible con RoCE en cada controladora, la tercera bandeja solo se cableará a los módulos de I/O del tercer o tercer y cuarto. No es necesario volver a conectar ninguna bandeja existente.

** Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 11 y la ranura 10 de cada controladora.
+
Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 11 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 11, puerto b (e11b), a la ranura 10, puerto b (e10b).
... Repita el mismo cable y mueva la controladora B.


** Si va a agregar en caliente una cuarta bandeja, vuelva a conectar la tercera bandeja entre los módulos de I/O compatibles con RoCE en la ranura 9 y la ranura 8 de cada controladora.
+
En los subpasos se supone que la tercera bandeja se conecta mediante cable a un módulo I/O compatible con RoCE en la ranura 9 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 9, puerto b (e9b), a la ranura 8, puerto b (e8b).
... Repita el mismo cable y mueva la controladora B.




--
.ASA A70 o ASA A90
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 11 y la ranura 8 de cada controladora.

Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 11 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 11, puerto b (e11b), a la ranura 8, puerto b (e8b).
.. Repita el mismo cable y mueva la controladora B.


--
.ASA A800 o ASA C800
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar la primera bandeja entre los dos conjuntos de puertos compatibles con RoCE de la ranura 5 y la ranura 3 de cada controladora.

Los subpasos dan por sentado que la bandeja existente se cableó a tarjetas PCIe compatibles con roce en la ranura 5 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 5, puerto b (e5b), a la ranura 3, puerto b (e3b).
.. Repita el mismo cable y mueva la controladora B.


--
.ASA A400 o ASA C400
--
Si añade una segunda bandeja en caliente, según el modelo de plataforma, realice una de las siguientes acciones:

** En el ASA A400:
+
Vuelva a conectar la primera bandeja de los dos conjuntos de puertos compatibles con RoCE, e0c/e0d internos y en la ranura 5, en cada controladora.

+
En los subpasos se asume que la bandeja existente se cablea a los puertos integrados compatibles con RoCE e0c/e0d en cada controladora.

+
... En la controladora A, mueva el cable del puerto e0d a la ranura 5 puerto b (e5b).
... Repita el mismo cable y mueva la controladora B.


** En el ASA C400:
+
Vuelva a conectar la primera bandeja de los dos conjuntos de puertos compatibles con RoCE en la ranura 4 y la ranura 5, en cada controladora.

+
Los subpasos suponen que la bandeja existente está cableada a puertos compatibles con RoCE en la ranura 4 de cada controladora.

+
... En el controlador A, mueva el cable de la ranura 4, puerto a (e4a), a la ranura 5, puerto b (e5b).
... Repita el mismo cable y mueva la controladora B.




--
.ASA A900
--
Realice una de las siguientes acciones si va a añadir una segunda bandeja o una cuarta bandeja en caliente.

** Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 2 y la ranura 10 de cada controladora.
+
Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 2 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 2, puerto b (e2b), a la ranura 10, puerto b (e10b).
... Repita el mismo cable y mueva la controladora B.


** Si va a agregar en caliente una cuarta bandeja, vuelva a conectar la tercera bandeja entre los módulos de I/O compatibles con RoCE en la ranura 1 y la ranura 11 de cada controladora.
+
En los subpasos se supone que la tercera bandeja se conecta mediante cable a un módulo I/O compatible con RoCE en la ranura 1 de cada controladora.

+
... En la controladora A, mueva el cable de la ranura 1, puerto b (e1b), a la ranura 11, puerto b (e11b).
... Repita el mismo cable y mueva la controladora B.




--
.ASA A30 o ASA A50
--
Si va a agregar en caliente una segunda bandeja, vuelva a conectar los cables de la primera bandeja entre los módulos de I/O compatibles con RoCE de la ranura 3 y la ranura 1 de cada controladora.

Los subpasos suponen que la bandeja existente se conecta mediante cable a un módulo de I/O compatible con RoCE en la ranura 3 de cada controladora.

.. En la controladora A, mueva el cable de la ranura 3, puerto b (e3b), a la ranura 1, puerto b (e1b).
.. Repita el mismo cable y mueva la controladora B.


--
====


. Compruebe que la bandeja remachada está cableada correctamente mediante https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Si se genera algún error de cableado, siga las acciones correctivas proporcionadas.





== Deshabilite la asignación automática de unidades

Si desea asignar manualmente propiedad de unidad para la bandeja NS224 que se añade en caliente, debe deshabilitar la asignación de unidades automática si está habilitada.

Si no está seguro si debe asignar manualmente propiedad de una unidad o desea comprender la asignación automática de políticas de propiedad de unidades para el sistema de almacenamiento, vaya a https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["Acerca de la asignación automática de propiedad de disco"^].

.Pasos
. Compruebe si la asignación automática de unidades está habilitada: `storage disk option show`
+
Puede introducir el comando en cualquiera de los nodos.

+
Si la asignación automática de unidades está habilitada, el resultado se muestra `on` en `Auto Assign` la columna (en cada nodo).

. Si la asignación automática de unidades está habilitada, deshabilítela: `storage disk option modify -node _node_name_ -autoassign off`
+
Debe deshabilitar la asignación automática de unidades en ambos nodos.


