---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 'Cuando se produce un error en los medios de arranque de una bandeja de unidades NS224 en una pareja de alta disponibilidad que ejecuta ONTAP 9.7 o una versión posterior, o bien la bandeja ejecuta el módulo de la bandeja NVMe \(NSM\) versión del firmware 1.1x o posterior, puede sustituir el medio de arranque. El reemplazo de los medios de arranque puede realizarse de forma no disruptiva, mientras la bandeja de unidades está encendida y las operaciones de I/o están en curso.' 
---
= Reemplace el soporte de arranque - bandejas NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se produce un error en los medios de arranque de una bandeja de unidades NS224 en una pareja de alta disponibilidad que ejecuta ONTAP 9.7 o una versión posterior, o bien la bandeja ejecuta el firmware 0111 o posterior del módulo de bandeja NVMe (NSM), puede sustituir el medio de arranque. El reemplazo de los medios de arranque puede realizarse de forma no disruptiva, mientras la bandeja de unidades está encendida y las operaciones de I/o están en curso.

.Antes de empezar
* Su pareja de alta disponibilidad ya debe ejecutar ONTAP 9.7 o posterior, que tenga la versión mínima admitida de firmware NSM, o su pareja de alta disponibilidad ya debe ejecutar una versión de ONTAP 9.6 con la versión de firmware NSM 0111 o posterior.
+
Puede introducir el `storage shelf show -module` Comando en la consola de cualquiera de las controladoras para verificar la versión del firmware NSM de la bandeja.

+
[NOTE]
====
Si la bandeja no ejecuta la versión 0111 o posterior del firmware NSM, no puede sustituir el medio de arranque, debe sustituir el módulo NSM.

link:service-replace-nsm100.html["Sustituya un módulo NSM - bandejas NS224"^]

====
* Necesita un destornillador Phillips número 1.
+
El tornillo utilizado para fijar el soporte del maletero a la placa requiere un destornillador Phillips número 1; con un tipo diferente de destornillador se puede pelar el tornillo.

* El módulo NSM de partners de la bandeja debe estar activo y en funcionamiento y debe cablearse correctamente de manera que su bandeja mantenga la conectividad al quitar el módulo NSM con el FRU fallido (módulo NSM de destino).
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"^]

* Todos los demás componentes del sistema deben funcionar correctamente.


.Acerca de esta tarea
* Una vez reemplazados el medio de arranque, la imagen de arranque del módulo NSM del partner de la bandeja se copia automáticamente en el medio de arranque de reemplazo.
+
Esto puede tardar hasta cinco minutos.

* Permita al menos 70 segundos entre la eliminación y la instalación del módulo de bandeja de NVMe (NSM).
+
Esto le da tiempo suficiente para que ONTAP procese el evento de eliminación de NSM.

* Si es necesario, puede encender los LED de ubicación (azul) de la bandeja para ayudar a localizar físicamente la bandeja afectada: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Si no conoce la `_shelf_name_` de la bandeja afectada, ejecute el `storage shelf show` comando.

+
Una bandeja tiene tres LED de ubicación: Uno en el panel de visualización del operador y uno en cada módulo NSM. Los LED de ubicación permanecen encendidos durante 30 minutos. Puede desactivarlos introduciendo el mismo comando, pero mediante el `off` opción.

* Tras sustituir el soporte de arranque, puede devolver la pieza con error a NetApp tal como se describe en las instrucciones de la RMA que se suministran con el kit.
+
Si necesita el número de la RMA o ayuda adicional con el procedimiento de reemplazo, póngase en contacto con el soporte técnico en https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"^], 888-463-8277 (América del Norte), 00-800-44-638277 (Europa), o +800-800-80-800 (Asia/Pacífico).

* Puede utilizar la animación siguiente o los pasos escritos para reemplazar el soporte de arranque.
+
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[Animation,width=Replace the NS224 shelf boot media]


.Pasos
. Asegúrese de que ambos módulos NSM de la bandeja ejecuten la misma versión de firmware: Versión 0200 o posterior.
. Puesta a tierra apropiadamente usted mismo.
. Desconecte el cableado del módulo NSM que contiene la FRU que desea sustituir:
+
.. Desconecte el cable de alimentación de la fuente de alimentación abriendo el retenedor del cable de alimentación si es una fuente de alimentación de CA, o desenroscando los dos tornillos si es una fuente de alimentación de CC y, a continuación, desenchufe el cable de alimentación de la fuente de alimentación.
+
Las fuentes de alimentación no tienen un switch de alimentación.

.. Desconecte el cableado de almacenamiento de los puertos del módulo NSM.
+
Anote los puertos del módulo NSM a los que está conectado cada cable. Vuelva a conectar los cables a los mismos puertos cuando vuelva a insertar el módulo NSM, más adelante en este procedimiento.



. Quite el módulo NSM de la bandeja:
+
.. Enrolle los dedos de índice a través de los orificios de los dedos de los mecanismos de bloqueo a ambos lados del módulo NSM.
+

NOTE: Si va a extraer el módulo NSM inferior y si el riel inferior obstruye el acceso a los mecanismos de bloqueo, coloque los dedos de índice a través de los orificios de los dedos desde el interior (cruzando los brazos).

.. Con los pulgares, presione y sostenga las lengüetas naranjas en la parte superior de los mecanismos de bloqueo.
+
Los mecanismos de bloqueo se elevan, borrando los pasadores de cierre de la bandeja.

.. Tire suavemente hasta que el módulo NSM salga de la estantería aproximadamente un tercio, sujete los lados del módulo NSM con ambas manos para sostener su peso y, a continuación, colóquelo sobre una superficie plana y estable.
+
Cuando comience a tirar, los brazos del mecanismo de bloqueo se extienden desde el módulo NSM y se bloquean en su posición completamente extendida.



. Afloje el tornillo de palomilla de la cubierta del módulo NSM y abra la cubierta.
. Localice físicamente el medio de arranque con errores.
+
El soporte de arranque se encuentra a lo largo de la pared del chasis de la bandeja frente a la fuente de alimentación.

. Sustituya el soporte de arranque:
+
.. Con el destornillador Phillips número 1, retire con cuidado el tornillo que fija el extremo inferior (con muescas) del soporte del maletero a la placa.
.. Retire el soporte del maletero girando ligeramente el extremo ranurado hacia arriba y, a continuación, tirando suavemente de él hacia usted hasta que salga del zócalo.
+
Puede sujetar el soporte del maletero colocando el pulgar y el índice en los bordes laterales, en el extremo con muescas

.. Desembale el soporte del maletero de la bolsa antiestática.
.. Inserte el soporte de la funda de repuesto empujándolo suavemente en el zócalo hasta que quede asentado completamente en el zócalo.
+
Puede sujetar el soporte del maletero colocando el pulgar y el índice en los bordes laterales, en el extremo con muescas Asegúrese de que el lado con el disipador de calor está hacia arriba.

+
Cuando está correctamente asentado, y cuando se deja salir del soporte de la funda, el extremo ranurado del soporte de la funda está inclinado hacia arriba, lejos de la placa, porque aún no está fijado con el tornillo.

.. Sujete con cuidado el extremo ranurado del soporte del maletero mientras inserta y apriete el tornillo con el destornillador para fijar el soporte del maletero en su lugar.
+

NOTE: Apriete el tornillo lo suficiente como para sujetar el soporte del maletero firmemente en su lugar, pero no lo apriete en exceso.



. Cierre la cubierta del módulo NSM y, a continuación, apriete el tornillo de mariposa.
. Vuelva a insertar el módulo NSM en la bandeja:
+
.. Asegúrese de que los brazos del mecanismo de bloqueo están bloqueados en la posición completamente extendida.
.. Con ambas manos, deslice suavemente el módulo NSM hacia dentro de la bandeja hasta que el peso del módulo NSM sea totalmente compatible con la bandeja.
.. Inserte el módulo NSM en la bandeja hasta que se detenga (aproximadamente media pulgada de la parte posterior de la bandeja).
+
Puede colocar los pulgares en las lengüetas naranjas de la parte frontal de cada bucle de dedos (de los brazos del mecanismo de bloqueo) para empujar el módulo NSM.

.. Enrolle los dedos de índice a través de los orificios de los dedos de los mecanismos de bloqueo a ambos lados del módulo NSM.
+

NOTE: Si va a insertar el módulo NSM inferior y si el riel inferior obstruye el acceso a los mecanismos de bloqueo, coloque los dedos de índice a través de los orificios de los dedos desde el interior (cruzando los brazos).

.. Con los pulgares, presione y sostenga las lengüetas naranjas en la parte superior de los mecanismos de bloqueo.
.. Empuje suavemente hacia adelante para que los pestillos queden sobre el tope.
.. Suelte los pulgares de la parte superior de los mecanismos de bloqueo y, a continuación, siga presionando hasta que los mecanismos de bloqueo encajen en su lugar.
+
El módulo NSM debe insertarse por completo en el estante y enrasarse con los bordes del estante.



. Vuelva a conectar el cableado al módulo NSM:
+
.. Vuelva a conectar el cableado de almacenamiento a los mismos dos puertos del módulo NSM.
+
Los cables se insertan con la lengüeta de extracción del conector hacia arriba. Cuando se inserta correctamente un cable, éste hace clic en su lugar.

.. Vuelva a conectar el cable de alimentación a la fuente de alimentación y, a continuación, asegure el cable de alimentación con el retenedor del cable de alimentación si es una fuente de alimentación de CA, o apriete los dos tornillos de palomilla si es una fuente de alimentación de CC.
+
Cuando funciona correctamente, el LED bicolor de una fuente de alimentación se ilumina en verde.

+
Además, se encienden los dos LED LNK (verde) del puerto del módulo NSM. Si un LED LNK no se ilumina, vuelva a colocar el cable.



. Compruebe que los LED de atención (ámbar) del módulo NSM que contiene el soporte de arranque fallido y el panel de visualización del operador de la bandeja ya no están encendidos.
+
Puede tardar entre 5 y 10 minutos en que se aptotal los LED de atención. Esta es la cantidad de tiempo que tarda el módulo NSM en reiniciarse y la copia de la imagen del soporte de arranque en completarse.

+
Si los LED de fallo permanecen encendidos, es posible que el soporte de arranque no se encuentre correctamente o que haya otro problema y deberá ponerse en contacto con el soporte técnico para obtener ayuda.

. Verifique que el módulo NSM esté cableado correctamente ejecutando Active IQ Config Advisor.
+
Si se genera algún error de cableado, siga las acciones correctivas proporcionadas.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"^]


