---
permalink: ns224/service-replace-nsm100.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, impair, nvme, module, nsm, nondisruptive, drive, i/o, nsm, replace an nsm module 
summary: 'Puede sustituir un módulo de bandeja NVMe \(NSM\) dañado sin interrupciones en una bandeja de unidades NS224 encendida y mientras la I/o está en curso.' 
---
= Sustituya un módulo NSM - bandejas NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede reemplazar un módulo de bandeja NVMe (NSM) con alteraciones en una bandeja de unidades NS224 encendida y mientras hay I/o en curso.

.Antes de empezar
* El módulo NSM para partners de la bandeja debe estar activo y en funcionamiento y debe cablearse correctamente de manera que su bandeja mantenga la conectividad al quitar el módulo NSM que ha fallado.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"^]

* Todos los demás componentes del sistema deben funcionar correctamente.


.Acerca de esta tarea
* La sustitución del módulo NSM implica mover los DIMM, los ventiladores y la fuente de alimentación del módulo NSM afectado al módulo NSM de repuesto.
+
No mueve la batería del reloj en tiempo real (RTC) ni el soporte de arranque. Vienen preinstalados en el módulo NSM de repuesto.

* Permita al menos 70 segundos entre la eliminación y la instalación del módulo de bandeja de NVMe (NSM).
+
Esto le da tiempo suficiente para que ONTAP procese el evento de eliminación de NSM.

* *Mejor práctica:* la práctica recomendada es tener versiones actuales del firmware del módulo de bandeja NVMe (NSM) y del firmware de unidades en el sistema antes de sustituir componentes FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Descargas de NetApp: Firmware de bandeja de discos"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Descargas de NetApp: Firmware de la unidad de disco"^]

+
[NOTE]
====
No revierte el firmware a una versión que no admite la bandeja y sus componentes.

====
* El firmware de la bandeja (NSM) se actualiza automáticamente (sin interrupciones) en un módulo NSM nuevo que tiene una versión de firmware no actual.
+
Las comprobaciones del firmware del módulo NSM se realizan cada 10 minutos. Una actualización del firmware del módulo NSM puede tardar hasta 30 minutos.

* Si es necesario, puede encender los LED de ubicación (azul) de la bandeja para ayudar a localizar físicamente la bandeja afectada: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Si no conoce la `shelf_name` de la bandeja afectada, ejecute el `storage shelf show` comando.

+
Una bandeja tiene tres LED de ubicación: Uno en el panel de visualización del operador y uno en cada módulo NSM. Los LED de ubicación permanecen encendidos durante 30 minutos. Puede desactivarlos introduciendo el mismo comando, pero mediante el `off` opción.

* Cuando desembale el módulo NSM de repuesto, guarde todos los materiales de embalaje para usarlos cuando devuelva el módulo NSM fallido.
+
Si necesita el número de la RMA o ayuda adicional con el procedimiento de reemplazo, póngase en contacto con el soporte técnico en https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"^], 888-463-8277 (América del Norte), 00-800-44-638277 (Europa), o +800-800-80-800 (Asia/Pacífico).

* Puede utilizar la siguiente animación o los pasos escritos para reemplazar un módulo NSM.
+
video::f57693b3-b164-4014-a827-aa86002f4b34[Animation,width=Replace an NSM module in an NS224 shelf"]


.Pasos
. Puesta a tierra apropiadamente usted mismo.
. Identifique físicamente el módulo NSM dañado.
+
El sistema registra un mensaje de advertencia a la consola del sistema que indica qué módulo está dañado. Además, se iluminan el LED de atención (ámbar) del panel de la pantalla del operador de la bandeja de unidades y el módulo dañado.

. Desconecte el cableado del módulo NSM afectado:
+
.. Desconecte el cable de alimentación de la fuente de alimentación abriendo el retenedor del cable de alimentación si se trata de una fuente de alimentación de CA, o desenroscando los dos tornillos de los pulgares si se trata de una fuente de alimentación de CC y, a continuación, desenchufe el cable de alimentación de la fuente de alimentación.
+
Las fuentes de alimentación no tienen un switch de alimentación.

.. Desconecte el cableado de almacenamiento de los puertos del módulo NSM.
+
Anote los puertos del módulo NSM a los que está conectado cada cable. Vuelva a conectar los cables a los mismos puertos del módulo NSM de repuesto, más adelante en este procedimiento.



. Quite el módulo NSM de la bandeja:
+
.. Enrolle los dedos de índice a través de los orificios de los dedos de los mecanismos de bloqueo a ambos lados del módulo NSM.
+

NOTE: Si va a extraer el módulo NSM inferior y si el riel inferior obstruye el acceso a los mecanismos de bloqueo, coloque los dedos de índice a través de los orificios de los dedos desde el interior (cruzando los brazos).

.. Con los pulgares, presione y sostenga las lengüetas naranjas en la parte superior de los mecanismos de bloqueo.
+
Los mecanismos de bloqueo se elevan, borrando los pasadores de cierre de la bandeja.

.. Tire suavemente hasta que el módulo NSM salga de la estantería aproximadamente un tercio, sujete los lados del módulo NSM con ambas manos para sostener su peso y, a continuación, colóquelo sobre una superficie plana y estable.
+
Cuando comience a tirar, los brazos del mecanismo de bloqueo se extienden desde el módulo NSM y se bloquean en su posición completamente extendida.



. Desembale el módulo NSM de repuesto y configúrelo en una superficie nivelada cerca del módulo NSM afectado.
. Abra la cubierta del módulo NSM afectado y el módulo NSM de repuesto aflojando el tornillo de mano en cada cubierta.
+

NOTE: La etiqueta FRU de la cubierta del módulo NSM muestra la ubicación de los módulos DIMM y ventiladores.

. Mueva los DIMM del módulo NSM alterado al módulo NSM de repuesto:
+
.. Tenga en cuenta la orientación de los módulos DIMM en las ranuras para que pueda insertar los módulos DIMM en el módulo NSM de repuesto con la misma orientación.
.. Extraiga un módulo DIMM de su ranura empujando lentamente las lengüetas expulsoras de ambos extremos de la ranura DIMM y, a continuación, levante el módulo DIMM para extraerlo de la ranura.
+

NOTE: Sujete con cuidado el DIMM por las esquinas o bordes para evitar la presión en los componentes de la placa de circuitos DIMM. Las lengüetas del expulsor permanecen en la posición abierta.

.. Sujete el DIMM por las esquinas y, a continuación, inserte el DIMM directamente en una ranura del módulo NSM de repuesto.
+
La muesca de la parte inferior del DIMM, entre los pasadores, debe alinearse con la lengüeta de la ranura.

+
Cuando se inserta correctamente, el DIMM debe entrar fácilmente pero ajustarse firmemente en la ranura. De lo contrario, vuelva a insertar el DIMM.

.. Empuje hacia abajo con cuidado, pero firmemente, en el borde superior del DIMM hasta que las lengüetas expulsoras encajen en su lugar sobre las muescas de ambos extremos del DIMM.
.. Repita los subpasos 7a 7d para los módulos DIMM restantes.


. Mueva los ventiladores del módulo NSM afectado al módulo NSM de repuesto:
+
.. Sujete firmemente un ventilador de los laterales, donde están situados los puntos táctiles azules y, a continuación, levántelo verticalmente para desconectarlo de la toma.
+
Es posible que tenga que golpear suavemente el ventilador hacia adelante y hacia atrás para desconectarlo antes de levantarlo.

.. Alinee el ventilador con las guías del módulo NSM de repuesto y, a continuación, empuje hacia abajo hasta que el conector del módulo de ventilador esté completamente asentado en el zócalo.
.. Repita los subpasos 8a y 8b para los ventiladores restantes.


. Cierre la cubierta de cada módulo NSM y, a continuación, apriete cada tornillo.
. Mueva la fuente de alimentación del módulo NSM afectado al módulo NSM de repuesto:
+
.. Gire el asa hacia arriba, a su posición horizontal y, a continuación, sujételo.
.. Con el pulgar, presione la lengüeta azul para liberar el mecanismo de bloqueo.
.. Extraiga la fuente de alimentación del módulo NSM mientras utiliza la otra mano para soportar su peso.
.. Con ambas manos, sujete y alinee los bordes de la fuente de alimentación con la abertura del módulo NSM de repuesto.
.. Empuje suavemente la fuente de alimentación en el módulo NSM hasta que el mecanismo de bloqueo encaje en su lugar.
+

NOTE: No ejerza una fuerza excesiva o podría dañar el conector interno.

.. Gire el asa hacia abajo, de manera que quede fuera del camino de las operaciones normales.


. Inserte el módulo NSM de repuesto en la bandeja:
+
.. Asegúrese de que los brazos del mecanismo de bloqueo están bloqueados en la posición completamente extendida.
.. Con ambas manos, deslice suavemente el módulo NSM hacia dentro de la bandeja hasta que el peso del módulo NSM sea totalmente compatible con la bandeja.
.. Inserte el módulo NSM en la bandeja hasta que se detenga (aproximadamente media pulgada de la parte posterior de la bandeja).
+
Puede colocar los pulgares en las lengüetas naranjas de la parte frontal de cada bucle de dedos (de los brazos del mecanismo de bloqueo) para empujar el módulo NSM.

.. Enrolle los dedos de índice a través de los orificios de los dedos de los mecanismos de bloqueo a ambos lados del módulo NSM.
+

NOTE: Si va a insertar el módulo NSM inferior y si el riel inferior obstruye el acceso a los mecanismos de bloqueo, coloque los dedos de índice a través de los orificios de los dedos desde el interior (cruzando los brazos).

.. Con los pulgares, presione y sostenga las lengüetas naranjas en la parte superior de los mecanismos de bloqueo.
.. Empuje suavemente hacia adelante para que los pestillos queden sobre el tope.
.. Suelte los pulgares de la parte superior de los mecanismos de bloqueo y, a continuación, siga presionando hasta que los mecanismos de bloqueo encajen en su lugar.
+
El módulo NSM debe insertarse por completo en el estante y enrasarse con los bordes del estante.



. Vuelva a conectar el cableado al módulo NSM:
+
.. Vuelva a conectar el cableado de almacenamiento a los mismos dos puertos del módulo NSM.
+
Los cables se insertan con la lengüeta de extracción del conector hacia arriba. Cuando se inserta correctamente un cable, éste hace clic en su lugar.

.. Vuelva a conectar el cable de alimentación a la fuente de alimentación y, a continuación, asegure el cable de alimentación con el retenedor del cable de alimentación si es una fuente de alimentación de CA, o apriete los dos tornillos de palomilla si es una fuente de alimentación de CC.
+
Cuando funciona correctamente, el LED bicolor de una fuente de alimentación se ilumina en verde.

+
Además, se encienden los dos LED LNK (verde) del puerto del módulo NSM. Si un LED LNK no se ilumina, vuelva a colocar el cable.



. Verifique que el LED de atención (ámbar) del panel de la pantalla del operador de la bandeja ya no esté iluminado.
+
El LED de atención del panel de visualización del operador se apaga después de reiniciar el módulo NSM. Esto puede tardar entre tres y cinco minutos.

. Verifique que el módulo NSM esté cableado correctamente ejecutando Active IQ Config Advisor.
+
Si se genera algún error de cableado, siga las acciones correctivas proporcionadas.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"^]

. Asegúrese de que ambos módulos NSM de la bandeja ejecuten la misma versión de firmware: Versión 0200 o posterior.

