---
permalink: fas8300/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system 
summary: Para sustituir el chasis, debe apagar las controladoras. 
---
= Apague las controladoras - FAS8300 y FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Opción 1: Mayoría de las configuraciones

Debe apagar la controladora o la controladora del chasis antes de moverlos al nuevo chasis.

.Acerca de esta tarea
* Si tiene un clúster con más de dos controladoras, debe estar quórum. Si el clúster no está en quórum o si se muestra una controladora en buen estado `false` para la elegibilidad y la salud, debe corregir el problema antes de apagar el controlador dañado; consulte link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronice un nodo con el clúster"^].
* Si AutoSupport está habilitado, elimine la creación automática de casos invocando un mensaje de AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
El siguiente mensaje de AutoSupport suprime la creación automática de casos durante dos horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`



.Pasos
. Si su sistema tiene dos módulos de controladora, desactive el par de alta disponibilidad.
+
[cols="1,2"]
|===
| Si su sistema utiliza Clustered ONTAP con... | Realice lo siguiente... 


 a| 
Dos controladoras en el clúster
 a| 
`cluster ha modify -configured false`

`storage failover modify -node node0 -enabled false`



 a| 
Más de dos controladoras en el clúster
 a| 
`storage failover modify -node node0 -enabled false`

|===
. Detenga el controlador, pulse `y` cuando se le pida que confirme la detención: `system node halt -node _node_name_`
+
El mensaje de confirmación tiene el aspecto siguiente:

+
[listing]
----
Warning: This operation will cause controller "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the controller goes out of service and one more controller goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: Debe realizar un apagado correcto del sistema antes de sustituir el chasis para evitar perder datos no escritos en la memoria no volátil (NVMEM/NVRAM). Dependiendo del sistema, si el LED de NVMEM/NVRAM parpadea, hay contenido en el NVMEM/NVRAM que no se ha guardado en el disco. Es necesario reiniciar la controladora y comenzar desde el principio de este procedimiento. Si se repite los intentos para apagar correctamente la controladora, tenga en cuenta que se podrían perder datos que no se han guardado en el disco.

. Cuando sea aplicable, detenga la segunda controladora para evitar un posible mensaje de error de quórum en una configuración de par de alta disponibilidad: `system node halt -node _second_node_name_ -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true`
+
Responda `y` cuando se le solicite.





== Opción 2: La controladora está en una configuración MetroCluster de dos nodos

Para apagar el controlador dañado, debe determinar el estado del controlador y, si es necesario, cambiar el controlador para que el controlador correcto siga sirviendo datos del almacenamiento del controlador dañado.

.Acerca de esta tarea
* Si utiliza el cifrado de almacenamiento de NetApp, debe haber restablecido el MSID mediante las instrucciones de la sección "devolver una unidad FIPS o SED a modo sin protección" de link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Información general del cifrado de NetApp con la interfaz de línea de comandos"^].
* Debe dejar las fuentes de alimentación encendidas al final de este procedimiento para proporcionar alimentación a la controladora en buen estado.


.Pasos
. Compruebe el estado de MetroCluster para determinar si el controlador dañado ha cambiado automáticamente al controlador en buen estado: `metrocluster show`
. En función de si se ha producido una conmutación automática, proceda según la siguiente tabla:
+
[cols="1,2"]
|===
| Si el controlador está dañado... | Realice lo siguiente... 


 a| 
Se ha cambiado automáticamente
 a| 
Continúe con el próximo paso.



 a| 
No se ha cambiado automáticamente
 a| 
Realice una operación de conmutación de sitios planificada desde el controlador en buen estado: `metrocluster switchover`



 a| 
No se ha cambiado automáticamente, ha intentado efectuar una conmutación con el `metrocluster switchover` y se vetó la conmutación
 a| 
Revise los mensajes de veto y, si es posible, resuelva el problema e inténtelo de nuevo. Si no puede resolver el problema, póngase en contacto con el soporte técnico.

|===
. Resincronice los agregados de datos ejecutando el `metrocluster heal -phase aggregates` comando del clúster superviviente.
+
[listing]
----
controller_A_1::> metrocluster heal -phase aggregates
[Job 130] Job succeeded: Heal Aggregates is successful.
----
+
Si la curación es vetada, usted tiene la opción de reemitir el `metrocluster heal` con el `-override-vetoes` parámetro. Si utiliza este parámetro opcional, el sistema anula cualquier vetoo suave que impida la operación de reparación.

. Compruebe que se ha completado la operación con el comando MetroCluster operation show.
+
[listing]
----
controller_A_1::> metrocluster operation show
    Operation: heal-aggregates
      State: successful
Start Time: 7/25/2016 18:45:55
   End Time: 7/25/2016 18:45:56
     Errors: -
----
. Compruebe el estado de los agregados mediante `storage aggregate show` comando.
+
[listing]
----
controller_A_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 mcc1-a2          raid_dp, mirrored, normal...
----
. Repare los agregados raíz mediante el `metrocluster heal -phase root-aggregates` comando.
+
[listing]
----
mcc1A::> metrocluster heal -phase root-aggregates
[Job 137] Job succeeded: Heal Root Aggregates is successful
----
+
Si la curación es vetada, usted tiene la opción de reemitir el `metrocluster heal` comando con el parámetro -override-vetoes. Si utiliza este parámetro opcional, el sistema anula cualquier vetoo suave que impida la operación de reparación.

. Compruebe que la operación reparar se ha completado mediante el `metrocluster operation show` comando en el clúster de destino:
+
[listing]
----

mcc1A::> metrocluster operation show
  Operation: heal-root-aggregates
      State: successful
 Start Time: 7/29/2016 20:54:41
   End Time: 7/29/2016 20:54:42
     Errors: -
----
. En el módulo del controlador dañado, desconecte las fuentes de alimentación.

