---
permalink: fas8300/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system 
summary: Reemplace un chasis dañado el nuevo chasis del mismo modelo que el chasis dañado. 
---
= Revisa los requisitos antes de sustituir el chasis en un sistema FAS8300 o FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de sustituir el chasis de tu sistema FAS8300 o FAS8700, todos los demás componentes del sistema deben estar funcionando correctamente; si no es así, debes ponerte en contacto con soporte técnico. Este procedimiento es compatible con todas las versiones de ONTAP, pero provoca una interrupción total del servicio en un clúster de dos controladoras y una interrupción parcial en un clúster de varios nodos.

* Puede utilizar este procedimiento con todas las versiones de ONTAP admitidas por el sistema.
* Este procedimiento provoca interrupciones: un clúster con dos controladores sufre una interrupción total del servicio y un clúster multinodo sufre una interrupción parcial.

