---
permalink: fas8300/install-setup.html 
sidebar: sidebar 
keywords: fas8300, fas8700, install, setup, initial configuration 
summary: Elige tu experiencia de instalación y configuración del FAS8300 o FAS8700. 
---
= Elige tu experiencia de instalación y configuración del FAS8300 o FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la mayoría de las configuraciones de FAS8300 y FAS8700, puedes elegir el formato de instalación y configuración que mejor se adapte a tus necesidades: pasos rápidos, pasos en vídeo o pasos detallados.

* link:../fas8300/install-quick-guide.html["Pasos rápidos"]
+
Un PDF imprimible de instrucciones paso a paso con enlaces directos a contenido adicional.

* link:../fas8300/install-videos.html["Pasos de vídeo"]
+
Instrucciones paso a paso de vídeo.

* link:../fas8300/install-detailed-guide.html["Pasos detallados"]
+
Instrucciones paso a paso en línea con enlaces directos a contenido adicional.



Para configuraciones MetroCluster, consulte:

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Instale la configuración de IP de MetroCluster"]
* https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Instale la configuración estructural de MetroCluster"]

