---
permalink: a700s/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery 
summary: Obtenga información sobre el reemplazo del medio de arranque en un sistema AFF A700s y comprenda los métodos de recuperación. El sistema AFF A700s solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque. 
---
= Descripción general de la sustitución de medios de arranque: AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga información sobre el reemplazo del medio de arranque en un sistema AFF A700s y comprenda los métodos de recuperación. El medio de arranque principal almacena la imagen de arranque ONTAP que el sistema utiliza durante el inicio. Puede restaurar la imagen del medio de arranque principal utilizando la imagen ONTAP del medio de arranque secundario o, si es necesario, desde una unidad flash USB formateada en FAT32.

El sistema AFF A700s solo admite procedimientos de recuperación de medios de arranque manuales. No se admite la recuperación automática de medios de arranque.

Si el soporte de arranque secundario ha fallado o le falta el archivo image.tgz, debe restaurar el soporte de arranque primario mediante una unidad flash USB. La unidad debe formatearse con FAT32 y debe disponer de la cantidad de almacenamiento adecuada para alojar el archivo image_xxx.tgz.

* El proceso de sustitución restaura el sistema de archivos var desde el soporte de arranque secundario o la unidad flash USB al medio de arranque principal.
* Debe sustituir el componente con errores por un componente FRU de repuesto que haya recibido de su proveedor.
* Es importante que aplique los comandos en estos pasos en la controladora correcta:
+
** El controlador _drinated_ es el controlador en el que está realizando tareas de mantenimiento.
** El controlador _heated_ es el compañero de alta disponibilidad del controlador dañado.




Si necesita reemplazar el soporte de arranque secundario mientras el soporte de arranque principal está instalado y en buen estado, póngase en contacto con el soporte de NetApp y mencione el https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["Cómo reemplazar el dispositivo de arranque secundario de un AFF A700s"^] artículo de la base de conocimientos.
