---
permalink: a700s/maintain-overview.html 
sidebar: sidebar 
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components 
summary: Mantenga el hardware de AFF A700s 
---
= Infórmate sobre el mantenimiento de tu sistema de almacenamiento AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para el sistema de almacenamiento AFF A700s, puede realizar procedimientos de mantenimiento en los componentes siguientes.



[[boot-media]]
== Soporte de arranque

El medio de arranque almacena un conjunto primario y secundario de archivos de imagen de arranque que el sistema utiliza cuando se inicia.



[[chassis]]
== Chasis

El chasis es el compartimento físico que aloja todos los componentes de la controladora, como la unidad controladora/CPU, el suministro de alimentación y las operaciones de I/O.



[[controller]]
== Controladora

Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de ONTAP.



[[dimm]]
== DIMM

Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



[[drive]]
== Unidad

Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



[[fan]]
== Ventilador

El ventilador enfría el controlador.



[[nvram-battery]]
== Batería NVRAM

El controlador incluye una batería y proporciona la alimentación de respaldo si falla la alimentación de CA.



[[nvram-module]]
== Módulo de NVRAM

El módulo NVRAM (memoria no volátil de acceso aleatorio) conserva los datos en caché si falla la alimentación.



[[pcie-card]]
== Tarjeta PCIe

Una tarjeta PCIe (interconexión de componentes periféricos express) es una tarjeta de expansión que se conecta a la ranura PCIe de la placa base.



[[power-supply]]
== Suministro de alimentación

Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



[[real-time-clock-battery]]
== Batería del reloj en tiempo real

Una batería de reloj en tiempo real conserva la información de fecha y hora del sistema si la alimentación está apagada.
