---
permalink: asa-r2/asa-r2-install-setup.html 
sidebar: sidebar 
keywords: asa r2 a1k, a70, a90, install, setup, initial configuration 
summary: Instale y configure el sistema. 
---
= Instale y configure sus sistemas ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vaya al https://docs.netapp.com/us-en/asa-r2/install-setup/install-setup-workflow.html["Instrucciones de instalación y configuración de ASA R2"^] para saber cómo instalar y configurar el sistema.

La https://docs.netapp.com/us-en/asa-r2/index.html["Documentación del sistema ASA R2"^] incluye información como la siguiente:

* Instrucciones de instalación y configuración
* Instrucciones de administración para configurar su sistema, como aprovisionar almacenamiento SAN, clonar datos y redimensionar almacenamiento local.
* Instrucciones para administrar su sistema, incluida la administración del acceso de clientes, la protección de sus datos y la protección de sus datos.
* Instrucciones de supervisión y solución de problemas, incluida información sobre alertas, eventos del clúster y registros del sistema.


Los procedimientos de mantenimiento específicos para cada tipo de sistema ASA R2 se encuentran en el link:../asa-r2-landing-maintain/index.html["Sección de mantenimiento de sistemas ASA R2"].
